import { ProblemList } from '../Problems';

export const acordar: ProblemList = {
  verb: 'acordar',
  problems: [
    {
      sentence: 'Eu {blank} cedo todos os dias.',
      verb: 'acordar',
      tense: 'presente',
      answers: ['acordo'],
    },
    {
      sentence: 'Ele {blank} às seis horas da manhã.',
      verb: 'acordar',
      tense: 'presente',
      answers: ['acorda'],
    },
    {
      sentence: 'Você {blank} com uma boa disposição.',
      verb: 'acordar',
      tense: 'presente',
      answers: ['acorda'],
    },
    {
      sentence: 'Nós {blank} felizes no fim de semana.',
      verb: 'acordar',
      tense: 'presente',
      answers: ['acordamos'],
    },
    {
      sentence: 'Ela {blank} sempre bem disposta.',
      verb: 'acordar',
      tense: 'presente',
      answers: ['acorda'],
    },
    {
      sentence: 'Maria {blank} animada para a festa.',
      verb: 'acordar',
      tense: 'presente',
      answers: ['acorda'],
    },
    {
      sentence: 'Os meninos {blank} tarde aos sábados.',
      verb: 'acordar',
      tense: 'presente',
      answers: ['acordam'],
    },
    {
      sentence: 'Vocês {blank} prontos para o dia.',
      verb: 'acordar',
      tense: 'presente',
      answers: ['acordam'],
    },
    {
      sentence: 'As crianças {blank} com muito barulho.',
      verb: 'acordar',
      tense: 'presente',
      answers: ['acordam'],
    },
    {
      sentence: 'Meu irmão {blank} cansado hoje.',
      verb: 'acordar',
      tense: 'presente',
      answers: ['acorda'],
    },
    {
      sentence: 'Eu {blank} cedo para o trabalho na segunda-feira.',
      verb: 'acordar',
      tense: 'pretérito perfeito',
      answers: ['acordei'],
    },
    {
      sentence: 'Ela {blank} feliz ao ouvir a notícia.',
      verb: 'acordar',
      tense: 'pretérito perfeito',
      answers: ['acordou'],
    },
    {
      sentence: 'Nós {blank} à mesma hora que sempre.',
      verb: 'acordar',
      tense: 'pretérito perfeito',
      answers: ['acordamos'],
    },
    {
      sentence: 'Você {blank} antes das 7 horas ontem.',
      verb: 'acordar',
      tense: 'pretérito perfeito',
      answers: ['acordou'],
    },
    {
      sentence: 'Ele {blank} e já começou a trabalhar.',
      verb: 'acordar',
      tense: 'pretérito perfeito',
      answers: ['acordou'],
    },
    {
      sentence: 'As crianças {blank} animadas para a escola.',
      verb: 'acordar',
      tense: 'pretérito perfeito',
      answers: ['acordaram'],
    },
    {
      sentence: 'Maria e eu {blank} antes do amanhecer.',
      verb: 'acordar',
      tense: 'pretérito perfeito',
      answers: ['acordamos'],
    },
    {
      sentence: 'Vocês {blank} tarde no sábado passado.',
      verb: 'acordar',
      tense: 'pretérito perfeito',
      answers: ['acordaram'],
    },
    {
      sentence: 'Pedro {blank} um pouco assustado esta manhã.',
      verb: 'acordar',
      tense: 'pretérito perfeito',
      answers: ['acordou'],
    },
    {
      sentence: 'Ela {blank} com muita energia hoje.',
      verb: 'acordar',
      tense: 'pretérito perfeito',
      answers: ['acordou'],
    },
    {
      sentence: 'Eu {blank} cedo amanhã.',
      verb: 'acordar',
      tense: 'futuro',
      answers: ['acordarei', 'vou acordar'],
    },
    {
      sentence: 'Ela {blank} para a escola na semana que vem.',
      verb: 'acordar',
      tense: 'futuro',
      answers: ['acordará', 'vai acordar'],
    },
    {
      sentence: 'Nós {blank} às 7 horas no sábado.',
      verb: 'acordar',
      tense: 'futuro',
      answers: ['acordaremos', 'vamos acordar'],
    },
    {
      sentence: 'Vocês {blank} preparados para o treino na quarta-feira.',
      verb: 'acordar',
      tense: 'futuro',
      answers: ['acordarão', 'vão acordar'],
    },
    {
      sentence: 'João {blank} mais cedo para o trabalho amanhã.',
      verb: 'acordar',
      tense: 'futuro',
      answers: ['acordará', 'vai acordar'],
    },
    {
      sentence: 'Maria e eu {blank} para a festa no próximo fim de semana.',
      verb: 'acordar',
      tense: 'futuro',
      answers: ['acordaremos', 'vamos acordar'],
    },
    {
      sentence: 'Você {blank} no hotel nesta noite.',
      verb: 'acordar',
      tense: 'futuro',
      answers: ['acordará', 'vai acordar'],
    },
    {
      sentence: 'Eles {blank} depois que a luz do sol nascer.',
      verb: 'acordar',
      tense: 'futuro',
      answers: ['acordarão', 'vão acordar'],
    },
    {
      sentence: 'Pedro {blank} pronto para o exame na próxima semana.',
      verb: 'acordar',
      tense: 'futuro',
      answers: ['acordará', 'vai acordar'],
    },
    {
      sentence: 'Ana e você {blank} a tempo para o evento.',
      verb: 'acordar',
      tense: 'futuro',
      answers: ['acordarão', 'vão acordar'],
    },
  ],
};
