import { ProblemList } from '../Problems';

export const amar: ProblemList = {
  verb: 'amar',
  problems: [
    {
      sentence: 'Eu {blank} muito meu trabalho diário.',
      verb: 'amar',
      tense: 'presente',
      answers: ['amo'],
    },
    {
      sentence: 'Ela {blank} os livros que lê com paixão.',
      verb: 'amar',
      tense: 'presente',
      answers: ['ama'],
    },
    {
      sentence: 'Nós {blank} viajar em família durante as férias.',
      verb: 'amar',
      tense: 'presente',
      answers: ['amamos'],
    },
    {
      sentence: 'Vocês {blank} os animais que têm em casa.',
      verb: 'amar',
      tense: 'presente',
      answers: ['amam'],
    },
    {
      sentence: 'Ele {blank} cada momento ao lado dos amigos.',
      verb: 'amar',
      tense: 'presente',
      answers: ['ama'],
    },
    {
      sentence: 'Maria {blank} música clássica e toca piano.',
      verb: 'amar',
      tense: 'presente',
      answers: ['ama'],
    },
    {
      sentence: 'Nós {blank} o que fazemos e nos dedicamos todos os dias.',
      verb: 'amar',
      tense: 'presente',
      answers: ['amamos'],
    },
    {
      sentence: 'Você {blank} a natureza e passeia muito por ela.',
      verb: 'amar',
      tense: 'presente',
      answers: ['ama'],
    },
    {
      sentence: 'Eles {blank} fazer novas amizades e sempre se esforçam.',
      verb: 'amar',
      tense: 'presente',
      answers: ['amam'],
    },
    {
      sentence: 'João e Ana {blank} praticar esportes juntos.',
      verb: 'amar',
      tense: 'presente',
      answers: ['amam'],
    },
    {
      sentence: 'Eu {blank} muito a minha família durante a pandemia.',
      verb: 'amar',
      tense: 'pretérito perfeito',
      answers: ['amei'],
    },
    {
      sentence: 'Ela {blank} de verdade o seu novo cachorro.',
      verb: 'amar',
      tense: 'pretérito perfeito',
      answers: ['amou'],
    },
    {
      sentence: 'Nós {blank} os livros de história na escola.',
      verb: 'amar',
      tense: 'pretérito perfeito',
      answers: ['amamos'],
    },
    {
      sentence: 'Você {blank} as flores do seu jardim.',
      verb: 'amar',
      tense: 'pretérito perfeito',
      answers: ['amou'],
    },
    {
      sentence: 'Eles {blank} o novo restaurante do bairro.',
      verb: 'amar',
      tense: 'pretérito perfeito',
      answers: ['amaram'],
    },
    {
      sentence: 'João {blank} muito a música brasileira.',
      verb: 'amar',
      tense: 'pretérito perfeito',
      answers: ['amou'],
    },
    {
      sentence: 'Nós {blank} o filme que assistimos ontem.',
      verb: 'amar',
      tense: 'pretérito perfeito',
      answers: ['amamos'],
    },
    {
      sentence: 'Você e eu {blank} juntos até agora.',
      verb: 'amar',
      tense: 'pretérito perfeito',
      answers: ['amamos'],
    },
    {
      sentence: 'Ela e Maria {blank} as roupas novas que compraram.',
      verb: 'amar',
      tense: 'pretérito perfeito',
      answers: ['amaram'],
    },
    {
      sentence: 'Eu e você {blank} muito este lugar.',
      verb: 'amar',
      tense: 'pretérito perfeito',
      answers: ['amamos'],
    },
    {
      sentence: 'Eu {blank} muito você na próxima semana.',
      verb: 'amar',
      tense: 'futuro',
      answers: ['amarei', 'vou amar'],
    },
    {
      sentence: 'Ela {blank} sempre sua família no Natal.',
      verb: 'amar',
      tense: 'futuro',
      answers: ['amarão', 'vão amar'],
    },
    {
      sentence: 'Nós {blank} os amigos que vierem à festa.',
      verb: 'amar',
      tense: 'futuro',
      answers: ['amaremos', 'vamos amar'],
    },
    {
      sentence: 'Vocês {blank} a música nova no próximo mês.',
      verb: 'amar',
      tense: 'futuro',
      answers: ['amarão', 'vão amar'],
    },
    {
      sentence: 'Ele {blank} a vida que construiu até agora.',
      verb: 'amar',
      tense: 'futuro',
      answers: ['amarão', 'vão amar'],
    },
    {
      sentence: 'Eu e você {blank} nossa amizade para sempre.',
      verb: 'amar',
      tense: 'futuro',
      answers: ['amaremos', 'vamos amar'],
    },
    {
      sentence: 'Maria {blank} os animais do abrigo no próximo verão.',
      verb: 'amar',
      tense: 'futuro',
      answers: ['amarão', 'vão amar'],
    },
    {
      sentence: 'Nós {blank} a história do Brasil na próxima aula.',
      verb: 'amar',
      tense: 'futuro',
      answers: ['amacaremos', 'vamos amar'],
    },
    {
      sentence: 'Você {blank} seu novo projeto a partir do mês que vem.',
      verb: 'amar',
      tense: 'futuro',
      answers: ['amarão', 'vão amar'],
    },
    {
      sentence: 'Eles {blank} nosso time na competição do ano que vem.',
      verb: 'amar',
      tense: 'futuro',
      answers: ['amarão', 'vão amar'],
    },
  ],
};
