import { ProblemList } from '../Problems';

export const analisar: ProblemList = {
  verb: 'analisar',
  problems: [
    {
      sentence: 'Eu {blank} todos os dados para o relatório.',
      verb: 'analisar',
      tense: 'pretérito perfeito',
      answers: ['analisei'],
    },
    {
      sentence: 'Ela {blank} as opções disponíveis antes de decidir.',
      verb: 'analisar',
      tense: 'pretérito perfeito',
      answers: ['analisou'],
    },
    {
      sentence: 'Nós {blank} o projeto com atenção.',
      verb: 'analisar',
      tense: 'pretérito perfeito',
      answers: ['analisamos'],
    },
    {
      sentence: 'Você {blank} o desempenho da equipe no último mês.',
      verb: 'analisar',
      tense: 'pretérito perfeito',
      answers: ['analisou'],
    },
    {
      sentence: 'Luis {blank} as vantagens e desvantagens da proposta.',
      verb: 'analisar',
      tense: 'pretérito perfeito',
      answers: ['analisou'],
    },
    {
      sentence: 'Eles {blank} os resultados da pesquisa com cuidado.',
      verb: 'analisar',
      tense: 'pretérito perfeito',
      answers: ['analisaram'],
    },
    {
      sentence: 'Nós {blank} as condições do contrato antes de assinar.',
      verb: 'analisar',
      tense: 'pretérito perfeito',
      answers: ['analisamos'],
    },
    {
      sentence: 'Você e eu {blank} as possibilidades de viagem.',
      verb: 'analisar',
      tense: 'pretérito perfeito',
      answers: ['analisamos'],
    },
    {
      sentence: 'Maria {blank} a antiga biblioteca da faculdade.',
      verb: 'analisar',
      tense: 'pretérito perfeito',
      answers: ['analisou'],
    },
    {
      sentence: 'As professoras {blank} os trabalhos dos alunos ontem.',
      verb: 'analisar',
      tense: 'pretérito perfeito',
      answers: ['analisaram'],
    },
    {
      sentence: 'Eu {blank} a proposta antes da reunião.',
      verb: 'analisar',
      tense: 'futuro',
      answers: ['analisarei', 'vou analisar'],
    },
    {
      sentence: 'Você {blank} as estatísticas na próxima semana.',
      verb: 'analisar',
      tense: 'futuro',
      answers: ['analisará', 'vai analisar'],
    },
    {
      sentence: 'Nós {blank} os resultados do experimento amanhã.',
      verb: 'analisar',
      tense: 'futuro',
      answers: ['analisaremos', 'vamos analisar'],
    },
    {
      sentence: 'Ela {blank} todos os dados antes da apresentação.',
      verb: 'analisar',
      tense: 'futuro',
      answers: ['analisará', 'vai analisar'],
    },
    {
      sentence: 'Eles {blank} as opções disponíveis até sexta-feira.',
      verb: 'analisar',
      tense: 'futuro',
      answers: ['analisarão', 'vão analisar'],
    },
    {
      sentence: 'Nós {blank} o relatório final na próxima reunião.',
      verb: 'analisar',
      tense: 'futuro',
      answers: ['analisaremos', 'vamos analisar'],
    },
    {
      sentence: 'Você e eu {blank} o projeto juntos na semana que vem.',
      verb: 'analisar',
      tense: 'futuro',
      answers: ['analisaremos', 'vamos analisar'],
    },
    {
      sentence: 'Eles {blank} as novas diretrizes na próxima segunda.',
      verb: 'analisar',
      tense: 'futuro',
      answers: ['analisarão', 'vão analisar'],
    },
    {
      sentence: 'Eu {blank} as informações que você me enviou.',
      verb: 'analisar',
      tense: 'futuro',
      answers: ['analisarei', 'vou analisar'],
    },
    {
      sentence: 'Você {blank} os pontos importantes do relatório depois.',
      verb: 'analisar',
      tense: 'futuro',
      answers: ['analisará', 'vai analisar'],
    },
    {
      sentence: 'Eu {blank} todos os dados antes da reunião.',
      verb: 'analisar',
      tense: 'presente',
      answers: ['analiso'],
    },
    {
      sentence: 'Ela {blank} o relatório com muito cuidado.',
      verb: 'analisar',
      tense: 'presente',
      answers: ['analisa'],
    },
    {
      sentence: 'Nós {blank} as informações essenciais para o projeto.',
      verb: 'analisar',
      tense: 'presente',
      answers: ['analisamos'],
    },
    {
      sentence: 'Você {blank} as alternativas disponíveis.',
      verb: 'analisar',
      tense: 'presente',
      answers: ['analisa'],
    },
    {
      sentence: 'Eles {blank} o cenário antes de tomar a decisão.',
      verb: 'analisar',
      tense: 'presente',
      answers: ['analisam'],
    },
    {
      sentence: 'Maria {blank} as propostas recebidas.',
      verb: 'analisar',
      tense: 'presente',
      answers: ['analisa'],
    },
    {
      sentence: 'Você e eu {blank} as evidências do caso.',
      verb: 'analisar',
      tense: 'presente',
      answers: ['analisamos'],
    },
    {
      sentence: 'Os alunos {blank} o conteúdo da aula.',
      verb: 'analisar',
      tense: 'presente',
      answers: ['analisam'],
    },
    {
      sentence: 'Ela e você {blank} os resultados do experimento.',
      verb: 'analisar',
      tense: 'presente',
      answers: ['analisam'],
    },
    {
      sentence: 'Meu amigo {blank} os dados estatísticos do estudo.',
      verb: 'analisar',
      tense: 'presente',
      answers: ['analisa'],
    },
  ],
};
