import { ProblemList } from '../Problems';

export const andar: ProblemList = {
  verb: 'andar',
  problems: [
    {
      sentence: 'Eu {blank} no parque todas as manhãs.',
      verb: 'andar',
      tense: 'presente',
      answers: ['ando'],
    },
    {
      sentence: 'Ela {blank} pela cidade com seus amigos.',
      verb: 'andar',
      tense: 'presente',
      answers: ['anda'],
    },
    {
      sentence: 'Nós {blank} juntos para o trabalho.',
      verb: 'andar',
      tense: 'presente',
      answers: ['andamos'],
    },
    {
      sentence: 'Você {blank} muito bem na trilha.',
      verb: 'andar',
      tense: 'presente',
      answers: ['anda'],
    },
    {
      sentence: 'Eles {blank} na escola após as aulas.',
      verb: 'andar',
      tense: 'presente',
      answers: ['andam'],
    },
    {
      sentence: 'Ana {blank} com seus filhos no parque.',
      verb: 'andar',
      tense: 'presente',
      answers: ['anda'],
    },
    {
      sentence: 'Carlos e eu {blank} todos os sábados na praia.',
      verb: 'andar',
      tense: 'presente',
      answers: ['andamos'],
    },
    {
      sentence: 'Você e Maria {blank} pelo centro da cidade.',
      verb: 'andar',
      tense: 'presente',
      answers: ['andam'],
    },
    {
      sentence: 'João {blank} de bicicleta para a escola.',
      verb: 'andar',
      tense: 'presente',
      answers: ['anda'],
    },
    {
      sentence: 'Nós {blank} para o restaurante frequentemente.',
      verb: 'andar',
      tense: 'presente',
      answers: ['andamos'],
    },
    {
      sentence: 'Eu {blank} na praia durante as férias.',
      verb: 'andar',
      tense: 'pretérito perfeito',
      answers: ['andei'],
    },
    {
      sentence: 'Ela {blank} pelo parque com seu cachorro.',
      verb: 'andar',
      tense: 'pretérito perfeito',
      answers: ['andou'],
    },
    {
      sentence: 'Nós {blank} por toda a cidade no sábado.',
      verb: 'andar',
      tense: 'pretérito perfeito',
      answers: ['andamos'],
    },
    {
      sentence: 'Vocês {blank} muito no último encontro.',
      verb: 'andar',
      tense: 'pretérito perfeito',
      answers: ['andaram'],
    },
    {
      sentence: 'Ele {blank} até a escola ontem.',
      verb: 'andar',
      tense: 'pretérito perfeito',
      answers: ['andou'],
    },
    {
      sentence: 'Maria {blank} com os amigos no parque.',
      verb: 'andar',
      tense: 'pretérito perfeito',
      answers: ['andou'],
    },
    {
      sentence: 'Eu {blank} na feira no domingo passado.',
      verb: 'andar',
      tense: 'pretérito perfeito',
      answers: ['andei'],
    },
    {
      sentence: 'Vocês {blank} pela montanha antes da tempestade.',
      verb: 'andar',
      tense: 'pretérito perfeito',
      answers: ['andaram'],
    },
    {
      sentence: 'Nós {blank} juntos para ver o pôr do sol.',
      verb: 'andar',
      tense: 'pretérito perfeito',
      answers: ['andamos'],
    },
    {
      sentence: 'Ela {blank} pela casa procurando suas chaves.',
      verb: 'andar',
      tense: 'pretérito perfeito',
      answers: ['andou'],
    },
    {
      sentence: 'Eu {blank} pelo parque amanhã.',
      verb: 'andar',
      tense: 'futuro',
      answers: ['andarei', 'vou andar'],
    },
    {
      sentence: 'Ela {blank} na praia no próximo fim de semana.',
      verb: 'andar',
      tense: 'futuro',
      answers: ['andará', 'vai andar'],
    },
    {
      sentence: 'Nós {blank} por Lisboa durante as férias.',
      verb: 'andar',
      tense: 'futuro',
      answers: ['andearemos', 'vamos andar'],
    },
    {
      sentence: 'Você {blank} na festa amanhã à noite.',
      verb: 'andar',
      tense: 'futuro',
      answers: ['andará', 'vai andar'],
    },
    {
      sentence: 'Eles {blank} até o centro no domingo.',
      verb: 'andar',
      tense: 'futuro',
      answers: ['andarão', 'vão andar'],
    },
    {
      sentence: 'Maria e eu {blank} pela cidade no próximo mês.',
      verb: 'andar',
      tense: 'futuro',
      answers: ['andaremos', 'vamos andar'],
    },
    {
      sentence: 'Você e eu {blank} no parque mais tarde.',
      verb: 'andar',
      tense: 'futuro',
      answers: ['andaremos', 'vamos andar'],
    },
    {
      sentence: 'João {blank} a pé para a escola amanhã.',
      verb: 'andar',
      tense: 'futuro',
      answers: ['andará', 'vai andar'],
    },
    {
      sentence: 'As crianças {blank} no passeio de sábado.',
      verb: 'andar',
      tense: 'futuro',
      answers: ['andarão', 'vão andar'],
    },
    {
      sentence: 'Você {blank} com seus amigos no parque na próxima semana.',
      verb: 'andar',
      tense: 'futuro',
      answers: ['andará', 'vai andar'],
    },
  ],
};
