import { ProblemList } from '../Problems';

export const anunciar: ProblemList = {
  verb: 'anunciar',
  problems: [
    {
      sentence: 'Eu {blank} a nova proposta ontem.',
      verb: 'anunciar',
      tense: 'pretérito perfeito',
      answers: ['anunciei'],
    },
    {
      sentence: 'Ela {blank} as mudanças no projeto na semana passada.',
      verb: 'anunciar',
      tense: 'pretérito perfeito',
      answers: ['anunciou'],
    },
    {
      sentence: 'Nós {blank} a festa surpresa para o João.',
      verb: 'anunciar',
      tense: 'pretérito perfeito',
      answers: ['anunciamos'],
    },
    {
      sentence: 'Você {blank} as boas notícias para toda a equipe.',
      verb: 'anunciar',
      tense: 'pretérito perfeito',
      answers: ['anunciou'],
    },
    {
      sentence: 'Eles {blank} os resultados do concurso no mês passado.',
      verb: 'anunciar',
      tense: 'pretérito perfeito',
      answers: ['anunciaram'],
    },
    {
      sentence: 'Maria {blank} com entusiasmo a sua nova iniciativa.',
      verb: 'anunciar',
      tense: 'pretérito perfeito',
      answers: ['anunciou'],
    },
    {
      sentence: 'Nós {blank} os vencedores do sorteio no evento.',
      verb: 'anunciar',
      tense: 'pretérito perfeito',
      answers: ['anunciamos'],
    },
    {
      sentence: 'Você e eu {blank} a nova parceria para o projeto.',
      verb: 'anunciar',
      tense: 'pretérito perfeito',
      answers: ['anunciamos'],
    },
    {
      sentence: 'Os professores {blank} o novo currículo para os alunos.',
      verb: 'anunciar',
      tense: 'pretérito perfeito',
      answers: ['anunciaram'],
    },
    {
      sentence: 'Carlos {blank} a data do próximo evento cultural.',
      verb: 'anunciar',
      tense: 'pretérito perfeito',
      answers: ['anunciou'],
    },
    {
      sentence: 'Ela {blank} as novidades na próxima reunião.',
      verb: 'anunciar',
      tense: 'futuro',
      answers: ['anunciará', 'vai anunciar'],
    },
    {
      sentence: 'Nós {blank} o lançamento do novo produto em breve.',
      verb: 'anunciar',
      tense: 'futuro',
      answers: ['anunciaremos', 'vamos anunciar'],
    },
    {
      sentence: 'Vocês {blank} os resultados da pesquisa na sexta-feira.',
      verb: 'anunciar',
      tense: 'futuro',
      answers: ['anunciarão', 'vão anunciar'],
    },
    {
      sentence: 'Eu {blank} a nossa participação no evento amanhã.',
      verb: 'anunciar',
      tense: 'futuro',
      answers: ['anunciarei', 'vou anunciar'],
    },
    {
      sentence: 'Ele {blank} as atualizações do projeto no próximo mês.',
      verb: 'anunciar',
      tense: 'futuro',
      answers: ['anunciará', 'vai anunciar'],
    },
    {
      sentence: 'Você {blank} a nova campanha publicitária em breve.',
      verb: 'anunciar',
      tense: 'futuro',
      answers: ['anunciará', 'vai anunciar'],
    },
    {
      sentence: 'Nós {blank} as novas regras na próxima semana.',
      verb: 'anunciar',
      tense: 'futuro',
      answers: ['anunciaremos', 'vamos anunciar'],
    },
    {
      sentence: 'Elas {blank} a data do evento na próxima terça-feira.',
      verb: 'anunciar',
      tense: 'futuro',
      answers: ['anunciarão', 'vão anunciar'],
    },
    {
      sentence: 'Você e eu {blank} a novidade juntos amanhã.',
      verb: 'anunciar',
      tense: 'futuro',
      answers: ['anunciaremos', 'vamos anunciar'],
    },
    {
      sentence: 'Pedro {blank} os detalhes do projeto na apresentação.',
      verb: 'anunciar',
      tense: 'futuro',
      answers: ['anunciará', 'vai anunciar'],
    },
    {
      sentence: 'Eu {blank} que o projeto foi um sucesso.',
      verb: 'anunciar',
      tense: 'presente',
      answers: ['anuncio'],
    },
    {
      sentence: 'Ela {blank} as novidades para os colegas.',
      verb: 'anunciar',
      tense: 'presente',
      answers: ['anuncia'],
    },
    {
      sentence: 'Nós {blank} as atualizações de segurança regularmente.',
      verb: 'anunciar',
      tense: 'presente',
      answers: ['anunciamos'],
    },
    {
      sentence: 'Você {blank} sempre a verdade!',
      verb: 'anunciar',
      tense: 'presente',
      answers: ['anuncia'],
    },
    {
      sentence: 'Eles {blank} os resultados da pesquisa ontem.',
      verb: 'anunciar',
      tense: 'presente',
      answers: ['anunciam'],
    },
    {
      sentence: 'João {blank} seu novo filme no próximo mês.',
      verb: 'anunciar',
      tense: 'presente',
      answers: ['anuncia'],
    },
    {
      sentence: 'Ana e Carlos {blank} as novas regras na reunião.',
      verb: 'anunciar',
      tense: 'presente',
      answers: ['anunciam'],
    },
    {
      sentence: 'Você e eu {blank} a nova campanha publicitária juntos.',
      verb: 'anunciar',
      tense: 'presente',
      answers: ['anunciamos'],
    },
    {
      sentence: 'A professora {blank} os temas da prova amanhã.',
      verb: 'anunciar',
      tense: 'presente',
      answers: ['anuncia'],
    },
    {
      sentence: 'Eles {blank} as mudanças no cronograma do projeto.',
      verb: 'anunciar',
      tense: 'presente',
      answers: ['anunciam'],
    },
  ],
};
