import { ProblemList } from '../Problems';

export const apresentar: ProblemList = {
  verb: 'apresentar',
  problems: [
    {
      sentence: 'Nós {blank} o projeto na semana passada.',
      verb: 'apresentar',
      tense: 'pretérito perfeito',
      answers: ['apresentamos'],
    },
    {
      sentence: 'Ela {blank} os resultados da pesquisa ontem.',
      verb: 'apresentar',
      tense: 'pretérito perfeito',
      answers: ['apresentou'],
    },
    {
      sentence: 'Você {blank} o seu trabalho na reunião anterior.',
      verb: 'apresentar',
      tense: 'pretérito perfeito',
      answers: ['apresentou'],
    },
    {
      sentence: 'Eu {blank} a proposta ao cliente na sexta-feira.',
      verb: 'apresentar',
      tense: 'pretérito perfeito',
      answers: ['apresentei'],
    },
    {
      sentence: 'Eles {blank} as soluções na conferência recente.',
      verb: 'apresentar',
      tense: 'pretérito perfeito',
      answers: ['apresentaram'],
    },
    {
      sentence: 'Carlos {blank} o novo produto na feira.',
      verb: 'apresentar',
      tense: 'pretérito perfeito',
      answers: ['apresentou'],
    },
    {
      sentence: 'Nós {blank} a ideia no encontro de ontem.',
      verb: 'apresentar',
      tense: 'pretérito perfeito',
      answers: ['apresentamos'],
    },
    {
      sentence: 'Vocês {blank} a estratégia na última reunião.',
      verb: 'apresentar',
      tense: 'pretérito perfeito',
      answers: ['apresentaram'],
    },
    {
      sentence: 'Maria {blank} a proposta de parceria na terça-feira.',
      verb: 'apresentar',
      tense: 'pretérito perfeito',
      answers: ['apresentou'],
    },
    {
      sentence: 'Eu {blank} o relatório no seminário no mês passado.',
      verb: 'apresentar',
      tense: 'pretérito perfeito',
      answers: ['apresentei'],
    },
    {
      sentence: 'Eu {blank} o projeto na semana que vem.',
      verb: 'apresentar',
      tense: 'futuro',
      answers: ['apresentarei', 'vou apresentar'],
    },
    {
      sentence: 'Ela {blank} os resultados da pesquisa amanhã.',
      verb: 'apresentar',
      tense: 'futuro',
      answers: ['apresentará', 'vai apresentar'],
    },
    {
      sentence: 'Nós {blank} a nova campanha no próximo mês.',
      verb: 'apresentar',
      tense: 'futuro',
      answers: ['apresentaremos', 'vamos apresentar'],
    },
    {
      sentence: 'Você {blank} os alunos ao professor na próxima reunião.',
      verb: 'apresentar',
      tense: 'futuro',
      answers: ['apresentará', 'vai apresentar'],
    },
    {
      sentence: 'Eles {blank} o espetáculo nas férias.',
      verb: 'apresentar',
      tense: 'futuro',
      answers: ['apresentarão', 'vão apresentar'],
    },
    {
      sentence: 'João {blank} o seu trabalho na conferência.',
      verb: 'apresentar',
      tense: 'futuro',
      answers: ['apresentará', 'vai apresentar'],
    },
    {
      sentence: 'Vocês {blank} as novidades no evento na semana que vem.',
      verb: 'apresentar',
      tense: 'futuro',
      answers: ['apresentarão', 'vão apresentar'],
    },
    {
      sentence: 'Maria e eu {blank} a proposta para o cliente.',
      verb: 'apresentar',
      tense: 'futuro',
      answers: ['apresentaremos', 'vamos apresentar'],
    },
    {
      sentence: 'A equipe {blank} os resultados do projeto na sexta-feira.',
      verb: 'apresentar',
      tense: 'futuro',
      answers: ['apresentará', 'vai apresentar'],
    },
    {
      sentence: 'Você e eu {blank} as novas ideias para a empresa.',
      verb: 'apresentar',
      tense: 'futuro',
      answers: ['apresentaremos', 'vamos apresentar'],
    },
    {
      sentence: 'Eu {blank} o projeto para a equipe.',
      verb: 'apresentar',
      tense: 'presente',
      answers: ['apresento'],
    },
    {
      sentence: 'Ela {blank} suas ideias na reunião.',
      verb: 'apresentar',
      tense: 'presente',
      answers: ['apresenta'],
    },
    {
      sentence: 'Nós {blank} o trabalho durante a conferência.',
      verb: 'apresentar',
      tense: 'presente',
      answers: ['apresentamos'],
    },
    {
      sentence: 'Você {blank} soluções inovadoras para o problema.',
      verb: 'apresentar',
      tense: 'presente',
      answers: ['apresenta'],
    },
    {
      sentence: 'Eles {blank} o relatório na próxima semana.',
      verb: 'apresentar',
      tense: 'presente',
      answers: ['apresentam'],
    },
    {
      sentence: 'Carlos {blank} suas pesquisas na aula.',
      verb: 'apresentar',
      tense: 'presente',
      answers: ['apresenta'],
    },
    {
      sentence: 'Nós {blank} novidades sobre o projeto.',
      verb: 'apresentar',
      tense: 'presente',
      answers: ['apresentamos'],
    },
    {
      sentence: 'Você e eu {blank} um novo produto em breve.',
      verb: 'apresentar',
      tense: 'presente',
      answers: ['apresentamos'],
    },
    {
      sentence: 'As crianças {blank} suas apresentações no festival.',
      verb: 'apresentar',
      tense: 'presente',
      answers: ['apresentam'],
    },
    {
      sentence: 'Todos nós {blank} sugestões para o evento.',
      verb: 'apresentar',
      tense: 'presente',
      answers: ['apresentamos'],
    },
  ],
};
