import { ProblemList } from '../Problems';

export const aprender: ProblemList = {
  verb: 'aprender',
  problems: [
    {
      sentence: 'Eu {blank} uma nova habilidade durante o curso.',
      verb: 'aprender',
      tense: 'pretérito perfeito',
      answers: ['aprendi'],
    },
    {
      sentence: 'Você {blank} muito sobre a história da arte.',
      verb: 'aprender',
      tense: 'pretérito perfeito',
      answers: ['aprendeu'],
    },
    {
      sentence: 'Ela {blank} a dançar no ano passado.',
      verb: 'aprender',
      tense: 'pretérito perfeito',
      answers: ['aprendeu'],
    },
    {
      sentence: 'Nós {blank} a cozinhar pratos deliciosos juntos.',
      verb: 'aprender',
      tense: 'pretérito perfeito',
      answers: ['aprendemos'],
    },
    {
      sentence: 'Eles {blank} a tocar violão durante as férias.',
      verb: 'aprender',
      tense: 'pretérito perfeito',
      answers: ['aprenderam'],
    },
    {
      sentence: 'João {blank} a programar no último semestre.',
      verb: 'aprender',
      tense: 'pretérito perfeito',
      answers: ['aprendeu'],
    },
    {
      sentence: 'Você e eu {blank} muitas coisas novas na conferência.',
      verb: 'aprender',
      tense: 'pretérito perfeito',
      answers: ['aprendemos'],
    },
    {
      sentence: 'Maria {blank} a falar francês rapidamente.',
      verb: 'aprender',
      tense: 'pretérito perfeito',
      answers: ['aprendeu'],
    },
    {
      sentence: 'As crianças {blank} a respeitar os mais velhos.',
      verb: 'aprender',
      tense: 'pretérito perfeito',
      answers: ['aprenderam'],
    },
    {
      sentence: 'Nós {blank} o que realmente importa na vida.',
      verb: 'aprender',
      tense: 'pretérito perfeito',
      answers: ['aprendemos'],
    },
    {
      sentence: 'Eu {blank} uma nova habilidade no próximo semestre.',
      verb: 'aprender',
      tense: 'futuro',
      answers: ['aprenderai', 'vou aprender'],
    },
    {
      sentence: 'Vocês {blank} sobre matemática avançada na próxima aula.',
      verb: 'aprender',
      tense: 'futuro',
      answers: ['aprenderão', 'vão aprender'],
    },
    {
      sentence: 'Ela {blank} a importância da reciclagem no futuro.',
      verb: 'aprender',
      tense: 'futuro',
      answers: ['aprenderá', 'vai aprender'],
    },
    {
      sentence: 'Nós {blank} novas línguas durante a viagem seguinte.',
      verb: 'aprender',
      tense: 'futuro',
      answers: ['aprenderemos', 'vamos aprender'],
    },
    {
      sentence: 'Você {blank} a tocar violão em breve.',
      verb: 'aprender',
      tense: 'futuro',
      answers: ['aprenderá', 'vai aprender'],
    },
    {
      sentence: 'Elas {blank} sobre história no próximo mês.',
      verb: 'aprender',
      tense: 'futuro',
      answers: ['aprenderão', 'vão aprender'],
    },
    {
      sentence: 'Pedro {blank} a programar em uma semana.',
      verb: 'aprender',
      tense: 'futuro',
      answers: ['aprenderá', 'vai aprender'],
    },
    {
      sentence: 'Nós {blank} a importância da saúde mental no futuro.',
      verb: 'aprender',
      tense: 'futuro',
      answers: ['aprenderemos', 'vamos aprender'],
    },
    {
      sentence:
        'Ela {blank} sobre culinária italiana em sua próxima aula de cozinha.',
      verb: 'aprender',
      tense: 'futuro',
      answers: ['aprenderá', 'vai aprender'],
    },
    {
      sentence: 'Você e eu {blank} a dançar juntos na próxima festa.',
      verb: 'aprender',
      tense: 'futuro',
      answers: ['aprenderemos', 'vamos aprender'],
    },
    {
      sentence: 'Eu {blank} muito sobre a história do Brasil.',
      verb: 'aprender',
      tense: 'presente',
      answers: ['aprendo'],
    },
    {
      sentence: 'Ela {blank} francês na escola todos os dias.',
      verb: 'aprender',
      tense: 'presente',
      answers: ['aprende'],
    },
    {
      sentence: 'Nós {blank} novas técnicas de trabalho.',
      verb: 'aprender',
      tense: 'presente',
      answers: ['aprendemos'],
    },
    {
      sentence: 'Você {blank} a tocar violão muito bem.',
      verb: 'aprender',
      tense: 'presente',
      answers: ['aprende'],
    },
    {
      sentence: 'Eles {blank} sobre as mudanças climáticas.',
      verb: 'aprender',
      tense: 'presente',
      answers: ['aprendem'],
    },
    {
      sentence: 'João {blank} matemática com facilidade.',
      verb: 'aprender',
      tense: 'presente',
      answers: ['aprende'],
    },
    {
      sentence: 'Maria e eu {blank} sobre programação juntos.',
      verb: 'aprender',
      tense: 'presente',
      answers: ['aprendemos'],
    },
    {
      sentence: 'Vocês {blank} muito nos últimos meses.',
      verb: 'aprender',
      tense: 'presente',
      answers: ['aprendem'],
    },
    {
      sentence: 'A Ana {blank} a dançar balé agora.',
      verb: 'aprender',
      tense: 'presente',
      answers: ['aprende'],
    },
    {
      sentence: 'Elas {blank} como cozinhar pratos novos.',
      verb: 'aprender',
      tense: 'presente',
      answers: ['aprendem'],
    },
  ],
};
