import { ProblemList } from '../Problems';

export const arrumar: ProblemList = {
  verb: 'arrumar',
  problems: [
    {
      sentence: 'Eu {blank} todos os brinquedos antes da festa.',
      verb: 'arrumar',
      tense: 'futuro',
      answers: ['vou arrumar', 'arrumarei'],
    },
    {
      sentence: 'Ela {blank} a sala para receber os convidados.',
      verb: 'arrumar',
      tense: 'futuro',
      answers: ['vai arrumar', 'arrumará'],
    },
    {
      sentence: 'Nós {blank} os arquivos na próxima reunião.',
      verb: 'arrumar',
      tense: 'futuro',
      answers: ['vamos arrumar', 'arrumaremos'],
    },
    {
      sentence: 'Vocês {blank} as malas antes de viajar.',
      verb: 'arrumar',
      tense: 'futuro',
      answers: ['vão arrumar', 'arrumarão'],
    },
    {
      sentence: 'João {blank} seu quarto no próximo sábado.',
      verb: 'arrumar',
      tense: 'futuro',
      answers: ['vai arrumar', 'arrumará'],
    },
    {
      sentence: 'Maria e eu {blank} tudo para a apresentação.',
      verb: 'arrumar',
      tense: 'futuro',
      answers: ['vamos arrumar', 'arrumaremos'],
    },
    {
      sentence: 'Eles {blank} os livros na biblioteca.',
      verb: 'arrumar',
      tense: 'futuro',
      answers: ['vão arrumar', 'arrumarão'],
    },
    {
      sentence: 'Você {blank} a cozinha antes de cozinhar.',
      verb: 'arrumar',
      tense: 'futuro',
      answers: ['vai arrumar', 'arrumará'],
    },
    {
      sentence: 'Ana {blank} os documentos para a reunião amanhã.',
      verb: 'arrumar',
      tense: 'futuro',
      answers: ['vai arrumar', 'arrumará'],
    },
    {
      sentence: 'Nós {blank} as cadeiras para o evento.',
      verb: 'arrumar',
      tense: 'futuro',
      answers: ['vamos arrumar', 'arrumaremos'],
    },
    {
      sentence: 'Eu {blank} meu quarto toda semana.',
      verb: 'arrumar',
      tense: 'presente',
      answers: ['arrumo'],
    },
    {
      sentence: 'Ela {blank} a casa antes da festa.',
      verb: 'arrumar',
      tense: 'presente',
      answers: ['arruma'],
    },
    {
      sentence: 'Nós {blank} as coisas para a viagem.',
      verb: 'arrumar',
      tense: 'presente',
      answers: ['arrumamos'],
    },
    {
      sentence: 'Você {blank} seu carro de vez em quando.',
      verb: 'arrumar',
      tense: 'presente',
      answers: ['arruma'],
    },
    {
      sentence: 'Eles {blank} os documentos para a reunião.',
      verb: 'arrumar',
      tense: 'presente',
      answers: ['arrumam'],
    },
    {
      sentence: 'A Ana {blank} a mochila antes de ir para a escola.',
      verb: 'arrumar',
      tense: 'presente',
      answers: ['arruma'],
    },
    {
      sentence: 'João e eu {blank} o escritório juntos.',
      verb: 'arrumar',
      tense: 'presente',
      answers: ['arrumamos'],
    },
    {
      sentence: 'Vocês {blank} o espaço para o evento amanhã.',
      verb: 'arrumar',
      tense: 'presente',
      answers: ['arrumam'],
    },
    {
      sentence: 'Meu irmão {blank} seu quarto sempre que pode.',
      verb: 'arrumar',
      tense: 'presente',
      answers: ['arruma'],
    },
    {
      sentence: 'Tu {blank} a área de lazer para os convidados.',
      verb: 'arrumar',
      tense: 'presente',
      answers: ['arrumas'],
    },
    {
      sentence: 'Eu {blank} meu quarto antes da visita.',
      verb: 'arrumar',
      tense: 'pretérito perfeito',
      answers: ['arrumei'],
    },
    {
      sentence: 'Ela {blank} as coisas para a viagem.',
      verb: 'arrumar',
      tense: 'pretérito perfeito',
      answers: ['arrumou'],
    },
    {
      sentence: 'Nós {blank} a casa para a festa.',
      verb: 'arrumar',
      tense: 'pretérito perfeito',
      answers: ['arrumamos'],
    },
    {
      sentence: 'Você {blank} os livros na estante.',
      verb: 'arrumar',
      tense: 'pretérito perfeito',
      answers: ['arrumou'],
    },
    {
      sentence: 'Eles {blank} os detalhes do evento.',
      verb: 'arrumar',
      tense: 'pretérito perfeito',
      answers: ['arrumaram'],
    },
    {
      sentence: 'Carlos {blank} o carro antes da viagem.',
      verb: 'arrumar',
      tense: 'pretérito perfeito',
      answers: ['arrumou'],
    },
    {
      sentence: 'Ana e eu {blank} tudo para a apresentação.',
      verb: 'arrumar',
      tense: 'pretérito perfeito',
      answers: ['arrumamos'],
    },
    {
      sentence: 'Vocês {blank} os materiais para o projeto.',
      verb: 'arrumar',
      tense: 'pretérito perfeito',
      answers: ['arrumaram'],
    },
    {
      sentence: 'Ela {blank} seu armário no fim de semana.',
      verb: 'arrumar',
      tense: 'pretérito perfeito',
      answers: ['arrumou'],
    },
    {
      sentence: 'Meu irmão {blank} a garagem ontem.',
      verb: 'arrumar',
      tense: 'pretérito perfeito',
      answers: ['arrumou'],
    },
  ],
};
