import { ProblemList } from '../Problems';

export const assinar: ProblemList = {
  verb: 'assinar',
  problems: [
    {
      sentence: 'Eu {blank} o contrato na [quinta-feira] passada.',
      verb: 'assinar',
      tense: 'pretérito perfeito',
      answers: ['assinei'],
    },
    {
      sentence: 'Ela {blank} todos os papéis que precisávamos.',
      verb: 'assinar',
      tense: 'pretérito perfeito',
      answers: ['assinou'],
    },
    {
      sentence: 'Nós {blank} a proposta durante a reunião.',
      verb: 'assinar',
      tense: 'pretérito perfeito',
      answers: ['assinamos'],
    },
    {
      sentence: 'Você {blank} o documento que enviei?',
      verb: 'assinar',
      tense: 'pretérito perfeito',
      answers: ['assinou'],
    },
    {
      sentence: 'João {blank} o termo de compromisso ontem.',
      verb: 'assinar',
      tense: 'pretérito perfeito',
      answers: ['assinou'],
    },
    {
      sentence: 'Maria e eu {blank} o acordo na presença de todos.',
      verb: 'assinar',
      tense: 'pretérito perfeito',
      answers: ['assinamos'],
    },
    {
      sentence: 'Vocês {blank} os contratos com as cláusulas revisadas.',
      verb: 'assinar',
      tense: 'pretérito perfeito',
      answers: ['assinaram'],
    },
    {
      sentence: 'Ana {blank} o registro na semana passada.',
      verb: 'assinar',
      tense: 'pretérito perfeito',
      answers: ['assinou'],
    },
    {
      sentence: 'Os alunos {blank} os documentos necessário para a matrícula.',
      verb: 'assinar',
      tense: 'pretérito perfeito',
      answers: ['assinaram'],
    },
    {
      sentence: 'Eu e você {blank} a petição antes do prazo.',
      verb: 'assinar',
      tense: 'pretérito perfeito',
      answers: ['assinamos'],
    },
    {
      sentence: 'Eu {blank} o contrato amanhã.',
      verb: 'assinar',
      tense: 'futuro',
      answers: ['assinarei', 'vou assinar'],
    },
    {
      sentence: 'Vocês {blank} os papéis na próxima semana.',
      verb: 'assinar',
      tense: 'futuro',
      answers: ['assinarão', 'vão assinar'],
    },
    {
      sentence: 'Ela {blank} o documento importante depois do almoço.',
      verb: 'assinar',
      tense: 'futuro',
      answers: ['assinará', 'vai assinar'],
    },
    {
      sentence: 'Nós {blank} o acordo na próxima reunião.',
      verb: 'assinar',
      tense: 'futuro',
      answers: ['assinaremos', 'vamos assinar'],
    },
    {
      sentence: 'Você {blank} os termos de serviço no site.',
      verb: 'assinar',
      tense: 'futuro',
      answers: ['assinará', 'vai assinar'],
    },
    {
      sentence: 'Eles {blank} o compromisso com a empresa na sexta-feira.',
      verb: 'assinar',
      tense: 'futuro',
      answers: ['assinarão', 'vão assinar'],
    },
    {
      sentence: 'Maria {blank} o formulário até o final do dia.',
      verb: 'assinar',
      tense: 'futuro',
      answers: ['assinará', 'vai assinar'],
    },
    {
      sentence: 'João e eu {blank} o novo projeto em breve.',
      verb: 'assinar',
      tense: 'futuro',
      answers: ['assinaremos', 'vamos assinar'],
    },
    {
      sentence: 'Vocês {blank} a petição até amanhã.',
      verb: 'assinar',
      tense: 'futuro',
      answers: ['assinarão', 'vão assinar'],
    },
    {
      sentence: 'Ela e eu {blank} o contrato de locação na segunda-feira.',
      verb: 'assinar',
      tense: 'futuro',
      answers: ['assinaremos', 'vamos assinar'],
    },
    {
      sentence: 'Eu {blank} o contrato hoje de manhã.',
      verb: 'assinar',
      tense: 'presente',
      answers: ['assino'],
    },
    {
      sentence: 'Você {blank} a petição para o juiz.',
      verb: 'assinar',
      tense: 'presente',
      answers: ['assina'],
    },
    {
      sentence: 'Ela {blank} todos os documentos antes do prazo.',
      verb: 'assinar',
      tense: 'presente',
      answers: ['assina'],
    },
    {
      sentence: 'Nós {blank} o acordo na próxima reunião.',
      verb: 'assinar',
      tense: 'presente',
      answers: ['assinamos'],
    },
    {
      sentence: 'Eles {blank} a minuta que você pediu.',
      verb: 'assinar',
      tense: 'presente',
      answers: ['assinam'],
    },
    {
      sentence: 'Lucas {blank} o recibo corretamente.',
      verb: 'assinar',
      tense: 'presente',
      answers: ['assina'],
    },
    {
      sentence: 'Você e eu {blank} os papéis juntos.',
      verb: 'assinar',
      tense: 'presente',
      answers: ['assinamos'],
    },
    {
      sentence: 'As alunas {blank} o projeto na última aula.',
      verb: 'assinar',
      tense: 'presente',
      answers: ['assinam'],
    },
    {
      sentence: 'A diretora {blank} o plano de ação nesta semana.',
      verb: 'assinar',
      tense: 'presente',
      answers: ['assina'],
    },
    {
      sentence: 'Você {blank} a proposta para o cliente ontem.',
      verb: 'assinar',
      tense: 'presente',
      answers: ['assina'],
    },
  ],
};
