import { ProblemList } from '../Problems';

export const assistir: ProblemList = {
  verb: 'assistir',
  problems: [
    {
      sentence: 'Eu {blank} ao filme que você recomendou.',
      verb: 'assistir',
      tense: 'pretérito perfeito',
      answers: ['assisti'],
    },
    {
      sentence: 'Ela {blank} uma série incrível no fim de semana.',
      verb: 'assistir',
      tense: 'pretérito perfeito',
      answers: ['assistiu'],
    },
    {
      sentence: 'Nós {blank} à peça de teatro na sexta-feira passada.',
      verb: 'assistir',
      tense: 'pretérito perfeito',
      answers: ['assistimos'],
    },
    {
      sentence: 'Você {blank} ao documentário que passou na TV?',
      verb: 'assistir',
      tense: 'pretérito perfeito',
      answers: ['assistiu'],
    },
    {
      sentence: 'Meus amigos {blank} a final do campeonato juntos.',
      verb: 'assistir',
      tense: 'pretérito perfeito',
      answers: ['assistiram'],
    },
    {
      sentence: 'João {blank} ao jogo do seu time favorito.',
      verb: 'assistir',
      tense: 'pretérito perfeito',
      answers: ['assistiu'],
    },
    {
      sentence: 'Nós {blank} às aulas online durante a pandemia.',
      verb: 'assistir',
      tense: 'pretérito perfeito',
      answers: ['assistimos'],
    },
    {
      sentence: 'Você e eu {blank} o curso de culinária no mês passado.',
      verb: 'assistir',
      tense: 'pretérito perfeito',
      answers: ['assistimos'],
    },
    {
      sentence: 'As crianças {blank} ao filme de animação ontem.',
      verb: 'assistir',
      tense: 'pretérito perfeito',
      answers: ['assistiram'],
    },
    {
      sentence: 'Ana {blank} a série nova e adorou.',
      verb: 'assistir',
      tense: 'pretérito perfeito',
      answers: ['assistiu'],
    },
    {
      sentence: 'Nós {blank} ao filme no próximo sábado.',
      verb: 'assistir',
      tense: 'futuro',
      answers: ['assistiremos', 'vamos assistir'],
    },
    {
      sentence: 'Você {blank} à apresentação na próxima [quinta-feira].',
      verb: 'assistir',
      tense: 'futuro',
      answers: ['assistirá', 'vai assistir'],
    },
    {
      sentence: 'Eles {blank} ao concerto no próximo mês.',
      verb: 'assistir',
      tense: 'futuro',
      answers: ['assistirão', 'vão assistir'],
    },
    {
      sentence: 'Eu {blank} aquele filme na próxima semana.',
      verb: 'assistir',
      tense: 'futuro',
      answers: ['assistirei', 'vou assistir'],
    },
    {
      sentence: 'Maria {blank} à aula de dança na sexta-feira.',
      verb: 'assistir',
      tense: 'futuro',
      answers: ['assistirá', 'vai assistir'],
    },
    {
      sentence: 'Você e eu {blank} juntos ao programa na terça-feira.',
      verb: 'assistir',
      tense: 'futuro',
      answers: ['assistiremos', 'vamos assistir'],
    },
    {
      sentence: 'João {blank} à partida de futebol no próximo domingo.',
      verb: 'assistir',
      tense: 'futuro',
      answers: ['assistirá', 'vai assistir'],
    },
    {
      sentence: 'Ana e Pedro {blank} ao show na próxima semana.',
      verb: 'assistir',
      tense: 'futuro',
      answers: ['assistirão', 'vão assistir'],
    },
    {
      sentence: 'Vocês {blank} à conferência no próximo mês.',
      verb: 'assistir',
      tense: 'futuro',
      answers: ['assistirão', 'vão assistir'],
    },
    {
      sentence:
        'Eu e minha irmã {blank} a nova série na plataforma de streaming.',
      verb: 'assistir',
      tense: 'futuro',
      answers: ['assistiremos', 'vamos assistir'],
    },
    {
      sentence: 'Eu {blank} todos os episódios da série nova.',
      verb: 'assistir',
      tense: 'presente',
      answers: ['assisto'],
    },
    {
      sentence: 'Ela {blank} a aula de matemática todas as segundas.',
      verb: 'assistir',
      tense: 'presente',
      answers: ['assiste'],
    },
    {
      sentence: 'Nós {blank} o filme no cinema hoje à noite.',
      verb: 'assistir',
      tense: 'presente',
      answers: ['assistimos'],
    },
    {
      sentence: 'Você {blank} ao meu podcast frequentemente.',
      verb: 'assistir',
      tense: 'presente',
      answers: ['assiste'],
    },
    {
      sentence: 'Eles {blank} os jogos do campeonato todos os sábados.',
      verb: 'assistir',
      tense: 'presente',
      answers: ['assistem'],
    },
    {
      sentence: 'Carlos e eu {blank} à conferência online neste mês.',
      verb: 'assistir',
      tense: 'presente',
      answers: ['assistimos'],
    },
    {
      sentence: 'Maria e você {blank} ao espetáculo de dança amanhã.',
      verb: 'assistir',
      tense: 'presente',
      answers: ['assistem'],
    },
    {
      sentence: 'Tu {blank} as notícias pela manhã todos os dias.',
      verb: 'assistir',
      tense: 'presente',
      answers: ['assistís'],
    },
    {
      sentence: 'A gente {blank} ao documentário sobre natureza hoje.',
      verb: 'assistir',
      tense: 'presente',
      answers: ['assiste'],
    },
    {
      sentence: 'Seu pai {blank} os jogos de futebol todos os domingos.',
      verb: 'assistir',
      tense: 'presente',
      answers: ['assiste'],
    },
  ],
};
