import { ProblemList } from '../Problems';

export const beber: ProblemList = {
  verb: 'beber',
  problems: [
    {
      sentence: 'Eu {blank} um copo de água antes da corrida.',
      verb: 'beber',
      tense: 'pretérito perfeito',
      answers: ['bebi'],
    },
    {
      sentence: 'Ela {blank} um suco natural na festa.',
      verb: 'beber',
      tense: 'pretérito perfeito',
      answers: ['bebeu'],
    },
    {
      sentence: 'Nós {blank} cerveja na reunião de amigos.',
      verb: 'beber',
      tense: 'pretérito perfeito',
      answers: ['bebemos'],
    },
    {
      sentence: 'Você {blank} muito refrigerante na festa de aniversário.',
      verb: 'beber',
      tense: 'pretérito perfeito',
      answers: ['bebeu'],
    },
    {
      sentence: 'Lucas {blank} vinho tinto em seu jantar.',
      verb: 'beber',
      tense: 'pretérito perfeito',
      answers: ['bebeu'],
    },
    {
      sentence: 'Elas {blank} água de coco na praia.',
      verb: 'beber',
      tense: 'pretérito perfeito',
      answers: ['beberam'],
    },
    {
      sentence: 'Nós {blank} café quente pela manhã.',
      verb: 'beber',
      tense: 'pretérito perfeito',
      answers: ['bebemos'],
    },
    {
      sentence: 'João {blank} um chá relaxante à noite.',
      verb: 'beber',
      tense: 'pretérito perfeito',
      answers: ['bebeu'],
    },
    {
      sentence: 'Vocês {blank} seus líquidos diários recomendados.',
      verb: 'beber',
      tense: 'pretérito perfeito',
      answers: ['beberam'],
    },
    {
      sentence: 'Ana {blank} uma limonada muito refrescante.',
      verb: 'beber',
      tense: 'pretérito perfeito',
      answers: ['bebeu'],
    },
    {
      sentence: 'Eu {blank} um copo de água antes da reunião.',
      verb: 'beber',
      tense: 'futuro',
      answers: ['beberei', 'vou beber'],
    },
    {
      sentence: 'Ela {blank} um refrigerante no aniversário.',
      verb: 'beber',
      tense: 'futuro',
      answers: ['bebeu', 'vaó beber'],
    },
    {
      sentence: 'Nós {blank} um brinde especial na festa.',
      verb: 'beber',
      tense: 'futuro',
      answers: ['beberemos', 'vamos beber'],
    },
    {
      sentence: 'Vocês {blank} suco natural amanhã.',
      verb: 'beber',
      tense: 'futuro',
      answers: ['beberão', 'vão beber'],
    },
    {
      sentence: 'Ele {blank} vinho na comemoração.',
      verb: 'beber',
      tense: 'futuro',
      answers: ['beberá', 'vai beber'],
    },
    {
      sentence: 'Eu {blank} mais água durante o treino.',
      verb: 'beber',
      tense: 'futuro',
      answers: ['beberei', 'vou beber'],
    },
    {
      sentence: 'Maria {blank} um café quentinho à tarde.',
      verb: 'beber',
      tense: 'futuro',
      answers: ['bebeu', 'vai beber'],
    },
    {
      sentence: 'Você {blank} chá gelado no verão.',
      verb: 'beber',
      tense: 'futuro',
      answers: ['beberá', 'vai beber'],
    },
    {
      sentence: 'Nós {blank} cerveja na próxima festa.',
      verb: 'beber',
      tense: 'futuro',
      answers: ['bebere-mos', 'vamos beber'],
    },
    {
      sentence: 'Eles {blank} um coquetel diferente este fim de semana.',
      verb: 'beber',
      tense: 'futuro',
      answers: ['beberão', 'vão beber'],
    },
    {
      sentence: 'Eu {blank} água todos os dias.',
      verb: 'beber',
      tense: 'presente',
      answers: ['bebo'],
    },
    {
      sentence: 'Ela {blank} suco de laranja no café da manhã.',
      verb: 'beber',
      tense: 'presente',
      answers: ['bebe'],
    },
    {
      sentence: 'Nós {blank} vinho tinto durante o jantar.',
      verb: 'beber',
      tense: 'presente',
      answers: ['bebemos'],
    },
    {
      sentence: 'Vocês {blank} cerveja nas festas.',
      verb: 'beber',
      tense: 'presente',
      answers: ['bebem'],
    },
    {
      sentence: 'Ele {blank} água mineral no trabalho.',
      verb: 'beber',
      tense: 'presente',
      answers: ['bebe'],
    },
    {
      sentence: 'Maria {blank} chá todos os dias.',
      verb: 'beber',
      tense: 'presente',
      answers: ['bebe'],
    },
    {
      sentence: 'João e eu {blank} refrigerante juntos.',
      verb: 'beber',
      tense: 'presente',
      answers: ['bebemos'],
    },
    {
      sentence: 'Vocês {blank} sempre café pela manhã.',
      verb: 'beber',
      tense: 'presente',
      answers: ['bebem'],
    },
    {
      sentence: 'Eu e Ana {blank} água de coco na praia.',
      verb: 'beber',
      tense: 'presente',
      answers: ['bebemos'],
    },
    {
      sentence: 'Ele {blank} leite com chocolate antes de dormir.',
      verb: 'beber',
      tense: 'presente',
      answers: ['bebe'],
    },
  ],
};
