import { ProblemList } from '../Problems';

export const brincar: ProblemList = {
  verb: 'brincar',
  problems: [
    {
      sentence: 'Eu {blank} no parque ontem à tarde.',
      verb: 'brincar',
      tense: 'pretérito perfeito',
      answers: ['brinquei'],
    },
    {
      sentence: 'Ela {blank} com os amigos na semana passada.',
      verb: 'brincar',
      tense: 'pretérito perfeito',
      answers: ['brincou'],
    },
    {
      sentence: 'Nós {blank} muito durante as férias.',
      verb: 'brincar',
      tense: 'pretérito perfeito',
      answers: ['brincamos'],
    },
    {
      sentence: 'Você {blank} no clube ontem à noite.',
      verb: 'brincar',
      tense: 'pretérito perfeito',
      answers: ['brincou'],
    },
    {
      sentence: 'As crianças {blank} na chuva no sábado.',
      verb: 'brincar',
      tense: 'pretérito perfeito',
      answers: ['brincaram'],
    },
    {
      sentence: 'Josué {blank} com seu cachorro na sexta-feira.',
      verb: 'brincar',
      tense: 'pretérito perfeito',
      answers: ['brincou'],
    },
    {
      sentence: 'Nós {blank} de esconde-esconde no quintal.',
      verb: 'brincar',
      tense: 'pretérito perfeito',
      answers: ['brincamos'],
    },
    {
      sentence: 'Vocês {blank} de bola no campo ontem.',
      verb: 'brincar',
      tense: 'pretérito perfeito',
      answers: ['brincaram'],
    },
    {
      sentence: 'Maria e João {blank} na festa de aniversário.',
      verb: 'brincar',
      tense: 'pretérito perfeito',
      answers: ['brincaram'],
    },
    {
      sentence: 'Eu e você {blank} muito juntos na infância.',
      verb: 'brincar',
      tense: 'pretérito perfeito',
      answers: ['brincamos'],
    },
    {
      sentence: 'Eu {blank} no parque com meus amigos.',
      verb: 'brincar',
      tense: 'presente',
      answers: ['brinco'],
    },
    {
      sentence: 'Ela {blank} com os brinquedos novos.',
      verb: 'brincar',
      tense: 'presente',
      answers: ['brinca'],
    },
    {
      sentence: 'Nós {blank} juntos todo fim de semana.',
      verb: 'brincar',
      tense: 'presente',
      answers: ['brincamos'],
    },
    {
      sentence: 'Você {blank} muito bem com as crianças.',
      verb: 'brincar',
      tense: 'presente',
      answers: ['brinca'],
    },
    {
      sentence: 'Eles {blank} no colégio durante o recreio.',
      verb: 'brincar',
      tense: 'presente',
      answers: ['brincam'],
    },
    {
      sentence: 'João {blank} com os amigos na festa.',
      verb: 'brincar',
      tense: 'presente',
      answers: ['brinca'],
    },
    {
      sentence: 'Maria e eu {blank} de esconde-esconde.',
      verb: 'brincar',
      tense: 'presente',
      answers: ['brincamos'],
    },
    {
      sentence: 'Vocês {blank} felizes no parque de diversões.',
      verb: 'brincar',
      tense: 'presente',
      answers: ['brincam'],
    },
    {
      sentence: 'A Ana {blank} com o seu cachorro no quintal.',
      verb: 'brincar',
      tense: 'presente',
      answers: ['brinca'],
    },
    {
      sentence: 'Nós {blank} de futebol no intervalo.',
      verb: 'brincar',
      tense: 'presente',
      answers: ['brincamos'],
    },
    {
      sentence: 'Eu {blank} com os meus amigos no parque amanhã.',
      verb: 'brincar',
      tense: 'futuro',
      answers: ['brincarei', 'vou brincar'],
    },
    {
      sentence: 'Ela {blank} com seus filhos durante o feriado.',
      verb: 'brincar',
      tense: 'futuro',
      answers: ['brincará', 'vai brincar'],
    },
    {
      sentence: 'Nós {blank} na praia na próxima semana.',
      verb: 'brincar',
      tense: 'futuro',
      answers: ['brincaremos', 'vamos brincar'],
    },
    {
      sentence: 'Vocês {blank} com os jogos novos no sábado.',
      verb: 'brincar',
      tense: 'futuro',
      answers: ['brincarão', 'vão brincar'],
    },
    {
      sentence: 'Eles {blank} na escola no próximo mês.',
      verb: 'brincar',
      tense: 'futuro',
      answers: ['brincarão', 'vão brincar'],
    },
    {
      sentence: 'João {blank} com os colegas na festa no domingo.',
      verb: 'brincar',
      tense: 'futuro',
      answers: ['brincará', 'vai brincar'],
    },
    {
      sentence: 'Maria e eu {blank} no parque infantil na próxima sexta.',
      verb: 'brincar',
      tense: 'futuro',
      answers: ['brincaremos', 'vamos brincar'],
    },
    {
      sentence: 'Você {blank} com o cachorro amanhã à tarde.',
      verb: 'brincar',
      tense: 'futuro',
      answers: ['brincará', 'vai brincar'],
    },
    {
      sentence: 'Elas {blank} juntas na competição de dança.',
      verb: 'brincar',
      tense: 'futuro',
      answers: ['brincarão', 'vão brincar'],
    },
    {
      sentence: 'Nós {blank} com os novos brinquedos este mês.',
      verb: 'brincar',
      tense: 'futuro',
      answers: ['brincaremos', 'vamos brincar'],
    },
  ],
};
