import { ProblemList } from '../Problems';

export const caminhar: ProblemList = {
  verb: 'caminhar',
  problems: [
    {
      sentence: 'Eu {blank} no parque ontem à tarde.',
      verb: 'caminhar',
      tense: 'pretérito perfeito',
      answers: ['caminhei'],
    },
    {
      sentence: 'Ela {blank} com o cachorro antes do jantar.',
      verb: 'caminhar',
      tense: 'pretérito perfeito',
      answers: ['caminhou'],
    },
    {
      sentence: 'Nós {blank} pela praia durante o fim de semana.',
      verb: 'caminhar',
      tense: 'pretérito perfeito',
      answers: ['caminhamos'],
    },
    {
      sentence: 'Você {blank} muito rápido na última corrida.',
      verb: 'caminhar',
      tense: 'pretérito perfeito',
      answers: ['caminhou'],
    },
    {
      sentence: 'Maria {blank} até a escola pela manhã.',
      verb: 'caminhar',
      tense: 'pretérito perfeito',
      answers: ['caminhou'],
    },
    {
      sentence: 'Eu e João {blank} juntos no centro da cidade.',
      verb: 'caminhar',
      tense: 'pretérito perfeito',
      answers: ['caminhamos'],
    },
    {
      sentence: 'Eles {blank} em direção ao campo no sábado.',
      verb: 'caminhar',
      tense: 'pretérito perfeito',
      answers: ['caminharam'],
    },
    {
      sentence: 'Você e Ana {blank} ao redor do lago.',
      verb: 'caminhar',
      tense: 'pretérito perfeito',
      answers: ['caminharam'],
    },
    {
      sentence: 'Ele {blank} na trilha e viu muitos pássaros.',
      verb: 'caminhar',
      tense: 'pretérito perfeito',
      answers: ['caminhou'],
    },
    {
      sentence: 'Nós {blank} pela cidade e conhecemos novos lugares.',
      verb: 'caminhar',
      tense: 'pretérito perfeito',
      answers: ['caminhamos'],
    },
    {
      sentence: 'Eu {blank} na trilha amanhã de manhã.',
      verb: 'caminhar',
      tense: 'futuro',
      answers: ['caminharei', 'vou caminhar'],
    },
    {
      sentence: 'Ela {blank} pelo parque no próximo domingo.',
      verb: 'caminhar',
      tense: 'futuro',
      answers: ['caminhará', 'vai caminhar'],
    },
    {
      sentence: 'Nós {blank} juntos na corrida da semana que vem.',
      verb: 'caminhar',
      tense: 'futuro',
      answers: ['caminharemos', 'vamos caminhar'],
    },
    {
      sentence: 'Você {blank} na praia durante as férias.',
      verb: 'caminhar',
      tense: 'futuro',
      answers: ['caminhará', 'vai caminhar'],
    },
    {
      sentence: 'Eles {blank} para a cidade na próxima [quinta-feira].',
      verb: 'caminhar',
      tense: 'futuro',
      answers: ['caminharão', 'vão caminhar'],
    },
    {
      sentence: 'Lúcia e eu {blank} até a escola tomorrow.',
      verb: 'caminhar',
      tense: 'futuro',
      answers: ['caminharemos', 'vamos caminhar'],
    },
    {
      sentence: 'Tu {blank} no deserto durante a expedição.',
      verb: 'caminhar',
      tense: 'futuro',
      answers: ['caminharás', 'vais caminhar'],
    },
    {
      sentence: 'Marcos {blank} no bosque na próxima semana.',
      verb: 'caminhar',
      tense: 'futuro',
      answers: ['caminhará', 'vai caminhar'],
    },
    {
      sentence: 'Vocês {blank} para a montanha no próximo feriado.',
      verb: 'caminhar',
      tense: 'futuro',
      answers: ['caminharão', 'vão caminhar'],
    },
    {
      sentence: 'Eu e Ana {blank} pela orla na próxima tarde.',
      verb: 'caminhar',
      tense: 'futuro',
      answers: ['caminharemos', 'vamos caminhar'],
    },
    {
      sentence: 'Eu {blank} todos os dias no parque.',
      verb: 'caminhar',
      tense: 'presente',
      answers: ['caminho'],
    },
    {
      sentence: 'Você {blank} rapidamente na manhã.',
      verb: 'caminhar',
      tense: 'presente',
      answers: ['caminha'],
    },
    {
      sentence: 'Ela {blank} com seus amigos nos finais de semana.',
      verb: 'caminhar',
      tense: 'presente',
      answers: ['caminha'],
    },
    {
      sentence: 'Nós {blank} pela praia durante as férias.',
      verb: 'caminhar',
      tense: 'presente',
      answers: ['caminhamos'],
    },
    {
      sentence: 'Eles {blank} juntos para a escola.',
      verb: 'caminhar',
      tense: 'presente',
      answers: ['caminham'],
    },
    {
      sentence: 'João {blank} na trilha todas as manhãs.',
      verb: 'caminhar',
      tense: 'presente',
      answers: ['caminha'],
    },
    {
      sentence: 'Maria e eu {blank} por horas no centro da cidade.',
      verb: 'caminhar',
      tense: 'presente',
      answers: ['caminhamos'],
    },
    {
      sentence: 'Você e sua irmã {blank} na quadra depois da escola.',
      verb: 'caminhar',
      tense: 'presente',
      answers: ['caminham'],
    },
    {
      sentence: 'Eles {blank} na floresta frequentemente.',
      verb: 'caminhar',
      tense: 'presente',
      answers: ['caminham'],
    },
    {
      sentence: 'Eu e você {blank} para o trabalho juntos.',
      verb: 'caminhar',
      tense: 'presente',
      answers: ['caminhamos'],
    },
  ],
};
