import { ProblemList } from '../Problems';

export const cantar: ProblemList = {
  verb: 'cantar',
  problems: [
    {
      sentence: 'Eu {blank} uma nova música no sábado passado.',
      verb: 'cantar',
      tense: 'pretérito perfeito',
      answers: ['cantei'],
    },
    {
      sentence: 'Ela {blank} no concurso de talentos na escola.',
      verb: 'cantar',
      tense: 'pretérito perfeito',
      answers: ['cantou'],
    },
    {
      sentence: 'Nós {blank} juntos no chá de bebê da Maria.',
      verb: 'cantar',
      tense: 'pretérito perfeito',
      answers: ['cantamos'],
    },
    {
      sentence: 'Você {blank} uma canção linda durante a festa.',
      verb: 'cantar',
      tense: 'pretérito perfeito',
      answers: ['cantou'],
    },
    {
      sentence: 'Eles {blank} no coro da igreja na semana passada.',
      verb: 'cantar',
      tense: 'pretérito perfeito',
      answers: ['cantaram'],
    },
    {
      sentence: 'A Ana {blank} sua música favorita no karaokê.',
      verb: 'cantar',
      tense: 'pretérito perfeito',
      answers: ['cantou'],
    },
    {
      sentence: 'Nós {blank} felizes durante a apresentação da escola.',
      verb: 'cantar',
      tense: 'pretérito perfeito',
      answers: ['cantamos'],
    },
    {
      sentence: 'Você e o João {blank} juntos no evento de caridade.',
      verb: 'cantar',
      tense: 'pretérito perfeito',
      answers: ['cantaram'],
    },
    {
      sentence: 'Eu {blank} no aniversário do Pedro no mês passado.',
      verb: 'cantar',
      tense: 'pretérito perfeito',
      answers: ['cantei'],
    },
    {
      sentence: 'Ela e suas amigas {blank} uma canção famosa no verão.',
      verb: 'cantar',
      tense: 'pretérito perfeito',
      answers: ['cantaram'],
    },
    {
      sentence: 'Eu {blank} todos os dias no chuveiro.',
      verb: 'cantar',
      tense: 'presente',
      answers: ['canto'],
    },
    {
      sentence: 'Ela {blank} muito bem quando está feliz.',
      verb: 'cantar',
      tense: 'presente',
      answers: ['canta'],
    },
    {
      sentence: 'Nós {blank} juntos durante as festas.',
      verb: 'cantar',
      tense: 'presente',
      answers: ['cantamos'],
    },
    {
      sentence: 'Você {blank} a música nova da banda.',
      verb: 'cantar',
      tense: 'presente',
      answers: ['canta'],
    },
    {
      sentence: 'Eles {blank} em coro durante a apresentação.',
      verb: 'cantar',
      tense: 'presente',
      answers: ['cantam'],
    },
    {
      sentence: 'Maria {blank} com sua banda no festival.',
      verb: 'cantar',
      tense: 'presente',
      answers: ['canta'],
    },
    {
      sentence: 'João e eu {blank} em um dueto.',
      verb: 'cantar',
      tense: 'presente',
      answers: ['cantamos'],
    },
    {
      sentence: 'Vocês {blank} as músicas antigas na festa.',
      verb: 'cantar',
      tense: 'presente',
      answers: ['cantam'],
    },
    {
      sentence: 'Nós {blank} as canções que aprendemos na escola.',
      verb: 'cantar',
      tense: 'presente',
      answers: ['cantamos'],
    },
    {
      sentence: 'Lucas {blank} muito bem no concurso.',
      verb: 'cantar',
      tense: 'presente',
      answers: ['canta'],
    },
    {
      sentence: 'Eu {blank} na festa de aniversário do João.',
      verb: 'cantar',
      tense: 'futuro',
      answers: ['cantarei', 'vou cantar'],
    },
    {
      sentence: 'Ela {blank} uma canção nova no próximo show.',
      verb: 'cantar',
      tense: 'futuro',
      answers: ['cantará', 'vai cantar'],
    },
    {
      sentence: 'Nós {blank} juntos no evento de música.',
      verb: 'cantar',
      tense: 'futuro',
      answers: ['cantaremos', 'vamos cantar'],
    },
    {
      sentence: 'Vocês {blank} um dueto na próxima apresentação.',
      verb: 'cantar',
      tense: 'futuro',
      answers: ['cantarão', 'vão cantar'],
    },
    {
      sentence: 'Eu e Maria {blank} na competição de talentos.',
      verb: 'cantar',
      tense: 'futuro',
      answers: ['cantaremos', 'vamos cantar'],
    },
    {
      sentence: 'Ele {blank} suas músicas favoritas na festa.',
      verb: 'cantar',
      tense: 'futuro',
      answers: ['cantará', 'vai cantar'],
    },
    {
      sentence: 'Vocês {blank} para o público no próximo mês.',
      verb: 'cantar',
      tense: 'futuro',
      answers: ['cantarão', 'vão cantar'],
    },
    {
      sentence: 'Eu {blank} um solo impressionante na próxima gravação.',
      verb: 'cantar',
      tense: 'futuro',
      answers: ['cantarei', 'vou cantar'],
    },
    {
      sentence: 'Ela e eu {blank} em um evento beneficente este verão.',
      verb: 'cantar',
      tense: 'futuro',
      answers: ['cantaremos', 'vamos cantar'],
    },
    {
      sentence: 'Eles {blank} todos os clássicos na próxima reunião.',
      verb: 'cantar',
      tense: 'futuro',
      answers: ['cantarão', 'vão cantar'],
    },
  ],
};
