import { ProblemList } from '../Problems';

export const chegar: ProblemList = {
  verb: 'chegar',
  problems: [
    {
      sentence: 'Eu {blank} cedo ao trabalho ontem.',
      verb: 'chegar',
      tense: 'pretérito perfeito',
      answers: ['cheguei'],
    },
    {
      sentence: 'Ela {blank} na festa antes de todo mundo.',
      verb: 'chegar',
      tense: 'pretérito perfeito',
      answers: ['chegou'],
    },
    {
      sentence: 'Nós {blank} a conclusão do projeto na semana passada.',
      verb: 'chegar',
      tense: 'pretérito perfeito',
      answers: ['chegamos'],
    },
    {
      sentence: 'Você {blank} a cidade pela manhã.',
      verb: 'chegar',
      tense: 'pretérito perfeito',
      answers: ['chegou'],
    },
    {
      sentence: 'Eles {blank} até a escola juntos ontem.',
      verb: 'chegar',
      tense: 'pretérito perfeito',
      answers: ['chegaram'],
    },
    {
      sentence: 'A Maria {blank} ao treino mais tarde hoje.',
      verb: 'chegar',
      tense: 'pretérito perfeito',
      answers: ['chegou'],
    },
    {
      sentence: 'Eu {blank} ao café antes de você.',
      verb: 'chegar',
      tense: 'pretérito perfeito',
      answers: ['cheguei'],
    },
    {
      sentence: 'O João {blank} em casa depois do trabalho.',
      verb: 'chegar',
      tense: 'pretérito perfeito',
      answers: ['chegou'],
    },
    {
      sentence: 'Vocês {blank} a um acordo rapidamente.',
      verb: 'chegar',
      tense: 'pretérito perfeito',
      answers: ['chegaram'],
    },
    {
      sentence: 'Ela e eu {blank} a um entendimento mútuo.',
      verb: 'chegar',
      tense: 'pretérito perfeito',
      answers: ['chegamos'],
    },
    {
      sentence: 'Eu {blank} na festa mais tarde.',
      verb: 'chegar',
      tense: 'futuro',
      answers: ['chegarei', 'vou chegar'],
    },
    {
      sentence: 'Ela {blank} em casa antes do jantar.',
      verb: 'chegar',
      tense: 'futuro',
      answers: ['chegará', 'vai chegar'],
    },
    {
      sentence: 'Nós {blank} ao evento juntos.',
      verb: 'chegar',
      tense: 'futuro',
      answers: ['chegaremos', 'vamos chegar'],
    },
    {
      sentence: 'Vocês {blank} ao escritório amanhã de manhã.',
      verb: 'chegar',
      tense: 'futuro',
      answers: ['chegarão', 'vão chegar'],
    },
    {
      sentence: 'Eles {blank} a qualquer momento.',
      verb: 'chegar',
      tense: 'futuro',
      answers: ['chegarão', 'vão chegar'],
    },
    {
      sentence: 'Maria {blank} à aula assim que puder.',
      verb: 'chegar',
      tense: 'futuro',
      answers: ['chegará', 'vai chegar'],
    },
    {
      sentence: 'Você {blank} em São Paulo na sexta-feira.',
      verb: 'chegar',
      tense: 'futuro',
      answers: ['chegará', 'vai chegar'],
    },
    {
      sentence: 'Luiz e eu {blank} ao parque mais tarde.',
      verb: 'chegar',
      tense: 'futuro',
      answers: ['chegaremos', 'vamos chegar'],
    },
    {
      sentence: 'A turma {blank} ao museu no próximo mês.',
      verb: 'chegar',
      tense: 'futuro',
      answers: ['chegará', 'vai chegar'],
    },
    {
      sentence: 'Você e Ana {blank} juntos na próxima reunião.',
      verb: 'chegar',
      tense: 'futuro',
      answers: ['chegarão', 'vão chegar'],
    },
    {
      sentence: 'Eu {blank} à festa no sábado.',
      verb: 'chegar',
      tense: 'presente',
      answers: ['chego'],
    },
    {
      sentence: 'Você {blank} cedo todos os dias.',
      verb: 'chegar',
      tense: 'presente',
      answers: ['chega'],
    },
    {
      sentence: 'Ela {blank} sempre pontual.',
      verb: 'chegar',
      tense: 'presente',
      answers: ['chega'],
    },
    {
      sentence: 'Nós {blank} juntos ao trabalho.',
      verb: 'chegar',
      tense: 'presente',
      answers: ['chegamos'],
    },
    {
      sentence: 'Eles {blank} no horário combinado.',
      verb: 'chegar',
      tense: 'presente',
      answers: ['chegam'],
    },
    {
      sentence: 'Você e eu {blank} sempre no mesmo momento.',
      verb: 'chegar',
      tense: 'presente',
      answers: ['chegamos'],
    },
    {
      sentence: 'Maria {blank} em casa todas as noites.',
      verb: 'chegar',
      tense: 'presente',
      answers: ['chega'],
    },
    {
      sentence: 'João {blank} na escola antes das 8 horas.',
      verb: 'chegar',
      tense: 'presente',
      answers: ['chega'],
    },
    {
      sentence: 'Nós {blank} ao jogo todos os domingos.',
      verb: 'chegar',
      tense: 'presente',
      answers: ['chegamos'],
    },
    {
      sentence: 'Vocês {blank} felizes na escola.',
      verb: 'chegar',
      tense: 'presente',
      answers: ['chegam'],
    },
  ],
};
