import { ProblemList } from '../Problems';

export const colocar: ProblemList = {
  verb: 'colocar',
  problems: [
    {
      sentence: 'Eu {blank} os livros na estante.',
      verb: 'colocar',
      tense: 'presente',
      answers: ['coloco'],
    },
    {
      sentence: 'Você {blank} a mesa para o jantar.',
      verb: 'colocar',
      tense: 'presente',
      answers: ['coloca'],
    },
    {
      sentence: 'Ela {blank} as frutas na geladeira.',
      verb: 'colocar',
      tense: 'presente',
      answers: ['coloca'],
    },
    {
      sentence: 'Nós {blank} as cadeiras ao redor da mesa.',
      verb: 'colocar',
      tense: 'presente',
      answers: ['colocamos'],
    },
    {
      sentence: 'Vocês {blank} os equipamentos de volta no lugar.',
      verb: 'colocar',
      tense: 'presente',
      answers: ['colocam'],
    },
    {
      sentence: 'Ele {blank} a música para tocar durante a festa.',
      verb: 'colocar',
      tense: 'presente',
      answers: ['coloca'],
    },
    {
      sentence: 'Maria {blank} a foto do aniversário na parede.',
      verb: 'colocar',
      tense: 'presente',
      answers: ['coloca'],
    },
    {
      sentence: 'João e eu {blank} os planos na mesa.',
      verb: 'colocar',
      tense: 'presente',
      answers: ['colocamos'],
    },
    {
      sentence: 'As crianças {blank} os brinquedos no chão.',
      verb: 'colocar',
      tense: 'presente',
      answers: ['colocam'],
    },
    {
      sentence: 'Vocês {blank} suas expectativas nesta proposta.',
      verb: 'colocar',
      tense: 'presente',
      answers: ['colocam'],
    },
    {
      sentence: 'Eu {blank} os quadros na parede da sala.',
      verb: 'colocar',
      tense: 'pretérito perfeito',
      answers: ['coloquei'],
    },
    {
      sentence: 'Ela {blank} o livro na estante.',
      verb: 'colocar',
      tense: 'pretérito perfeito',
      answers: ['colocou'],
    },
    {
      sentence: 'Nós {blank} as cadeiras na mesa para o jantar.',
      verb: 'colocar',
      tense: 'pretérito perfeito',
      answers: ['colocamos'],
    },
    {
      sentence: 'Você {blank} a música para tocar na festa.',
      verb: 'colocar',
      tense: 'pretérito perfeito',
      answers: ['colocou'],
    },
    {
      sentence: 'Eles {blank} os pratos na mesa antes de servir.',
      verb: 'colocar',
      tense: 'pretérito perfeito',
      answers: ['colocaram'],
    },
    {
      sentence: 'Maria {blank} o vestido novo para a festa.',
      verb: 'colocar',
      tense: 'pretérito perfeito',
      answers: ['colocou'],
    },
    {
      sentence: 'João {blank} o relógio no pulso antes de sair.',
      verb: 'colocar',
      tense: 'pretérito perfeito',
      answers: ['colocou'],
    },
    {
      sentence: 'Nós {blank} as malas no carro antes da viagem.',
      verb: 'colocar',
      tense: 'pretérito perfeito',
      answers: ['colocamos'],
    },
    {
      sentence: 'Você e eu {blank} as plantas no jardim.',
      verb: 'colocar',
      tense: 'pretérito perfeito',
      answers: ['colocamos'],
    },
    {
      sentence: 'As crianças {blank} os brinquedos na caixa.',
      verb: 'colocar',
      tense: 'pretérito perfeito',
      answers: ['colocaram'],
    },
    {
      sentence: 'Eu {blank} os livros na estante amanhã.',
      verb: 'colocar',
      tense: 'futuro',
      answers: ['colocarei', 'vou colocar'],
    },
    {
      sentence: 'Você {blank} as cadeiras na sala de aula na próxima semana.',
      verb: 'colocar',
      tense: 'futuro',
      answers: ['colocará', 'vai colocar'],
    },
    {
      sentence: 'Ela {blank} as fotos no álbum no sábado.',
      verb: 'colocar',
      tense: 'futuro',
      answers: ['colocará', 'vai colocar'],
    },
    {
      sentence: 'Nós {blank} os materiais na mesa durante a palestra.',
      verb: 'colocar',
      tense: 'futuro',
      answers: ['colocaremos', 'vamos colocar'],
    },
    {
      sentence: 'Eles {blank} as novas regras na reunião de amanhã.',
      verb: 'colocar',
      tense: 'futuro',
      answers: ['colocarão', 'vão colocar'],
    },
    {
      sentence: 'Você e eu {blank} os brinquedos na caixa depois de brincar.',
      verb: 'colocar',
      tense: 'futuro',
      answers: ['colocaremos', 'vamos colocar'],
    },
    {
      sentence: 'João {blank} as peças do quebra-cabeça no lugar certo.',
      verb: 'colocar',
      tense: 'futuro',
      answers: ['colocará', 'vai colocar'],
    },
    {
      sentence: 'Maria e Ana {blank} as lanches na mesa para o piquenique.',
      verb: 'colocar',
      tense: 'futuro',
      answers: ['colocarão', 'vão colocar'],
    },
    {
      sentence: 'Vocês {blank} os projetos no mural na próxima reunião.',
      verb: 'colocar',
      tense: 'futuro',
      answers: ['colocarão', 'vão colocar'],
    },
    {
      sentence: 'Ele {blank} as informações no relatório até sexta-feira.',
      verb: 'colocar',
      tense: 'futuro',
      answers: ['colocará', 'vai colocar'],
    },
  ],
};
