import { ProblemList } from '../Problems';

export const começar: ProblemList = {
  verb: 'começar',
  problems: [
    {
      sentence: 'Eu {blank} o projeto na semana passada.',
      verb: 'começar',
      tense: 'pretérito perfeito',
      answers: ['comecei'],
    },
    {
      sentence: 'Ela {blank} a aula mais cedo ontem.',
      verb: 'começar',
      tense: 'pretérito perfeito',
      answers: ['começou'],
    },
    {
      sentence: 'Nós {blank} a reunião às 10 horas.',
      verb: 'começar',
      tense: 'pretérito perfeito',
      answers: ['começamos'],
    },
    {
      sentence: 'Você {blank} a leitura do livro na terça.',
      verb: 'começar',
      tense: 'pretérito perfeito',
      answers: ['começou'],
    },
    {
      sentence: 'Eles {blank} a festa sem avisar ninguém.',
      verb: 'começar',
      tense: 'pretérito perfeito',
      answers: ['começaram'],
    },
    {
      sentence: 'Maria {blank} o curso de francês recentemente.',
      verb: 'começar',
      tense: 'pretérito perfeito',
      answers: ['começou'],
    },
    {
      sentence: 'Nós {blank} a atividade logo após o almoço.',
      verb: 'começar',
      tense: 'pretérito perfeito',
      answers: ['começamos'],
    },
    {
      sentence: 'Você e eu {blank} a prática de esportes juntos.',
      verb: 'começar',
      tense: 'pretérito perfeito',
      answers: ['começamos'],
    },
    {
      sentence: 'Pedro {blank} a escrever seu livro há um mês.',
      verb: 'começar',
      tense: 'pretérito perfeito',
      answers: ['começou'],
    },
    {
      sentence: 'As aulas {blank} com uma dinâmica interessante.',
      verb: 'começar',
      tense: 'pretérito perfeito',
      answers: ['começaram'],
    },
    {
      sentence: 'Eu {blank} um novo projeto no próximo mês.',
      verb: 'começar',
      tense: 'futuro',
      answers: ['começarei', 'vou começar'],
    },
    {
      sentence: 'Ela {blank} a apresentação na semana que vem.',
      verb: 'começar',
      tense: 'futuro',
      answers: ['começará', 'vai começar'],
    },
    {
      sentence: 'Nós {blank} a reunião às 10 horas amanhã.',
      verb: 'começar',
      tense: 'futuro',
      answers: ['começaremos', 'vamos começar'],
    },
    {
      sentence: 'Vocês {blank} a leitura do livro na sexta-feira.',
      verb: 'começar',
      tense: 'futuro',
      answers: ['começarão', 'vão começar'],
    },
    {
      sentence: 'Meu amigo {blank} um curso de inglês em breve.',
      verb: 'começar',
      tense: 'futuro',
      answers: ['começará', 'vai começar'],
    },
    {
      sentence: 'Eu e você {blank} a nova dieta na próxima semana.',
      verb: 'começar',
      tense: 'futuro',
      answers: ['começaremos', 'vamos começar'],
    },
    {
      sentence: 'Os alunos {blank} a trabalhar no projeto na próxima aula.',
      verb: 'começar',
      tense: 'futuro',
      answers: ['começarão', 'vão começar'],
    },
    {
      sentence: 'A professora {blank} a explicar o novo tema amanhã.',
      verb: 'começar',
      tense: 'futuro',
      answers: ['começará', 'vai começar'],
    },
    {
      sentence: 'Nós {blank} a preparar a festa no próximo fim de semana.',
      verb: 'começar',
      tense: 'futuro',
      answers: ['começaremos', 'vamos começar'],
    },
    {
      sentence: 'Eles {blank} a praticar para o campeonato na próxima semana.',
      verb: 'começar',
      tense: 'futuro',
      answers: ['começarão', 'vão começar'],
    },
    {
      sentence: 'Eu {blank} a minha nova rotina hoje.',
      verb: 'começar',
      tense: 'presente',
      answers: ['começo'],
    },
    {
      sentence: 'Ela {blank} o projeto assim que tiver tempo.',
      verb: 'começar',
      tense: 'presente',
      answers: ['começa'],
    },
    {
      sentence: 'Nós {blank} a estudar para as provas na próxima semana.',
      verb: 'começar',
      tense: 'presente',
      answers: ['começamos'],
    },
    {
      sentence: 'Você {blank} a entender melhor a matéria agora?',
      verb: 'começar',
      tense: 'presente',
      answers: ['começa'],
    },
    {
      sentence: 'Carlos {blank} a trabalhar em um novo projeto hoje.',
      verb: 'começar',
      tense: 'presente',
      answers: ['começa'],
    },
    {
      sentence: 'Elas {blank} a planejar a viagem para o próximo mês.',
      verb: 'começar',
      tense: 'presente',
      answers: ['começam'],
    },
    {
      sentence: 'João e Pedro {blank} o treinamento na próxima segunda-feira.',
      verb: 'começar',
      tense: 'presente',
      answers: ['começam'],
    },
    {
      sentence: 'Vocês {blank} a reunir informações sobre o projeto.',
      verb: 'começar',
      tense: 'presente',
      answers: ['começam'],
    },
    {
      sentence: 'A professora {blank} a explicar a nova matéria agora.',
      verb: 'começar',
      tense: 'presente',
      answers: ['começa'],
    },
    {
      sentence: 'Nós {blank} a cuidar do jardim neste fim de semana.',
      verb: 'começar',
      tense: 'presente',
      answers: ['começamos'],
    },
  ],
};
