import { ProblemList } from '../Problems';

export const comer: ProblemList = {
  verb: 'comer',
  problems: [
    {
      sentence: 'Eu {blank} uma salada todos os dias.',
      verb: 'comer',
      tense: 'presente',
      answers: ['como'],
    },
    {
      sentence: 'Você {blank} um lanche saudável agora.',
      verb: 'comer',
      tense: 'presente',
      answers: ['come'],
    },
    {
      sentence: 'Ela {blank} frutas todos os sábados.',
      verb: 'comer',
      tense: 'presente',
      answers: ['come'],
    },
    {
      sentence: 'Nós {blank} no restaurante toda sexta-feira.',
      verb: 'comer',
      tense: 'presente',
      answers: ['comemos'],
    },
    {
      sentence: 'Eles {blank} pizza nas festas de aniversário.',
      verb: 'comer',
      tense: 'presente',
      answers: ['comem'],
    },
    {
      sentence: 'Você e eu {blank} juntos no bar.',
      verb: 'comer',
      tense: 'presente',
      answers: ['comemos'],
    },
    {
      sentence: 'Maria {blank} um pudim delicioso.',
      verb: 'comer',
      tense: 'presente',
      answers: ['come'],
    },
    {
      sentence: 'Pedro {blank} bastante em cada refeição.',
      verb: 'comer',
      tense: 'presente',
      answers: ['come'],
    },
    {
      sentence: 'Eles {blank} bolo de chocolate frequentemente.',
      verb: 'comer',
      tense: 'presente',
      answers: ['comem'],
    },
    {
      sentence: 'Você {blank} muito bem para a saúde.',
      verb: 'comer',
      tense: 'presente',
      answers: ['come'],
    },
    {
      sentence: 'Eu {blank} uma pizza deliciosa ontem à noite.',
      verb: 'comer',
      tense: 'pretérito perfeito',
      answers: ['comi'],
    },
    {
      sentence: 'Ela {blank} muito bem na festa na semana passada.',
      verb: 'comer',
      tense: 'pretérito perfeito',
      answers: ['comeu'],
    },
    {
      sentence: 'Nós {blank} um bolo incrível no aniversário de Maria.',
      verb: 'comer',
      tense: 'pretérito perfeito',
      answers: ['comemos'],
    },
    {
      sentence: 'Você {blank} frutas frescas durante as férias.',
      verb: 'comer',
      tense: 'pretérito perfeito',
      answers: ['comeu'],
    },
    {
      sentence: 'Eles {blank} sushi na nova restaurante no sábado.',
      verb: 'comer',
      tense: 'pretérito perfeito',
      answers: ['comeram'],
    },
    {
      sentence: 'João {blank} um lanche rápido antes da reunião.',
      verb: 'comer',
      tense: 'pretérito perfeito',
      answers: ['comeu'],
    },
    {
      sentence: 'Nós {blank} as massas que você fez na festa.',
      verb: 'comer',
      tense: 'pretérito perfeito',
      answers: ['comemos'],
    },
    {
      sentence: 'Você e Ana {blank} um sorvete no parque.',
      verb: 'comer',
      tense: 'pretérito perfeito',
      answers: ['comeram'],
    },
    {
      sentence: 'Eles {blank} no restaurante italiano da esquina.',
      verb: 'comer',
      tense: 'pretérito perfeito',
      answers: ['comeram'],
    },
    {
      sentence: 'Eu {blank} um bom livro enquanto esperava pelo jantar.',
      verb: 'comer',
      tense: 'pretérito perfeito',
      answers: ['comi'],
    },
    {
      sentence: 'Eu {blank} uma salada para o jantar amanhã.',
      verb: 'comer',
      tense: 'futuro',
      answers: ['comerei', 'vou comer'],
    },
    {
      sentence: 'Você {blank} pizza no sábado à noite.',
      verb: 'comer',
      tense: 'futuro',
      answers: ['comerá', 'vai comer'],
    },
    {
      sentence: 'Ela {blank} sobremesa depois do almoço.',
      verb: 'comer',
      tense: 'futuro',
      answers: ['comerá', 'vai comer'],
    },
    {
      sentence: 'Nós {blank} sushi no próximo fim de semana.',
      verb: 'comer',
      tense: 'futuro',
      answers: ['comeremos', 'vamos comer'],
    },
    {
      sentence: 'Eles {blank} um bom jantar na sexta-feira.',
      verb: 'comer',
      tense: 'futuro',
      answers: ['comerão', 'vão comer'],
    },
    {
      sentence: 'Você e eu {blank} na mesma mesa no restaurante.',
      verb: 'comer',
      tense: 'futuro',
      answers: ['comeremos', 'vamos comer'],
    },
    {
      sentence: 'O João {blank} uma feijoada no próximo domingo.',
      verb: 'comer',
      tense: 'futuro',
      answers: ['comerá', 'vai comer'],
    },
    {
      sentence: 'As meninas {blank} um lanche após a aula.',
      verb: 'comer',
      tense: 'futuro',
      answers: ['comerão', 'vão comer'],
    },
    {
      sentence: 'Meu pai {blank} um doce que ele adora.',
      verb: 'comer',
      tense: 'futuro',
      answers: ['comerá', 'vai comer'],
    },
    {
      sentence: 'A equipe {blank} todos os pratos do buffet.',
      verb: 'comer',
      tense: 'futuro',
      answers: ['comerá', 'vai comer'],
    },
  ],
};
