import { ProblemList } from '../Problems';

export const comprar: ProblemList = {
  verb: 'comprar',
  problems: [
    {
      sentence: 'Eu {blank} um presente especial para o meu amigo.',
      verb: 'comprar',
      tense: 'pretérito perfeito',
      answers: ['comprei'],
    },
    {
      sentence: 'Ela {blank} frutas frescas no mercado.',
      verb: 'comprar',
      tense: 'pretérito perfeito',
      answers: ['comprou'],
    },
    {
      sentence: 'Nós {blank} os ingressos para o show.',
      verb: 'comprar',
      tense: 'pretérito perfeito',
      answers: ['compramos'],
    },
    {
      sentence: 'Você {blank} um carro novo recentemente.',
      verb: 'comprar',
      tense: 'pretérito perfeito',
      answers: ['comprou'],
    },
    {
      sentence: 'Eles {blank} roupas novas para o inverno.',
      verb: 'comprar',
      tense: 'pretérito perfeito',
      answers: ['compraram'],
    },
    {
      sentence: 'Maria {blank} tudo que precisava para a festa.',
      verb: 'comprar',
      tense: 'pretérito perfeito',
      answers: ['comprou'],
    },
    {
      sentence: 'João e eu {blank} um livro interessante na livraria.',
      verb: 'comprar',
      tense: 'pretérito perfeito',
      answers: ['compramos'],
    },
    {
      sentence: 'Você e sua irmã {blank} um presente para a mãe de vocês.',
      verb: 'comprar',
      tense: 'pretérito perfeito',
      answers: ['compraram'],
    },
    {
      sentence: 'Nós {blank} alimentos para a semana toda.',
      verb: 'comprar',
      tense: 'pretérito perfeito',
      answers: ['compramos'],
    },
    {
      sentence: 'Ela {blank} ingredientes para o jantar.',
      verb: 'comprar',
      tense: 'pretérito perfeito',
      answers: ['comprou'],
    },
    {
      sentence: 'Eu {blank} um presente para você no seu aniversário.',
      verb: 'comprar',
      tense: 'futuro',
      answers: ['comprarei', 'vou comprar'],
    },
    {
      sentence: 'Ela {blank} os ingressos para o show na próxima semana.',
      verb: 'comprar',
      tense: 'futuro',
      answers: ['comprará', 'vai comprar'],
    },
    {
      sentence: 'Nós {blank} um carro novo no próximo mês.',
      verb: 'comprar',
      tense: 'futuro',
      answers: ['compraremos', 'vamos comprar'],
    },
    {
      sentence: 'Vocês {blank} as flores para a festa de casamento.',
      verb: 'comprar',
      tense: 'futuro',
      answers: ['comprarão', 'vão comprar'],
    },
    {
      sentence: 'João {blank} um laptop melhor em breve.',
      verb: 'comprar',
      tense: 'futuro',
      answers: ['comprará', 'vai comprar'],
    },
    {
      sentence: 'Maria e eu {blank} uma passagem para a viagem.',
      verb: 'comprar',
      tense: 'futuro',
      answers: ['vamos comprar', 'comprarmos'],
    },
    {
      sentence: 'Carlos {blank} um novo celular no próximo ano.',
      verb: 'comprar',
      tense: 'futuro',
      answers: ['comprará', 'vai comprar'],
    },
    {
      sentence: 'Vocês {blank} aquele traje elegante para a cerimônia.',
      verb: 'comprar',
      tense: 'futuro',
      answers: ['comprarão', 'vão comprar'],
    },
    {
      sentence: 'Eu e minha irmã {blank} novos livros para a escola.',
      verb: 'comprar',
      tense: 'futuro',
      answers: ['vamos comprar', 'comprarmos'],
    },
    {
      sentence: 'Ana {blank} um vestido bonito para a festa.',
      verb: 'comprar',
      tense: 'futuro',
      answers: ['comprará', 'vai comprar'],
    },
    {
      sentence: 'Eu {blank} um presente para o meu amigo.',
      verb: 'comprar',
      tense: 'presente',
      answers: ['compro'],
    },
    {
      sentence: 'Você {blank} frutas frescas no mercado?',
      verb: 'comprar',
      tense: 'presente',
      answers: ['compra'],
    },
    {
      sentence: 'Ela {blank} roupas novas para a viagem.',
      verb: 'comprar',
      tense: 'presente',
      answers: ['compra'],
    },
    {
      sentence: 'Nós {blank} novos livros para a biblioteca.',
      verb: 'comprar',
      tense: 'presente',
      answers: ['compramos'],
    },
    {
      sentence: 'Eles {blank} a comida para o jantar.',
      verb: 'comprar',
      tense: 'presente',
      answers: ['compram'],
    },
    {
      sentence: 'Tu {blank} os ingressos para o show?',
      verb: 'comprar',
      tense: 'presente',
      answers: ['compras'],
    },
    {
      sentence: 'A Maria {blank} pão toda manhã.',
      verb: 'comprar',
      tense: 'presente',
      answers: ['compra'],
    },
    {
      sentence: 'Você e eu {blank} um carro novo juntos.',
      verb: 'comprar',
      tense: 'presente',
      answers: ['compramos'],
    },
    {
      sentence: 'Os alunos {blank} materiais escolares no início do ano.',
      verb: 'comprar',
      tense: 'presente',
      answers: ['compram'],
    },
    {
      sentence: 'O João {blank} um videogame novo esta semana.',
      verb: 'comprar',
      tense: 'presente',
      answers: ['compra'],
    },
  ],
};
