import { ProblemList } from '../Problems';

export const completar: ProblemList = {
  verb: 'completar',
  problems: [
    {
      sentence: 'Eu {blank} a tarefa antes do prazo.',
      verb: 'completar',
      tense: 'pretérito perfeito',
      answers: ['completei'],
    },
    {
      sentence: 'Ela {blank} o projeto com sucesso.',
      verb: 'completar',
      tense: 'pretérito perfeito',
      answers: ['completou'],
    },
    {
      sentence: 'Nós {blank} as metas estabelecidas para este mês.',
      verb: 'completar',
      tense: 'pretérito perfeito',
      answers: ['completamos'],
    },
    {
      sentence: 'Você {blank} os exercícios de matemática ontem.',
      verb: 'completar',
      tense: 'pretérito perfeito',
      answers: ['completou'],
    },
    {
      sentence: 'Eles {blank} o curso de inglês no ano passado.',
      verb: 'completar',
      tense: 'pretérito perfeito',
      answers: ['completaram'],
    },
    {
      sentence: 'João {blank} a leitura do livro na semana passada.',
      verb: 'completar',
      tense: 'pretérito perfeito',
      answers: ['completou'],
    },
    {
      sentence: 'Maria e eu {blank} a apresentação no tempo certo.',
      verb: 'completar',
      tense: 'pretérito perfeito',
      answers: ['completamos'],
    },
    {
      sentence: 'Vocês {blank} as vendas do mês anterior.',
      verb: 'completar',
      tense: 'pretérito perfeito',
      answers: ['completaram'],
    },
    {
      sentence: 'Ela e você {blank} a receita sem erro.',
      verb: 'completar',
      tense: 'pretérito perfeito',
      answers: ['completaram'],
    },
    {
      sentence: 'Eu {blank} a limpeza da casa antes da festa.',
      verb: 'completar',
      tense: 'pretérito perfeito',
      answers: ['completei'],
    },
    {
      sentence: 'Eu {blank} meu projeto até o final da semana.',
      verb: 'completar',
      tense: 'futuro',
      answers: ['completarei', 'vou completar'],
    },
    {
      sentence: 'Ele {blank} a tarefa antes do prazo.',
      verb: 'completar',
      tense: 'futuro',
      answers: ['completará', 'vai completar'],
    },
    {
      sentence: 'Nós {blank} a análise financeira para o relatório.',
      verb: 'completar',
      tense: 'futuro',
      answers: ['completaremos', 'vamos completar'],
    },
    {
      sentence: 'Vocês {blank} o trabalho em grupo até amanhã.',
      verb: 'completar',
      tense: 'futuro',
      answers: ['completarão', 'vão completar'],
    },
    {
      sentence: 'Maria {blank} a leitura do livro esta semana.',
      verb: 'completar',
      tense: 'futuro',
      answers: ['completará', 'vai completar'],
    },
    {
      sentence: 'João e eu {blank} as etapas do projeto juntos.',
      verb: 'completar',
      tense: 'futuro',
      answers: ['completaremos', 'vamos completar'],
    },
    {
      sentence: 'Você {blank} o seu treinamento antes do mês que vem.',
      verb: 'completar',
      tense: 'futuro',
      answers: ['completará', 'vai completar'],
    },
    {
      sentence: 'Elas {blank} o curso de idiomas no próximo semestre.',
      verb: 'completar',
      tense: 'futuro',
      answers: ['completarão', 'vão completar'],
    },
    {
      sentence: 'Nós {blank} as atividades propostas para a aula.',
      verb: 'completar',
      tense: 'futuro',
      answers: ['completaremos', 'vamos completar'],
    },
    {
      sentence: 'Você e sua irmã {blank} a decoração para a festa.',
      verb: 'completar',
      tense: 'futuro',
      answers: ['completarão', 'vão completar'],
    },
    {
      sentence: 'Eu {blank} meu trabalho todos os dias.',
      verb: 'completar',
      tense: 'presente',
      answers: ['completo'],
    },
    {
      sentence: 'Ela {blank} a lição de casa a cada semana.',
      verb: 'completar',
      tense: 'presente',
      answers: ['completa'],
    },
    {
      sentence: 'Nós {blank} os exercícios juntos.',
      verb: 'completar',
      tense: 'presente',
      answers: ['completamos'],
    },
    {
      sentence: 'Vocês {blank} as atividades no prazo.',
      verb: 'completar',
      tense: 'presente',
      answers: ['completam'],
    },
    {
      sentence: 'Ele {blank} o projeto antes do prazo.',
      verb: 'completar',
      tense: 'presente',
      answers: ['completa'],
    },
    {
      sentence: 'Maria {blank} a prova assim que possível.',
      verb: 'completar',
      tense: 'presente',
      answers: ['completa'],
    },
    {
      sentence: 'João e eu {blank} a apresentação amanhã.',
      verb: 'completar',
      tense: 'presente',
      answers: ['completamos'],
    },
    {
      sentence: 'Vocês {blank} os formulários necessários.',
      verb: 'completar',
      tense: 'presente',
      answers: ['completam'],
    },
    {
      sentence: 'Nós {blank} a nossa parte do trabalho.',
      verb: 'completar',
      tense: 'presente',
      answers: ['completamos'],
    },
    {
      sentence: 'As crianças {blank} os desenhos antes do jantar.',
      verb: 'completar',
      tense: 'presente',
      answers: ['completam'],
    },
  ],
};
