import { ProblemList } from '../Problems';

export const concluir: ProblemList = {
  verb: 'concluir',
  problems: [
    {
      sentence: 'Eu {blank} o projeto a tempo.',
      verb: 'concluir',
      tense: 'pretérito perfeito',
      answers: ['concluí'],
    },
    {
      sentence: 'Ela {blank} todas as tarefas da lista.',
      verb: 'concluir',
      tense: 'pretérito perfeito',
      answers: ['concluiu'],
    },
    {
      sentence: 'Nós {blank} a reunião antes do almoço.',
      verb: 'concluir',
      tense: 'pretérito perfeito',
      answers: ['concluímos'],
    },
    {
      sentence: 'Você {blank} a apresentação com sucesso.',
      verb: 'concluir',
      tense: 'pretérito perfeito',
      answers: ['concluiu'],
    },
    {
      sentence: 'Carlos e Ana {blank} a compra do apartamento.',
      verb: 'concluir',
      tense: 'pretérito perfeito',
      answers: ['concluíram'],
    },
    {
      sentence: 'Eu {blank} a leitura do livro que você indicou.',
      verb: 'concluir',
      tense: 'pretérito perfeito',
      answers: ['concluí'],
    },
    {
      sentence: 'Eles {blank} o curso na semana passada.',
      verb: 'concluir',
      tense: 'pretérito perfeito',
      answers: ['concluíram'],
    },
    {
      sentence: 'Você e eu {blank} a reforma da casa.',
      verb: 'concluir',
      tense: 'pretérito perfeito',
      answers: ['concluímos'],
    },
    {
      sentence: 'O time {blank} o campeonato com vitória.',
      verb: 'concluir',
      tense: 'pretérito perfeito',
      answers: ['concluiu'],
    },
    {
      sentence: 'Maria {blank} a apresentação antes do prazo.',
      verb: 'concluir',
      tense: 'pretérito perfeito',
      answers: ['concluiu'],
    },
    {
      sentence: 'Eu {blank} o projeto até o fim da semana.',
      verb: 'concluir',
      tense: 'futuro',
      answers: ['concluirei', 'vou concluir'],
    },
    {
      sentence: 'Ela {blank} os estudos no próximo mês.',
      verb: 'concluir',
      tense: 'futuro',
      answers: ['concluirá', 'vai concluir'],
    },
    {
      sentence: 'Nós {blank} a apresentação na próxima sexta-feira.',
      verb: 'concluir',
      tense: 'futuro',
      answers: ['concluiremos', 'vamos concluir'],
    },
    {
      sentence: 'Vocês {blank} as correções até amanhã.',
      verb: 'concluir',
      tense: 'futuro',
      answers: ['concluirão', 'vão concluir'],
    },
    {
      sentence: 'Ele {blank} a leitura do livro esta semana.',
      verb: 'concluir',
      tense: 'futuro',
      answers: ['concluirá', 'vai concluir'],
    },
    {
      sentence: 'Maria e João {blank} o curso no final do semestre.',
      verb: 'concluir',
      tense: 'futuro',
      answers: ['concluirão', 'vão concluir'],
    },
    {
      sentence: 'Eu e você {blank} a tarefa juntos na próxima aula.',
      verb: 'concluir',
      tense: 'futuro',
      answers: ['concluiremos', 'vamos concluir'],
    },
    {
      sentence: 'Ela {blank} a análise dos dados em breve.',
      verb: 'concluir',
      tense: 'futuro',
      answers: ['concluirá', 'vai concluir'],
    },
    {
      sentence: 'Vocês {blank} a viagem de estudos até o final do ano.',
      verb: 'concluir',
      tense: 'futuro',
      answers: ['concluirão', 'vão concluir'],
    },
    {
      sentence: 'João {blank} sua formação universitária em dezembro.',
      verb: 'concluir',
      tense: 'futuro',
      answers: ['concluirá', 'vai concluir'],
    },
    {
      sentence: 'Eu {blank} meu trabalho antes do prazo.',
      verb: 'concluir',
      tense: 'presente',
      answers: ['concluo'],
    },
    {
      sentence: 'Você {blank} suas tarefas diárias com eficiência.',
      verb: 'concluir',
      tense: 'presente',
      answers: ['conclui'],
    },
    {
      sentence: 'Ela {blank} o projeto de arte para a escola.',
      verb: 'concluir',
      tense: 'presente',
      answers: ['conclui'],
    },
    {
      sentence: 'Nós {blank} a reunião a tempo.',
      verb: 'concluir',
      tense: 'presente',
      answers: ['concluímos'],
    },
    {
      sentence: 'Eles {blank} os estudos para o exame final.',
      verb: 'concluir',
      tense: 'presente',
      answers: ['concluem'],
    },
    {
      sentence: 'Maria {blank} o relatório com dedicação.',
      verb: 'concluir',
      tense: 'presente',
      answers: ['conclui'],
    },
    {
      sentence: 'Você e eu {blank} o trabalho juntos.',
      verb: 'concluir',
      tense: 'presente',
      answers: ['concluímos'],
    },
    {
      sentence: 'João {blank} suas obrigações diárias sem falta.',
      verb: 'concluir',
      tense: 'presente',
      answers: ['conclui'],
    },
    {
      sentence: 'Vocês {blank} as próximas etapas do projeto.',
      verb: 'concluir',
      tense: 'presente',
      answers: ['concluem'],
    },
    {
      sentence: 'Eu e você {blank} as metas do mês.',
      verb: 'concluir',
      tense: 'presente',
      answers: ['concluímos'],
    },
  ],
};
