import { ProblemList } from '../Problems';

export const conhecer: ProblemList = {
  verb: 'conhecer',
  problems: [
    {
      sentence: 'Eu {blank} pessoas interessantes na confraternização.',
      verb: 'conhecer',
      tense: 'futuro',
      answers: ['conhecerei', 'vou conhecer'],
    },
    {
      sentence: 'Você {blank} novas culturas durante a viagem.',
      verb: 'conhecer',
      tense: 'futuro',
      answers: ['conhecerá', 'vai conhecer'],
    },
    {
      sentence: 'Ela {blank} o novo professor na próxima semana.',
      verb: 'conhecer',
      tense: 'futuro',
      answers: ['conhecerá', 'vai conhecer'],
    },
    {
      sentence: 'Nós {blank} a cidade histórica no próximo mês.',
      verb: 'conhecer',
      tense: 'futuro',
      answers: ['conheceremos', 'vamos conhecer'],
    },
    {
      sentence: 'Vocês {blank} o evento importante no sábado.',
      verb: 'conhecer',
      tense: 'futuro',
      answers: ['conhecerão', 'vão conhecer'],
    },
    {
      sentence: 'Eles {blank} novas tecnologias na conferência.',
      verb: 'conhecer',
      tense: 'futuro',
      answers: ['conhecerão', 'vão conhecer'],
    },
    {
      sentence: 'Ana e eu {blank} várias pessoas legais na festa.',
      verb: 'conhecer',
      tense: 'futuro',
      answers: ['conheceremos', 'vamos conhecer'],
    },
    {
      sentence: 'Luiz {blank} o novo jeito de trabalhar amanhã.',
      verb: 'conhecer',
      tense: 'futuro',
      answers: ['conhecerá', 'vai conhecer'],
    },
    {
      sentence: 'Se você for ao parque, {blank} muitas crianças brincando.',
      verb: 'conhecer',
      tense: 'futuro',
      answers: ['conhecerá', 'vai conhecer'],
    },
    {
      sentence: 'No próximo ano, nós {blank} diversos artistas locais.',
      verb: 'conhecer',
      tense: 'futuro',
      answers: ['conheceremos', 'vamos conhecer'],
    },
    {
      sentence: 'Eu {blank} muitas pessoas interessantes na festa.',
      verb: 'conhecer',
      tense: 'presente',
      answers: ['conheço'],
    },
    {
      sentence: 'Ela {blank} os novos colegas de trabalho.',
      verb: 'conhecer',
      tense: 'presente',
      answers: ['conhece'],
    },
    {
      sentence: 'Nós {blank} a cidade muito bem.',
      verb: 'conhecer',
      tense: 'presente',
      answers: ['conhecemos'],
    },
    {
      sentence: 'Você {blank} o restaurante que eu te recomendei?',
      verb: 'conhecer',
      tense: 'presente',
      answers: ['conhece'],
    },
    {
      sentence: 'Eles {blank} as regras do jogo.',
      verb: 'conhecer',
      tense: 'presente',
      answers: ['conhecem'],
    },
    {
      sentence: 'Maria {blank} a nova professora da escola.',
      verb: 'conhecer',
      tense: 'presente',
      answers: ['conhece'],
    },
    {
      sentence: 'Pedro e eu {blank} muito sobre a cultura local.',
      verb: 'conhecer',
      tense: 'presente',
      answers: ['conhecemos'],
    },
    {
      sentence: 'Você e Ana {blank} aquele artista famoso?',
      verb: 'conhecer',
      tense: 'presente',
      answers: ['conhecem'],
    },
    {
      sentence: 'Os alunos {blank} as matérias do currículo.',
      verb: 'conhecer',
      tense: 'presente',
      answers: ['conhecem'],
    },
    {
      sentence: 'Ela e eu {blank} a música que tocou no evento.',
      verb: 'conhecer',
      tense: 'presente',
      answers: ['conhecemos'],
    },
    {
      sentence: 'Eu {blank} Maria na festa de aniversário.',
      verb: 'conhecer',
      tense: 'pretérito perfeito',
      answers: ['conheci'],
    },
    {
      sentence: 'Você {blank} o novo colega de trabalho ontem.',
      verb: 'conhecer',
      tense: 'pretérito perfeito',
      answers: ['conheceu'],
    },
    {
      sentence: 'Ela {blank} as tradições culturais durante a viagem.',
      verb: 'conhecer',
      tense: 'pretérito perfeito',
      answers: ['conheceu'],
    },
    {
      sentence: 'Nós {blank} um restaurante incrível na cidade.',
      verb: 'conhecer',
      tense: 'pretérito perfeito',
      answers: ['conhecemos'],
    },
    {
      sentence: 'Eles {blank} a história do lugar durante a visita.',
      verb: 'conhecer',
      tense: 'pretérito perfeito',
      answers: ['conheceram'],
    },
    {
      sentence: 'Você e eu {blank} a nova professora na semana passada.',
      verb: 'conhecer',
      tense: 'pretérito perfeito',
      answers: ['conhecemos'],
    },
    {
      sentence: 'João {blank} a cidade quando foi a trabalho.',
      verb: 'conhecer',
      tense: 'pretérito perfeito',
      answers: ['conheceu'],
    },
    {
      sentence: 'Ana e Carlos {blank} o famoso artista no evento.',
      verb: 'conhecer',
      tense: 'pretérito perfeito',
      answers: ['conheceram'],
    },
    {
      sentence: 'Eu {blank} os detalhes do projeto na reunião passada.',
      verb: 'conhecer',
      tense: 'pretérito perfeito',
      answers: ['conheci'],
    },
    {
      sentence: 'Vocês {blank} o novo filme que estreou no cinema.',
      verb: 'conhecer',
      tense: 'pretérito perfeito',
      answers: ['conheceram'],
    },
  ],
};
