import { ProblemList } from '../Problems';

export const conseguir: ProblemList = {
  verb: 'conseguir',
  problems: [
    {
      sentence: 'Eu {blank} uma promoção incrível no próximo mês.',
      verb: 'conseguir',
      tense: 'futuro',
      answers: ['conseguirei', 'vou conseguir'],
    },
    {
      sentence: 'Ela {blank} um novo emprego logo mais.',
      verb: 'conseguir',
      tense: 'futuro',
      answers: ['conseguirá', 'vai conseguir'],
    },
    {
      sentence: 'Nós {blank} terminar o projeto até sexta-feira.',
      verb: 'conseguir',
      tense: 'futuro',
      answers: ['conseguiremos', 'vamos conseguir'],
    },
    {
      sentence: 'Você {blank} resolver esse problema rapidamente.',
      verb: 'conseguir',
      tense: 'futuro',
      answers: ['conseguirá', 'vai conseguir'],
    },
    {
      sentence: 'Eles {blank} encontrar uma solução para a disputa.',
      verb: 'conseguir',
      tense: 'futuro',
      answers: ['conseguirão', 'vão conseguir'],
    },
    {
      sentence: 'João {blank} realizar a tarefa antes do prazo.',
      verb: 'conseguir',
      tense: 'futuro',
      answers: ['conseguirá', 'vai conseguir'],
    },
    {
      sentence: 'Nós {blank} alcançar nossos objetivos no próximo ano.',
      verb: 'conseguir',
      tense: 'futuro',
      answers: ['conseguiremos', 'vamos conseguir'],
    },
    {
      sentence: 'Vocês {blank} superar essa dificuldade juntos.',
      verb: 'conseguir',
      tense: 'futuro',
      answers: ['conseguirão', 'vão conseguir'],
    },
    {
      sentence: 'A Maria {blank} atingir suas metas este ano.',
      verb: 'conseguir',
      tense: 'futuro',
      answers: ['conseguirá', 'vai conseguir'],
    },
    {
      sentence: 'Eu e você {blank} tirar boas notas no exame.',
      verb: 'conseguir',
      tense: 'futuro',
      answers: ['conseguiremos', 'vamos conseguir'],
    },
    {
      sentence: 'Eu {blank} sempre concluir meus projetos a tempo.',
      verb: 'conseguir',
      tense: 'presente',
      answers: ['consigo'],
    },
    {
      sentence: 'Ela {blank} obter ajuda dos professores.',
      verb: 'conseguir',
      tense: 'presente',
      answers: ['consegue'],
    },
    {
      sentence: 'Nós {blank} resolver a situação juntos.',
      verb: 'conseguir',
      tense: 'presente',
      answers: ['conseguimos'],
    },
    {
      sentence: 'Vocês {blank} alcançar seus objetivos este ano.',
      verb: 'conseguir',
      tense: 'presente',
      answers: ['conseguem'],
    },
    {
      sentence: 'Carlos {blank} superar todos os desafios.',
      verb: 'conseguir',
      tense: 'presente',
      answers: ['consegue'],
    },
    {
      sentence: 'Ana e eu {blank} concluir o trabalho com sucesso.',
      verb: 'conseguir',
      tense: 'presente',
      answers: ['conseguimos'],
    },
    {
      sentence: 'Você {blank} praticar o idioma todos os dias.',
      verb: 'conseguir',
      tense: 'presente',
      answers: ['consegue'],
    },
    {
      sentence: 'Eles {blank} manter o foco nos estudos.',
      verb: 'conseguir',
      tense: 'presente',
      answers: ['conseguem'],
    },
    {
      sentence: 'Juliana {blank} fazer todos os exercícios de casa.',
      verb: 'conseguir',
      tense: 'presente',
      answers: ['consegue'],
    },
    {
      sentence: 'Nós {blank} participar da conferência anual.',
      verb: 'conseguir',
      tense: 'presente',
      answers: ['conseguimos'],
    },
    {
      sentence: 'Eu {blank} resolver o problema rapidamente.',
      verb: 'conseguir',
      tense: 'pretérito perfeito',
      answers: ['consegui'],
    },
    {
      sentence: 'Ela {blank} terminar o relatório antes do prazo.',
      verb: 'conseguir',
      tense: 'pretérito perfeito',
      answers: ['conseguiu'],
    },
    {
      sentence: 'Nós {blank} chegar a tempo ao evento.',
      verb: 'conseguir',
      tense: 'pretérito perfeito',
      answers: ['conseguimos'],
    },
    {
      sentence: 'Você {blank} encontrar o caminho certo para o restaurante.',
      verb: 'conseguir',
      tense: 'pretérito perfeito',
      answers: ['conseguiu'],
    },
    {
      sentence: 'João {blank} comprar os ingressos para o show.',
      verb: 'conseguir',
      tense: 'pretérito perfeito',
      answers: ['conseguiu'],
    },
    {
      sentence: 'Elas {blank} organizar todo o material para a apresentação.',
      verb: 'conseguir',
      tense: 'pretérito perfeito',
      answers: ['conseguiram'],
    },
    {
      sentence: 'Nós {blank} aprender os novos conceitos rapidamente.',
      verb: 'conseguir',
      tense: 'pretérito perfeito',
      answers: ['conseguimos'],
    },
    {
      sentence: 'Vocês {blank} convencer os diretores a investir no projeto.',
      verb: 'conseguir',
      tense: 'pretérito perfeito',
      answers: ['conseguiram'],
    },
    {
      sentence: 'Ela e eu {blank} compartilhar ideias durante a reunião.',
      verb: 'conseguir',
      tense: 'pretérito perfeito',
      answers: ['conseguimos'],
    },
    {
      sentence: 'O time {blank} vencer o campeonato este ano.',
      verb: 'conseguir',
      tense: 'pretérito perfeito',
      answers: ['conseguiu'],
    },
  ],
};
