import { ProblemList } from '../Problems';

export const considerar: ProblemList = {
  verb: 'considerar',
  problems: [
    {
      sentence: 'Eu {blank} sua proposta na reunião ontem.',
      verb: 'considerar',
      tense: 'pretérito perfeito',
      answers: ['considerei'],
    },
    {
      sentence: 'Ela {blank} todas as opções antes de decidir.',
      verb: 'considerar',
      tense: 'pretérito perfeito',
      answers: ['considerou'],
    },
    {
      sentence: 'Nós {blank} a possibilidade de viagem à Europa.',
      verb: 'considerar',
      tense: 'pretérito perfeito',
      answers: ['consideramos'],
    },
    {
      sentence: 'Você {blank} as consequências da sua decisão?',
      verb: 'considerar',
      tense: 'pretérito perfeito',
      answers: ['considerou'],
    },
    {
      sentence: 'Os alunos {blank} a proposta do professor.',
      verb: 'considerar',
      tense: 'pretérito perfeito',
      answers: ['consideraram'],
    },
    {
      sentence: 'Maria {blank} mudar de emprego no mês passado.',
      verb: 'considerar',
      tense: 'pretérito perfeito',
      answers: ['considerou'],
    },
    {
      sentence: 'Eu e João {blank} as críticas sobre o projeto.',
      verb: 'considerar',
      tense: 'pretérito perfeito',
      answers: ['consideramos'],
    },
    {
      sentence: 'Vocês {blank} a importância de trabalhar em equipe.',
      verb: 'considerar',
      tense: 'pretérito perfeito',
      answers: ['consideraram'],
    },
    {
      sentence: 'Ele {blank} as ideias que você apresentou.',
      verb: 'considerar',
      tense: 'pretérito perfeito',
      answers: ['considerou'],
    },
    {
      sentence: 'Nós {blank} as várias opções antes de fazer a escolha final.',
      verb: 'considerar',
      tense: 'pretérito perfeito',
      answers: ['consideramos'],
    },
    {
      sentence: 'Eu {blank} todas as opções antes de decidir.',
      verb: 'considerar',
      tense: 'futuro',
      answers: ['considerarei', 'vou considerar'],
    },
    {
      sentence: 'Nós {blank} diferentes abordagens para o projeto.',
      verb: 'considerar',
      tense: 'futuro',
      answers: ['consideraremos', 'vamos considerar'],
    },
    {
      sentence: 'Eles {blank} a proposta na próxima reunião.',
      verb: 'considerar',
      tense: 'futuro',
      answers: ['considerarão', 'vão considerar'],
    },
    {
      sentence: 'Você {blank} os resultados antes de fazer qualquer mudança.',
      verb: 'considerar',
      tense: 'futuro',
      answers: ['considerará', 'vai considerar'],
    },
    {
      sentence: 'Maria {blank} participar do evento no mês que vem.',
      verb: 'considerar',
      tense: 'futuro',
      answers: ['considerará', 'vai considerar'],
    },
    {
      sentence: 'Nós {blank} as implicações da decisão amanhã.',
      verb: 'considerar',
      tense: 'futuro',
      answers: ['consideraremos', 'vamos considerar'],
    },
    {
      sentence: 'Vocês {blank} a possibilidade de viajar nas férias.',
      verb: 'considerar',
      tense: 'futuro',
      answers: ['considerarão', 'vão considerar'],
    },
    {
      sentence: 'Ele {blank} a sua sugestão na próxima semana.',
      verb: 'considerar',
      tense: 'futuro',
      answers: ['considerará', 'vai considerar'],
    },
    {
      sentence: 'Ana e eu {blank} os prós e contras da mudança.',
      verb: 'considerar',
      tense: 'futuro',
      answers: ['consideraremos', 'vamos considerar'],
    },
    {
      sentence: 'Você {blank} as consequências da decisão.',
      verb: 'considerar',
      tense: 'futuro',
      answers: ['considerará', 'vai considerar'],
    },
    {
      sentence: 'Eu {blank} as opções disponíveis antes de decidir.',
      verb: 'considerar',
      tense: 'presente',
      answers: ['considero'],
    },
    {
      sentence: 'Ela {blank} todas as consequências de suas ações.',
      verb: 'considerar',
      tense: 'presente',
      answers: ['considera'],
    },
    {
      sentence: 'Nós {blank} a possibilidade de viajar no próximo mês.',
      verb: 'considerar',
      tense: 'presente',
      answers: ['consideramos'],
    },
    {
      sentence: 'Você {blank} esse projeto muito importante.',
      verb: 'considerar',
      tense: 'presente',
      answers: ['considera'],
    },
    {
      sentence: 'Eles {blank} as opiniões de todos os envolvidos.',
      verb: 'considerar',
      tense: 'presente',
      answers: ['consideram'],
    },
    {
      sentence: 'João {blank} a ideia de abrir um novo negócio.',
      verb: 'considerar',
      tense: 'presente',
      answers: ['considera'],
    },
    {
      sentence: 'Maria e eu {blank} mudar de cidade no futuro.',
      verb: 'considerar',
      tense: 'presente',
      answers: ['consideramos'],
    },
    {
      sentence: 'Vocês {blank} as regras do jogo antes de começar.',
      verb: 'considerar',
      tense: 'presente',
      answers: ['consideram'],
    },
    {
      sentence: 'Ana e Pedro {blank} todas as alternativas disponíveis.',
      verb: 'considerar',
      tense: 'presente',
      answers: ['consideram'],
    },
    {
      sentence: 'Eu e você {blank} os pros e contras dessa decisão.',
      verb: 'considerar',
      tense: 'presente',
      answers: ['consideramos'],
    },
  ],
};
