import { ProblemList } from '../Problems';

export const correr: ProblemList = {
  verb: 'correr',
  problems: [
    {
      sentence: 'Eu {blank} muito rápido na corrida.',
      verb: 'correr',
      tense: 'pretérito perfeito',
      answers: ['corri'],
    },
    {
      sentence: 'Ela {blank} na maratona no mês passado.',
      verb: 'correr',
      tense: 'pretérito perfeito',
      answers: ['correu'],
    },
    {
      sentence: 'Nós {blank} juntos na competição.',
      verb: 'correr',
      tense: 'pretérito perfeito',
      answers: ['corremos'],
    },
    {
      sentence: 'Vocês {blank} muito bem na corrida ontem.',
      verb: 'correr',
      tense: 'pretérito perfeito',
      answers: ['correram'],
    },
    {
      sentence: 'João {blank} na pista de atletismo.',
      verb: 'correr',
      tense: 'pretérito perfeito',
      answers: ['correu'],
    },
    {
      sentence: 'Maria e eu {blank} durante todo o treino.',
      verb: 'correr',
      tense: 'pretérito perfeito',
      answers: ['corremos'],
    },
    {
      sentence: 'Vocês {blank} para o estádio na última semana.',
      verb: 'correr',
      tense: 'pretérito perfeito',
      answers: ['correram'],
    },
    {
      sentence: 'Ele {blank} na trilha no fim de semana passado.',
      verb: 'correr',
      tense: 'pretérito perfeito',
      answers: ['correu'],
    },
    {
      sentence: 'Nós {blank} pra escola todos os dias.',
      verb: 'correr',
      tense: 'pretérito perfeito',
      answers: ['corríamos'],
    },
    {
      sentence: 'Você {blank} para pegar o ônibus.',
      verb: 'correr',
      tense: 'pretérito perfeito',
      answers: ['correu'],
    },
    {
      sentence: 'Eu {blank} a corrida amanhã cedo.',
      verb: 'correr',
      tense: 'futuro',
      answers: ['correrei', 'vou correr'],
    },
    {
      sentence: 'Você {blank} a maratona no próximo mês.',
      verb: 'correr',
      tense: 'futuro',
      answers: ['correrá', 'vai correr'],
    },
    {
      sentence: 'Eles {blank} muito mais rápido na próxima prova.',
      verb: 'correr',
      tense: 'futuro',
      answers: ['correrão', 'vão correr'],
    },
    {
      sentence: 'Nós {blank} juntos pela cidade no fim de semana.',
      verb: 'correr',
      tense: 'futuro',
      answers: ['corrermos', 'vamos correr'],
    },
    {
      sentence: 'A Ana {blank} para o trabalho na próxima semana.',
      verb: 'correr',
      tense: 'futuro',
      answers: ['correrá', 'vai correr'],
    },
    {
      sentence: 'Você e eu {blank} muito longe no domingo.',
      verb: 'correr',
      tense: 'futuro',
      answers: ['correremos', 'vamos correr'],
    },
    {
      sentence: 'Os alunos {blank} na pista após a aula.',
      verb: 'correr',
      tense: 'futuro',
      answers: ['correrão', 'vão correr'],
    },
    {
      sentence: 'A Maria e o João {blank} na competição no mês que vem.',
      verb: 'correr',
      tense: 'futuro',
      answers: ['correrão', 'vão correr'],
    },
    {
      sentence: 'Eu e minha irmã {blank} todos os dias no verão.',
      verb: 'correr',
      tense: 'futuro',
      answers: ['correremos', 'vamos correr'],
    },
    {
      sentence: 'Você {blank} no parque amanhã à tarde.',
      verb: 'correr',
      tense: 'futuro',
      answers: ['correrá', 'vai correr'],
    },
    {
      sentence: 'Eu {blank} todos os dias no parque.',
      verb: 'correr',
      tense: 'presente',
      answers: ['corro'],
    },
    {
      sentence: 'Ela {blank} muito rápido durante a corrida.',
      verb: 'correr',
      tense: 'presente',
      answers: ['corre'],
    },
    {
      sentence: 'Nós {blank} juntos na maratona.',
      verb: 'correr',
      tense: 'presente',
      answers: ['corrermos'],
    },
    {
      sentence: 'Você {blank} sempre para se manter saudável.',
      verb: 'correr',
      tense: 'presente',
      answers: ['corre'],
    },
    {
      sentence: 'Eles {blank} a pista todos os sábados.',
      verb: 'correr',
      tense: 'presente',
      answers: ['correm'],
    },
    {
      sentence: 'João {blank} todos os dias pela manhã.',
      verb: 'correr',
      tense: 'presente',
      answers: ['corre'],
    },
    {
      sentence: 'Mariana e eu {blank} uma vez por semana.',
      verb: 'correr',
      tense: 'presente',
      answers: ['corremos'],
    },
    {
      sentence: 'Você e Carlos {blank} na competição este mês.',
      verb: 'correr',
      tense: 'presente',
      answers: ['correm'],
    },
    {
      sentence: 'As crianças {blank} no parque depois da escola.',
      verb: 'correr',
      tense: 'presente',
      answers: ['correm'],
    },
    {
      sentence: 'Meu pai {blank} muito bem por causa do treino.',
      verb: 'correr',
      tense: 'presente',
      answers: ['corre'],
    },
  ],
};
