import { ProblemList } from '../Problems';

export const cozinhar: ProblemList = {
  verb: 'cozinhar',
  problems: [
    {
      sentence: 'Eu {blank} um prato especial para o jantar.',
      verb: 'cozinhar',
      tense: 'pretérito perfeito',
      answers: ['cozinhei'],
    },
    {
      sentence: 'Ela {blank} um bolo maravilhoso para o aniversário.',
      verb: 'cozinhar',
      tense: 'pretérito perfeito',
      answers: ['cozinhar'],
    },
    {
      sentence: 'Nós {blank} juntos uma refeição deliciosa.',
      verb: 'cozinhar',
      tense: 'pretérito perfeito',
      answers: ['cozinhamos'],
    },
    {
      sentence: 'Vocês {blank} o almoço na casa da avó.',
      verb: 'cozinhar',
      tense: 'pretérito perfeito',
      answers: ['cozinharam'],
    },
    {
      sentence: 'Ele {blank} um peixe grelhado para o jantar.',
      verb: 'cozinhar',
      tense: 'pretérito perfeito',
      answers: ['cozinhar'],
    },
    {
      sentence: 'Nós {blank} uma refeição incrível para os convidados.',
      verb: 'cozinhar',
      tense: 'pretérito perfeito',
      answers: ['cozinhamos'],
    },
    {
      sentence: 'Marta {blank} um prato típico para a festa.',
      verb: 'cozinhar',
      tense: 'pretérito perfeito',
      answers: ['cozinhar'],
    },
    {
      sentence: 'Você {blank} as verduras para a salada.',
      verb: 'cozinhar',
      tense: 'pretérito perfeito',
      answers: ['cozinhar'],
    },
    {
      sentence: 'Eles {blank} um delicioso brunch no domingo.',
      verb: 'cozinhar',
      tense: 'pretérito perfeito',
      answers: ['cozinharam'],
    },
    {
      sentence: 'João {blank} um lanche rápido antes de sair.',
      verb: 'cozinhar',
      tense: 'pretérito perfeito',
      answers: ['cozinhar'],
    },
    {
      sentence: 'Eu {blank} um jantar especial para vocês no próximo sábado.',
      verb: 'cozinhar',
      tense: 'futuro',
      answers: ['cozinhar', 'vou cozinhar'],
    },
    {
      sentence: 'Ela {blank} um ótimo prato para a festa amanhã.',
      verb: 'cozinhar',
      tense: 'futuro',
      answers: ['cozinhará', 'vai cozinhar'],
    },
    {
      sentence: 'Nós {blank} um bolo delicioso para o aniversário do João.',
      verb: 'cozinhar',
      tense: 'futuro',
      answers: ['cozinharão', 'vamos cozinhar'],
    },
    {
      sentence: 'Vocês {blank} um almoço para a reunião na próxima terça.',
      verb: 'cozinhar',
      tense: 'futuro',
      answers: ['cozinharão', 'vão cozinhar'],
    },
    {
      sentence: 'Ele {blank} uma sopa saudável na sexta-feira.',
      verb: 'cozinhar',
      tense: 'futuro',
      answers: ['cozinhará', 'vai cozinhar'],
    },
    {
      sentence: 'Eu {blank} uma receita nova para a ceia de Natal.',
      verb: 'cozinhar',
      tense: 'futuro',
      answers: ['cozinhar', 'vou cozinhar'],
    },
    {
      sentence: 'Vocês {blank} uma deliciosa lasanha para o jantar.',
      verb: 'cozinhar',
      tense: 'futuro',
      answers: ['cozinharão', 'vão cozinhar'],
    },
    {
      sentence: 'Nós {blank} um brunch para os amigos no próximo domingo.',
      verb: 'cozinhar',
      tense: 'futuro',
      answers: ['cozinhar', 'vamos cozinhar'],
    },
    {
      sentence: 'Ela {blank} um prato vegetariano para a reunião.',
      verb: 'cozinhar',
      tense: 'futuro',
      answers: ['cozinhará', 'vai cozinhar'],
    },
    {
      sentence: 'Eles {blank} uma refeição maravilhosa para a visita.',
      verb: 'cozinhar',
      tense: 'futuro',
      answers: ['cozinharão', 'vão cozinhar'],
    },
    {
      sentence: 'Eu {blank} um bolo para o aniversário do João.',
      verb: 'cozinhar',
      tense: 'presente',
      answers: ['cozinho'],
    },
    {
      sentence: 'Ela {blank} um jantar especial todos os sábados.',
      verb: 'cozinhar',
      tense: 'presente',
      answers: ['cozinha'],
    },
    {
      sentence: 'Nós {blank} a receita preferida da Ana.',
      verb: 'cozinhar',
      tense: 'presente',
      answers: ['cozinhamos'],
    },
    {
      sentence: 'Você {blank} os pratos com muito carinho.',
      verb: 'cozinhar',
      tense: 'presente',
      answers: ['cozinha'],
    },
    {
      sentence: 'Eles {blank} sempre juntos nas festas de fim de ano.',
      verb: 'cozinhar',
      tense: 'presente',
      answers: ['cozinham'],
    },
    {
      sentence: 'Maria e eu {blank} uma sopa deliciosa para o inverno.',
      verb: 'cozinhar',
      tense: 'presente',
      answers: ['cozinhamos'],
    },
    {
      sentence: 'Você e o Paulo {blank} um almoço no domingo.',
      verb: 'cozinhar',
      tense: 'presente',
      answers: ['cozinham'],
    },
    {
      sentence: 'A sobremesa que a Clara {blank} é sempre um sucesso.',
      verb: 'cozinhar',
      tense: 'presente',
      answers: ['cozinha'],
    },
    {
      sentence: 'Nós {blank} uma variedade de pratos na nossa casa.',
      verb: 'cozinhar',
      tense: 'presente',
      answers: ['cozinhamos'],
    },
    {
      sentence: 'Você {blank} comida italiana muito bem.',
      verb: 'cozinhar',
      tense: 'presente',
      answers: ['cozinha'],
    },
  ],
};
