import { ProblemList } from '../Problems';

export const dançar: ProblemList = {
  verb: 'dançar',
  problems: [
    {
      sentence: 'Nós {blank} na festa de aniversário da Maria.',
      verb: 'dançar',
      tense: 'pretérito perfeito',
      answers: ['dançamos'],
    },
    {
      sentence: 'Ele {blank} com os amigos na balada na sexta-feira.',
      verb: 'dançar',
      tense: 'pretérito perfeito',
      answers: ['dançou'],
    },
    {
      sentence: 'Você {blank} muito bem na apresentação de dança.',
      verb: 'dançar',
      tense: 'pretérito perfeito',
      answers: ['dançou'],
    },
    {
      sentence: 'Ela {blank} com alegria no festival de música.',
      verb: 'dançar',
      tense: 'pretérito perfeito',
      answers: ['dançou'],
    },
    {
      sentence: 'Eu {blank} até o amanhecer na festa.',
      verb: 'dançar',
      tense: 'pretérito perfeito',
      answers: ['dancei'],
    },
    {
      sentence: 'Os alunos {blank} em grupo na aula de dança.',
      verb: 'dançar',
      tense: 'pretérito perfeito',
      answers: ['dançaram'],
    },
    {
      sentence: 'Lucas e Ana {blank} juntos no evento escolar.',
      verb: 'dançar',
      tense: 'pretérito perfeito',
      answers: ['dançaram'],
    },
    {
      sentence: 'Vocês {blank} uma coreografia linda no concurso.',
      verb: 'dançar',
      tense: 'pretérito perfeito',
      answers: ['dançaram'],
    },
    {
      sentence: 'Eu e meu irmão {blank} a noite toda durante a festa.',
      verb: 'dançar',
      tense: 'pretérito perfeito',
      answers: ['dançamos'],
    },
    {
      sentence: 'A turma {blank} para celebrar a vitória.',
      verb: 'dançar',
      tense: 'pretérito perfeito',
      answers: ['dançou'],
    },
    {
      sentence: 'Eu {blank} na festa de aniversário da Maria.',
      verb: 'dançar',
      tense: 'presente',
      answers: ['danço'],
    },
    {
      sentence: 'Ela {blank} muito bem nas aulas de dança.',
      verb: 'dançar',
      tense: 'presente',
      answers: ['dance'],
    },
    {
      sentence: 'Nós {blank} juntos na festa na semana passada.',
      verb: 'dançar',
      tense: 'presente',
      answers: ['dançamos'],
    },
    {
      sentence: 'Vocês {blank} a coreografia nova na competição.',
      verb: 'dançar',
      tense: 'presente',
      answers: ['dançam'],
    },
    {
      sentence: 'Ele {blank} todos os sábados na escola de dança.',
      verb: 'dançar',
      tense: 'presente',
      answers: ['dança'],
    },
    {
      sentence: 'Ana e eu {blank} por horas na festa.',
      verb: 'dançar',
      tense: 'presente',
      answers: ['dançamos'],
    },
    {
      sentence: 'Vocês {blank} muito alegremente na celebração.',
      verb: 'dançar',
      tense: 'presente',
      answers: ['dançam'],
    },
    {
      sentence: 'Meu irmão {blank} com a namorada durante a festa.',
      verb: 'dançar',
      tense: 'presente',
      answers: ['dança'],
    },
    {
      sentence: 'Esther {blank} a música favorita dela.',
      verb: 'dançar',
      tense: 'presente',
      answers: ['dança'],
    },
    {
      sentence: 'A gente {blank} muito quando estamos juntos.',
      verb: 'dançar',
      tense: 'presente',
      answers: ['dança'],
    },
    {
      sentence: 'Eu {blank} na festa de aniversário do João no próximo mês.',
      verb: 'dançar',
      tense: 'futuro',
      answers: ['dançarei', 'vou dançar'],
    },
    {
      sentence: 'Ela {blank} no casamento da sua irmã no próximo verão.',
      verb: 'dançar',
      tense: 'futuro',
      answers: ['dançará', 'vai dançar'],
    },
    {
      sentence: 'Nós {blank} juntos no evento da escola na próxima semana.',
      verb: 'dançar',
      tense: 'futuro',
      answers: ['dançaremos', 'vamos dançar'],
    },
    {
      sentence: 'Vocês {blank} na competição de dança no próximo ano.',
      verb: 'dançar',
      tense: 'futuro',
      answers: ['dançarão', 'vão dançar'],
    },
    {
      sentence: 'O Lucas e a Maria {blank} na balada no próximo sábado.',
      verb: 'dançar',
      tense: 'futuro',
      answers: ['dançarão', 'vão dançar'],
    },
    {
      sentence: 'Eu e você {blank} em um concurso de dança no próximo mês.',
      verb: 'dançar',
      tense: 'futuro',
      answers: ['dançaremos', 'vamos dançar'],
    },
    {
      sentence: 'Ela {blank} na aula de dança na próxima quarta-feira.',
      verb: 'dançar',
      tense: 'futuro',
      answers: ['dançará', 'vai dançar'],
    },
    {
      sentence: 'Nós {blank} no festival de cultura no próximo verão.',
      verb: 'dançar',
      tense: 'futuro',
      answers: ['dançaremos', 'vamos dançar'],
    },
    {
      sentence: 'Eles {blank} no encontro de família na próxima festa.',
      verb: 'dançar',
      tense: 'futuro',
      answers: ['dançarão', 'vão dançar'],
    },
    {
      sentence: 'Você {blank} no show de talentos na próxima semana.',
      verb: 'dançar',
      tense: 'futuro',
      answers: ['dançará', 'vai dançar'],
    },
  ],
};
