import { ProblemList } from '../Problems';

export const deixar: ProblemList = {
  verb: 'deixar',
  problems: [
    {
      sentence: 'Eu {blank} a porta aberta por um tempo.',
      verb: 'deixar',
      tense: 'pretérito perfeito',
      answers: ['deixei'],
    },
    {
      sentence: 'Ela {blank} as chaves em cima da mesa.',
      verb: 'deixar',
      tense: 'pretérito perfeito',
      answers: ['deixou'],
    },
    {
      sentence: 'Nós {blank} o carro na garagem depois do passeio.',
      verb: 'deixar',
      tense: 'pretérito perfeito',
      answers: ['deixamos'],
    },
    {
      sentence: 'Você {blank} um recado para mim.',
      verb: 'deixar',
      tense: 'pretérito perfeito',
      answers: ['deixou'],
    },
    {
      sentence: 'Eles {blank} uma mensagem importante no grupo.',
      verb: 'deixar',
      tense: 'pretérito perfeito',
      answers: ['deixaram'],
    },
    {
      sentence: 'Maria {blank} os livros na biblioteca.',
      verb: 'deixar',
      tense: 'pretérito perfeito',
      answers: ['deixou'],
    },
    {
      sentence: 'João {blank} a luz acesa durante a noite.',
      verb: 'deixar',
      tense: 'pretérito perfeito',
      answers: ['deixou'],
    },
    {
      sentence: 'Nós {blank} os planos para depois.',
      verb: 'deixar',
      tense: 'pretérito perfeito',
      answers: ['deixamos'],
    },
    {
      sentence: 'Você e eu {blank} a reunião marcada para amanhã.',
      verb: 'deixar',
      tense: 'pretérito perfeito',
      answers: ['deixamos'],
    },
    {
      sentence: 'As garotas {blank} o projeto para o professor.',
      verb: 'deixar',
      tense: 'pretérito perfeito',
      answers: ['deixaram'],
    },
    {
      sentence: 'Eu {blank} os problemas para resolver mais tarde.',
      verb: 'deixar',
      tense: 'presente',
      answers: ['deixo'],
    },
    {
      sentence: 'Ela {blank} a janela aberta durante a noite.',
      verb: 'deixar',
      tense: 'presente',
      answers: ['deixa'],
    },
    {
      sentence: 'Nós {blank} as preocupações de lado e nos divertimos.',
      verb: 'deixar',
      tense: 'presente',
      answers: ['deixamos'],
    },
    {
      sentence: 'Vocês {blank} as opções em aberto para discutir depois.',
      verb: 'deixar',
      tense: 'presente',
      answers: ['deixam'],
    },
    {
      sentence: 'Eu {blank} uma mensagem para você mais tarde.',
      verb: 'deixar',
      tense: 'presente',
      answers: ['deixo'],
    },
    {
      sentence: 'Carlos {blank} a decisão a cargo dos outros.',
      verb: 'deixar',
      tense: 'presente',
      answers: ['deixa'],
    },
    {
      sentence: 'Vocês {blank} sempre as melhores dicas de viagem.',
      verb: 'deixar',
      tense: 'presente',
      answers: ['deixam'],
    },
    {
      sentence: 'Ela {blank} claro que tudo vai ficar bem.',
      verb: 'deixar',
      tense: 'presente',
      answers: ['deixa'],
    },
    {
      sentence:
        'Marcos e eu {blank} as portas abertas para novas oportunidades.',
      verb: 'deixar',
      tense: 'presente',
      answers: ['deixamos'],
    },
    {
      sentence: 'Eles {blank} a pergunta sem resposta.',
      verb: 'deixar',
      tense: 'presente',
      answers: ['deixam'],
    },
    {
      sentence: 'Eu {blank} as chaves na mesa amanhã.',
      verb: 'deixar',
      tense: 'futuro',
      answers: ['deixarei', 'vou deixar'],
    },
    {
      sentence: 'Ela {blank} seu celular no carro na próxima semana.',
      verb: 'deixar',
      tense: 'futuro',
      answers: ['deixará', 'vai deixar'],
    },
    {
      sentence: 'Nós {blank} as luzes acesas ao sair.',
      verb: 'deixar',
      tense: 'futuro',
      answers: ['deixaremos', 'vamos deixar'],
    },
    {
      sentence: 'Você {blank} a porta aberta ao sair.',
      verb: 'deixar',
      tense: 'futuro',
      answers: ['deixará', 'vai deixar'],
    },
    {
      sentence: 'Eles {blank} a comida pronta para vocês.',
      verb: 'deixar',
      tense: 'futuro',
      answers: ['deixarão', 'vão deixar'],
    },
    {
      sentence: 'João {blank} a mensagem para você amanhã.',
      verb: 'deixar',
      tense: 'futuro',
      answers: ['deixará', 'vai deixar'],
    },
    {
      sentence: 'Maria {blank} o livro na biblioteca na próxima quarta-feira.',
      verb: 'deixar',
      tense: 'futuro',
      answers: ['deixará', 'vai deixar'],
    },
    {
      sentence: 'Vocês {blank} os brinquedos no parque amanhã.',
      verb: 'deixar',
      tense: 'futuro',
      answers: ['deixarão', 'vão deixar'],
    },
    {
      sentence: 'Nós {blank} o carro na oficina na próxima segunda.',
      verb: 'deixar',
      tense: 'futuro',
      answers: ['deixaremos', 'vamos deixar'],
    },
    {
      sentence: 'A professora {blank} a tarefa fácil para a próxima aula.',
      verb: 'deixar',
      tense: 'futuro',
      answers: ['deixará', 'vai deixar'],
    },
  ],
};
