import { ProblemList } from '../Problems';

export const descansar: ProblemList = {
  verb: 'descansar',
  problems: [
    {
      sentence: 'Eu {blank} no sofá depois do trabalho.',
      verb: 'descansar',
      tense: 'presente',
      answers: ['descanço'],
    },
    {
      sentence: 'Ela {blank} um pouco antes do jantar.',
      verb: 'descansar',
      tense: 'presente',
      answers: ['descansa'],
    },
    {
      sentence: 'Nós {blank} durante os finais de semana.',
      verb: 'descansar',
      tense: 'presente',
      answers: ['descansamos'],
    },
    {
      sentence: 'Você {blank} sempre que pode.',
      verb: 'descansar',
      tense: 'presente',
      answers: ['descansa'],
    },
    {
      sentence: 'Eles {blank} após a aula todos os dias.',
      verb: 'descansar',
      tense: 'presente',
      answers: ['descansam'],
    },
    {
      sentence: 'João {blank} no parque frequentemente.',
      verb: 'descansar',
      tense: 'presente',
      answers: ['descansa'],
    },
    {
      sentence: 'Maria e eu {blank} um pouco na cama.',
      verb: 'descansar',
      tense: 'presente',
      answers: ['descansamos'],
    },
    {
      sentence: 'Vocês {blank} em casa nas férias.',
      verb: 'descansar',
      tense: 'presente',
      answers: ['descansam'],
    },
    {
      sentence: 'Ela e você {blank} juntos no final de semana.',
      verb: 'descansar',
      tense: 'presente',
      answers: ['descansam'],
    },
    {
      sentence: 'Eu e você {blank} depois do almoço.',
      verb: 'descansar',
      tense: 'presente',
      answers: ['descansamos'],
    },
    {
      sentence: 'Eu {blank} após o trabalho na sexta-feira passada.',
      verb: 'descansar',
      tense: 'pretérito perfeito',
      answers: ['descansei'],
    },
    {
      sentence: 'Ela {blank} muito durante o fim de semana.',
      verb: 'descansar',
      tense: 'pretérito perfeito',
      answers: ['descansou'],
    },
    {
      sentence: 'Nós {blank} antes da viagem de férias.',
      verb: 'descansar',
      tense: 'pretérito perfeito',
      answers: ['descansamos'],
    },
    {
      sentence: 'Você {blank} bem na semana passada.',
      verb: 'descansar',
      tense: 'pretérito perfeito',
      answers: ['descansou'],
    },
    {
      sentence: 'Eles {blank} na casa de praia durante o feriado.',
      verb: 'descansar',
      tense: 'pretérito perfeito',
      answers: ['descansaram'],
    },
    {
      sentence: 'João {blank} em casa no sábado.',
      verb: 'descansar',
      tense: 'pretérito perfeito',
      answers: ['descansou'],
    },
    {
      sentence: 'Nós {blank} antes do grande evento.',
      verb: 'descansar',
      tense: 'pretérito perfeito',
      answers: ['descansamos'],
    },
    {
      sentence: 'Você e Maria {blank} bastante no último feriado.',
      verb: 'descansar',
      tense: 'pretérito perfeito',
      answers: ['descansaram'],
    },
    {
      sentence: 'Ana e eu {blank} após as provas.',
      verb: 'descansar',
      tense: 'pretérito perfeito',
      answers: ['descansamos'],
    },
    {
      sentence: 'Os meninos {blank} muito antes da competição.',
      verb: 'descansar',
      tense: 'pretérito perfeito',
      answers: ['descanaram'],
    },
    {
      sentence: 'Eu {blank} um pouco mais no próximo feriado.',
      verb: 'descansar',
      tense: 'futuro',
      answers: ['descansarei', 'vou descansar'],
    },
    {
      sentence: 'Você {blank} após o trabalho na sexta-feira.',
      verb: 'descansar',
      tense: 'futuro',
      answers: ['descansará', 'vai descansar'],
    },
    {
      sentence: 'Nós {blank} no fim de semana seguinte.',
      verb: 'descansar',
      tense: 'futuro',
      answers: ['descansaremos', 'vamos descansar'],
    },
    {
      sentence: 'Ela {blank} na casa de praia durante as férias.',
      verb: 'descansar',
      tense: 'futuro',
      answers: ['descansará', 'vai descansar'],
    },
    {
      sentence: 'Eles {blank} bastante antes do exame.',
      verb: 'descansar',
      tense: 'futuro',
      answers: ['descansarão', 'vão descansar'],
    },
    {
      sentence: 'João {blank} depois de terminar o projeto.',
      verb: 'descansar',
      tense: 'futuro',
      answers: ['descansará', 'vai descansar'],
    },
    {
      sentence: 'Vocês {blank} sempre que tiverem oportunidade.',
      verb: 'descansar',
      tense: 'futuro',
      answers: ['descansarão', 'vão descansar'],
    },
    {
      sentence: 'Maria e você {blank} no próximo mês.',
      verb: 'descansar',
      tense: 'futuro',
      answers: ['descansarão', 'vão descansar'],
    },
    {
      sentence: 'Nós {blank} mais tempo juntos no verão.',
      verb: 'descansar',
      tense: 'futuro',
      answers: ['descansaremos', 'vamos descansar'],
    },
    {
      sentence: 'Ela e eu {blank} durante os feriados.',
      verb: 'descansar',
      tense: 'futuro',
      answers: ['descansaremos', 'vamos descansar'],
    },
  ],
};
