import { ProblemList } from '../Problems';

export const dever: ProblemList = {
  verb: 'dever',
  problems: [
    {
      sentence: 'Eu {blank} o trabalho até amanhã.',
      verb: 'dever',
      tense: 'futuro',
      answers: ['deverei', 'vou dever'],
    },
    {
      sentence: 'Você {blank} trazer os livros que pediu.',
      verb: 'dever',
      tense: 'futuro',
      answers: ['deverá', 'vai dever'],
    },
    {
      sentence: 'Ela {blank} entregar o relatório na sexta-feira.',
      verb: 'dever',
      tense: 'futuro',
      answers: ['deverá', 'vai dever'],
    },
    {
      sentence: 'Nós {blank} revisar o projeto juntos.',
      verb: 'dever',
      tense: 'futuro',
      answers: ['deveremos', 'vamos dever'],
    },
    {
      sentence: 'Vocês {blank} cumprir os prazos estabelecidos.',
      verb: 'dever',
      tense: 'futuro',
      answers: ['deverão', 'vão dever'],
    },
    {
      sentence: 'João {blank} participar da reunião amanhã.',
      verb: 'dever',
      tense: 'futuro',
      answers: ['deverá', 'vai dever'],
    },
    {
      sentence: 'Maria e eu {blank} buscar as crianças na escola.',
      verb: 'dever',
      tense: 'futuro',
      answers: ['devemos', 'vamos dever'],
    },
    {
      sentence: 'Você e Pedro {blank} encontrar com a equipe na quinta.',
      verb: 'dever',
      tense: 'futuro',
      answers: ['deverão', 'vão dever'],
    },
    {
      sentence: 'As meninas {blank} fazer o trabalho de casa hoje.',
      verb: 'dever',
      tense: 'futuro',
      answers: ['deverão', 'vão dever'],
    },
    {
      sentence: 'Meu pai {blank} levar o carro para a revisão.',
      verb: 'dever',
      tense: 'futuro',
      answers: ['deverá', 'vai dever'],
    },
    {
      sentence: 'Eu {blank} as minhas tarefas todos os dias.',
      verb: 'dever',
      tense: 'presente',
      answers: ['devo'],
    },
    {
      sentence: 'Ela {blank} se exercitar regularmente.',
      verb: 'dever',
      tense: 'presente',
      answers: ['deve'],
    },
    {
      sentence: 'Nós {blank} estudar para a prova amanhã.',
      verb: 'dever',
      tense: 'presente',
      answers: ['devemos'],
    },
    {
      sentence: 'Você {blank} ser mais pontual.',
      verb: 'dever',
      tense: 'presente',
      answers: ['deve'],
    },
    {
      sentence: 'Eles {blank} ajudar no projeto este mês.',
      verb: 'dever',
      tense: 'presente',
      answers: ['devem'],
    },
    {
      sentence: 'João {blank} terminar a lição antes do jantar.',
      verb: 'dever',
      tense: 'presente',
      answers: ['deve'],
    },
    {
      sentence: 'Maria e eu {blank} ir ao médico na próxima semana.',
      verb: 'dever',
      tense: 'presente',
      answers: ['devemos'],
    },
    {
      sentence: 'Você e seus amigos {blank} participar do evento.',
      verb: 'dever',
      tense: 'presente',
      answers: ['devem'],
    },
    {
      sentence: 'Ana {blank} comprar leite hoje à tarde.',
      verb: 'dever',
      tense: 'presente',
      answers: ['deve'],
    },
    {
      sentence: 'Nós {blank} respeitar as regras do local.',
      verb: 'dever',
      tense: 'presente',
      answers: ['devemos'],
    },
    {
      sentence: 'Eu {blank} a verdade para ela ontem.',
      verb: 'dever',
      tense: 'pretérito perfeito',
      answers: ['devi'],
    },
    {
      sentence: 'Você {blank} estudar para a prova na semana passada.',
      verb: 'dever',
      tense: 'pretérito perfeito',
      answers: ['devia'],
    },
    {
      sentence: 'Ele {blank} terminar o projeto a tempo.',
      verb: 'dever',
      tense: 'pretérito perfeito',
      answers: ['deveu'],
    },
    {
      sentence: 'Nós {blank} respeitar as regras da casa.',
      verb: 'dever',
      tense: 'pretérito perfeito',
      answers: ['devemos'],
    },
    {
      sentence: 'Maria {blank} ajudar os colegas com a tarefa.',
      verb: 'dever',
      tense: 'pretérito perfeito',
      answers: ['deveu'],
    },
    {
      sentence: 'Vocês {blank} sair mais cedo do trabalho.',
      verb: 'dever',
      tense: 'pretérito perfeito',
      answers: ['deveram'],
    },
    {
      sentence: 'Ele e Ana {blank} ir à festa juntos.',
      verb: 'dever',
      tense: 'pretérito perfeito',
      answers: ['deveram'],
    },
    {
      sentence: 'Eu {blank} voltar para casa antes da meia-noite.',
      verb: 'dever',
      tense: 'pretérito perfeito',
      answers: ['devi'],
    },
    {
      sentence: 'Nós {blank} ser mais cuidadosos com as palavras.',
      verb: 'dever',
      tense: 'pretérito perfeito',
      answers: ['devemos'],
    },
    {
      sentence: 'Você {blank} lembrar de trazer o material.',
      verb: 'dever',
      tense: 'pretérito perfeito',
      answers: ['deveu'],
    },
  ],
};
