import { ProblemList } from '../Problems';

export const diminuir: ProblemList = {
  verb: 'diminuir',
  problems: [
    {
      sentence: 'Eu {blank} a quantidade de açúcar na receita.',
      verb: 'diminuir',
      tense: 'presente',
      answers: ['diminuo'],
    },
    {
      sentence: 'Ela {blank} o tempo que dedica ao trabalho.',
      verb: 'diminuir',
      tense: 'presente',
      answers: ['diminui'],
    },
    {
      sentence:
        'Nós {blank} a velocidade do carro para economizar combustível.',
      verb: 'diminuir',
      tense: 'presente',
      answers: ['diminuímos'],
    },
    {
      sentence: 'Você {blank} os gastos com alimentação este mês.',
      verb: 'diminuir',
      tense: 'presente',
      answers: ['diminui'],
    },
    {
      sentence: 'Eles {blank} a quantidade de plástico que utilizam.',
      verb: 'diminuir',
      tense: 'presente',
      answers: ['diminuem'],
    },
    {
      sentence: 'Maria {blank} a frequência de treinos na academia.',
      verb: 'diminuir',
      tense: 'presente',
      answers: ['diminui'],
    },
    {
      sentence: 'Nós {blank} as reuniões para ser mais produtivos.',
      verb: 'diminuir',
      tense: 'presente',
      answers: ['diminuímos'],
    },
    {
      sentence: 'Você e eu {blank} nossos custos mensais juntos.',
      verb: 'diminuir',
      tense: 'presente',
      answers: ['diminuímos'],
    },
    {
      sentence: 'João {blank} a quantidade de horas que passa no celular.',
      verb: 'diminuir',
      tense: 'presente',
      answers: ['diminui'],
    },
    {
      sentence: 'Ela e suas amigas {blank} o uso de maquiagem.',
      verb: 'diminuir',
      tense: 'presente',
      answers: ['diminuem'],
    },
    {
      sentence: 'Eu {blank} o barulho antes de sair de casa.',
      verb: 'diminuir',
      tense: 'pretérito perfeito',
      answers: ['diminuí'],
    },
    {
      sentence: 'Ela {blank} a intensidade da luz no escritório.',
      verb: 'diminuir',
      tense: 'pretérito perfeito',
      answers: ['diminuíu'],
    },
    {
      sentence: 'Nós {blank} a velocidade do carro na estrada.',
      verb: 'diminuir',
      tense: 'pretérito perfeito',
      answers: ['diminuímos'],
    },
    {
      sentence: 'Ele {blank} o consumo de energia em casa.',
      verb: 'diminuir',
      tense: 'pretérito perfeito',
      answers: ['diminuíu'],
    },
    {
      sentence: 'Vocês {blank} a quantidade de açúcar na receita.',
      verb: 'diminuir',
      tense: 'pretérito perfeito',
      answers: ['diminuíram'],
    },
    {
      sentence: 'A Maria {blank} as despesas do mês passado.',
      verb: 'diminuir',
      tense: 'pretérito perfeito',
      answers: ['diminiu'],
    },
    {
      sentence: 'Nós {blank} a poluição na cidade.',
      verb: 'diminuir',
      tense: 'pretérito perfeito',
      answers: ['diminuímos'],
    },
    {
      sentence: 'Você {blank} o barulho na festa.',
      verb: 'diminuir',
      tense: 'pretérito perfeito',
      answers: ['diminuíu'],
    },
    {
      sentence: 'Eles {blank} os problemas na empresa.',
      verb: 'diminuir',
      tense: 'pretérito perfeito',
      answers: ['diminuíram'],
    },
    {
      sentence: 'O João {blank} a produção no último mês.',
      verb: 'diminuir',
      tense: 'pretérito perfeito',
      answers: ['diminiu'],
    },
    {
      sentence: 'Eu {blank} o meu consumo de açúcar na próxima semana.',
      verb: 'diminuir',
      tense: 'futuro',
      answers: ['diminuirei', 'vou diminuir'],
    },
    {
      sentence: 'Você {blank} o barulho ao lado do seu escritório amanhã.',
      verb: 'diminuir',
      tense: 'futuro',
      answers: ['diminuirá', 'vai diminuir'],
    },
    {
      sentence: 'Ela {blank} a quantidade de café que toma durante o dia.',
      verb: 'diminuir',
      tense: 'futuro',
      answers: ['diminuirá', 'vai diminuir'],
    },
    {
      sentence: 'Nós {blank} o consumo de energia em casa no próximo mês.',
      verb: 'diminuir',
      tense: 'futuro',
      answers: ['diminuiremos', 'vamos diminuir'],
    },
    {
      sentence: 'Eles {blank} os preços dos ingressos para o show.',
      verb: 'diminuir',
      tense: 'futuro',
      answers: ['diminuirão', 'vão diminuir'],
    },
    {
      sentence: 'Eu e você {blank} a quantidade de plástico que usamos.',
      verb: 'diminuir',
      tense: 'futuro',
      answers: ['diminuiremos', 'vamos diminuir'],
    },
    {
      sentence: 'Joana e Pedro {blank} a frequência das reuniões na empresa.',
      verb: 'diminuir',
      tense: 'futuro',
      answers: ['diminuirão', 'vão diminuir'],
    },
    {
      sentence: 'Você e eu {blank} a velocidade da apresentação do projeto.',
      verb: 'diminuir',
      tense: 'futuro',
      answers: ['diminuiremos', 'vamos diminuir'],
    },
    {
      sentence: 'O governo {blank} os impostos sobre os produtos básicos.',
      verb: 'diminuir',
      tense: 'futuro',
      answers: ['diminuirá', 'vai diminuir'],
    },
    {
      sentence: 'Ana {blank} o tempo que passa jogando videogame.',
      verb: 'diminuir',
      tense: 'futuro',
      answers: ['diminuirá', 'vai diminuir'],
    },
  ],
};
