import { ProblemList } from '../Problems';

export const discutir: ProblemList = {
  verb: 'discutir',
  problems: [
    {
      sentence: 'Nós {blank} sobre o projeto na última reunião.',
      verb: 'discutir',
      tense: 'pretérito perfeito',
      answers: ['discutimos'],
    },
    {
      sentence: 'Ela {blank} os resultados com a equipe ontem.',
      verb: 'discutir',
      tense: 'pretérito perfeito',
      answers: ['discutiu'],
    },
    {
      sentence: 'Eu {blank} os problemas que tivemos na semana passada.',
      verb: 'discutir',
      tense: 'pretérito perfeito',
      answers: ['discuti'],
    },
    {
      sentence: 'Você {blank} a nova estratégia com o chefe recentemente.',
      verb: 'discutir',
      tense: 'pretérito perfeito',
      answers: ['discutiu'],
    },
    {
      sentence: 'Eles {blank} a proposta na conferência anterior.',
      verb: 'discutir',
      tense: 'pretérito perfeito',
      answers: ['discutiram'],
    },
    {
      sentence: 'Ana e eu {blank} as opções de investimento ontem.',
      verb: 'discutir',
      tense: 'pretérito perfeito',
      answers: ['discutimos'],
    },
    {
      sentence: 'Você e ela {blank} sobre as mudanças no plano.',
      verb: 'discutir',
      tense: 'pretérito perfeito',
      answers: ['discutiram'],
    },
    {
      sentence: 'José {blank} a questão da sustentabilidade na reunião.',
      verb: 'discutir',
      tense: 'pretérito perfeito',
      answers: ['discutiu'],
    },
    {
      sentence: 'Nós {blank} os detalhes do evento na última semana.',
      verb: 'discutir',
      tense: 'pretérito perfeito',
      answers: ['discutimos'],
    },
    {
      sentence: 'Vocês {blank} a importância da colaboração recentemente.',
      verb: 'discutir',
      tense: 'pretérito perfeito',
      answers: ['discutiram'],
    },
    {
      sentence: 'Eu {blank} sobre o novo projeto com a equipe.',
      verb: 'discutir',
      tense: 'presente',
      answers: ['discuto'],
    },
    {
      sentence: 'Ela {blank} frequentemente com o gerente sobre as metas.',
      verb: 'discutir',
      tense: 'presente',
      answers: ['discute'],
    },
    {
      sentence: 'Nós {blank} as prioridades na reunião de hoje.',
      verb: 'discutir',
      tense: 'presente',
      answers: ['discutimos'],
    },
    {
      sentence: 'Você {blank} as ideias que propus no encontro.',
      verb: 'discutir',
      tense: 'presente',
      answers: ['discute'],
    },
    {
      sentence: 'Eles {blank} a situação política atual com frequência.',
      verb: 'discutir',
      tense: 'presente',
      answers: ['discutem'],
    },
    {
      sentence: 'Carla e João {blank} sobre as férias recentemente.',
      verb: 'discutir',
      tense: 'presente',
      answers: ['discutem'],
    },
    {
      sentence: 'Eu e você {blank} o relatório na próxima semana.',
      verb: 'discutir',
      tense: 'presente',
      answers: ['discutimos'],
    },
    {
      sentence: 'Ela {blank} a melhor estratégia com os colegas.',
      verb: 'discutir',
      tense: 'presente',
      answers: ['discute'],
    },
    {
      sentence: 'Nós {blank} a nova política da empresa amanhã.',
      verb: 'discutir',
      tense: 'presente',
      answers: ['discutiremos'],
    },
    {
      sentence: 'Vocês {blank} o problema técnico que enfrentaram.',
      verb: 'discutir',
      tense: 'presente',
      answers: ['discutem'],
    },
    {
      sentence: 'Nós {blank} sobre o projeto na próxima reunião.',
      verb: 'discutir',
      tense: 'futuro',
      answers: ['discutiremos', 'vamos discutir'],
    },
    {
      sentence: 'Ela {blank} os detalhes do evento amanhã.',
      verb: 'discutir',
      tense: 'futuro',
      answers: ['discutirá', 'vai discutir'],
    },
    {
      sentence: 'Vocês {blank} as opções disponíveis no próximo mês.',
      verb: 'discutir',
      tense: 'futuro',
      answers: ['discutirão', 'vão discutir'],
    },
    {
      sentence: 'Eu {blank} as metas do time na sexta-feira.',
      verb: 'discutir',
      tense: 'futuro',
      answers: ['discutirei', 'vou discutir'],
    },
    {
      sentence: 'João e Maria {blank} as estratégias para o projeto.',
      verb: 'discutir',
      tense: 'futuro',
      answers: ['discutirão', 'vão discutir'],
    },
    {
      sentence: 'Você {blank} a situação com seu supervisor amanhã.',
      verb: 'discutir',
      tense: 'futuro',
      answers: ['discutirá', 'vai discutir'],
    },
    {
      sentence: 'Nós {blank} a proposta com o cliente na próxima semana.',
      verb: 'discutir',
      tense: 'futuro',
      answers: ['discutiremos', 'vamos discutir'],
    },
    {
      sentence: 'Ana {blank} as implicações da mudança de plano.',
      verb: 'discutir',
      tense: 'futuro',
      answers: ['discutirá', 'vai discutir'],
    },
    {
      sentence: 'Você e eu {blank} as ideias na próxima chamada.',
      verb: 'discutir',
      tense: 'futuro',
      answers: ['discutiremos', 'vamos discutir'],
    },
    {
      sentence: 'Eles {blank} o orçamento durante a conferência.',
      verb: 'discutir',
      tense: 'futuro',
      answers: ['discutirão', 'vão discutir'],
    },
  ],
};
