import { ProblemList } from '../Problems';

export const dizer: ProblemList = {
  verb: 'dizer',
  problems: [
    {
      sentence: 'Eu {blank} o que realmente aconteceu na reunião amanhã.',
      verb: 'dizer',
      tense: 'futuro',
      answers: ['direi', 'vou dizer'],
    },
    {
      sentence: 'Você {blank} a verdade sobre o projeto na próxima semana.',
      verb: 'dizer',
      tense: 'futuro',
      answers: ['dirá', 'vai dizer'],
    },
    {
      sentence: 'Ela {blank} a resposta correta na próxima prova.',
      verb: 'dizer',
      tense: 'futuro',
      answers: ['dirá', 'vai dizer'],
    },
    {
      sentence: 'Nós {blank} os resultados do teste na segunda-feira.',
      verb: 'dizer',
      tense: 'futuro',
      answers: ['diremos', 'vamos dizer'],
    },
    {
      sentence: 'Vocês {blank} o que pensam sobre a nova proposta.',
      verb: 'dizer',
      tense: 'futuro',
      answers: ['dirão', 'vão dizer'],
    },
    {
      sentence: 'Maria {blank} as novidades para os colegas ainda hoje.',
      verb: 'dizer',
      tense: 'futuro',
      answers: ['dirá', 'vai dizer'],
    },
    {
      sentence: 'João {blank} a mensagem assim que puder.',
      verb: 'dizer',
      tense: 'futuro',
      answers: ['dirá', 'vai dizer'],
    },
    {
      sentence: 'Vocês {blank} o que aconteceu durante a reunião.',
      verb: 'dizer',
      tense: 'futuro',
      answers: ['dirão', 'vão dizer'],
    },
    {
      sentence: 'Eu {blank} a verdade sobre o que fiz na viagem.',
      verb: 'dizer',
      tense: 'futuro',
      answers: ['direi', 'vou dizer'],
    },
    {
      sentence: 'Ela {blank} como foi a experiência depois do evento.',
      verb: 'dizer',
      tense: 'futuro',
      answers: ['dirá', 'vai dizer'],
    },
    {
      sentence: 'Eu {blank} a verdade sobre a situação.',
      verb: 'dizer',
      tense: 'presente',
      answers: ['digo'],
    },
    {
      sentence: 'Ela {blank} sempre o que pensa.',
      verb: 'dizer',
      tense: 'presente',
      answers: ['diz'],
    },
    {
      sentence: 'Nós {blank} aos alunos sobre as novas regras.',
      verb: 'dizer',
      tense: 'presente',
      answers: ['dizemos'],
    },
    {
      sentence: 'Vocês {blank} que precisam estudar mais.',
      verb: 'dizer',
      tense: 'presente',
      answers: ['dizem'],
    },
    {
      sentence: 'Ele {blank} que vai participar do evento.',
      verb: 'dizer',
      tense: 'presente',
      answers: ['diz'],
    },
    {
      sentence: 'Você {blank} as instruções claramente.',
      verb: 'dizer',
      tense: 'presente',
      answers: ['diz'],
    },
    {
      sentence: 'Maria {blank} sempre a verdade.',
      verb: 'dizer',
      tense: 'presente',
      answers: ['diz'],
    },
    {
      sentence: 'João e eu {blank} que estamos prontos.',
      verb: 'dizer',
      tense: 'presente',
      answers: ['dizemos'],
    },
    {
      sentence: 'Você e Ana {blank} suas opiniões sobre o assunto.',
      verb: 'dizer',
      tense: 'presente',
      answers: ['dizem'],
    },
    {
      sentence: 'Eles {blank} que a situação vai melhorar.',
      verb: 'dizer',
      tense: 'presente',
      answers: ['dizem'],
    },
    {
      sentence: 'Eu {blank} a verdade sobre o que aconteceu.',
      verb: 'dizer',
      tense: 'pretérito perfeito',
      answers: ['disse'],
    },
    {
      sentence: 'Ela {blank} que iria chegar mais cedo.',
      verb: 'dizer',
      tense: 'pretérito perfeito',
      answers: ['disse'],
    },
    {
      sentence: 'Nós {blank} para eles a nossa decisão.',
      verb: 'dizer',
      tense: 'pretérito perfeito',
      answers: ['dissemos'],
    },
    {
      sentence: 'Você {blank} como se sentia naquele dia.',
      verb: 'dizer',
      tense: 'pretérito perfeito',
      answers: ['disse'],
    },
    {
      sentence: 'Eles {blank} que estavam prontos para sair.',
      verb: 'dizer',
      tense: 'pretérito perfeito',
      answers: ['disseram'],
    },
    {
      sentence: 'João {blank} que viria mais tarde.',
      verb: 'dizer',
      tense: 'pretérito perfeito',
      answers: ['disse'],
    },
    {
      sentence: 'Maria e eu {blank} que a festa foi incrível.',
      verb: 'dizer',
      tense: 'pretérito perfeito',
      answers: ['dissemos'],
    },
    {
      sentence: 'Você e sua irmã {blank} a verdade uns para os outros.',
      verb: 'dizer',
      tense: 'pretérito perfeito',
      answers: ['disseram'],
    },
    {
      sentence: 'A professora {blank} que teríamos prova na semana seguinte.',
      verb: 'dizer',
      tense: 'pretérito perfeito',
      answers: ['disse'],
    },
    {
      sentence: 'Os alunos {blank} que entenderam a matéria.',
      verb: 'dizer',
      tense: 'pretérito perfeito',
      answers: ['disseram'],
    },
  ],
};
