import { ProblemList } from '../Problems';

export const dormir: ProblemList = {
  verb: 'dormir',
  problems: [
    {
      sentence: 'Eu {blank} cedo todas as noites.',
      verb: 'dormir',
      tense: 'presente',
      answers: ['durmo'],
    },
    {
      sentence: 'Você {blank} bem durante a viagem?',
      verb: 'dormir',
      tense: 'presente',
      answers: ['dormiu'],
    },
    {
      sentence: 'Ela {blank} muito para se recuperar.',
      verb: 'dormir',
      tense: 'presente',
      answers: ['dorme'],
    },
    {
      sentence: 'Nós {blank} o suficiente para sermos produtivos.',
      verb: 'dormir',
      tense: 'presente',
      answers: ['dormimos'],
    },
    {
      sentence: 'Eles {blank} no sofá depois do jantar.',
      verb: 'dormir',
      tense: 'presente',
      answers: ['dormem'],
    },
    {
      sentence: 'Você e eu {blank} mais cedo amanhã.',
      verb: 'dormir',
      tense: 'presente',
      answers: ['dormimos'],
    },
    {
      sentence: 'Maria {blank} bem toda noite.',
      verb: 'dormir',
      tense: 'presente',
      answers: ['dorme'],
    },
    {
      sentence: 'As crianças {blank} a tarde toda.',
      verb: 'dormir',
      tense: 'presente',
      answers: ['dormem'],
    },
    {
      sentence: 'Você {blank} tranquilo antes do exame.',
      verb: 'dormir',
      tense: 'presente',
      answers: ['dorme'],
    },
    {
      sentence: 'João {blank} muito quando tem férias.',
      verb: 'dormir',
      tense: 'presente',
      answers: ['dorme'],
    },
    {
      sentence: 'Eu {blank} cedo ontem à noite.',
      verb: 'dormir',
      tense: 'pretérito perfeito',
      answers: ['dormi'],
    },
    {
      sentence: 'Ela {blank} muito durante o final de semana.',
      verb: 'dormir',
      tense: 'pretérito perfeito',
      answers: ['dormiu'],
    },
    {
      sentence: 'Nós {blank} bem na casa de praia.',
      verb: 'dormir',
      tense: 'pretérito perfeito',
      answers: ['dormimos'],
    },
    {
      sentence: 'Você {blank} como um bebê na sua cama.',
      verb: 'dormir',
      tense: 'pretérito perfeito',
      answers: ['dormiu'],
    },
    {
      sentence: 'Eles {blank} durante a viagem toda.',
      verb: 'dormir',
      tense: 'pretérito perfeito',
      answers: ['dormiram'],
    },
    {
      sentence: 'João {blank} tarde na noite de sexta-feira.',
      verb: 'dormir',
      tense: 'pretérito perfeito',
      answers: ['dormiu'],
    },
    {
      sentence: 'Maria e eu {blank} bem na última noite.',
      verb: 'dormir',
      tense: 'pretérito perfeito',
      answers: ['dormimos'],
    },
    {
      sentence: 'A gente {blank} no sofá durante o filme.',
      verb: 'dormir',
      tense: 'pretérito perfeito',
      answers: ['dormiu'],
    },
    {
      sentence: 'Vocês {blank} na sala de aula ontem.',
      verb: 'dormir',
      tense: 'pretérito perfeito',
      answers: ['dormiram'],
    },
    {
      sentence: 'Eles {blank} tarde demais para acordar a tempo.',
      verb: 'dormir',
      tense: 'pretérito perfeito',
      answers: ['dormiram'],
    },
    {
      sentence: 'Eu {blank} bem esta noite.',
      verb: 'dormir',
      tense: 'futuro',
      answers: ['dormirei', 'vou dormir'],
    },
    {
      sentence: 'Ela {blank} cedo amanhã.',
      verb: 'dormir',
      tense: 'futuro',
      answers: ['dormirá', 'vai dormir'],
    },
    {
      sentence: 'Nós {blank} a tarde inteira no sofá.',
      verb: 'dormir',
      tense: 'futuro',
      answers: ['dormiremos', 'vamos dormir'],
    },
    {
      sentence: 'Você {blank} em casa amanhã à noite.',
      verb: 'dormir',
      tense: 'futuro',
      answers: ['dormirá', 'vai dormir'],
    },
    {
      sentence: 'Eles {blank} depois do almoço.',
      verb: 'dormir',
      tense: 'futuro',
      answers: ['dormirão', 'vão dormir'],
    },
    {
      sentence: 'João {blank} bem depois do trabalho.',
      verb: 'dormir',
      tense: 'futuro',
      answers: ['dormirá', 'vai dormir'],
    },
    {
      sentence: 'Maria e eu {blank} no carro durante a viagem.',
      verb: 'dormir',
      tense: 'futuro',
      answers: ['dormiremos', 'vamos dormir'],
    },
    {
      sentence: 'Vocês {blank} pelas nuvens enquanto assistem ao filme.',
      verb: 'dormir',
      tense: 'futuro',
      answers: ['dormirão', 'vão dormir'],
    },
    {
      sentence: 'Carlos e Ana {blank} depois da festa.',
      verb: 'dormir',
      tense: 'futuro',
      answers: ['dormirão', 'vão dormir'],
    },
    {
      sentence: 'Eu e você {blank} em um hotel durante as férias.',
      verb: 'dormir',
      tense: 'futuro',
      answers: ['dormiremos', 'vamos dormir'],
    },
  ],
};
