import { ProblemList } from '../Problems';

export const encontrar: ProblemList = {
  verb: 'encontrar',
  problems: [
    {
      sentence: 'Eu {blank} a solução para o problema.',
      verb: 'encontrar',
      tense: 'pretérito perfeito',
      answers: ['encontrou'],
    },
    {
      sentence: 'Ela {blank} o livro que estava procurando.',
      verb: 'encontrar',
      tense: 'pretérito perfeito',
      answers: ['encontrou'],
    },
    {
      sentence: 'Nós {blank} um ótimo restaurante no centro.',
      verb: 'encontrar',
      tense: 'pretérito perfeito',
      answers: ['encontramos'],
    },
    {
      sentence: 'Você {blank} as chaves que perdeu?',
      verb: 'encontrar',
      tense: 'pretérito perfeito',
      answers: ['encontrou'],
    },
    {
      sentence: 'Eles {blank} a informação que precisavam.',
      verb: 'encontrar',
      tense: 'pretérito perfeito',
      answers: ['encontraram'],
    },
    {
      sentence: 'João {blank} a resposta correta na prova.',
      verb: 'encontrar',
      tense: 'pretérito perfeito',
      answers: ['encontrou'],
    },
    {
      sentence: 'Nós {blank} um lugar tranquilo para descansar.',
      verb: 'encontrar',
      tense: 'pretérito perfeito',
      answers: ['encontramos'],
    },
    {
      sentence: 'Você e eu {blank} muitos amigos em comum.',
      verb: 'encontrar',
      tense: 'pretérito perfeito',
      answers: ['encontramos'],
    },
    {
      sentence: 'Maria {blank} um presente perfeito para a festa.',
      verb: 'encontrar',
      tense: 'pretérito perfeito',
      answers: ['encontrou'],
    },
    {
      sentence: 'Eles {blank} a cidade que tanto queriam visitar.',
      verb: 'encontrar',
      tense: 'pretérito perfeito',
      answers: ['encontraram'],
    },
    {
      sentence: 'Eu {blank} meus amigos à festa.',
      verb: 'encontrar',
      tense: 'presente',
      answers: ['encontro'],
    },
    {
      sentence: 'Você {blank} a solução para o problema.',
      verb: 'encontrar',
      tense: 'presente',
      answers: ['encontra'],
    },
    {
      sentence: 'Ela {blank} sempre a resposta certa.',
      verb: 'encontrar',
      tense: 'presente',
      answers: ['encontra'],
    },
    {
      sentence: 'Nós {blank} os livros que precisamos para estudar.',
      verb: 'encontrar',
      tense: 'presente',
      answers: ['encontramos'],
    },
    {
      sentence: 'Eles {blank} novos caminhos na cidade.',
      verb: 'encontrar',
      tense: 'presente',
      answers: ['encontram'],
    },
    {
      sentence: 'Maria {blank} o endereço da escola.',
      verb: 'encontrar',
      tense: 'presente',
      answers: ['encontra'],
    },
    {
      sentence: 'João e eu {blank} um bom restaurante no centro.',
      verb: 'encontrar',
      tense: 'presente',
      answers: ['encontramos'],
    },
    {
      sentence: 'Vocês {blank} a chave que estava perdida?',
      verb: 'encontrar',
      tense: 'presente',
      answers: ['encontram'],
    },
    {
      sentence: 'Meu irmão {blank} os amigos dele na praia.',
      verb: 'encontrar',
      tense: 'presente',
      answers: ['encontra'],
    },
    {
      sentence: 'As meninas {blank} novas brincadeiras para o parque.',
      verb: 'encontrar',
      tense: 'presente',
      answers: ['encontram'],
    },
    {
      sentence: 'Eu {blank} o meu amigo na festa na próxima semana.',
      verb: 'encontrar',
      tense: 'futuro',
      answers: ['encontrarei', 'vou encontrar'],
    },
    {
      sentence: 'Vocês {blank} as chaves que estão perdidas.',
      verb: 'encontrar',
      tense: 'futuro',
      answers: ['encontrarão', 'vão encontrar'],
    },
    {
      sentence: 'Ela {blank} o livro que perdeu ontem.',
      verb: 'encontrar',
      tense: 'futuro',
      answers: ['encontrará', 'vai encontrar'],
    },
    {
      sentence: 'Nós {blank} a solução para o problema em breve.',
      verb: 'encontrar',
      tense: 'futuro',
      answers: ['encontraremos', 'vamos encontrar'],
    },
    {
      sentence: 'Você {blank} alguém interessante na viagem.',
      verb: 'encontrar',
      tense: 'futuro',
      answers: ['encontrará', 'vai encontrar'],
    },
    {
      sentence: 'Eles {blank} um bom restaurante para o jantar.',
      verb: 'encontrar',
      tense: 'futuro',
      answers: ['encontrarão', 'vão encontrar'],
    },
    {
      sentence: 'Eu {blank} um novo hobby que me faça feliz.',
      verb: 'encontrar',
      tense: 'futuro',
      answers: ['encontrarei', 'vou encontrar'],
    },
    {
      sentence: 'Ana e eu {blank} as respostas corretas para o teste.',
      verb: 'encontrar',
      tense: 'futuro',
      answers: ['encontraremos', 'vamos encontrar'],
    },
    {
      sentence: 'Eles {blank} os documentos que precisam amanhã.',
      verb: 'encontrar',
      tense: 'futuro',
      answers: ['encontrarão', 'vão encontrar'],
    },
    {
      sentence: 'Você {blank} seus fones de ouvido na casa da Maria.',
      verb: 'encontrar',
      tense: 'futuro',
      answers: ['encontrará', 'vai encontrar'],
    },
  ],
};
