import { ProblemList } from '../Problems';

export const entregar: ProblemList = {
  verb: 'entregar',
  problems: [
    {
      sentence: 'Eu {blank} o relatório ontem à noite.',
      verb: 'entregar',
      tense: 'pretérito perfeito',
      answers: ['entreguei'],
    },
    {
      sentence: 'Ela {blank} os presentes para a festa.',
      verb: 'entregar',
      tense: 'pretérito perfeito',
      answers: ['entregou'],
    },
    {
      sentence: 'Nós {blank} as chaves do carro na semana passada.',
      verb: 'entregar',
      tense: 'pretérito perfeito',
      answers: ['entregamos'],
    },
    {
      sentence: 'Você {blank} a carta que eu te pedi?',
      verb: 'entregar',
      tense: 'pretérito perfeito',
      answers: ['entregou'],
    },
    {
      sentence: 'Os professores {blank} as tarefas corrigidas aos alunos.',
      verb: 'entregar',
      tense: 'pretérito perfeito',
      answers: ['entregaram'],
    },
    {
      sentence: 'Maria {blank} os documentos antes do prazo.',
      verb: 'entregar',
      tense: 'pretérito perfeito',
      answers: ['entregou'],
    },
    {
      sentence: 'Eu e João {blank} os resultados da pesquisa juntos.',
      verb: 'entregar',
      tense: 'pretérito perfeito',
      answers: ['entregamos'],
    },
    {
      sentence: 'Eles {blank} os formulários preenchidos para a reunião.',
      verb: 'entregar',
      tense: 'pretérito perfeito',
      answers: ['entregaram'],
    },
    {
      sentence: 'Você e eu {blank} as provas na escola.',
      verb: 'entregar',
      tense: 'pretérito perfeito',
      answers: ['entregamos'],
    },
    {
      sentence: 'Ela {blank} o pacote na portaria.',
      verb: 'entregar',
      tense: 'pretérito perfeito',
      answers: ['entregou'],
    },
    {
      sentence: 'Eu {blank} os relatórios todos os dias.',
      verb: 'entregar',
      tense: 'presente',
      answers: ['entrego'],
    },
    {
      sentence: 'Ela {blank} as tarefas antes do prazo.',
      verb: 'entregar',
      tense: 'presente',
      answers: ['entrega'],
    },
    {
      sentence: 'Nós {blank} os presentes na festa de aniversário.',
      verb: 'entregar',
      tense: 'presente',
      answers: ['entregamos'],
    },
    {
      sentence: 'Você {blank} sempre seus projetos a tempo.',
      verb: 'entregar',
      tense: 'presente',
      answers: ['entrega'],
    },
    {
      sentence: 'Eles {blank} os livros na biblioteca.',
      verb: 'entregar',
      tense: 'presente',
      answers: ['entregam'],
    },
    {
      sentence: 'Ana {blank} as chaves para o escritório todas as manhãs.',
      verb: 'entregar',
      tense: 'presente',
      answers: ['entrega'],
    },
    {
      sentence: 'Lucas {blank} os resultados assim que os recebe.',
      verb: 'entregar',
      tense: 'presente',
      answers: ['entrega'],
    },
    {
      sentence: 'Você e eu {blank} as receitas para o jantar.',
      verb: 'entregar',
      tense: 'presente',
      answers: ['entregamos'],
    },
    {
      sentence: 'João {blank} sua apresentação na reunião semanal.',
      verb: 'entregar',
      tense: 'presente',
      answers: ['entrega'],
    },
    {
      sentence: 'Vocês {blank} as respostas do exame amanhã.',
      verb: 'entregar',
      tense: 'presente',
      answers: ['entregam'],
    },
    {
      sentence: 'Eu {blank} os relatórios amanhã.',
      verb: 'entregar',
      tense: 'futuro',
      answers: ['entregarei', 'vou entregar'],
    },
    {
      sentence: 'Ana {blank} os presentes no aniversário.',
      verb: 'entregar',
      tense: 'futuro',
      answers: ['entregará', 'vai entregar'],
    },
    {
      sentence: 'Nós {blank} as propostas na próxima reunião.',
      verb: 'entregar',
      tense: 'futuro',
      answers: ['entregaremos', 'vamos entregar'],
    },
    {
      sentence: 'Vocês {blank} o feedback sobre o projeto.',
      verb: 'entregar',
      tense: 'futuro',
      answers: ['entregarão', 'vão entregar'],
    },
    {
      sentence: 'Ele {blank} a documentação até sexta-feira.',
      verb: 'entregar',
      tense: 'futuro',
      answers: ['entregará', 'vai entregar'],
    },
    {
      sentence: 'Maria e eu {blank} as chaves do carro para você.',
      verb: 'entregar',
      tense: 'futuro',
      answers: ['entregaremos', 'vamos entregar'],
    },
    {
      sentence: 'Você {blank} os arquivos antes do prazo.',
      verb: 'entregar',
      tense: 'futuro',
      answers: ['entregará', 'vai entregar'],
    },
    {
      sentence: 'Eles {blank} os resultados aos professores amanhã.',
      verb: 'entregar',
      tense: 'futuro',
      answers: ['entregarão', 'vão entregar'],
    },
    {
      sentence: 'Nós {blank} o equipamento na próxima semana.',
      verb: 'entregar',
      tense: 'futuro',
      answers: ['entregaremos', 'vamos entregar'],
    },
    {
      sentence: 'João {blank} a cópia final do relatório hoje.',
      verb: 'entregar',
      tense: 'futuro',
      answers: ['entregará', 'vai entregar'],
    },
  ],
};
