import { ProblemList } from '../Problems';

export const entrar: ProblemList = {
  verb: 'entrar',
  problems: [
    {
      sentence: 'Eu {blank} na sala de aula todos os dias.',
      verb: 'entrar',
      tense: 'presente',
      answers: ['entro'],
    },
    {
      sentence: 'Ela {blank} pela porta principal.',
      verb: 'entrar',
      tense: 'presente',
      answers: ['entra'],
    },
    {
      sentence: 'Nós {blank} juntos na reunião de hoje.',
      verb: 'entrar',
      tense: 'presente',
      answers: ['entramos'],
    },
    {
      sentence: 'Você {blank} sempre na hora certa.',
      verb: 'entrar',
      tense: 'presente',
      answers: ['entra'],
    },
    {
      sentence: 'João {blank} na festa com toda a família.',
      verb: 'entrar',
      tense: 'presente',
      answers: ['entra'],
    },
    {
      sentence: 'Vocês {blank} na discussão sobre o projeto.',
      verb: 'entrar',
      tense: 'presente',
      answers: ['entram'],
    },
    {
      sentence: 'Eles {blank} no cinema assim que o filme começou.',
      verb: 'entrar',
      tense: 'presente',
      answers: ['entram'],
    },
    {
      sentence: 'Maria e eu {blank} pela janela quando começou a chuva.',
      verb: 'entrar',
      tense: 'presente',
      answers: ['entramos'],
    },
    {
      sentence: 'Você e sua irmã {blank} na loja para fazer compras.',
      verb: 'entrar',
      tense: 'presente',
      answers: ['entram'],
    },
    {
      sentence: 'A Cláudia {blank} na competição este ano.',
      verb: 'entrar',
      tense: 'presente',
      answers: ['entra'],
    },
    {
      sentence: 'Eu {blank} na festa amanhã à noite.',
      verb: 'entrar',
      tense: 'futuro',
      answers: ['entrarei', 'vou entrar'],
    },
    {
      sentence: 'Ela {blank} no cinema assim que a sessão começar.',
      verb: 'entrar',
      tense: 'futuro',
      answers: ['entrará', 'vai entrar'],
    },
    {
      sentence: 'Nós {blank} juntos na apresentação na próxima semana.',
      verb: 'entrar',
      tense: 'futuro',
      answers: ['entraremos', 'vamos entrar'],
    },
    {
      sentence: 'Vocês {blank} no evento se confirmarem a presença.',
      verb: 'entrar',
      tense: 'futuro',
      answers: ['entrarão', 'vão entrar'],
    },
    {
      sentence: 'Carlos {blank} na equipe se for aceito.',
      verb: 'entrar',
      tense: 'futuro',
      answers: ['entrará', 'vai entrar'],
    },
    {
      sentence: 'Luana e eu {blank} na biblioteca depois do almoço.',
      verb: 'entrar',
      tense: 'futuro',
      answers: ['entraremos', 'vamos entrar'],
    },
    {
      sentence: 'Se você quiser, {blank} na reunião comigo.',
      verb: 'entrar',
      tense: 'futuro',
      answers: ['entrará', 'vai entrar'],
    },
    {
      sentence: 'Eles {blank} na nova casa até o final do mês.',
      verb: 'entrar',
      tense: 'futuro',
      answers: ['entrarão', 'vão entrar'],
    },
    {
      sentence: 'Eu {blank} no projeto assim que tiver mais informações.',
      verb: 'entrar',
      tense: 'futuro',
      answers: ['entrarei', 'vou entrar'],
    },
    {
      sentence: 'Você {blank} na discussão se tiver interesse.',
      verb: 'entrar',
      tense: 'futuro',
      answers: ['entrará', 'vai entrar'],
    },
    {
      sentence: 'Eu {blank} na festa ontem à noite.',
      verb: 'entrar',
      tense: 'pretérito perfeito',
      answers: ['entrei'],
    },
    {
      sentence: 'Ela {blank} na sala de aula parcelado.',
      verb: 'entrar',
      tense: 'pretérito perfeito',
      answers: ['entrou'],
    },
    {
      sentence: 'Nós {blank} no evento comunitário na semana passada.',
      verb: 'entrar',
      tense: 'pretérito perfeito',
      answers: ['entramos'],
    },
    {
      sentence: 'Você {blank} no prédio antes do horário.',
      verb: 'entrar',
      tense: 'pretérito perfeito',
      answers: ['entrou'],
    },
    {
      sentence: 'Francisco {blank} na competição e impressionou a todos.',
      verb: 'entrar',
      tense: 'pretérito perfeito',
      answers: ['entrou'],
    },
    {
      sentence: 'Elas {blank} na biblioteca para estudar.',
      verb: 'entrar',
      tense: 'pretérito perfeito',
      answers: ['entraram'],
    },
    {
      sentence: 'Nós {blank} na loja e encontramos ótimas ofertas.',
      verb: 'entrar',
      tense: 'pretérito perfeito',
      answers: ['entramos'],
    },
    {
      sentence: 'Você e eu {blank} no parque para o piquenique.',
      verb: 'entrar',
      tense: 'pretérito perfeito',
      answers: ['entramos'],
    },
    {
      sentence: 'João e Maria {blank} na consulta médica a tempo.',
      verb: 'entrar',
      tense: 'pretérito perfeito',
      answers: ['entraram'],
    },
    {
      sentence: 'Eles {blank} rapidamente na sala de conferências.',
      verb: 'entrar',
      tense: 'pretérito perfeito',
      answers: ['entraram'],
    },
  ],
};
