import { ProblemList } from '../Problems';

export const estar: ProblemList = {
  verb: 'estar',
  problems: [
    {
      sentence: 'Eu {blank} na casa da minha avó no fim de semana passado.',
      verb: 'estar',
      tense: 'pretérito perfeito',
      answers: ['estive'],
    },
    {
      sentence: 'Você {blank} em casa quando o telefone tocou.',
      verb: 'estar',
      tense: 'pretérito perfeito',
      answers: ['esteve'],
    },
    {
      sentence: 'Ela {blank} muito feliz com a surpresa.',
      verb: 'estar',
      tense: 'pretérito perfeito',
      answers: ['esteve'],
    },
    {
      sentence: 'Nós {blank} no cinema ontem à noite.',
      verb: 'estar',
      tense: 'pretérito perfeito',
      answers: ['estivemos'],
    },
    {
      sentence: 'Eles {blank} na festa de aniversário do João.',
      verb: 'estar',
      tense: 'pretérito perfeito',
      answers: ['estiveram'],
    },
    {
      sentence: 'Você e eu {blank} durante a reunião na sexta-feira.',
      verb: 'estar',
      tense: 'pretérito perfeito',
      answers: ['estivemos'],
    },
    {
      sentence: 'A Maria {blank} preocupada com o exame.',
      verb: 'estar',
      tense: 'pretérito perfeito',
      answers: ['esteve'],
    },
    {
      sentence: 'O Pedro {blank} muito ocupado na semana passada.',
      verb: 'estar',
      tense: 'pretérito perfeito',
      answers: ['esteve'],
    },
    {
      sentence: 'Nós {blank} na biblioteca para estudar.',
      verb: 'estar',
      tense: 'pretérito perfeito',
      answers: ['estivemos'],
    },
    {
      sentence: 'As crianças {blank} brincando no parque.',
      verb: 'estar',
      tense: 'pretérito perfeito',
      answers: ['estiveram'],
    },
    {
      sentence: 'Eu {blank} feliz com a notícia que recebi.',
      verb: 'estar',
      tense: 'presente',
      answers: ['estou'],
    },
    {
      sentence: 'Ela {blank} trabalhando no novo projeto hoje.',
      verb: 'estar',
      tense: 'presente',
      answers: ['está'],
    },
    {
      sentence: 'Nós {blank} prontos para a apresentação.',
      verb: 'estar',
      tense: 'presente',
      answers: ['estamos'],
    },
    {
      sentence: 'Você {blank} sempre tão gentil com os outros.',
      verb: 'estar',
      tense: 'presente',
      answers: ['está'],
    },
    {
      sentence: 'Eles {blank} no parque agora.',
      verb: 'estar',
      tense: 'presente',
      answers: ['estão'],
    },
    {
      sentence: 'João {blank} ansioso para o resultado do exame.',
      verb: 'estar',
      tense: 'presente',
      answers: ['está'],
    },
    {
      sentence: 'Nós {blank} em um momento importante da nossa vida.',
      verb: 'estar',
      tense: 'presente',
      answers: ['estamos'],
    },
    {
      sentence: 'Vocês {blank} cientes da nova política da empresa?',
      verb: 'estar',
      tense: 'presente',
      answers: ['estão'],
    },
    {
      sentence: 'Mariana e Felipe {blank} na aula de dança.',
      verb: 'estar',
      tense: 'presente',
      answers: ['estão'],
    },
    {
      sentence: 'Eu e você {blank} na mesma equipe para o projeto.',
      verb: 'estar',
      tense: 'presente',
      answers: ['estamos'],
    },
    {
      sentence: 'Eu {blank} muito feliz com a nova promoção.',
      verb: 'estar',
      tense: 'futuro',
      answers: ['estarei', 'vou estar'],
    },
    {
      sentence: 'Ela {blank} em casa na próxima semana.',
      verb: 'estar',
      tense: 'futuro',
      answers: ['estará', 'vai estar'],
    },
    {
      sentence: 'Nós {blank} prontos para a viagem amanhã.',
      verb: 'estar',
      tense: 'futuro',
      answers: ['estaremos', 'vamos estar'],
    },
    {
      sentence: 'Vocês {blank} no evento às 18 horas.',
      verb: 'estar',
      tense: 'futuro',
      answers: ['estarão', 'vão estar'],
    },
    {
      sentence: 'Ela e eu {blank} no futebol no fim de semana.',
      verb: 'estar',
      tense: 'futuro',
      answers: ['estaremos', 'vamos estar'],
    },
    {
      sentence: 'Você {blank} na reunião de negócios na sexta-feira.',
      verb: 'estar',
      tense: 'futuro',
      answers: ['estará', 'vai estar'],
    },
    {
      sentence: 'João {blank} preocupado com a prova quarta-feira.',
      verb: 'estar',
      tense: 'futuro',
      answers: ['estará', 'vai estar'],
    },
    {
      sentence: 'Elas {blank} muito ocupadas com o novo projeto.',
      verb: 'estar',
      tense: 'futuro',
      answers: ['estarão', 'vão estar'],
    },
    {
      sentence: 'Eu e você {blank} na mesma sala para a apresentação.',
      verb: 'estar',
      tense: 'futuro',
      answers: ['estaremos', 'vamos estar'],
    },
    {
      sentence: 'Carlos e Ana {blank} animados para o show na próxima semana.',
      verb: 'estar',
      tense: 'futuro',
      answers: ['estarão', 'vão estar'],
    },
  ],
};
