import { ProblemList } from '../Problems';

export const estudar: ProblemList = {
  verb: 'estudar',
  problems: [
    {
      sentence: 'Eu {blank} para o exame na semana passada.',
      verb: 'estudar',
      tense: 'pretérito perfeito',
      answers: ['estudei'],
    },
    {
      sentence: 'Ela {blank} muito nas férias.',
      verb: 'estudar',
      tense: 'pretérito perfeito',
      answers: ['estudou'],
    },
    {
      sentence: 'Nós {blank} juntos para a prova final.',
      verb: 'estudar',
      tense: 'pretérito perfeito',
      answers: ['estudamos'],
    },
    {
      sentence: 'Você {blank} para a apresentação ontem.',
      verb: 'estudar',
      tense: 'pretérito perfeito',
      answers: ['estudou'],
    },
    {
      sentence: 'João {blank} a matéria toda para o teste.',
      verb: 'estudar',
      tense: 'pretérito perfeito',
      answers: ['estudou'],
    },
    {
      sentence: 'Elas {blank} para a aula de literatura.',
      verb: 'estudar',
      tense: 'pretérito perfeito',
      answers: ['estudaram'],
    },
    {
      sentence: 'Eu e você {blank} muito para o concurso.',
      verb: 'estudar',
      tense: 'pretérito perfeito',
      answers: ['estudamos'],
    },
    {
      sentence: 'Vocês {blank} a história da arte.',
      verb: 'estudar',
      tense: 'pretérito perfeito',
      answers: ['estudaram'],
    },
    {
      sentence: 'Eles {blank} gramática na última semana.',
      verb: 'estudar',
      tense: 'pretérito perfeito',
      answers: ['estudaram'],
    },
    {
      sentence: 'A professora {blank} novos métodos de ensino.',
      verb: 'estudar',
      tense: 'pretérito perfeito',
      answers: ['estudou'],
    },
    {
      sentence: 'Eu {blank} todos os dias para melhorar minhas notas.',
      verb: 'estudar',
      tense: 'presente',
      answers: ['estudo'],
    },
    {
      sentence: 'Ela {blank} na biblioteca toda semana.',
      verb: 'estudar',
      tense: 'presente',
      answers: ['estuda'],
    },
    {
      sentence: 'Nós {blank} para a prova de matemática juntos.',
      verb: 'estudar',
      tense: 'presente',
      answers: ['estudamos'],
    },
    {
      sentence: 'Você {blank} sobre história na aula de hoje.',
      verb: 'estudar',
      tense: 'presente',
      answers: ['estuda'],
    },
    {
      sentence: 'Eles {blank} as matérias do semestre com atenção.',
      verb: 'estudar',
      tense: 'presente',
      answers: ['estudam'],
    },
    {
      sentence: 'João {blank} para o exame de admissão ao colégio.',
      verb: 'estudar',
      tense: 'presente',
      answers: ['estuda'],
    },
    {
      sentence: 'Maria e eu {blank} juntos para a avaliação.',
      verb: 'estudar',
      tense: 'presente',
      answers: ['estudamos'],
    },
    {
      sentence: 'Vocês {blank} todas as lições de casa a tempo?',
      verb: 'estudar',
      tense: 'presente',
      answers: ['estudam'],
    },
    {
      sentence: 'Ele {blank} ciência da computação na faculdade.',
      verb: 'estudar',
      tense: 'presente',
      answers: ['estuda'],
    },
    {
      sentence: 'Ana e os amigos {blank} para o concurso no próximo mês.',
      verb: 'estudar',
      tense: 'presente',
      answers: ['estudam'],
    },
    {
      sentence: 'Eu {blank} para o exame na próxima semana.',
      verb: 'estudar',
      tense: 'futuro',
      answers: ['estudarei', 'vou estudar'],
    },
    {
      sentence: 'Ela {blank} as matérias antes da prova.',
      verb: 'estudar',
      tense: 'futuro',
      answers: ['estudará', 'vai estudar'],
    },
    {
      sentence: 'Nós {blank} para a apresentação nesta sexta-feira.',
      verb: 'estudar',
      tense: 'futuro',
      answers: ['estudaremos', 'vamos estudar'],
    },
    {
      sentence: 'Você {blank} com seu irmão para o projeto amanhã.',
      verb: 'estudar',
      tense: 'futuro',
      answers: ['estudará', 'vai estudar'],
    },
    {
      sentence: 'Eles {blank} juntos para o concurso no mês que vem.',
      verb: 'estudar',
      tense: 'futuro',
      answers: ['estudarão', 'vão estudar'],
    },
    {
      sentence: 'Carlos e Ana {blank} para a recuperação na próxima semana.',
      verb: 'estudar',
      tense: 'futuro',
      answers: ['estudarão', 'vão estudar'],
    },
    {
      sentence: 'Eu e você {blank} a matéria juntos no fim de semana.',
      verb: 'estudar',
      tense: 'futuro',
      answers: ['estudaremos', 'vamos estudar'],
    },
    {
      sentence: 'Maria {blank} bastante para o vestibular no próximo mês.',
      verb: 'estudar',
      tense: 'futuro',
      answers: ['estudará', 'vai estudar'],
    },
    {
      sentence: 'Os alunos {blank} no laboratório na próxima terça-feira.',
      verb: 'estudar',
      tense: 'futuro',
      answers: ['estudarão', 'vão estudar'],
    },
    {
      sentence: 'Você e eu {blank} as regras da gramática até lá.',
      verb: 'estudar',
      tense: 'futuro',
      answers: ['estudaremos', 'vamos estudar'],
    },
  ],
};
