import { ProblemList } from '../Problems';

export const fazer: ProblemList = {
  verb: 'fazer',
  problems: [
    {
      sentence: 'Eu {blank} o relatório ontem à noite.',
      verb: 'fazer',
      tense: 'pretérito perfeito',
      answers: ['fiz'],
    },
    {
      sentence: 'Ela {blank} um bolo de chocolate para o aniversário.',
      verb: 'fazer',
      tense: 'pretérito perfeito',
      answers: ['fez'],
    },
    {
      sentence: 'Nós {blank} a tarefa juntos no sábado.',
      verb: 'fazer',
      tense: 'pretérito perfeito',
      answers: ['fizemos'],
    },
    {
      sentence: 'Você {blank} a mudança de planos de última hora.',
      verb: 'fazer',
      tense: 'pretérito perfeito',
      answers: ['fez'],
    },
    {
      sentence: 'Eles {blank} uma apresentação excelente na reunião.',
      verb: 'fazer',
      tense: 'pretérito perfeito',
      answers: ['fizeram'],
    },
    {
      sentence: 'Maria {blank} um excelente trabalho no projeto.',
      verb: 'fazer',
      tense: 'pretérito perfeito',
      answers: ['fez'],
    },
    {
      sentence: 'Pedro e eu {blank} a reserva do hotel para as férias.',
      verb: 'fazer',
      tense: 'pretérito perfeito',
      answers: ['fizemos'],
    },
    {
      sentence: 'Vocês {blank} a inscrição para o curso ontem.',
      verb: 'fazer',
      tense: 'pretérito perfeito',
      answers: ['fizeram'],
    },
    {
      sentence: 'Eu e você {blank} um plano de ação para o projeto.',
      verb: 'fazer',
      tense: 'pretérito perfeito',
      answers: ['fizemos'],
    },
    {
      sentence: 'Ana {blank} uma viagem incrível no último mês.',
      verb: 'fazer',
      tense: 'pretérito perfeito',
      answers: ['fez'],
    },
    {
      sentence: 'Eu {blank} o trabalho de casa todos os dias.',
      verb: 'fazer',
      tense: 'presente',
      answers: ['faço'],
    },
    {
      sentence: 'Você {blank} um excelente ponto sobre o projeto.',
      verb: 'fazer',
      tense: 'presente',
      answers: ['faz'],
    },
    {
      sentence: 'Ela {blank} as compras no supermercado.',
      verb: 'fazer',
      tense: 'presente',
      answers: ['faz'],
    },
    {
      sentence: 'Nós {blank} o planejamento para as férias.',
      verb: 'fazer',
      tense: 'presente',
      answers: ['fazemos'],
    },
    {
      sentence: 'Eles {blank} exercícios todos os dias.',
      verb: 'fazer',
      tense: 'presente',
      answers: ['fazem'],
    },
    {
      sentence: 'Tu {blank} muito bem na apresentação.',
      verb: 'fazer',
      tense: 'presente',
      answers: ['fazes'],
    },
    {
      sentence: 'O Paulo {blank} um ótimo trabalho na reunião.',
      verb: 'fazer',
      tense: 'presente',
      answers: ['faz'],
    },
    {
      sentence: 'As garotas {blank} as atividades da escola juntas.',
      verb: 'fazer',
      tense: 'presente',
      answers: ['fazem'],
    },
    {
      sentence: 'Nós {blank} as malas antes da viagem.',
      verb: 'fazer',
      tense: 'presente',
      answers: ['fazemos'],
    },
    {
      sentence: 'Você e eu {blank} um bom time.',
      verb: 'fazer',
      tense: 'presente',
      answers: ['fazemos'],
    },
    {
      sentence: 'Eu {blank} o relatório até amanhã.',
      verb: 'fazer',
      tense: 'futuro',
      answers: ['farei', 'vou fazer'],
    },
    {
      sentence: 'Ela {blank} uma apresentação incrível na próxima semana.',
      verb: 'fazer',
      tense: 'futuro',
      answers: ['fará', 'vai fazer'],
    },
    {
      sentence: 'Nós {blank} um passeio no parque no domingo.',
      verb: 'fazer',
      tense: 'futuro',
      answers: ['faremos', 'vamos fazer'],
    },
    {
      sentence: 'Você {blank} a tarefa de casa mais tarde.',
      verb: 'fazer',
      tense: 'futuro',
      answers: ['fará', 'vai fazer'],
    },
    {
      sentence: 'Eles {blank} o que for necessário para ajudar.',
      verb: 'fazer',
      tense: 'futuro',
      answers: ['farão', 'vão fazer'],
    },
    {
      sentence: 'João {blank} os planos para a festa no próximo mês.',
      verb: 'fazer',
      tense: 'futuro',
      answers: ['fará', 'vai fazer'],
    },
    {
      sentence: 'Maria e eu {blank} uma nova receita de bolo.',
      verb: 'fazer',
      tense: 'futuro',
      answers: ['faremos', 'vamos fazer'],
    },
    {
      sentence: 'Vocês {blank} a reunião na próxima sexta-feira.',
      verb: 'fazer',
      tense: 'futuro',
      answers: ['farão', 'vão fazer'],
    },
    {
      sentence: 'A professora {blank} uma revisão para o exame.',
      verb: 'fazer',
      tense: 'futuro',
      answers: ['fará', 'vai fazer'],
    },
    {
      sentence: 'Eu e você {blank} uma parceria para o projeto.',
      verb: 'fazer',
      tense: 'futuro',
      answers: ['faremos', 'vamos fazer'],
    },
  ],
};
