import { ProblemList } from '../Problems';

export const ficar: ProblemList = {
  verb: 'ficar',
  problems: [
    {
      sentence: 'Eu {blank} muito feliz com a notícia.',
      verb: 'ficar',
      tense: 'presente',
      answers: ['fico'],
    },
    {
      sentence: 'Ela {blank} ansiosa para a festa.',
      verb: 'ficar',
      tense: 'presente',
      answers: ['fica'],
    },
    {
      sentence: 'Nós {blank} na casa dos meus pais este fim de semana.',
      verb: 'ficar',
      tense: 'presente',
      answers: ['ficamos'],
    },
    {
      sentence: 'Você {blank} sempre ocupado com o trabalho.',
      verb: 'ficar',
      tense: 'presente',
      answers: ['fica'],
    },
    {
      sentence: 'Eles {blank} juntos há um bom tempo.',
      verb: 'ficar',
      tense: 'presente',
      answers: ['ficam'],
    },
    {
      sentence: 'Maria {blank} com dúvida sobre a prova.',
      verb: 'ficar',
      tense: 'presente',
      answers: ['fica'],
    },
    {
      sentence: 'João e eu {blank} no mesmo grupo de trabalho.',
      verb: 'ficar',
      tense: 'presente',
      answers: ['ficamos'],
    },
    {
      sentence: 'Ana e você {blank} bem informados sobre o projeto.',
      verb: 'ficar',
      tense: 'presente',
      answers: ['ficam'],
    },
    {
      sentence: 'Meus amigos {blank} animados para a viagem.',
      verb: 'ficar',
      tense: 'presente',
      answers: ['ficam'],
    },
    {
      sentence: 'Você {blank} com a gente no próximo encontro?',
      verb: 'ficar',
      tense: 'presente',
      answers: ['fica'],
    },
    {
      sentence: 'Eu {blank} em casa durante o final de semana passado.',
      verb: 'ficar',
      tense: 'pretérito perfeito',
      answers: ['fiquei'],
    },
    {
      sentence: 'Ela {blank} aborrecida com a situação.',
      verb: 'ficar',
      tense: 'pretérito perfeito',
      answers: ['ficou'],
    },
    {
      sentence: 'Nós {blank} satisfeitos com os resultados do trabalho.',
      verb: 'ficar',
      tense: 'pretérito perfeito',
      answers: ['ficamos'],
    },
    {
      sentence: 'Você {blank} contente ao receber os amigos.',
      verb: 'ficar',
      tense: 'pretérito perfeito',
      answers: ['ficou'],
    },
    {
      sentence: 'João {blank} em dúvida sobre a decisão.',
      verb: 'ficar',
      tense: 'pretérito perfeito',
      answers: ['ficou'],
    },
    {
      sentence: 'Eles {blank} juntos durante a festa.',
      verb: 'ficar',
      tense: 'pretérito perfeito',
      answers: ['ficaram'],
    },
    {
      sentence: 'Nós {blank} admirados com a apresentação.',
      verb: 'ficar',
      tense: 'pretérito perfeito',
      answers: ['ficamos'],
    },
    {
      sentence: 'Você e eu {blank} felizes com a notícia.',
      verb: 'ficar',
      tense: 'pretérito perfeito',
      answers: ['ficamos'],
    },
    {
      sentence: 'Maria {blank} muito emocionada com o resultado.',
      verb: 'ficar',
      tense: 'pretérito perfeito',
      answers: ['ficou'],
    },
    {
      sentence: 'As crianças {blank} muito empolgadas com o brinquedo novo.',
      verb: 'ficar',
      tense: 'pretérito perfeito',
      answers: ['ficaram'],
    },
    {
      sentence: 'Eu {blank} no hotel para a próxima conferência.',
      verb: 'ficar',
      tense: 'futuro',
      answers: ['ficarei', 'vou ficar'],
    },
    {
      sentence: 'Ela {blank} em casa durante as férias.',
      verb: 'ficar',
      tense: 'futuro',
      answers: ['ficará', 'vai ficar'],
    },
    {
      sentence: 'Nós {blank} felizes com a nova situação.',
      verb: 'ficar',
      tense: 'futuro',
      answers: ['ficaremos', 'vamos ficar'],
    },
    {
      sentence: 'Vocês {blank} ansiosos para o evento.',
      verb: 'ficar',
      tense: 'futuro',
      answers: ['ficarão', 'vão ficar'],
    },
    {
      sentence: 'Ele {blank} no trabalho até mais tarde.',
      verb: 'ficar',
      tense: 'futuro',
      answers: ['ficará', 'vai ficar'],
    },
    {
      sentence: 'A Maria e o João {blank} juntos no próximo semestre.',
      verb: 'ficar',
      tense: 'futuro',
      answers: ['ficarão', 'vão ficar'],
    },
    {
      sentence: 'Eu e a Ana {blank} muito ocupados no futuro.',
      verb: 'ficar',
      tense: 'futuro',
      answers: ['ficaremos', 'vamos ficar'],
    },
    {
      sentence: 'Vocês {blank} em contato após a apresentação.',
      verb: 'ficar',
      tense: 'futuro',
      answers: ['ficarão', 'vão ficar'],
    },
    {
      sentence: 'Nós {blank} surpresos com a notícia.',
      verb: 'ficar',
      tense: 'futuro',
      answers: ['ficaremos', 'vamos ficar'],
    },
    {
      sentence: 'Ele {blank} com muitas perguntas após a reunião.',
      verb: 'ficar',
      tense: 'futuro',
      answers: ['ficará', 'vai ficar'],
    },
  ],
};
