import { ProblemList } from '../Problems';

export const finalizar: ProblemList = {
  verb: 'finalizar',
  problems: [
    {
      sentence: 'Eu {blank} o projeto hoje.',
      verb: 'finalizar',
      tense: 'presente',
      answers: ['finalizo'],
    },
    {
      sentence: 'Você {blank} suas tarefas diárias.',
      verb: 'finalizar',
      tense: 'presente',
      answers: ['finaliza'],
    },
    {
      sentence: 'Ela {blank} a lição de casa antes do jantar.',
      verb: 'finalizar',
      tense: 'presente',
      answers: ['finaliza'],
    },
    {
      sentence: 'Nós {blank} o trabalho em grupo na escola.',
      verb: 'finalizar',
      tense: 'presente',
      answers: ['finalizamos'],
    },
    {
      sentence: 'Eles {blank} a reunião às cinco horas.',
      verb: 'finalizar',
      tense: 'presente',
      answers: ['finalizam'],
    },
    {
      sentence: 'Você e eu {blank} as compras antes do fim de semana.',
      verb: 'finalizar',
      tense: 'presente',
      answers: ['finalizamos'],
    },
    {
      sentence: 'Carlos {blank} a apresentação para a conferência.',
      verb: 'finalizar',
      tense: 'presente',
      answers: ['finaliza'],
    },
    {
      sentence: 'Maria e Ana {blank} o relatório juntas.',
      verb: 'finalizar',
      tense: 'presente',
      answers: ['finalizam'],
    },
    {
      sentence: 'Meu pai {blank} a reforma da casa agora.',
      verb: 'finalizar',
      tense: 'presente',
      answers: ['finaliza'],
    },
    {
      sentence: 'As crianças {blank} os trabalhos de arte na escola.',
      verb: 'finalizar',
      tense: 'presente',
      answers: ['finalizam'],
    },
    {
      sentence: 'Eu {blank} o relatório antes do prazo.',
      verb: 'finalizar',
      tense: 'pretérito perfeito',
      answers: ['finalizei'],
    },
    {
      sentence: 'Ela {blank} todas as tarefas propostas.',
      verb: 'finalizar',
      tense: 'pretérito perfeito',
      answers: ['finalizou'],
    },
    {
      sentence: 'Nós {blank} o projeto de forma eficiente.',
      verb: 'finalizar',
      tense: 'pretérito perfeito',
      answers: ['finalizamos'],
    },
    {
      sentence: 'Você {blank} a apresentação ontem.',
      verb: 'finalizar',
      tense: 'pretérito perfeito',
      answers: ['finalizou'],
    },
    {
      sentence: 'Eles {blank} o curso com sucesso.',
      verb: 'finalizar',
      tense: 'pretérito perfeito',
      answers: ['finalizaram'],
    },
    {
      sentence: 'Maria {blank} a prova antes de ir embora.',
      verb: 'finalizar',
      tense: 'pretérito perfeito',
      answers: ['finalizou'],
    },
    {
      sentence: 'João {blank} as compras antes do jantar.',
      verb: 'finalizar',
      tense: 'pretérito perfeito',
      answers: ['finalizou'],
    },
    {
      sentence: 'Nós {blank} as discussões na reunião anterior.',
      verb: 'finalizar',
      tense: 'pretérito perfeito',
      answers: ['finalizamos'],
    },
    {
      sentence: 'Você e eu {blank} um ótimo trabalho juntos.',
      verb: 'finalizar',
      tense: 'pretérito perfeito',
      answers: ['finalizamos'],
    },
    {
      sentence: 'Os alunos {blank} as atividades a tempo.',
      verb: 'finalizar',
      tense: 'pretérito perfeito',
      answers: ['finalizaram'],
    },
    {
      sentence: 'Eu {blank} o projeto até o final do mês.',
      verb: 'finalizar',
      tense: 'futuro',
      answers: ['finalizarei', 'vou finalizar'],
    },
    {
      sentence: 'Você {blank} a apresentação na próxima semana.',
      verb: 'finalizar',
      tense: 'futuro',
      answers: ['finalizará', 'vai finalizar'],
    },
    {
      sentence: 'Nós {blank} a reunião em breve.',
      verb: 'finalizar',
      tense: 'futuro',
      answers: ['finalizaremos', 'vamos finalizar'],
    },
    {
      sentence: 'Eles {blank} o relatório até amanhã.',
      verb: 'finalizar',
      tense: 'futuro',
      answers: ['finalizarão', 'vão finalizar'],
    },
    {
      sentence: 'A Ana {blank} o trabalho antes do prazo.',
      verb: 'finalizar',
      tense: 'futuro',
      answers: ['finalizará', 'vai finalizar'],
    },
    {
      sentence: 'Você e eu {blank} a tarefa juntos.',
      verb: 'finalizar',
      tense: 'futuro',
      answers: ['finalizaremos', 'vamos finalizar'],
    },
    {
      sentence: 'O João {blank} a documentação necessária amanhã.',
      verb: 'finalizar',
      tense: 'futuro',
      answers: ['finalizará', 'vai finalizar'],
    },
    {
      sentence: 'As meninas {blank} o evento com sucesso.',
      verb: 'finalizar',
      tense: 'futuro',
      answers: ['finalizarão', 'vão finalizar'],
    },
    {
      sentence: 'Nós {blank} as inscrições no próximo mês.',
      verb: 'finalizar',
      tense: 'futuro',
      answers: ['finalizaremos', 'vamos finalizar'],
    },
    {
      sentence: 'Você {blank} os ajustes finais até o fim do dia.',
      verb: 'finalizar',
      tense: 'futuro',
      answers: ['finalizará', 'vai finalizar'],
    },
  ],
};
