import { ProblemList } from '../Problems';

export const gostar: ProblemList = {
  verb: 'gostar',
  problems: [
    {
      sentence: 'Eu {blank} a nova música do artista.',
      verb: 'gostar',
      tense: 'futuro',
      answers: ['gostarei', 'vou gostar'],
    },
    {
      sentence: 'Nós {blank} da festa de aniversário dela.',
      verb: 'gostar',
      tense: 'futuro',
      answers: ['gostaremos', 'vamos gostar'],
    },
    {
      sentence: 'Vocês {blank} do filme que está no cinema.',
      verb: 'gostar',
      tense: 'futuro',
      answers: ['gostarão', 'vão gostar'],
    },
    {
      sentence: 'Elas {blank} do novo restaurante na cidade.',
      verb: 'gostar',
      tense: 'futuro',
      answers: ['gostarão', 'vão gostar'],
    },
    {
      sentence: 'Ele {blank} do jogo que lançaram ontem.',
      verb: 'gostar',
      tense: 'futuro',
      answers: ['gostará', 'vai gostar'],
    },
    {
      sentence: 'Ana e eu {blank} das novidades do mês passado.',
      verb: 'gostar',
      tense: 'futuro',
      answers: ['gostaremos', 'vamos gostar'],
    },
    {
      sentence: 'Você {blank} da coleção de livros dela.',
      verb: 'gostar',
      tense: 'futuro',
      answers: ['gostará', 'vai gostar'],
    },
    {
      sentence: 'Maria e Luís {blank} do passeio que fizemos.',
      verb: 'gostar',
      tense: 'futuro',
      answers: ['gostarão', 'vão gostar'],
    },
    {
      sentence: 'Nós {blank} da nova exposição no museu.',
      verb: 'gostar',
      tense: 'futuro',
      answers: ['gostaremos', 'vamos gostar'],
    },
    {
      sentence: 'Você e eu {blank} das músicas que tocaram no show.',
      verb: 'gostar',
      tense: 'futuro',
      answers: ['gostaremos', 'vamos gostar'],
    },
    {
      sentence: 'Eu {blank} muito de arte moderna.',
      verb: 'gostar',
      tense: 'presente',
      answers: ['gosto'],
    },
    {
      sentence: 'Ela {blank} de assistir filmes de comédia.',
      verb: 'gostar',
      tense: 'presente',
      answers: ['gosta'],
    },
    {
      sentence: 'Nós {blank} de viajar nas férias.',
      verb: 'gostar',
      tense: 'presente',
      answers: ['gostamos'],
    },
    {
      sentence: 'Você {blank} de ler livros de ficção científica.',
      verb: 'gostar',
      tense: 'presente',
      answers: ['gosta'],
    },
    {
      sentence: 'Eles {blank} de jogar futebol aos sábados.',
      verb: 'gostar',
      tense: 'presente',
      answers: ['gostam'],
    },
    {
      sentence: 'Maria e eu {blank} de cozinhar juntas.',
      verb: 'gostar',
      tense: 'presente',
      answers: ['gostamos'],
    },
    {
      sentence: 'Carlos {blank} muito de estudar matemática.',
      verb: 'gostar',
      tense: 'presente',
      answers: ['gosta'],
    },
    {
      sentence: 'Vocês {blank} de ir ao parque no domingo.',
      verb: 'gostar',
      tense: 'presente',
      answers: ['gostam'],
    },
    {
      sentence: 'Ele {blank} de tocar guitarra à noite.',
      verb: 'gostar',
      tense: 'presente',
      answers: ['gosta'],
    },
    {
      sentence: 'Nós {blank} de passar tempo em família.',
      verb: 'gostar',
      tense: 'presente',
      answers: ['gostamos'],
    },
    {
      sentence: 'Eu {blank} do novo filme que assistimos ontem.',
      verb: 'gostar',
      tense: 'pretérito perfeito',
      answers: ['gostei'],
    },
    {
      sentence: 'Você {blank} da apresentação da equipe.',
      verb: 'gostar',
      tense: 'pretérito perfeito',
      answers: ['gostou'],
    },
    {
      sentence: 'Ela {blank} da festa de aniversário do Carlos.',
      verb: 'gostar',
      tense: 'pretérito perfeito',
      answers: ['gostou'],
    },
    {
      sentence: 'Nós {blank} muito da viagem para o Rio de Janeiro.',
      verb: 'gostar',
      tense: 'pretérito perfeito',
      answers: ['gostamos'],
    },
    {
      sentence: 'Eles {blank} daquele restaurante novo.',
      verb: 'gostar',
      tense: 'pretérito perfeito',
      answers: ['gostaram'],
    },
    {
      sentence: 'Você e eu {blank} da música que tocou.',
      verb: 'gostar',
      tense: 'pretérito perfeito',
      answers: ['gostamos'],
    },
    {
      sentence: 'A Ana {blank} da nova coleção de roupas.',
      verb: 'gostar',
      tense: 'pretérito perfeito',
      answers: ['gostou'],
    },
    {
      sentence: 'O João {blank} do livro que leu na semana passada.',
      verb: 'gostar',
      tense: 'pretérito perfeito',
      answers: ['gostou'],
    },
    {
      sentence: 'Nós dois {blank} da ideia que você trouxe.',
      verb: 'gostar',
      tense: 'pretérito perfeito',
      answers: ['gostamos'],
    },
    {
      sentence: 'Vocês {blank} muito das atividades do final de semana.',
      verb: 'gostar',
      tense: 'pretérito perfeito',
      answers: ['gostaram'],
    },
  ],
};
