import { ProblemList } from '../Problems';

export const haver: ProblemList = {
  verb: 'haver',
  problems: [
    {
      sentence: 'Haverá uma festa na casa de Ana no sábado.',
      verb: 'haver',
      tense: 'futuro',
      answers: ['haverá', 'vai haver'],
    },
    {
      sentence: 'Nós {blank} muitas oportunidades no próximo mês.',
      verb: 'haver',
      tense: 'futuro',
      answers: ['haverá', 'vai haver'],
    },
    {
      sentence: 'Você {blank} uma explicação sobre o projeto amanhã.',
      verb: 'haver',
      tense: 'futuro',
      answers: ['haverá', 'vai haver'],
    },
    {
      sentence: 'Eles {blank} uma solução para o problema até a reunião.',
      verb: 'haver',
      tense: 'futuro',
      answers: ['haverá', 'vai haver'],
    },
    {
      sentence: 'Eu {blank} um novo sistema de trabalho no próximo ano.',
      verb: 'haver',
      tense: 'futuro',
      answers: ['haverá', 'vai haver'],
    },
    {
      sentence: 'Você e eu {blank} muitos desafios pela frente.',
      verb: 'haver',
      tense: 'futuro',
      answers: ['haverá', 'vai haver'],
    },
    {
      sentence: 'Sara {blank} um novo projeto em andamento em breve.',
      verb: 'haver',
      tense: 'futuro',
      answers: ['haverá', 'vai haver'],
    },
    {
      sentence: 'No próximo semestre, {blank} uma grande mudança na escola.',
      verb: 'haver',
      tense: 'futuro',
      answers: ['haverá', 'vai haver'],
    },
    {
      sentence: 'As crianças {blank} muitas atividades divertidas no verão.',
      verb: 'haver',
      tense: 'futuro',
      answers: ['haverá', 'vai haver'],
    },
    {
      sentence: 'Nós {blank} alguma novidade sobre a viagem em breve.',
      verb: 'haver',
      tense: 'futuro',
      answers: ['haverá', 'vai haver'],
    },
    {
      sentence: 'Eu {blank} certeza de que vamos vencer.',
      verb: 'haver',
      tense: 'presente',
      answers: ['há'],
    },
    {
      sentence: 'Você {blank} muitos livros interessantes na estante.',
      verb: 'haver',
      tense: 'presente',
      answers: ['há'],
    },
    {
      sentence: 'Ela {blank} uma explicação para a situação.',
      verb: 'haver',
      tense: 'presente',
      answers: ['há'],
    },
    {
      sentence: 'Nós {blank} cinco opções para escolher.',
      verb: 'haver',
      tense: 'presente',
      answers: ['há'],
    },
    {
      sentence: 'Eles {blank} bastante tempo para estudar.',
      verb: 'haver',
      tense: 'presente',
      answers: ['há'],
    },
    {
      sentence: 'João {blank} uma grande ideia para o projeto.',
      verb: 'haver',
      tense: 'presente',
      answers: ['há'],
    },
    {
      sentence: 'Vocês {blank} muitos desafios pela frente.',
      verb: 'haver',
      tense: 'presente',
      answers: ['há'],
    },
    {
      sentence: 'Maria {blank} um plano para o fim de semana.',
      verb: 'haver',
      tense: 'presente',
      answers: ['há'],
    },
    {
      sentence: 'Nós {blank} um evento importante amanhã.',
      verb: 'haver',
      tense: 'presente',
      answers: ['há'],
    },
    {
      sentence: 'Carlos {blank} uma nova oportunidade de trabalho.',
      verb: 'haver',
      tense: 'presente',
      answers: ['há'],
    },
    {
      sentence: 'Eu {blank} um ótimo dia ontem.',
      verb: 'haver',
      tense: 'pretérito perfeito',
      answers: ['houve'],
    },
    {
      sentence: 'Ela {blank} várias oportunidades na conferência.',
      verb: 'haver',
      tense: 'pretérito perfeito',
      answers: ['houve'],
    },
    {
      sentence: 'Nós {blank} um grande progresso no projeto.',
      verb: 'haver',
      tense: 'pretérito perfeito',
      answers: ['houve'],
    },
    {
      sentence: 'Vocês {blank} muitas pessoas na festa.',
      verb: 'haver',
      tense: 'pretérito perfeito',
      answers: ['houve'],
    },
    {
      sentence: 'Os alunos {blank} uma discussão interessante na aula.',
      verb: 'haver',
      tense: 'pretérito perfeito',
      answers: ['houve'],
    },
    {
      sentence: 'Meu amigo {blank} muitas ideias boas para o evento.',
      verb: 'haver',
      tense: 'pretérito perfeito',
      answers: ['houve'],
    },
    {
      sentence: 'Ana e João {blank} um encontro importante na semana passada.',
      verb: 'haver',
      tense: 'pretérito perfeito',
      answers: ['houve'],
    },
    {
      sentence: 'Vocês {blank} uma grande chance de vencer.',
      verb: 'haver',
      tense: 'pretérito perfeito',
      answers: ['houve'],
    },
    {
      sentence: 'Eu {blank} uma reunião com o gerente ontem.',
      verb: 'haver',
      tense: 'pretérito perfeito',
      answers: ['houve'],
    },
    {
      sentence: 'Ela {blank} várias dificuldades ao longo do ano.',
      verb: 'haver',
      tense: 'pretérito perfeito',
      answers: ['houve'],
    },
  ],
};
