import { ProblemList } from '../Problems';

export const ir: ProblemList = {
  verb: 'ir',
  problems: [
    {
      sentence: 'Eu {blank} ao cinema esta noite.',
      verb: 'ir',
      tense: 'presente',
      answers: ['vou'],
    },
    {
      sentence: 'Ela {blank} ao supermercado todo sábado.',
      verb: 'ir',
      tense: 'presente',
      answers: ['vai'],
    },
    {
      sentence: 'Nós {blank} à praia sempre que podemos.',
      verb: 'ir',
      tense: 'presente',
      answers: ['vamos'],
    },
    {
      sentence: 'Você {blank} a uma festa amanhã?',
      verb: 'ir',
      tense: 'presente',
      answers: ['vai'],
    },
    {
      sentence: 'João {blank} ao parque com os amigos.',
      verb: 'ir',
      tense: 'presente',
      answers: ['vai'],
    },
    {
      sentence: 'Elas {blank} ao museu no final de semana.',
      verb: 'ir',
      tense: 'presente',
      answers: ['vão'],
    },
    {
      sentence: 'Eu e você {blank} ao teatro hoje à noite.',
      verb: 'ir',
      tense: 'presente',
      answers: ['vamos'],
    },
    {
      sentence: 'Eles {blank} ao médico toda quarta-feira.',
      verb: 'ir',
      tense: 'presente',
      answers: ['vão'],
    },
    {
      sentence: 'Maria {blank} à escola pela manhã.',
      verb: 'ir',
      tense: 'presente',
      answers: ['vai'],
    },
    {
      sentence: 'Nós {blank} ao jantar de família amanhã.',
      verb: 'ir',
      tense: 'presente',
      answers: ['vamos'],
    },
    {
      sentence: 'Eu {blank} ao cinema com os meus amigos no sábado passado.',
      verb: 'ir',
      tense: 'pretérito perfeito',
      answers: ['fui'],
    },
    {
      sentence: 'Ela {blank} à festa de aniversário da Maria.',
      verb: 'ir',
      tense: 'pretérito perfeito',
      answers: ['foi'],
    },
    {
      sentence: 'Nós {blank} ao parque para um piquenique no domingo.',
      verb: 'ir',
      tense: 'pretérito perfeito',
      answers: ['fomos'],
    },
    {
      sentence: 'Você {blank} à reunião importante ontem.',
      verb: 'ir',
      tense: 'pretérito perfeito',
      answers: ['foi'],
    },
    {
      sentence: 'Eles {blank} à escola juntos na semana passada.',
      verb: 'ir',
      tense: 'pretérito perfeito',
      answers: ['foram'],
    },
    {
      sentence: 'A Ana e o Carlos {blank} aos jogos de futebol no último mês.',
      verb: 'ir',
      tense: 'pretérito perfeito',
      answers: ['foram'],
    },
    {
      sentence: 'João {blank} à consulta médica ontem.',
      verb: 'ir',
      tense: 'pretérito perfeito',
      answers: ['foi'],
    },
    {
      sentence: 'Nós {blank} ao shopping comprar algumas roupas.',
      verb: 'ir',
      tense: 'pretérito perfeito',
      answers: ['fomos'],
    },
    {
      sentence: 'Você e eu {blank} ao teatro no último fim de semana.',
      verb: 'ir',
      tense: 'pretérito perfeito',
      answers: ['fomos'],
    },
    {
      sentence: 'Eles {blank} à cidade para um evento cultural.',
      verb: 'ir',
      tense: 'pretérito perfeito',
      answers: ['foram'],
    },
    {
      sentence: 'Eu {blank} ao cinema amanhã.',
      verb: 'ir',
      tense: 'futuro',
      answers: ['irei', 'vou'],
    },
    {
      sentence: 'Ela {blank} para a festa na próxima semana.',
      verb: 'ir',
      tense: 'futuro',
      answers: ['irá', 'vai'],
    },
    {
      sentence: 'Nós {blank} visitar os avós no sábado.',
      verb: 'ir',
      tense: 'futuro',
      answers: ['iremos', 'vamos'],
    },
    {
      sentence: 'Você {blank} estudar para a prova na próxima terça.',
      verb: 'ir',
      tense: 'futuro',
      answers: ['vai', 'irá'],
    },
    {
      sentence: 'Eles {blank} à praia no próximo mês.',
      verb: 'ir',
      tense: 'futuro',
      answers: ['irão', 'vão'],
    },
    {
      sentence: 'Miguel {blank} ao parque com os amigos mais tarde.',
      verb: 'ir',
      tense: 'futuro',
      answers: ['vai', 'irá'],
    },
    {
      sentence: 'Ana e eu {blank} fazer compras amanhã.',
      verb: 'ir',
      tense: 'futuro',
      answers: ['vamos', 'iremos'],
    },
    {
      sentence: 'Vocês {blank} ao shopping no final de semana.',
      verb: 'ir',
      tense: 'futuro',
      answers: ['vão', 'irão'],
    },
    {
      sentence: 'Ela {blank} viajar para a Europa no verão.',
      verb: 'ir',
      tense: 'futuro',
      answers: ['vai', 'irá'],
    },
    {
      sentence: 'Meu pai {blank} ao médico na próxima semana.',
      verb: 'ir',
      tense: 'futuro',
      answers: ['irá', 'vai'],
    },
  ],
};
