import { ProblemList } from '../Problems';

export const jogar: ProblemList = {
  verb: 'jogar',
  problems: [
    {
      sentence: 'Eu {blank} futebol todos os sábados.',
      verb: 'jogar',
      tense: 'presente',
      answers: ['jogo'],
    },
    {
      sentence: 'Ela {blank} basquete com os amigos durante a semana.',
      verb: 'jogar',
      tense: 'presente',
      answers: ['joga'],
    },
    {
      sentence: 'Nós {blank} vôlei na praia nos fins de semana.',
      verb: 'jogar',
      tense: 'presente',
      answers: ['jogamos'],
    },
    {
      sentence: 'Você {blank} cartas com seus avós toda sexta-feira.',
      verb: 'jogar',
      tense: 'presente',
      answers: ['joga'],
    },
    {
      sentence: 'Os alunos {blank} xadrez no intervalo.',
      verb: 'jogar',
      tense: 'presente',
      answers: ['jogam'],
    },
    {
      sentence: 'Maria {blank} handebol no time da escola.',
      verb: 'jogar',
      tense: 'presente',
      answers: ['joga'],
    },
    {
      sentence: 'Nós e vocês {blank} jogo de tabuleiro na casa de Ana.',
      verb: 'jogar',
      tense: 'presente',
      answers: ['jogamos'],
    },
    {
      sentence: 'Carlos {blank} vídeo game todos os dias.',
      verb: 'jogar',
      tense: 'presente',
      answers: ['joga'],
    },
    {
      sentence: 'Vocês {blank} futebol de mesa na sala.',
      verb: 'jogar',
      tense: 'presente',
      answers: ['jogam'],
    },
    {
      sentence: 'Eles {blank} RPG nas noites de sexta.',
      verb: 'jogar',
      tense: 'presente',
      answers: ['jogam'],
    },
    {
      sentence: 'Eu {blank} muito bem no campeonato no ano passado.',
      verb: 'jogar',
      tense: 'pretérito perfeito',
      answers: ['joguei'],
    },
    {
      sentence: 'Ela {blank} com seus amigos na praia no fim de semana.',
      verb: 'jogar',
      tense: 'pretérito perfeito',
      answers: ['jogou'],
    },
    {
      sentence: 'Nós {blank} uma partida incrível ontem à noite.',
      verb: 'jogar',
      tense: 'pretérito perfeito',
      answers: ['jogamos'],
    },
    {
      sentence: 'Você {blank} dois jogos seguidos na quinta-feira passada.',
      verb: 'jogar',
      tense: 'pretérito perfeito',
      answers: ['jogou'],
    },
    {
      sentence: 'Eles {blank} futebol no parque no sábado.',
      verb: 'jogar',
      tense: 'pretérito perfeito',
      answers: ['jogaram'],
    },
    {
      sentence: 'Rafael {blank} muito bem na última competição.',
      verb: 'jogar',
      tense: 'pretérito perfeito',
      answers: ['jogou'],
    },
    {
      sentence: 'Maria e eu {blank} vôlei na escola na semana passada.',
      verb: 'jogar',
      tense: 'pretérito perfeito',
      answers: ['jogamos'],
    },
    {
      sentence: 'Vocês {blank} basquete na quadra municipal.',
      verb: 'jogar',
      tense: 'pretérito perfeito',
      answers: ['jogaram'],
    },
    {
      sentence: 'Nós {blank} um jogo amistoso contra os vizinhos.',
      verb: 'jogar',
      tense: 'pretérito perfeito',
      answers: ['jogamos'],
    },
    {
      sentence: 'Ele {blank} cartas com a família no Natal.',
      verb: 'jogar',
      tense: 'pretérito perfeito',
      answers: ['jogou'],
    },
    {
      sentence: 'Nós {blank} um jogo importante no próximo fim de semana.',
      verb: 'jogar',
      tense: 'futuro',
      answers: ['jogaremos', 'vamos jogar'],
    },
    {
      sentence: 'Ela {blank} futebol com os amigos no sábado.',
      verb: 'jogar',
      tense: 'futuro',
      answers: ['jogará', 'vai jogar'],
    },
    {
      sentence: 'Eu {blank} vôlei na próxima quinta-feira.',
      verb: 'jogar',
      tense: 'futuro',
      answers: ['jogarei', 'vou jogar'],
    },
    {
      sentence: 'Vocês {blank} basquete na semana que vem.',
      verb: 'jogar',
      tense: 'futuro',
      answers: ['jogarão', 'vão jogar'],
    },
    {
      sentence: 'Ele {blank} em um campeonato de xadrez no próximo mês.',
      verb: 'jogar',
      tense: 'futuro',
      answers: ['jogará', 'vai jogar'],
    },
    {
      sentence: 'Ana e eu {blank} no time de handebol no próximo ano.',
      verb: 'jogar',
      tense: 'futuro',
      answers: ['jogaremos', 'vamos jogar'],
    },
    {
      sentence: 'Eles {blank} jogos eletrônicos no fim de semana.',
      verb: 'jogar',
      tense: 'futuro',
      answers: ['jogarão', 'vão jogar'],
    },
    {
      sentence: 'Você {blank} cartas com seus amigos amanhã.',
      verb: 'jogar',
      tense: 'futuro',
      answers: ['jogará', 'vai jogar'],
    },
    {
      sentence: 'Maria e João {blank} em um torneio de futebol no próximo mês.',
      verb: 'jogar',
      tense: 'futuro',
      answers: ['jogarão', 'vão jogar'],
    },
    {
      sentence: 'Nós {blank} vídeo games juntos na próxima sexta-feira.',
      verb: 'jogar',
      tense: 'futuro',
      answers: ['jogaremos', 'vamos jogar'],
    },
  ],
};
