import { ProblemList } from '../Problems';

export const lavar: ProblemList = {
  verb: 'lavar',
  problems: [
    {
      sentence: 'Eu {blank} o carro ontem à noite.',
      verb: 'lavar',
      tense: 'pretérito perfeito',
      answers: ['lavei'],
    },
    {
      sentence: 'Ela {blank} a roupa para a festa.',
      verb: 'lavar',
      tense: 'pretérito perfeito',
      answers: ['lavou'],
    },
    {
      sentence: 'Nós {blank} os pratos após o jantar.',
      verb: 'lavar',
      tense: 'pretérito perfeito',
      answers: ['lavamos'],
    },
    {
      sentence: 'Você {blank} o carro do seu irmão?',
      verb: 'lavar',
      tense: 'pretérito perfeito',
      answers: ['lavou'],
    },
    {
      sentence: 'João {blank} as mãos antes de comer.',
      verb: 'lavar',
      tense: 'pretérito perfeito',
      answers: ['lavou'],
    },
    {
      sentence: 'Eles {blank} a casa no final de semana.',
      verb: 'lavar',
      tense: 'pretérito perfeito',
      answers: ['lavaram'],
    },
    {
      sentence: 'Maria e eu {blank} a lençol da cama.',
      verb: 'lavar',
      tense: 'pretérito perfeito',
      answers: ['lavamos'],
    },
    {
      sentence: 'Você e eu {blank} os tênis depois da corrida.',
      verb: 'lavar',
      tense: 'pretérito perfeito',
      answers: ['lavamos'],
    },
    {
      sentence: 'Ela {blank} a cortina que estava suja.',
      verb: 'lavar',
      tense: 'pretérito perfeito',
      answers: ['lavou'],
    },
    {
      sentence: 'Eles {blank} os utensílios na pia.',
      verb: 'lavar',
      tense: 'pretérito perfeito',
      answers: ['lavaram'],
    },
    {
      sentence: 'Eu {blank} o carro no sábado.',
      verb: 'lavar',
      tense: 'futuro',
      answers: ['lavarei', 'vou lavar'],
    },
    {
      sentence: 'Ela {blank} as roupas antes da viagem.',
      verb: 'lavar',
      tense: 'futuro',
      answers: ['lavará', 'vai lavar'],
    },
    {
      sentence: 'Nós {blank} a varanda no próximo mês.',
      verb: 'lavar',
      tense: 'futuro',
      answers: ['lavaremos', 'vamos lavar'],
    },
    {
      sentence: 'Vocês {blank} a mesa para o jantar amanhã.',
      verb: 'lavar',
      tense: 'futuro',
      answers: ['lavarão', 'vão lavar'],
    },
    {
      sentence: 'Os meninos {blank} o cachorro no domingo.',
      verb: 'lavar',
      tense: 'futuro',
      answers: ['lavarão', 'vão lavar'],
    },
    {
      sentence: 'Maria {blank} a louça depois do almoço.',
      verb: 'lavar',
      tense: 'futuro',
      answers: ['lavará', 'vai lavar'],
    },
    {
      sentence: 'Eu e Pedro {blank} os vidros das janelas neste fim de semana.',
      verb: 'lavar',
      tense: 'futuro',
      answers: ['lavaremos', 'vamos lavar'],
    },
    {
      sentence: 'Você {blank} o tapete da sala na terça-feira.',
      verb: 'lavar',
      tense: 'futuro',
      answers: ['lavará', 'vai lavar'],
    },
    {
      sentence: 'As meninas {blank} as mãos antes do lanche.',
      verb: 'lavar',
      tense: 'futuro',
      answers: ['lavarão', 'vão lavar'],
    },
    {
      sentence: 'Eu {blank} o banheiro amanhã à tarde.',
      verb: 'lavar',
      tense: 'futuro',
      answers: ['lavarei', 'vou lavar'],
    },
    {
      sentence: 'Eu {blank} o carro todos os sábados.',
      verb: 'lavar',
      tense: 'presente',
      answers: ['lavo'],
    },
    {
      sentence: 'Ela {blank} as mãos antes de cozinhar.',
      verb: 'lavar',
      tense: 'presente',
      answers: ['lava'],
    },
    {
      sentence: 'Nós {blank} as roupas que usamos no final de semana.',
      verb: 'lavar',
      tense: 'presente',
      answers: ['lavamos'],
    },
    {
      sentence: 'Você {blank} o chão da cozinha toda semana.',
      verb: 'lavar',
      tense: 'presente',
      answers: ['lava'],
    },
    {
      sentence: 'Eles {blank} o gato quando ele volta da rua.',
      verb: 'lavar',
      tense: 'presente',
      answers: ['lavam'],
    },
    {
      sentence: 'João {blank} o carro frequentemente.',
      verb: 'lavar',
      tense: 'presente',
      answers: ['lava'],
    },
    {
      sentence: 'Nós {blank} as frutas antes de comer.',
      verb: 'lavar',
      tense: 'presente',
      answers: ['lavamos'],
    },
    {
      sentence: 'Você e eu {blank} a louça juntos.',
      verb: 'lavar',
      tense: 'presente',
      answers: ['lavamos'],
    },
    {
      sentence: 'Ela e a Maria {blank} os bonecos do filho.',
      verb: 'lavar',
      tense: 'presente',
      answers: ['lavam'],
    },
    {
      sentence: 'O professor {blank} o quadro depois da aula.',
      verb: 'lavar',
      tense: 'presente',
      answers: ['lava'],
    },
  ],
};
