import { ProblemList } from '../Problems';

export const ler: ProblemList = {
  verb: 'ler',
  problems: [
    {
      sentence: 'Eu {blank} o livro que você me recomendou.',
      verb: 'ler',
      tense: 'pretérito perfeito',
      answers: ['li'],
    },
    {
      sentence: 'Ela {blank} todos os capítulos antes do exame.',
      verb: 'ler',
      tense: 'pretérito perfeito',
      answers: ['leu'],
    },
    {
      sentence: 'Nós {blank} a mensagem que você enviou ontem.',
      verb: 'ler',
      tense: 'pretérito perfeito',
      answers: ['lemos'],
    },
    {
      sentence: 'Você {blank} a revista nova que chegou na biblioteca?',
      verb: 'ler',
      tense: 'pretérito perfeito',
      answers: ['leu'],
    },
    {
      sentence: 'Eles {blank} o relatório antes da apresentação.',
      verb: 'ler',
      tense: 'pretérito perfeito',
      answers: ['leram'],
    },
    {
      sentence: 'Maria {blank} aquele artigo interessante sobre ciência.',
      verb: 'ler',
      tense: 'pretérito perfeito',
      answers: ['leu'],
    },
    {
      sentence: 'João {blank} as instruções e fez tudo certo.',
      verb: 'ler',
      tense: 'pretérito perfeito',
      answers: ['leu'],
    },
    {
      sentence: 'Vocês {blank} o novo livro do autor famoso?',
      verb: 'ler',
      tense: 'pretérito perfeito',
      answers: ['leram'],
    },
    {
      sentence: 'Eu {blank} o texto completo antes de comentar.',
      verb: 'ler',
      tense: 'pretérito perfeito',
      answers: ['li'],
    },
    {
      sentence: 'Eles {blank} as regras do jogo antes de começar.',
      verb: 'ler',
      tense: 'pretérito perfeito',
      answers: ['leram'],
    },
    {
      sentence: 'Eu {blank} o livro que você me recomendou.',
      verb: 'ler',
      tense: 'futuro',
      answers: ['lerei', 'vou ler'],
    },
    {
      sentence: 'Ela {blank} as mensagens importantes antes da reunião.',
      verb: 'ler',
      tense: 'futuro',
      answers: ['lerá', 'vai ler'],
    },
    {
      sentence: 'Nós {blank} o relatório até amanhã.',
      verb: 'ler',
      tense: 'futuro',
      answers: ['leremos', 'vamos ler'],
    },
    {
      sentence: 'Vocês {blank} as instruções antes de começarem.',
      verb: 'ler',
      tense: 'futuro',
      answers: ['lerão', 'vão ler'],
    },
    {
      sentence: 'João {blank} os capítulos que estavam faltando.',
      verb: 'ler',
      tense: 'futuro',
      answers: ['lerá', 'vai ler'],
    },
    {
      sentence: 'Meu amigo e eu {blank} o artigo no fim de semana.',
      verb: 'ler',
      tense: 'futuro',
      answers: ['leremos', 'vamos ler'],
    },
    {
      sentence: 'Vocês {blank} a obra completa do autor famoso.',
      verb: 'ler',
      tense: 'futuro',
      answers: ['lerão', 'vão ler'],
    },
    {
      sentence: 'Ana {blank} todas as notícias do dia.',
      verb: 'ler',
      tense: 'futuro',
      answers: ['lerá', 'vai ler'],
    },
    {
      sentence: 'Eu e você {blank} as regras do jogo antes de jogarmos.',
      verb: 'ler',
      tense: 'futuro',
      answers: ['leremos', 'vamos ler'],
    },
    {
      sentence: 'Eles {blank} as pesquisas de campo com atenção.',
      verb: 'ler',
      tense: 'futuro',
      answers: ['lerão', 'vão ler'],
    },
    {
      sentence: 'Eu {blank} todos os dias antes do trabalho.',
      verb: 'ler',
      tense: 'presente',
      answers: ['leio'],
    },
    {
      sentence: 'Ela {blank} o livro que ganhou de presente.',
      verb: 'ler',
      tense: 'presente',
      answers: ['lê'],
    },
    {
      sentence: 'Nós {blank} as notícias sempre pela manhã.',
      verb: 'ler',
      tense: 'presente',
      answers: ['lemos'],
    },
    {
      sentence: 'Você {blank} os relatórios antes da reunião.',
      verb: 'ler',
      tense: 'presente',
      answers: ['lê'],
    },
    {
      sentence: 'Eles {blank} a mesma revista todos os meses.',
      verb: 'ler',
      tense: 'presente',
      answers: ['leem'],
    },
    {
      sentence: 'Maria {blank} as postagens nas redes sociais.',
      verb: 'ler',
      tense: 'presente',
      answers: ['lê'],
    },
    {
      sentence: 'Eu e você {blank} juntos os livros da biblioteca.',
      verb: 'ler',
      tense: 'presente',
      answers: ['lemos'],
    },
    {
      sentence: 'João {blank} as instruções cuidadosamente.',
      verb: 'ler',
      tense: 'presente',
      answers: ['lê'],
    },
    {
      sentence: 'Elas {blank} revistas de moda regularmente.',
      verb: 'ler',
      tense: 'presente',
      answers: ['leem'],
    },
    {
      sentence: 'Vocês {blank} os artigos mais recentes sobre ciência.',
      verb: 'ler',
      tense: 'presente',
      answers: ['leem'],
    },
  ],
};
