import { ProblemList } from '../Problems';

export const levar: ProblemList = {
  verb: 'levar',
  problems: [
    {
      sentence: 'Eu {blank} meu filho para a escola todos os dias.',
      verb: 'levar',
      tense: 'presente',
      answers: ['levo'],
    },
    {
      sentence: 'Você {blank} os amigos para a festa hoje à noite.',
      verb: 'levar',
      tense: 'presente',
      answers: ['leva'],
    },
    {
      sentence: 'Ela {blank} sempre seus cães para o parque.',
      verb: 'levar',
      tense: 'presente',
      answers: ['leva'],
    },
    {
      sentence: 'Nós {blank} o carro para o mecânico na segunda-feira.',
      verb: 'levar',
      tense: 'presente',
      answers: ['levamos'],
    },
    {
      sentence: 'Vocês {blank} os materiais certos para a aula.',
      verb: 'levar',
      tense: 'presente',
      answers: ['levam'],
    },
    {
      sentence: 'Ele {blank} seu laptop para o trabalho todas as semanas.',
      verb: 'levar',
      tense: 'presente',
      answers: ['leva'],
    },
    {
      sentence: 'Maria e João {blank} frutas frescas do mercado.',
      verb: 'levar',
      tense: 'presente',
      answers: ['levam'],
    },
    {
      sentence: 'Eu {blank} sempre um livro na bolsa.',
      verb: 'levar',
      tense: 'presente',
      answers: ['levo'],
    },
    {
      sentence: 'Você e eu {blank} o projeto para discussão amanhã.',
      verb: 'levar',
      tense: 'presente',
      answers: ['levamos'],
    },
    {
      sentence: 'Os alunos {blank} suas mochilas para a escola.',
      verb: 'levar',
      tense: 'presente',
      answers: ['levam'],
    },
    {
      sentence: 'Ela {blank} os livros para a biblioteca.',
      verb: 'levar',
      tense: 'pretérito perfeito',
      answers: ['levou'],
    },
    {
      sentence: 'Nós {blank} as crianças para o parque ontem.',
      verb: 'levar',
      tense: 'pretérito perfeito',
      answers: ['levamos'],
    },
    {
      sentence: 'Eu {blank} meu jantar para o trabalho.',
      verb: 'levar',
      tense: 'pretérito perfeito',
      answers: ['levei'],
    },
    {
      sentence: 'Você {blank} a bolsa para a escola na semana passada.',
      verb: 'levar',
      tense: 'pretérito perfeito',
      answers: ['levou'],
    },
    {
      sentence: 'Eles {blank} o carro para o mecânico.',
      verb: 'levar',
      tense: 'pretérito perfeito',
      answers: ['levaram'],
    },
    {
      sentence: 'João {blank} seu cachorro ao veterinário ontem.',
      verb: 'levar',
      tense: 'pretérito perfeito',
      answers: ['levou'],
    },
    {
      sentence: 'Maria e eu {blank} muitos presentes para a festa.',
      verb: 'levar',
      tense: 'pretérito perfeito',
      answers: ['levamos'],
    },
    {
      sentence: 'Vocês {blank} a matéria para a prova.',
      verb: 'levar',
      tense: 'pretérito perfeito',
      answers: ['levaram'],
    },
    {
      sentence: 'O professor {blank} os alunos para a excursão.',
      verb: 'levar',
      tense: 'pretérito perfeito',
      answers: ['levou'],
    },
    {
      sentence: 'Ela {blank} frutas frescas para o piquenique.',
      verb: 'levar',
      tense: 'pretérito perfeito',
      answers: ['levou'],
    },
    {
      sentence: 'Eu {blank} os livros para a biblioteca amanhã.',
      verb: 'levar',
      tense: 'futuro',
      answers: ['levarei', 'vou levar'],
    },
    {
      sentence: 'Você {blank} seu irmão para o show na próxima semana.',
      verb: 'levar',
      tense: 'futuro',
      answers: ['levará', 'vai levar'],
    },
    {
      sentence: 'Eles {blank} as crianças ao parque no sábado.',
      verb: 'levar',
      tense: 'futuro',
      answers: ['levam', 'vão levar'],
    },
    {
      sentence: 'Nós {blank} um fotógrafo para o nosso casamento.',
      verb: 'levar',
      tense: 'futuro',
      answers: ['levaremos', 'vamos levar'],
    },
    {
      sentence: 'Você e eu {blank} nossos amigos para a festa.',
      verb: 'levar',
      tense: 'futuro',
      answers: ['levaremos', 'vamos levar'],
    },
    {
      sentence: 'Ela {blank} o cachorro ao veterinário na próxima consulta.',
      verb: 'levar',
      tense: 'futuro',
      answers: ['levará', 'vai levar'],
    },
    {
      sentence: 'Carlos {blank} os documentos para a reunião amanhã.',
      verb: 'levar',
      tense: 'futuro',
      answers: ['levará', 'vai levar'],
    },
    {
      sentence: 'Os alunos {blank} suas obras de arte para a exposição.',
      verb: 'levar',
      tense: 'futuro',
      answers: ['levarão', 'vão levar'],
    },
    {
      sentence: 'Seu pai {blank} você ao médico logo mais.',
      verb: 'levar',
      tense: 'futuro',
      answers: ['levará', 'vai levar'],
    },
    {
      sentence: 'Nós {blank} um presente para a festa de aniversário.',
      verb: 'levar',
      tense: 'futuro',
      answers: ['levaremos', 'vamos levar'],
    },
  ],
};
