import { ProblemList } from '../Problems';

export const lidar: ProblemList = {
  verb: 'lidar',
  problems: [
    {
      sentence: 'Eu {blank} bem com os meus sentimentos.',
      verb: 'lidar',
      tense: 'presente',
      answers: ['lido'],
    },
    {
      sentence: 'Ela {blank} sempre com as críticas de forma construtiva.',
      verb: 'lidar',
      tense: 'presente',
      answers: ['lida'],
    },
    {
      sentence: 'Nós {blank} com várias situações difíceis no trabalho.',
      verb: 'lidar',
      tense: 'presente',
      answers: ['lidamos'],
    },
    {
      sentence: 'Você {blank} melhor com os desafios diários.',
      verb: 'lidar',
      tense: 'presente',
      answers: ['lida'],
    },
    {
      sentence: 'Eles {blank} com os problemas de forma eficaz.',
      verb: 'lidar',
      tense: 'presente',
      answers: ['lidam'],
    },
    {
      sentence: 'João {blank} bem com o estresse da rotina.',
      verb: 'lidar',
      tense: 'presente',
      answers: ['lida'],
    },
    {
      sentence: 'Maria e eu {blank} juntos com os conflitos.',
      verb: 'lidar',
      tense: 'presente',
      answers: ['lidamos'],
    },
    {
      sentence: 'Vocês {blank} bem com a mudança.',
      verb: 'lidar',
      tense: 'presente',
      answers: ['lidam'],
    },
    {
      sentence: 'O time {blank} com a pressão nas competições.',
      verb: 'lidar',
      tense: 'presente',
      answers: ['lida'],
    },
    {
      sentence: 'Ela e você {blank} com todos os desafios que surgem.',
      verb: 'lidar',
      tense: 'presente',
      answers: ['lidam'],
    },
    {
      sentence: 'Eu {blank} com a situação delicada na reunião.',
      verb: 'lidar',
      tense: 'pretérito perfeito',
      answers: ['lidei'],
    },
    {
      sentence: 'Ela {blank} muito bem com os problemas apresentados.',
      verb: 'lidar',
      tense: 'pretérito perfeito',
      answers: ['lidou'],
    },
    {
      sentence: 'Nós {blank} com as dificuldades da equipe.',
      verb: 'lidar',
      tense: 'pretérito perfeito',
      answers: ['lidamos'],
    },
    {
      sentence: 'Você {blank} perfeitamente com a situação difícil.',
      verb: 'lidar',
      tense: 'pretérito perfeito',
      answers: ['lidou'],
    },
    {
      sentence: 'Os alunos {blank} com a pressão das provas.',
      verb: 'lidar',
      tense: 'pretérito perfeito',
      answers: ['lidaram'],
    },
    {
      sentence: 'Joana {blank} muito bem com o estresse do trabalho.',
      verb: 'lidar',
      tense: 'pretérito perfeito',
      answers: ['lidou'],
    },
    {
      sentence: 'Nós {blank} com a mudança de planos inesperada.',
      verb: 'lidar',
      tense: 'pretérito perfeito',
      answers: ['lidamos'],
    },
    {
      sentence: 'Ele {blank} com a situação complicadora sem dificuldades.',
      verb: 'lidar',
      tense: 'pretérito perfeito',
      answers: ['lidou'],
    },
    {
      sentence: 'Vocês {blank} com a crítica de forma construtiva.',
      verb: 'lidar',
      tense: 'pretérito perfeito',
      answers: ['lidaram'],
    },
    {
      sentence: 'Maria {blank} muito bem com os desafios do projeto.',
      verb: 'lidar',
      tense: 'pretérito perfeito',
      answers: ['lidou'],
    },
    {
      sentence: 'Eu {blank} melhor com os novos desafios no trabalho.',
      verb: 'lidar',
      tense: 'futuro',
      answers: ['lidarei', 'vou lidar'],
    },
    {
      sentence: 'Você {blank} com a situação delicada na próxima reunião.',
      verb: 'lidar',
      tense: 'futuro',
      answers: ['lidará', 'vai lidar'],
    },
    {
      sentence: 'Ela {blank} com os problemas de forma eficiente.',
      verb: 'lidar',
      tense: 'futuro',
      answers: ['lidará', 'vai lidar'],
    },
    {
      sentence:
        'Nós {blank} com as expectativas dos clientes na semana que vem.',
      verb: 'lidar',
      tense: 'futuro',
      answers: ['lidaremos', 'vamos lidar'],
    },
    {
      sentence: 'Eles {blank} com essa situação complicada juntos.',
      verb: 'lidar',
      tense: 'futuro',
      answers: ['lidarão', 'vão lidar'],
    },
    {
      sentence: 'Você e eu {blank} com os desafios da vida adulta.',
      verb: 'lidar',
      tense: 'futuro',
      answers: ['lidaremos', 'vamos lidar'],
    },
    {
      sentence: 'João {blank} com as críticas de maneira profissional.',
      verb: 'lidar',
      tense: 'futuro',
      answers: ['lidará', 'vai lidar'],
    },
    {
      sentence: 'Maria e Pedro {blank} com a pressão do trabalho em equipe.',
      verb: 'lidar',
      tense: 'futuro',
      answers: ['lidarão', 'vão lidar'],
    },
    {
      sentence: 'Vocês {blank} com qualquer situação que surgir.',
      verb: 'lidar',
      tense: 'futuro',
      answers: ['lidarão', 'vão lidar'],
    },
    {
      sentence: 'Ele {blank} melhor com os desafios neste novo projeto.',
      verb: 'lidar',
      tense: 'futuro',
      answers: ['lidará', 'vai lidar'],
    },
  ],
};
