import { ProblemList } from '../Problems';

export const ligar: ProblemList = {
  verb: 'ligar',
  problems: [
    {
      sentence: 'Eu {blank} para você agora.',
      verb: 'ligar',
      tense: 'presente',
      answers: ['ligo'],
    },
    {
      sentence: 'Ela {blank} para a mãe todos os dias.',
      verb: 'ligar',
      tense: 'presente',
      answers: ['liga'],
    },
    {
      sentence: 'Nós {blank} para os amigos antes do jantar.',
      verb: 'ligar',
      tense: 'presente',
      answers: ['ligamos'],
    },
    {
      sentence: 'Você {blank} o celular para a avó?',
      verb: 'ligar',
      tense: 'presente',
      answers: ['liga'],
    },
    {
      sentence: 'Eles {blank} para o trabalho toda manhã.',
      verb: 'ligar',
      tense: 'presente',
      answers: ['ligam'],
    },
    {
      sentence: 'Maria {blank} para o Dr. Carlos sempre.',
      verb: 'ligar',
      tense: 'presente',
      answers: ['liga'],
    },
    {
      sentence: 'Eu e você {blank} para confirmar a reunião.',
      verb: 'ligar',
      tense: 'presente',
      answers: ['ligamos'],
    },
    {
      sentence: 'João {blank} para a empresa frequentemente.',
      verb: 'ligar',
      tense: 'presente',
      answers: ['liga'],
    },
    {
      sentence: 'Vocês {blank} quando precisarem de ajuda.',
      verb: 'ligar',
      tense: 'presente',
      answers: ['ligam'],
    },
    {
      sentence: 'Ana e eu {blank} todos os sábados.',
      verb: 'ligar',
      tense: 'presente',
      answers: ['ligamos'],
    },
    {
      sentence: 'Eu {blank} para a festa ontem à noite.',
      verb: 'ligar',
      tense: 'pretérito perfeito',
      answers: ['liguei'],
    },
    {
      sentence: 'Você {blank} para mim no sábado passado.',
      verb: 'ligar',
      tense: 'pretérito perfeito',
      answers: ['ligou'],
    },
    {
      sentence: 'Ela {blank} para a amiga dela na terça-feira.',
      verb: 'ligar',
      tense: 'pretérito perfeito',
      answers: ['ligou'],
    },
    {
      sentence: 'Nós {blank} para o cliente quando ele chegou.',
      verb: 'ligar',
      tense: 'pretérito perfeito',
      answers: ['ligamos'],
    },
    {
      sentence: 'Eles {blank} para confirmar a reunião.',
      verb: 'ligar',
      tense: 'pretérito perfeito',
      answers: ['ligaram'],
    },
    {
      sentence: 'A Maria {blank} para o irmão dela no domingo.',
      verb: 'ligar',
      tense: 'pretérito perfeito',
      answers: ['ligou'],
    },
    {
      sentence: 'Você e eu {blank} para o dentista na semana passada.',
      verb: 'ligar',
      tense: 'pretérito perfeito',
      answers: ['ligamos'],
    },
    {
      sentence: 'O João {blank} para a namorada dele na sexta-feira.',
      verb: 'ligar',
      tense: 'pretérito perfeito',
      answers: ['ligou'],
    },
    {
      sentence: 'Os professores {blank} para os alunos ontem.',
      verb: 'ligar',
      tense: 'pretérito perfeito',
      answers: ['ligaram'],
    },
    {
      sentence: 'Ela e a Ana {blank} para avisar sobre o evento.',
      verb: 'ligar',
      tense: 'pretérito perfeito',
      answers: ['ligaram'],
    },
    {
      sentence: 'Eu {blank} para você amanhã.',
      verb: 'ligar',
      tense: 'futuro',
      answers: ['vou ligar', 'ligarei'],
    },
    {
      sentence: 'Ela {blank} para o chefe na próxima semana.',
      verb: 'ligar',
      tense: 'futuro',
      answers: ['vai ligar', 'ligará'],
    },
    {
      sentence: 'Nós {blank} para confirmar a reserva no sábado.',
      verb: 'ligar',
      tense: 'futuro',
      answers: ['vamos ligar', 'ligaremos'],
    },
    {
      sentence: 'Vocês {blank} para a agência de viagens na sexta-feira.',
      verb: 'ligar',
      tense: 'futuro',
      answers: ['vão ligar', 'ligarão'],
    },
    {
      sentence: 'João {blank} para a professora na próxima aula.',
      verb: 'ligar',
      tense: 'futuro',
      answers: ['vai ligar', 'ligará'],
    },
    {
      sentence: 'Maria e eu {blank} para nossos amigos mais tarde.',
      verb: 'ligar',
      tense: 'futuro',
      answers: ['vamos ligar', 'ligaremos'],
    },
    {
      sentence: 'Ele {blank} para o médico amanhã cedo.',
      verb: 'ligar',
      tense: 'futuro',
      answers: ['vai ligar', 'ligará'],
    },
    {
      sentence: 'As crianças {blank} para os avós durante o feriado.',
      verb: 'ligar',
      tense: 'futuro',
      answers: ['vão ligar', 'ligarão'],
    },
    {
      sentence: 'Vocês e eu {blank} para a empresa na próxima quinta.',
      verb: 'ligar',
      tense: 'futuro',
      answers: ['vamos ligar', 'ligaremos'],
    },
    {
      sentence: 'Ela {blank} para o cliente se houver problemas.',
      verb: 'ligar',
      tense: 'futuro',
      answers: ['vai ligar', 'ligará'],
    },
  ],
};
