import { ProblemList } from '../Problems';

export const morar: ProblemList = {
  verb: 'morar',
  problems: [
    {
      sentence: 'Eu {blank} em Lisboa durante um ano.',
      verb: 'morar',
      tense: 'pretérito perfeito',
      answers: ['morei'],
    },
    {
      sentence: 'Ela {blank} na casa da avó durante a infância.',
      verb: 'morar',
      tense: 'pretérito perfeito',
      answers: ['morou'],
    },
    {
      sentence: 'Nós {blank} juntos por muito tempo.',
      verb: 'morar',
      tense: 'pretérito perfeito',
      answers: ['moramos'],
    },
    {
      sentence: 'Você {blank} na praia durante o verão passado.',
      verb: 'morar',
      tense: 'pretérito perfeito',
      answers: ['morou'],
    },
    {
      sentence: 'Eles {blank} em São Paulo antes de se mudarem.',
      verb: 'morar',
      tense: 'pretérito perfeito',
      answers: ['moraram'],
    },
    {
      sentence: 'Maria e João {blank} no mesmo bairro.',
      verb: 'morar',
      tense: 'pretérito perfeito',
      answers: ['moraram'],
    },
    {
      sentence: 'Eu {blank} em uma pequena cidade até os dez anos.',
      verb: 'morar',
      tense: 'pretérito perfeito',
      answers: ['morei'],
    },
    {
      sentence: 'Você e eu {blank} em apartamentos diferentes na faculdade.',
      verb: 'morar',
      tense: 'pretérito perfeito',
      answers: ['moramos'],
    },
    {
      sentence: 'Ela {blank} em Londres durante o intercâmbio.',
      verb: 'morar',
      tense: 'pretérito perfeito',
      answers: ['morou'],
    },
    {
      sentence: 'Os estudantes {blank} no campus durante o semestre passado.',
      verb: 'morar',
      tense: 'pretérito perfeito',
      answers: ['moraram'],
    },
    {
      sentence: 'Eu {blank} em São Paulo no próximo ano.',
      verb: 'morar',
      tense: 'futuro',
      answers: ['morrerei', 'vou morar'],
    },
    {
      sentence: 'Ela {blank} perto da praia na próxima semana.',
      verb: 'morar',
      tense: 'futuro',
      answers: ['morarão', 'vão morar'],
    },
    {
      sentence: 'Nós {blank} em uma casa nova no próximo mês.',
      verb: 'morar',
      tense: 'futuro',
      answers: ['morreremos', 'vamos morar'],
    },
    {
      sentence: 'Você {blank} com seus amigos no próximo semestre.',
      verb: 'morar',
      tense: 'futuro',
      answers: ['morarão', 'vão morar'],
    },
    {
      sentence: 'Eles {blank} em um apartamento maior no próximo ano.',
      verb: 'morar',
      tense: 'futuro',
      answers: ['morarão', 'vão morar'],
    },
    {
      sentence: 'Ana e Carlos {blank} juntos no próximo ano.',
      verb: 'morar',
      tense: 'futuro',
      answers: ['morarão', 'vão morar'],
    },
    {
      sentence: 'Você e eu {blank} em uma cidade diferente em breve.',
      verb: 'morar',
      tense: 'futuro',
      answers: ['morreremos', 'vamos morar'],
    },
    {
      sentence: 'João {blank} com seus pais no próximo mês.',
      verb: 'morar',
      tense: 'futuro',
      answers: ['morarão', 'vão morar'],
    },
    {
      sentence: 'Ela {blank} em Lisboa no próximo verão.',
      verb: 'morar',
      tense: 'futuro',
      answers: ['morarão', 'vão morar'],
    },
    {
      sentence: 'Nós {blank} juntos em uma nova casa na primavera.',
      verb: 'morar',
      tense: 'futuro',
      answers: ['morreremos', 'vamos morar'],
    },
    {
      sentence: 'Eu {blank} em São Paulo.',
      verb: 'morar',
      tense: 'presente',
      answers: ['moro'],
    },
    {
      sentence: 'Ela {blank} com os pais.',
      verb: 'morar',
      tense: 'presente',
      answers: ['mora'],
    },
    {
      sentence: 'Nós {blank} no centro da cidade.',
      verb: 'morar',
      tense: 'presente',
      answers: ['moramos'],
    },
    {
      sentence: 'Você {blank} perto da escola.',
      verb: 'morar',
      tense: 'presente',
      answers: ['mora'],
    },
    {
      sentence: 'Eles {blank} em um apartamento.',
      verb: 'morar',
      tense: 'presente',
      answers: ['moram'],
    },
    {
      sentence: 'João {blank} com a avó.',
      verb: 'morar',
      tense: 'presente',
      answers: ['mora'],
    },
    {
      sentence: 'Maria e eu {blank} na mesma rua.',
      verb: 'morar',
      tense: 'presente',
      answers: ['moramos'],
    },
    {
      sentence: 'Vocês {blank} nas montanhas.',
      verb: 'morar',
      tense: 'presente',
      answers: ['moram'],
    },
    {
      sentence: 'Carlos {blank} em Lisboa.',
      verb: 'morar',
      tense: 'presente',
      answers: ['mora'],
    },
    {
      sentence: 'Ana e você {blank} em casas diferentes.',
      verb: 'morar',
      tense: 'presente',
      answers: ['moram'],
    },
  ],
};
