import { ProblemList } from '../Problems';

export const mudar: ProblemList = {
  verb: 'mudar',
  problems: [
    {
      sentence: 'Eu {blank} de ideia com frequência.',
      verb: 'mudar',
      tense: 'presente',
      answers: ['mudo'],
    },
    {
      sentence: 'Ela {blank} a decoração da casa todos os anos.',
      verb: 'mudar',
      tense: 'presente',
      answers: ['muda'],
    },
    {
      sentence: 'Nós {blank} o plano original para melhorar o projeto.',
      verb: 'mudar',
      tense: 'presente',
      answers: ['mudamos'],
    },
    {
      sentence: 'Você {blank} de opinião sobre o assunto.',
      verb: 'mudar',
      tense: 'presente',
      answers: ['muda'],
    },
    {
      sentence: 'Eles {blank} de estilo musical com frequência.',
      verb: 'mudar',
      tense: 'presente',
      answers: ['mudam'],
    },
    {
      sentence: 'Maria {blank} de profissão a cada ano.',
      verb: 'mudar',
      tense: 'presente',
      answers: ['muda'],
    },
    {
      sentence: 'João e eu {blank} a rotina para aumentar a produtividade.',
      verb: 'mudar',
      tense: 'presente',
      answers: ['mudamos'],
    },
    {
      sentence: 'Vocês {blank} de cidade a cada dois anos.',
      verb: 'mudar',
      tense: 'presente',
      answers: ['mudam'],
    },
    {
      sentence: 'Ela e você {blank} frequentemente de estilo.',
      verb: 'mudar',
      tense: 'presente',
      answers: ['mudam'],
    },
    {
      sentence: 'Ele {blank} de carro todos os meses.',
      verb: 'mudar',
      tense: 'presente',
      answers: ['muda'],
    },
    {
      sentence: 'Eu {blank} de cidade no ano passado.',
      verb: 'mudar',
      tense: 'pretérito perfeito',
      answers: ['mudei'],
    },
    {
      sentence: 'Você {blank} de ideia sobre o projeto.',
      verb: 'mudar',
      tense: 'pretérito perfeito',
      answers: ['mudou'],
    },
    {
      sentence: 'Ela {blank} o endereço do evento.',
      verb: 'mudar',
      tense: 'pretérito perfeito',
      answers: ['mudou'],
    },
    {
      sentence: 'Nós {blank} as regras do jogo.',
      verb: 'mudar',
      tense: 'pretérito perfeito',
      answers: ['mudamos'],
    },
    {
      sentence: 'Eles {blank} o plano de viagem.',
      verb: 'mudar',
      tense: 'pretérito perfeito',
      answers: ['mudaram'],
    },
    {
      sentence: 'Pedro {blank} o estilo de vida recentemente.',
      verb: 'mudar',
      tense: 'pretérito perfeito',
      answers: ['mudou'],
    },
    {
      sentence: 'Joana e eu {blank} de escola este ano.',
      verb: 'mudar',
      tense: 'pretérito perfeito',
      answers: ['mudamos'],
    },
    {
      sentence: 'Você e seus amigos {blank} de ideia rapidamente.',
      verb: 'mudar',
      tense: 'pretérito perfeito',
      answers: ['mudaram'],
    },
    {
      sentence: 'Meu irmão {blank} muito durante o último mês.',
      verb: 'mudar',
      tense: 'pretérito perfeito',
      answers: ['mudou'],
    },
    {
      sentence: 'Nós {blank} a data do evento sem aviso.',
      verb: 'mudar',
      tense: 'pretérito perfeito',
      answers: ['mudamos'],
    },
    {
      sentence: 'Eu {blank} para uma nova cidade no próximo mês.',
      verb: 'mudar',
      tense: 'futuro',
      answers: ['mudarei', 'vou mudar'],
    },
    {
      sentence: 'Você {blank} de emprego na semana que vem.',
      verb: 'mudar',
      tense: 'futuro',
      answers: ['mudarão', 'vão mudar'],
    },
    {
      sentence: 'Ela {blank} seu nome no documento amanhã.',
      verb: 'mudar',
      tense: 'futuro',
      answers: ['mudará', 'vai mudar'],
    },
    {
      sentence: 'Nós {blank} nosso endereço no próximo ano.',
      verb: 'mudar',
      tense: 'futuro',
      answers: ['mudaremos', 'vamos mudar'],
    },
    {
      sentence: 'Eles {blank} de escola no próximo semestre.',
      verb: 'mudar',
      tense: 'futuro',
      answers: ['mudarão', 'vão mudar'],
    },
    {
      sentence: 'Você e eu {blank} de opinião na próxima reunião.',
      verb: 'mudar',
      tense: 'futuro',
      answers: ['mudaremos', 'vamos mudar'],
    },
    {
      sentence: 'Ana {blank} a decoração da casa em breve.',
      verb: 'mudar',
      tense: 'futuro',
      answers: ['mudará', 'vai mudar'],
    },
    {
      sentence: 'Vocês {blank} de estratégia para o projeto logo.',
      verb: 'mudar',
      tense: 'futuro',
      answers: ['mudarão', 'vão mudar'],
    },
    {
      sentence: 'Eu {blank} minha rotina de exercícios no mês que vem.',
      verb: 'mudar',
      tense: 'futuro',
      answers: ['mudarei', 'vou mudar'],
    },
    {
      sentence: 'João {blank} de carro na próxima viagem.',
      verb: 'mudar',
      tense: 'futuro',
      answers: ['mudará', 'vai mudar'],
    },
  ],
};
