import { ProblemList } from '../Problems';

export const odiar: ProblemList = {
  verb: 'odiar',
  problems: [
    {
      sentence: 'Eu {blank} a lição de casa todos os dias.',
      verb: 'odiar',
      tense: 'presente',
      answers: ['odio'],
    },
    {
      sentence: 'Você {blank} esperar por muito tempo.',
      verb: 'odiar',
      tense: 'presente',
      answers: ['odia'],
    },
    {
      sentence: 'Ela {blank} que as pessoas não respeitem as regras.',
      verb: 'odiar',
      tense: 'presente',
      answers: ['odia'],
    },
    {
      sentence: 'Nós {blank} festas barulhentas.',
      verb: 'odiar',
      tense: 'presente',
      answers: ['odiamos'],
    },
    {
      sentence: 'Eles {blank} acordar cedo.',
      verb: 'odiar',
      tense: 'presente',
      answers: ['odeiam'],
    },
    {
      sentence: 'Você e eu {blank} discutir sobre política.',
      verb: 'odiar',
      tense: 'presente',
      answers: ['odiamos'],
    },
    {
      sentence: 'A Maria {blank} fazer exercícios de matemática.',
      verb: 'odiar',
      tense: 'presente',
      answers: ['odia'],
    },
    {
      sentence: 'Os meninos {blank} ir ao cinema.',
      verb: 'odiar',
      tense: 'presente',
      answers: ['odeiam'],
    },
    {
      sentence: 'Tu {blank} fazer trabalho em grupo.',
      verb: 'odiar',
      tense: 'presente',
      answers: ['odias'],
    },
    {
      sentence: 'O João {blank} o trânsito caótico da cidade.',
      verb: 'odiar',
      tense: 'presente',
      answers: ['odia'],
    },
    {
      sentence: 'Eu {blank} o filme que você recomendou.',
      verb: 'odiar',
      tense: 'pretérito perfeito',
      answers: ['odiei'],
    },
    {
      sentence: 'Ela {blank} a comida da festa.',
      verb: 'odiar',
      tense: 'pretérito perfeito',
      answers: ['odiou'],
    },
    {
      sentence: 'Nós {blank} o clima daquela cidade.',
      verb: 'odiar',
      tense: 'pretérito perfeito',
      answers: ['odiamos'],
    },
    {
      sentence: 'Eles {blank} a nova música que lançaram.',
      verb: 'odiar',
      tense: 'pretérito perfeito',
      answers: ['odiaram'],
    },
    {
      sentence: 'Você {blank} a apresentação do projeto.',
      verb: 'odiar',
      tense: 'pretérito perfeito',
      answers: ['odiou'],
    },
    {
      sentence: 'João {blank} a ideia de mudar de trabalho.',
      verb: 'odiar',
      tense: 'pretérito perfeito',
      answers: ['odiou'],
    },
    {
      sentence: 'Nós {blank} aquele livro que você nos deu.',
      verb: 'odiar',
      tense: 'pretérito perfeito',
      answers: ['odiamos'],
    },
    {
      sentence: 'Ela e eu {blank} a série que assistimos.',
      verb: 'odiar',
      tense: 'pretérito perfeito',
      answers: ['odiamos'],
    },
    {
      sentence: 'Você {blank} a forma como ele falou com você.',
      verb: 'odiar',
      tense: 'pretérito perfeito',
      answers: ['odiou'],
    },
    {
      sentence: 'Francisco {blank} a maneira como as coisas foram organizadas.',
      verb: 'odiar',
      tense: 'pretérito perfeito',
      answers: ['odiou'],
    },
    {
      sentence: 'Eu {blank} o calor do verão.',
      verb: 'odiar',
      tense: 'futuro',
      answers: ['odiarei', 'vou odiar'],
    },
    {
      sentence: 'Ela {blank} esperar por muito tempo.',
      verb: 'odiar',
      tense: 'futuro',
      answers: ['odiará', 'vai odiar'],
    },
    {
      sentence: 'Nós {blank} pessoas que não ajudam.',
      verb: 'odiar',
      tense: 'futuro',
      answers: ['odiaremos', 'vamos odiar'],
    },
    {
      sentence: 'Você {blank} ter que acordar cedo.',
      verb: 'odiar',
      tense: 'futuro',
      answers: ['odiará', 'vai odiar'],
    },
    {
      sentence: 'Eles {blank} a chuva no inverno.',
      verb: 'odiar',
      tense: 'futuro',
      answers: ['odiarão', 'vão odiar'],
    },
    {
      sentence: 'Maria {blank} quando não há luz.',
      verb: 'odiar',
      tense: 'futuro',
      answers: ['odiará', 'vai odiar'],
    },
    {
      sentence: 'João e eu {blank} mesmo assim.',
      verb: 'odiar',
      tense: 'futuro',
      answers: ['odiaremos', 'vamos odiar'],
    },
    {
      sentence: 'Vocês {blank} a pressão do trabalho.',
      verb: 'odiar',
      tense: 'futuro',
      answers: ['odiarão', 'vão odiar'],
    },
    {
      sentence: 'Ela e você {blank} as longas filas.',
      verb: 'odiar',
      tense: 'futuro',
      answers: ['odiarão', 'vão odiar'],
    },
    {
      sentence: 'Eu e você {blank} as reuniões sem propósito.',
      verb: 'odiar',
      tense: 'futuro',
      answers: ['odiaremos', 'vamos odiar'],
    },
  ],
};
