import { ProblemList } from '../Problems';

export const organizar: ProblemList = {
  verb: 'organizar',
  problems: [
    {
      sentence: 'Eu {blank} a festa no próximo mês.',
      verb: 'organizar',
      tense: 'futuro',
      answers: ['organizarai', 'vou organizar'],
    },
    {
      sentence: 'Você {blank} os eventos para o próximo ano.',
      verb: 'organizar',
      tense: 'futuro',
      answers: ['organizará', 'vai organizar'],
    },
    {
      sentence: 'Ela {blank} a conferência em dezembro.',
      verb: 'organizar',
      tense: 'futuro',
      answers: ['organizará', 'vai organizar'],
    },
    {
      sentence: 'Nós {blank} o calendário de atividades em breve.',
      verb: 'organizar',
      tense: 'futuro',
      answers: ['organizaremos', 'vamos organizar'],
    },
    {
      sentence: 'Vocês {blank} uma reunião para discutir o projeto.',
      verb: 'organizar',
      tense: 'futuro',
      answers: ['organizarão', 'vão organizar'],
    },
    {
      sentence: 'O João {blank} um workshop para a equipe.',
      verb: 'organizar',
      tense: 'futuro',
      answers: ['organizará', 'vai organizar'],
    },
    {
      sentence: 'Nós {blank} a logística do evento até a próxima semana.',
      verb: 'organizar',
      tense: 'futuro',
      answers: ['organizaremos', 'vamos organizar'],
    },
    {
      sentence: 'Ela e eu {blank} um jantar para os amigos.',
      verb: 'organizar',
      tense: 'futuro',
      answers: ['organizaremos', 'vamos organizar'],
    },
    {
      sentence: 'Ele {blank} a arrecadação de fundos para a ONG.',
      verb: 'organizar',
      tense: 'futuro',
      answers: ['organizará', 'vai organizar'],
    },
    {
      sentence: 'Você e eu {blank} um seminário no próximo semestre.',
      verb: 'organizar',
      tense: 'futuro',
      answers: ['organizaremos', 'vamos organizar'],
    },
    {
      sentence: 'Eu {blank} a festa do meu amigo no sábado passado.',
      verb: 'organizar',
      tense: 'pretérito perfeito',
      answers: ['organizei'],
    },
    {
      sentence: 'Você {blank} a reunião de trabalho na semana passada.',
      verb: 'organizar',
      tense: 'pretérito perfeito',
      answers: ['organizou'],
    },
    {
      sentence: 'Ela {blank} um evento para a comunidade há dois dias.',
      verb: 'organizar',
      tense: 'pretérito perfeito',
      answers: ['organizou'],
    },
    {
      sentence: 'Nós {blank} uma campanha de arrecadação no mês passado.',
      verb: 'organizar',
      tense: 'pretérito perfeito',
      answers: ['organizamos'],
    },
    {
      sentence: 'Eles {blank} uma excursão para as montanhas recentemente.',
      verb: 'organizar',
      tense: 'pretérito perfeito',
      answers: ['organizaram'],
    },
    {
      sentence: 'Você e eu {blank} um almoço especial para o nosso pai.',
      verb: 'organizar',
      tense: 'pretérito perfeito',
      answers: ['organizamos'],
    },
    {
      sentence: 'Maria {blank} a festa surpresa para o Pedro no ano passado.',
      verb: 'organizar',
      tense: 'pretérito perfeito',
      answers: ['organizou'],
    },
    {
      sentence: 'Os alunos {blank} uma exposição de arte na escola.',
      verb: 'organizar',
      tense: 'pretérito perfeito',
      answers: ['organizaram'],
    },
    {
      sentence: 'Você {blank} a conferência de tecnologia no último mês.',
      verb: 'organizar',
      tense: 'pretérito perfeito',
      answers: ['organizou'],
    },
    {
      sentence: 'João e Ana {blank} um jantar beneficente ontem à noite.',
      verb: 'organizar',
      tense: 'pretérito perfeito',
      answers: ['organizaram'],
    },
    {
      sentence: 'Eu {blank} a festa de aniversário do João.',
      verb: 'organizar',
      tense: 'presente',
      answers: ['organizo'],
    },
    {
      sentence: 'Ela {blank} os detalhes da apresentação.',
      verb: 'organizar',
      tense: 'presente',
      answers: ['organiza'],
    },
    {
      sentence: 'Nós {blank} um evento especial para o fim de ano.',
      verb: 'organizar',
      tense: 'presente',
      answers: ['organizamos'],
    },
    {
      sentence: 'Você {blank} a equipe para o projeto.',
      verb: 'organizar',
      tense: 'presente',
      answers: ['organiza'],
    },
    {
      sentence: 'Eles {blank} a agenda de reuniões semanalmente.',
      verb: 'organizar',
      tense: 'presente',
      answers: ['organizam'],
    },
    {
      sentence: 'A Ana {blank} as tarefas diárias no trabalho.',
      verb: 'organizar',
      tense: 'presente',
      answers: ['organiza'],
    },
    {
      sentence: 'Você e eu {blank} um plano de ação conjunto.',
      verb: 'organizar',
      tense: 'presente',
      answers: ['organizamos'],
    },
    {
      sentence: 'Os meninos {blank} tudo para a viagem.',
      verb: 'organizar',
      tense: 'presente',
      answers: ['organizam'],
    },
    {
      sentence: 'Ele {blank} os arquivos no computador.',
      verb: 'organizar',
      tense: 'presente',
      answers: ['organiza'],
    },
    {
      sentence: 'Nós {blank} as informações para o relatório.',
      verb: 'organizar',
      tense: 'presente',
      answers: ['organizamos'],
    },
  ],
};
