import { ProblemList } from '../Problems';

export const ouvir: ProblemList = {
  verb: 'ouvir',
  problems: [
    {
      sentence: 'Eu {blank} música enquanto estudo.',
      verb: 'ouvir',
      tense: 'presente',
      answers: ['ouço'],
    },
    {
      sentence: 'Você {blank} o que eu estou dizendo?',
      verb: 'ouvir',
      tense: 'presente',
      answers: ['ouve'],
    },
    {
      sentence: 'Ela {blank} um podcast todas as manhãs.',
      verb: 'ouvir',
      tense: 'presente',
      answers: ['ouve'],
    },
    {
      sentence: 'Nós {blank} as notícias na rádio.',
      verb: 'ouvir',
      tense: 'presente',
      answers: ['ouvimos'],
    },
    {
      sentence: 'Eles {blank} a música nova da banda.',
      verb: 'ouvir',
      tense: 'presente',
      answers: ['ouvem'],
    },
    {
      sentence: 'João {blank} muito bem a explicação do professor.',
      verb: 'ouvir',
      tense: 'presente',
      answers: ['ouve'],
    },
    {
      sentence: 'Vocês {blank} o que está acontecendo?',
      verb: 'ouvir',
      tense: 'presente',
      answers: ['ouvem'],
    },
    {
      sentence: 'Maria {blank} as instruções cuidadosamente.',
      verb: 'ouvir',
      tense: 'presente',
      answers: ['ouve'],
    },
    {
      sentence: 'Nós {blank} o som do mar na praia.',
      verb: 'ouvir',
      tense: 'presente',
      answers: ['ouvimos'],
    },
    {
      sentence: 'Eles {blank} a conversa entre os colegas.',
      verb: 'ouvir',
      tense: 'presente',
      answers: ['ouvem'],
    },
    {
      sentence: 'Eu {blank} as músicas novas do artista.',
      verb: 'ouvir',
      tense: 'pretérito perfeito',
      answers: ['ouvi'],
    },
    {
      sentence: 'Ela {blank} a conversa entre os amigos.',
      verb: 'ouvir',
      tense: 'pretérito perfeito',
      answers: ['ouviu'],
    },
    {
      sentence: 'Nós {blank} o anúncio na rádio ontem.',
      verb: 'ouvir',
      tense: 'pretérito perfeito',
      answers: ['ouvimos'],
    },
    {
      sentence: 'Você {blank} a notícia sobre a festa?',
      verb: 'ouvir',
      tense: 'pretérito perfeito',
      answers: ['ouviu'],
    },
    {
      sentence: 'Eles {blank} os conselhos do professor.',
      verb: 'ouvir',
      tense: 'pretérito perfeito',
      answers: ['ouviram'],
    },
    {
      sentence: 'Carlos {blank} o que a sua mãe disse.',
      verb: 'ouvir',
      tense: 'pretérito perfeito',
      answers: ['ouviu'],
    },
    {
      sentence: 'João e Maria {blank} a apresentação.',
      verb: 'ouvir',
      tense: 'pretérito perfeito',
      answers: ['ouviram'],
    },
    {
      sentence: 'Você e eu {blank} a frase corretamente.',
      verb: 'ouvir',
      tense: 'pretérito perfeito',
      answers: ['ouvimos'],
    },
    {
      sentence: 'Ana {blank} a música que você recomendou.',
      verb: 'ouvir',
      tense: 'pretérito perfeito',
      answers: ['ouviu'],
    },
    {
      sentence: 'Nós {blank} o barulho na sala ao lado.',
      verb: 'ouvir',
      tense: 'pretérito perfeito',
      answers: ['ouvimos'],
    },
    {
      sentence: 'Eu {blank} a música nova que você recomendou.',
      verb: 'ouvir',
      tense: 'futuro',
      answers: ['ouvirei', 'vou ouvir'],
    },
    {
      sentence: 'Ela {blank} atentamente as instruções do professor.',
      verb: 'ouvir',
      tense: 'futuro',
      answers: ['ouvirá', 'vai ouvir'],
    },
    {
      sentence: 'Nós {blank} as novidades no encontro de amanhã.',
      verb: 'ouvir',
      tense: 'futuro',
      answers: ['ouviremos', 'vamos ouvir'],
    },
    {
      sentence: 'Você {blank} um ótimo podcast na próxima semana.',
      verb: 'ouvir',
      tense: 'futuro',
      answers: ['ouvirá', 'vai ouvir'],
    },
    {
      sentence: 'Eles {blank} o novo álbum da banda que amam.',
      verb: 'ouvir',
      tense: 'futuro',
      answers: ['ouvirão', 'vão ouvir'],
    },
    {
      sentence: 'João {blank} as notícias que todos comentam.',
      verb: 'ouvir',
      tense: 'futuro',
      answers: ['ouvirá', 'vai ouvir'],
    },
    {
      sentence: 'Maria e eu {blank} a conferência online na sexta-feira.',
      verb: 'ouvir',
      tense: 'futuro',
      answers: ['ouviremos', 'vamos ouvir'],
    },
    {
      sentence: 'Vocês {blank} o que eu disse na última reunião?',
      verb: 'ouvir',
      tense: 'futuro',
      answers: ['ouvirão', 'vão ouvir'],
    },
    {
      sentence: 'Eu {blank} as explicações do professor com atenção.',
      verb: 'ouvir',
      tense: 'futuro',
      answers: ['ouvirei', 'vou ouvir'],
    },
    {
      sentence: 'Ela {blank} as melodias antes do show.',
      verb: 'ouvir',
      tense: 'futuro',
      answers: ['ouvirá', 'vai ouvir'],
    },
  ],
};
