import { ProblemList } from '../Problems';

export const pegar: ProblemList = {
  verb: 'pegar',
  problems: [
    {
      sentence: 'Eu {blank} o ônibus todos os dias.',
      verb: 'pegar',
      tense: 'presente',
      answers: ['pego'],
    },
    {
      sentence: 'Ela {blank} um livro interessante na biblioteca.',
      verb: 'pegar',
      tense: 'presente',
      answers: ['pega'],
    },
    {
      sentence: 'Nós {blank} carona com nossos amigos frequentemente.',
      verb: 'pegar',
      tense: 'presente',
      answers: ['pegamos'],
    },
    {
      sentence: 'Vocês {blank} sempre as melhores ofertas.',
      verb: 'pegar',
      tense: 'presente',
      answers: ['pegam'],
    },
    {
      sentence: 'João {blank} o ônibus das 8 horas todas as manhãs.',
      verb: 'pegar',
      tense: 'presente',
      answers: ['pega'],
    },
    {
      sentence: 'Maria e eu {blank} emprestados os materiais.',
      verb: 'pegar',
      tense: 'presente',
      answers: ['pegamos'],
    },
    {
      sentence: 'Você {blank} as chaves na mesa da cozinha?',
      verb: 'pegar',
      tense: 'presente',
      answers: ['pega'],
    },
    {
      sentence: 'Eles {blank} sempre carona na volta da escola.',
      verb: 'pegar',
      tense: 'presente',
      answers: ['pegam'],
    },
    {
      sentence: 'Carlos {blank} um café toda manhã antes de trabalhar.',
      verb: 'pegar',
      tense: 'presente',
      answers: ['pega'],
    },
    {
      sentence: 'As meninas {blank} a linha de metrô para chegar ao centro.',
      verb: 'pegar',
      tense: 'presente',
      answers: ['pegam'],
    },
    {
      sentence: 'Eu {blank} o livro que você me pediu.',
      verb: 'pegar',
      tense: 'pretérito perfeito',
      answers: ['peguei'],
    },
    {
      sentence: 'Ela {blank} o ônibus na hora certa.',
      verb: 'pegar',
      tense: 'pretérito perfeito',
      answers: ['pegou'],
    },
    {
      sentence: 'Nós {blank} várias informações úteis na reunião.',
      verb: 'pegar',
      tense: 'pretérito perfeito',
      answers: ['pegamos'],
    },
    {
      sentence: 'Você {blank} o melhor assento no cinema.',
      verb: 'pegar',
      tense: 'pretérito perfeito',
      answers: ['pegou'],
    },
    {
      sentence: 'Eles {blank} as malas antes de viajar.',
      verb: 'pegar',
      tense: 'pretérito perfeito',
      answers: ['pegaram'],
    },
    {
      sentence: 'Maria {blank} um copo d’água ao acordar.',
      verb: 'pegar',
      tense: 'pretérito perfeito',
      answers: ['pegou'],
    },
    {
      sentence: 'João e eu {blank} muita chuva durante a viagem.',
      verb: 'pegar',
      tense: 'pretérito perfeito',
      answers: ['pegamos'],
    },
    {
      sentence: 'Vocês {blank} excelentes notas no exame.',
      verb: 'pegar',
      tense: 'pretérito perfeito',
      answers: ['pegaram'],
    },
    {
      sentence: 'A equipe {blank} a liderança do campeonato.',
      verb: 'pegar',
      tense: 'pretérito perfeito',
      answers: ['pegou'],
    },
    {
      sentence: 'Ela {blank} o primeiro lugar na competição.',
      verb: 'pegar',
      tense: 'pretérito perfeito',
      answers: ['pegou'],
    },
    {
      sentence: 'Eu {blank} o carro na oficina amanhã.',
      verb: 'pegar',
      tense: 'futuro',
      answers: ['pegarei', 'vou pegar'],
    },
    {
      sentence: 'Ela {blank} as chaves da casa na próxima semana.',
      verb: 'pegar',
      tense: 'futuro',
      answers: ['pegará', 'vai pegar'],
    },
    {
      sentence: 'Nós {blank} os livros na biblioteca na [quinta-feira].',
      verb: 'pegar',
      tense: 'futuro',
      answers: ['pegaremos', 'vamos pegar'],
    },
    {
      sentence: 'Vocês {blank} os ingredientes para a receita amanhã.',
      verb: 'pegar',
      tense: 'futuro',
      answers: ['pegarão', 'vão pegar'],
    },
    {
      sentence: 'Carlos {blank} o ônibus das 8 horas na segunda-feira.',
      verb: 'pegar',
      tense: 'futuro',
      answers: ['pegará', 'vai pegar'],
    },
    {
      sentence: 'Você {blank} muita coisa nova no curso no próximo mês.',
      verb: 'pegar',
      tense: 'futuro',
      answers: ['pegará', 'vai pegar'],
    },
    {
      sentence: 'Nós {blank} algumas dicas valiosas durante a palestra.',
      verb: 'pegar',
      tense: 'futuro',
      answers: ['pegaremos', 'vamos pegar'],
    },
    {
      sentence: 'Ela e eu {blank} um atalho para chegar mais rápido.',
      verb: 'pegar',
      tense: 'futuro',
      answers: ['pegaremos', 'vamos pegar'],
    },
    {
      sentence: 'João {blank} um bom emprego depois da faculdade.',
      verb: 'pegar',
      tense: 'futuro',
      answers: ['pegará', 'vai pegar'],
    },
    {
      sentence: 'Vocês {blank} as melhores cadeiras para o show.',
      verb: 'pegar',
      tense: 'futuro',
      answers: ['pegarão', 'vão pegar'],
    },
  ],
};
