import { ProblemList } from '../Problems';

export const pensar: ProblemList = {
  verb: 'pensar',
  problems: [
    {
      sentence: 'Eu {blank} frequentemente sobre o futuro.',
      verb: 'pensar',
      tense: 'presente',
      answers: ['penso'],
    },
    {
      sentence: 'Ela {blank} que devemos sair mais cedo.',
      verb: 'pensar',
      tense: 'presente',
      answers: ['pensa'],
    },
    {
      sentence: 'Nós {blank} nas opções disponíveis.',
      verb: 'pensar',
      tense: 'presente',
      answers: ['pensamos'],
    },
    {
      sentence: 'Você {blank} que o projeto é importante?',
      verb: 'pensar',
      tense: 'presente',
      answers: ['pensa'],
    },
    {
      sentence: 'Eles {blank} em como melhorar a equipe.',
      verb: 'pensar',
      tense: 'presente',
      answers: ['pensam'],
    },
    {
      sentence: 'Maria {blank} na melhor solução para o problema.',
      verb: 'pensar',
      tense: 'presente',
      answers: ['pensa'],
    },
    {
      sentence: 'João e eu {blank} que precisamos de mais tempo.',
      verb: 'pensar',
      tense: 'presente',
      answers: ['pensamos'],
    },
    {
      sentence: 'Ana {blank} em voltar a estudar.',
      verb: 'pensar',
      tense: 'presente',
      answers: ['pensa'],
    },
    {
      sentence: 'Vocês {blank} em fazer uma viagem juntos.',
      verb: 'pensar',
      tense: 'presente',
      answers: ['pensam'],
    },
    {
      sentence: 'Tu {blank} que é uma boa ideia?',
      verb: 'pensar',
      tense: 'presente',
      answers: ['pensar'],
    },
    {
      sentence: 'Eu {blank} que era uma boa ideia.',
      verb: 'pensar',
      tense: 'pretérito perfeito',
      answers: ['pensei'],
    },
    {
      sentence: 'Ela {blank} muito antes de tomar a decisão.',
      verb: 'pensar',
      tense: 'pretérito perfeito',
      answers: ['pensou'],
    },
    {
      sentence: 'Nós {blank} na estratégia correta para o projeto.',
      verb: 'pensar',
      tense: 'pretérito perfeito',
      answers: ['pensamos'],
    },
    {
      sentence: 'Você {blank} sobre o que falou ontem.',
      verb: 'pensar',
      tense: 'pretérito perfeito',
      answers: ['pensou'],
    },
    {
      sentence: 'Eles {blank} nas consequências de suas ações.',
      verb: 'pensar',
      tense: 'pretérito perfeito',
      answers: ['pensaram'],
    },
    {
      sentence: 'Maria {blank} em viajar nas férias.',
      verb: 'pensar',
      tense: 'pretérito perfeito',
      answers: ['pensou'],
    },
    {
      sentence: 'João e eu {blank} sobre a festa de aniversário.',
      verb: 'pensar',
      tense: 'pretérito perfeito',
      answers: ['pensamos'],
    },
    {
      sentence: 'Você e Ana {blank} que era uma boa escolha.',
      verb: 'pensar',
      tense: 'pretérito perfeito',
      answers: ['pensaram'],
    },
    {
      sentence: 'O professor {blank} em como motivar os alunos.',
      verb: 'pensar',
      tense: 'pretérito perfeito',
      answers: ['pensou'],
    },
    {
      sentence: 'Nós todos {blank} na possibilidade de um acampamento.',
      verb: 'pensar',
      tense: 'pretérito perfeito',
      answers: ['pensamos'],
    },
    {
      sentence: 'Eu {blank} em como vamos organizar o projeto.',
      verb: 'pensar',
      tense: 'futuro',
      answers: ['pensarei', 'vou pensar'],
    },
    {
      sentence: 'Você {blank} nas soluções para os problemas.',
      verb: 'pensar',
      tense: 'futuro',
      answers: ['pensará', 'vai pensar'],
    },
    {
      sentence: 'Eles {blank} juntos sobre a viagem nas próximas semanas.',
      verb: 'pensar',
      tense: 'futuro',
      answers: ['pensarão', 'vão pensar'],
    },
    {
      sentence: 'Ana e eu {blank} na estratégia para o próximo ano.',
      verb: 'pensar',
      tense: 'futuro',
      answers: ['pensaremos', 'vamos pensar'],
    },
    {
      sentence: 'Ela {blank} em como pode melhorar seu desempenho.',
      verb: 'pensar',
      tense: 'futuro',
      answers: ['pensará', 'vai pensar'],
    },
    {
      sentence: 'Nós {blank} em novas ideias para a apresentação.',
      verb: 'pensar',
      tense: 'futuro',
      answers: ['pensaremos', 'vamos pensar'],
    },
    {
      sentence: 'Você e eu {blank} em um bom plano para o evento.',
      verb: 'pensar',
      tense: 'futuro',
      answers: ['pensaremos', 'vamos pensar'],
    },
    {
      sentence: 'Eles {blank} na importância da colaboração.',
      verb: 'pensar',
      tense: 'futuro',
      answers: ['pensarão', 'vão pensar'],
    },
    {
      sentence: 'Maria {blank} em um jeito de economizar mais.',
      verb: 'pensar',
      tense: 'futuro',
      answers: ['pensará', 'vai pensar'],
    },
    {
      sentence: 'Vocês {blank} em como vão se preparar para o exame.',
      verb: 'pensar',
      tense: 'futuro',
      answers: ['pensarão', 'vão pensar'],
    },
  ],
};
