import { ProblemList } from '../Problems';

export const perder: ProblemList = {
  verb: 'perder',
  problems: [
    {
      sentence: 'Eu {blank} frequentemente a noção de tempo.',
      verb: 'perder',
      tense: 'presente',
      answers: ['perco'],
    },
    {
      sentence: 'Você {blank} a chance de viajar este ano.',
      verb: 'perder',
      tense: 'presente',
      answers: ['perde'],
    },
    {
      sentence: 'Ela {blank} sempre as chaves em casa.',
      verb: 'perder',
      tense: 'presente',
      answers: ['perde'],
    },
    {
      sentence: 'Nós {blank} a paciência com a demora.',
      verb: 'perder',
      tense: 'presente',
      answers: ['perdemos'],
    },
    {
      sentence: 'Eles {blank} o rumo durante a caminhada.',
      verb: 'perder',
      tense: 'presente',
      answers: ['perdem'],
    },
    {
      sentence: 'Você e eu {blank} o interesse na conversa.',
      verb: 'perder',
      tense: 'presente',
      answers: ['perdemos'],
    },
    {
      sentence: 'Maria {blank} a luta para se concentrar.',
      verb: 'perder',
      tense: 'presente',
      answers: ['perde'],
    },
    {
      sentence: 'João {blank} a motivação durante os estudos.',
      verb: 'perder',
      tense: 'presente',
      answers: ['perde'],
    },
    {
      sentence: 'Nós {blank} a esperança no futuro.',
      verb: 'perder',
      tense: 'presente',
      answers: ['perdemos'],
    },
    {
      sentence: 'As crianças {blank} a brincadeira na chuva.',
      verb: 'perder',
      tense: 'presente',
      answers: ['perdem'],
    },
    {
      sentence: 'Eu {blank} meu celular ontem à noite.',
      verb: 'perder',
      tense: 'pretérito perfeito',
      answers: ['perdi'],
    },
    {
      sentence: 'Você {blank} a chave do carro na festa.',
      verb: 'perder',
      tense: 'pretérito perfeito',
      answers: ['perdeu'],
    },
    {
      sentence: 'Ela {blank} o ônibus na manhã passada.',
      verb: 'perder',
      tense: 'pretérito perfeito',
      answers: ['perdeu'],
    },
    {
      sentence: 'Nós {blank} a oportunidade de fazer o curso.',
      verb: 'perder',
      tense: 'pretérito perfeito',
      answers: ['perdemos'],
    },
    {
      sentence: 'Eles {blank} a conta do restaurante.',
      verb: 'perder',
      tense: 'pretérito perfeito',
      answers: ['perderam'],
    },
    {
      sentence: 'Carlos {blank} o acesso à plataforma.',
      verb: 'perder',
      tense: 'pretérito perfeito',
      answers: ['perdeu'],
    },
    {
      sentence: 'Você e eu {blank} o livro que emprestamos.',
      verb: 'perder',
      tense: 'pretérito perfeito',
      answers: ['perdemos'],
    },
    {
      sentence: 'Maria {blank} o emprego que tanto gostava.',
      verb: 'perder',
      tense: 'pretérito perfeito',
      answers: ['perdeu'],
    },
    {
      sentence: 'Meus amigos {blank} a chance de viajar juntos.',
      verb: 'perder',
      tense: 'pretérito perfeito',
      answers: ['perderam'],
    },
    {
      sentence: 'Você {blank} a lembrança do evento especial.',
      verb: 'perder',
      tense: 'pretérito perfeito',
      answers: ['perdeu'],
    },
    {
      sentence: 'Eu {blank} o meu celular durante a viagem.',
      verb: 'perder',
      tense: 'futuro',
      answers: ['perderei', 'vou perder'],
    },
    {
      sentence: 'Ela {blank} muitos objetos importantes se não tomar cuidado.',
      verb: 'perder',
      tense: 'futuro',
      answers: ['perderá', 'vai perder'],
    },
    {
      sentence: 'Nós {blank} o jogo se não jogarmos bem.',
      verb: 'perder',
      tense: 'futuro',
      answers: ['perderemos', 'vamos perder'],
    },
    {
      sentence: 'Vocês {blank} os prazos se não se organizarem.',
      verb: 'perder',
      tense: 'futuro',
      answers: ['perderão', 'vão perder'],
    },
    {
      sentence: 'Eu {blank} muitas oportunidades se não me dedicar.',
      verb: 'perder',
      tense: 'futuro',
      answers: ['perderei', 'vou perder'],
    },
    {
      sentence: 'Eles {blank} a partida amanhã se não treinar.',
      verb: 'perder',
      tense: 'futuro',
      answers: ['perderão', 'vão perder'],
    },
    {
      sentence: 'Você {blank} o endereço se não prestar atenção.',
      verb: 'perder',
      tense: 'futuro',
      answers: ['perderá', 'vai perder'],
    },
    {
      sentence: 'Nós {blank} chance de ganhar se não formos estratégicos.',
      verb: 'perder',
      tense: 'futuro',
      answers: ['perderemos', 'vamos perder'],
    },
    {
      sentence: 'Ana e Carlos {blank} o ônibus se não se apressarem.',
      verb: 'perder',
      tense: 'futuro',
      answers: ['perderão', 'vão perder'],
    },
    {
      sentence: 'Se você não cuidar do seu livro, {blank} ele.',
      verb: 'perder',
      tense: 'futuro',
      answers: ['perderá', 'vai perder'],
    },
  ],
};
