import { ProblemList } from '../Problems';

export const planejar: ProblemList = {
  verb: 'planejar',
  problems: [
    {
      sentence: 'Eu {blank} a apresentação para a reunião na próxima semana.',
      verb: 'planejar',
      tense: 'futuro',
      answers: ['planejarei', 'vou planejar'],
    },
    {
      sentence: 'Nós {blank} um evento especial para o aniversário dela.',
      verb: 'planejar',
      tense: 'futuro',
      answers: ['planejaremos', 'vamos planejar'],
    },
    {
      sentence: 'Ela {blank} todos os detalhes da festa de formatura.',
      verb: 'planejar',
      tense: 'futuro',
      answers: ['planejará', 'vai planejar'],
    },
    {
      sentence: 'Vocês {blank} uma viagem incrível para o próximo feriado.',
      verb: 'planejar',
      tense: 'futuro',
      answers: ['planejarão', 'vão planejar'],
    },
    {
      sentence: 'Eu e você {blank} nosso projeto de trabalho em grupo.',
      verb: 'planejar',
      tense: 'futuro',
      answers: ['planejaremos', 'vamos planejar'],
    },
    {
      sentence: 'Eles {blank} a construção da nova escola até o mês que vem.',
      verb: 'planejar',
      tense: 'futuro',
      answers: ['planejarão', 'vão planejar'],
    },
    {
      sentence: 'João {blank} a festa surpresa para a Maria.',
      verb: 'planejar',
      tense: 'futuro',
      answers: ['planejará', 'vai planejar'],
    },
    {
      sentence: 'Ana e eu {blank} uma nova estratégia para o projeto.',
      verb: 'planejar',
      tense: 'futuro',
      answers: ['planejaremos', 'vamos planejar'],
    },
    {
      sentence: 'Vocês {blank} uma reunião na próxima sexta-feira.',
      verb: 'planejar',
      tense: 'futuro',
      answers: ['planejarão', 'vão planejar'],
    },
    {
      sentence: 'Ele {blank} suas próximas férias durante o verão.',
      verb: 'planejar',
      tense: 'futuro',
      answers: ['planejará', 'vai planejar'],
    },
    {
      sentence: 'Eu {blank} a viagem para o próximo mês.',
      verb: 'planejar',
      tense: 'presente',
      answers: ['planejo'],
    },
    {
      sentence: 'Ela {blank} a festa de aniversário do João.',
      verb: 'planejar',
      tense: 'presente',
      answers: ['planeja'],
    },
    {
      sentence: 'Nós {blank} as atividades do projeto juntos.',
      verb: 'planejar',
      tense: 'presente',
      answers: ['planejamos'],
    },
    {
      sentence: 'Você {blank} a apresentação para a reunião.',
      verb: 'planejar',
      tense: 'presente',
      answers: ['planeja'],
    },
    {
      sentence: 'Eles {blank} um encontro para discutir os planos.',
      verb: 'planejar',
      tense: 'presente',
      answers: ['planejam'],
    },
    {
      sentence: 'Maria e eu {blank} a viagem de férias na praia.',
      verb: 'planejar',
      tense: 'presente',
      answers: ['planejamos'],
    },
    {
      sentence: 'Você e sua irmã {blank} um surpresa para a mãe.',
      verb: 'planejar',
      tense: 'presente',
      answers: ['planejam'],
    },
    {
      sentence: 'O professor {blank} as aulas para o próximo semestre.',
      verb: 'planejar',
      tense: 'presente',
      answers: ['planeja'],
    },
    {
      sentence: 'Os alunos {blank} um projeto em grupo para a escola.',
      verb: 'planejar',
      tense: 'presente',
      answers: ['planejam'],
    },
    {
      sentence: 'Carlos {blank} o evento com bastante antecedência.',
      verb: 'planejar',
      tense: 'presente',
      answers: ['planeja'],
    },
    {
      sentence: 'Eu {blank} todos os detalhes do evento.',
      verb: 'planejar',
      tense: 'pretérito perfeito',
      answers: ['planejei'],
    },
    {
      sentence: 'Ela {blank} a festa surpresa para o amigo.',
      verb: 'planejar',
      tense: 'pretérito perfeito',
      answers: ['planejou'],
    },
    {
      sentence: 'Nós {blank} uma viagem incrível para as férias.',
      verb: 'planejar',
      tense: 'pretérito perfeito',
      answers: ['planejamos'],
    },
    {
      sentence: 'Vocês {blank} o lançamento do novo produto.',
      verb: 'planejar',
      tense: 'pretérito perfeito',
      answers: ['planejaram'],
    },
    {
      sentence: 'João {blank} a formação do time de futebol.',
      verb: 'planejar',
      tense: 'pretérito perfeito',
      answers: ['planejou'],
    },
    {
      sentence: 'Você {blank} todos os passos do projeto.',
      verb: 'planejar',
      tense: 'pretérito perfeito',
      answers: ['planejou'],
    },
    {
      sentence: 'As meninas {blank} uma surpresa para a professora.',
      verb: 'planejar',
      tense: 'pretérito perfeito',
      answers: ['planejaram'],
    },
    {
      sentence: 'Meu pai {blank} as despesas da casa cuidadosamente.',
      verb: 'planejar',
      tense: 'pretérito perfeito',
      answers: ['planejou'],
    },
    {
      sentence: 'Nós {blank} o roteiro da nossa viagem ao Brasil.',
      verb: 'planejar',
      tense: 'pretérito perfeito',
      answers: ['planejamos'],
    },
    {
      sentence: 'Ela e seu irmão {blank} o aniversário do pai.',
      verb: 'planejar',
      tense: 'pretérito perfeito',
      answers: ['planejaram'],
    },
  ],
};
