import { ProblemList } from '../Problems';

export const poder: ProblemList = {
  verb: 'poder',
  problems: [
    {
      sentence: 'Eu {blank} ajudar com o projeto amanhã.',
      verb: 'poder',
      tense: 'futuro',
      answers: ['poderei', 'vou poder'],
    },
    {
      sentence: 'Você {blank} concluir a tarefa até sexta-feira.',
      verb: 'poder',
      tense: 'futuro',
      answers: ['poderá', 'vai poder'],
    },
    {
      sentence: 'Ela {blank} participar da reunião na próxima semana.',
      verb: 'poder',
      tense: 'futuro',
      answers: ['poderá', 'vai poder'],
    },
    {
      sentence: 'Nós {blank} ir ao cinema no sábado.',
      verb: 'poder',
      tense: 'futuro',
      answers: ['poderemos', 'vamos poder'],
    },
    {
      sentence: 'Vocês {blank} apresentar as ideias no próximo encontro.',
      verb: 'poder',
      tense: 'futuro',
      answers: ['poderão', 'vão poder'],
    },
    {
      sentence: 'João {blank} resolver o problema até o final do dia.',
      verb: 'poder',
      tense: 'futuro',
      answers: ['poderá', 'vai poder'],
    },
    {
      sentence: 'Maria e eu {blank} visitar a exposição na próxima semana.',
      verb: 'poder',
      tense: 'futuro',
      answers: ['poderemos', 'vamos poder'],
    },
    {
      sentence: 'Eles {blank} viajar nas férias de julho.',
      verb: 'poder',
      tense: 'futuro',
      answers: ['poderão', 'vão poder'],
    },
    {
      sentence: 'Você e eu {blank} encontrar uma solução para isso.',
      verb: 'poder',
      tense: 'futuro',
      answers: ['poderemos', 'vamos poder'],
    },
    {
      sentence: 'Ana {blank} ajudar na organização do evento.',
      verb: 'poder',
      tense: 'futuro',
      answers: ['poderá', 'vai poder'],
    },
    {
      sentence: 'Eu {blank} ir à festa hoje à noite.',
      verb: 'poder',
      tense: 'presente',
      answers: ['posso'],
    },
    {
      sentence: 'Ela {blank} terminar o trabalho a tempo.',
      verb: 'poder',
      tense: 'presente',
      answers: ['pode'],
    },
    {
      sentence: 'Nós {blank} ajudar com a mudança amanhã.',
      verb: 'poder',
      tense: 'presente',
      answers: ['podemos'],
    },
    {
      sentence: 'Você {blank} fazer as compras hoje?',
      verb: 'poder',
      tense: 'presente',
      answers: ['pode'],
    },
    {
      sentence: 'Pedro e Maria {blank} assistir ao filme juntos.',
      verb: 'poder',
      tense: 'presente',
      answers: ['podem'],
    },
    {
      sentence: 'Eu e você {blank} ir à praia no sábado.',
      verb: 'poder',
      tense: 'presente',
      answers: ['podemos'],
    },
    {
      sentence: 'Ela {blank} falar três idiomas.',
      verb: 'poder',
      tense: 'presente',
      answers: ['pode'],
    },
    {
      sentence: 'Eles {blank} jogar futebol amanhã.',
      verb: 'poder',
      tense: 'presente',
      answers: ['podem'],
    },
    {
      sentence: 'Lucas {blank} resolver o problema sozinho.',
      verb: 'poder',
      tense: 'presente',
      answers: ['pode'],
    },
    {
      sentence: 'Nós {blank} encontrar um lugar melhor para trabalhar.',
      verb: 'poder',
      tense: 'presente',
      answers: ['podemos'],
    },
    {
      sentence: 'Eu {blank} ajudar meus amigos com o projeto.',
      verb: 'poder',
      tense: 'pretérito perfeito',
      answers: ['pude'],
    },
    {
      sentence: 'Ela {blank} resolver o problema sozinha.',
      verb: 'poder',
      tense: 'pretérito perfeito',
      answers: ['pôde'],
    },
    {
      sentence: 'Nós {blank} ir ao cinema ontem à noite.',
      verb: 'poder',
      tense: 'pretérito perfeito',
      answers: ['pudemos'],
    },
    {
      sentence: 'Você {blank} participar da reunião.',
      verb: 'poder',
      tense: 'pretérito perfeito',
      answers: ['pôde'],
    },
    {
      sentence: 'Eles {blank} finalizar o projeto a tempo.',
      verb: 'poder',
      tense: 'pretérito perfeito',
      answers: ['puderam'],
    },
    {
      sentence: 'Maria {blank} encontrar o caminho certo.',
      verb: 'poder',
      tense: 'pretérito perfeito',
      answers: ['pôde'],
    },
    {
      sentence: 'João {blank} comprar ingressos para o show.',
      verb: 'poder',
      tense: 'pretérito perfeito',
      answers: ['pôde'],
    },
    {
      sentence: 'Nós {blank} visitar nossa avó no fim de semana passado.',
      verb: 'poder',
      tense: 'pretérito perfeito',
      answers: ['pudemos'],
    },
    {
      sentence: 'Você e eu {blank} assistir ao filme juntos.',
      verb: 'poder',
      tense: 'pretérito perfeito',
      answers: ['pudemos'],
    },
    {
      sentence: 'As meninas {blank} completar a tarefa antes do prazo.',
      verb: 'poder',
      tense: 'pretérito perfeito',
      answers: ['puderam'],
    },
  ],
};
