import { ProblemList } from '../Problems';

export const possuir: ProblemList = {
  verb: 'possuir',
  problems: [
    {
      sentence: 'Eu {blank} um carro novo no próximo mês.',
      verb: 'possuir',
      tense: 'futuro',
      answers: ['possuirei', 'vou possuir'],
    },
    {
      sentence: 'Ela {blank} um apartamento na praia em breve.',
      verb: 'possuir',
      tense: 'futuro',
      answers: ['possuirá', 'vai possuir'],
    },
    {
      sentence: 'Nós {blank} um novo projeto para o escritório no próximo ano.',
      verb: 'possuir',
      tense: 'futuro',
      answers: ['possuremos', 'vamos possuir'],
    },
    {
      sentence: 'Você {blank} muitos desafios pela frente.',
      verb: 'possuir',
      tense: 'futuro',
      answers: ['possuirá', 'vai possuir'],
    },
    {
      sentence: 'Eles {blank} mais conhecimento após o curso.',
      verb: 'possuir',
      tense: 'futuro',
      answers: ['possuirão', 'vão possuir'],
    },
    {
      sentence: 'João {blank} um bom emprego no futuro.',
      verb: 'possuir',
      tense: 'futuro',
      answers: ['possuirá', 'vai possuir'],
    },
    {
      sentence: 'Nós {blank} todas as informações necessárias amanhã.',
      verb: 'possuir',
      tense: 'futuro',
      answers: ['possuremos', 'vamos possuir'],
    },
    {
      sentence: 'Você e eu {blank} muita sorte no próximo sorteio.',
      verb: 'possuir',
      tense: 'futuro',
      answers: ['possiremos', 'vamos possuir'],
    },
    {
      sentence: 'As crianças {blank} novos brinquedos no Natal.',
      verb: 'possuir',
      tense: 'futuro',
      answers: ['possuirão', 'vão possuir'],
    },
    {
      sentence: 'Ela e você {blank} um ótimo relacionamento no futuro.',
      verb: 'possuir',
      tense: 'futuro',
      answers: ['possuirão', 'vão possuir'],
    },
    {
      sentence: 'Eu {blank} um carro novo.',
      verb: 'possuir',
      tense: 'presente',
      answers: ['possuo'],
    },
    {
      sentence: 'Ela {blank} muitos livros interessantes.',
      verb: 'possuir',
      tense: 'presente',
      answers: ['possui'],
    },
    {
      sentence: 'Nós {blank} uma casa na praia.',
      verb: 'possuir',
      tense: 'presente',
      answers: ['possuímos'],
    },
    {
      sentence: 'Você {blank} um talento especial para a música.',
      verb: 'possuir',
      tense: 'presente',
      answers: ['possui'],
    },
    {
      sentence: 'Eles {blank} um time de futebol.',
      verb: 'possuir',
      tense: 'presente',
      answers: ['possuem'],
    },
    {
      sentence: 'A Mariana {blank} uma coleção de selos.',
      verb: 'possuir',
      tense: 'presente',
      answers: ['possui'],
    },
    {
      sentence: 'Os alunos {blank} um interesse crescente por ciência.',
      verb: 'possuir',
      tense: 'presente',
      answers: ['possuem'],
    },
    {
      sentence: 'Eu e você {blank} um bom entendimento sobre o projeto.',
      verb: 'possuir',
      tense: 'presente',
      answers: ['possuímos'],
    },
    {
      sentence: 'O Henrique {blank} uma vasta experiência na área.',
      verb: 'possuir',
      tense: 'presente',
      answers: ['possui'],
    },
    {
      sentence: 'As crianças {blank} muitas idéias criativas.',
      verb: 'possuir',
      tense: 'presente',
      answers: ['possuem'],
    },
    {
      sentence: 'Eu {blank} um carro novo no ano passado.',
      verb: 'possuir',
      tense: 'pretérito perfeito',
      answers: ['possui'],
    },
    {
      sentence: 'Ela {blank} uma casa na praia.',
      verb: 'possuir',
      tense: 'pretérito perfeito',
      answers: ['possuiu'],
    },
    {
      sentence: 'Nós {blank} muitas experiências incríveis em nossa viagem.',
      verb: 'possuir',
      tense: 'pretérito perfeito',
      answers: ['possuímos'],
    },
    {
      sentence: 'Você {blank} um cachorro quando era criança.',
      verb: 'possuir',
      tense: 'pretérito perfeito',
      answers: ['possuiu'],
    },
    {
      sentence: 'Eles {blank} uma coleção de selos raros.',
      verb: 'possuir',
      tense: 'pretérito perfeito',
      answers: ['possuiram'],
    },
    {
      sentence: 'Carlos {blank} um apartamento no centro da cidade.',
      verb: 'possuir',
      tense: 'pretérito perfeito',
      answers: ['possuiu'],
    },
    {
      sentence: 'Maria e Joana {blank} muitos livros na estante.',
      verb: 'possuir',
      tense: 'pretérito perfeito',
      answers: ['possuiram'],
    },
    {
      sentence: 'Você e eu {blank} um projeto muito interessante.',
      verb: 'possuir',
      tense: 'pretérito perfeito',
      answers: ['possuímos'],
    },
    {
      sentence: 'Os alunos {blank} um bom desempenho no teste.',
      verb: 'possuir',
      tense: 'pretérito perfeito',
      answers: ['possuiram'],
    },
    {
      sentence: 'Meu irmão {blank} um ótimo emprego no ano passado.',
      verb: 'possuir',
      tense: 'pretérito perfeito',
      answers: ['possuiu'],
    },
  ],
};
