import { ProblemList } from '../Problems';

export const precisar: ProblemList = {
  verb: 'precisar',
  problems: [
    {
      sentence: 'Eu {blank} de ajuda para terminar o projeto.',
      verb: 'precisar',
      tense: 'futuro',
      answers: ['precisarei', 'vou precisar'],
    },
    {
      sentence: 'Ela {blank} de um tempo para estudar melhor.',
      verb: 'precisar',
      tense: 'futuro',
      answers: ['precisará', 'vai precisar'],
    },
    {
      sentence: 'Nós {blank} de mais recursos para a pesquisa.',
      verb: 'precisar',
      tense: 'futuro',
      answers: ['precisaremos', 'vamos precisar'],
    },
    {
      sentence: 'Você {blank} de mais informações sobre o evento.',
      verb: 'precisar',
      tense: 'futuro',
      answers: ['precisará', 'vai precisar'],
    },
    {
      sentence: 'Eles {blank} de apoio durante a mudança.',
      verb: 'precisar',
      tense: 'futuro',
      answers: ['precisarão', 'vão precisar'],
    },
    {
      sentence: 'Maria {blank} de férias assim que possível.',
      verb: 'precisar',
      tense: 'futuro',
      answers: ['precisará', 'vai precisar'],
    },
    {
      sentence: 'João e eu {blank} de uma resposta rápida.',
      verb: 'precisar',
      tense: 'futuro',
      answers: ['precisaremos', 'vamos precisar'],
    },
    {
      sentence: 'Vocês {blank} de verificar os horários de voos.',
      verb: 'precisar',
      tense: 'futuro',
      answers: ['precisarão', 'vão precisar'],
    },
    {
      sentence: 'A equipe {blank} de se reunir para discutir o plano.',
      verb: 'precisar',
      tense: 'futuro',
      answers: ['precisará', 'vai precisar'],
    },
    {
      sentence: 'Meu pai {blank} de ajuda com o carro.',
      verb: 'precisar',
      tense: 'futuro',
      answers: ['precisará', 'vai precisar'],
    },
    {
      sentence: 'Eu {blank} de um plano melhor para o projeto.',
      verb: 'precisar',
      tense: 'presente',
      answers: ['preciso'],
    },
    {
      sentence: 'Ela {blank} de ajuda para terminar a apresentação.',
      verb: 'precisar',
      tense: 'presente',
      answers: ['precisa'],
    },
    {
      sentence: 'Nós {blank} de mais tempo para finalizar o relatório.',
      verb: 'precisar',
      tense: 'presente',
      answers: ['precisamos'],
    },
    {
      sentence: 'Vocês {blank} se organizar melhor para os estudos.',
      verb: 'precisar',
      tense: 'presente',
      answers: ['precisam'],
    },
    {
      sentence: 'Ele {blank} de um novo par de sapatos.',
      verb: 'precisar',
      tense: 'presente',
      answers: ['precisa'],
    },
    {
      sentence: 'Você {blank} de informações adicionais sobre o curso.',
      verb: 'precisar',
      tense: 'presente',
      answers: ['precisa'],
    },
    {
      sentence: 'Ana {blank} de um carro novo para ir ao trabalho.',
      verb: 'precisar',
      tense: 'presente',
      answers: ['precisa'],
    },
    {
      sentence: 'Nós {blank} de um lugar tranquilo para estudar.',
      verb: 'precisar',
      tense: 'presente',
      answers: ['precisamos'],
    },
    {
      sentence: 'Você e eu {blank} de pensar em uma solução.',
      verb: 'precisar',
      tense: 'presente',
      answers: ['precisamos'],
    },
    {
      sentence: 'Marcos {blank} de apoio para sua nova ideia.',
      verb: 'precisar',
      tense: 'presente',
      answers: ['precisa'],
    },
    {
      sentence: 'Eu {blank} de ajuda para terminar o projeto.',
      verb: 'precisar',
      tense: 'pretérito perfeito',
      answers: ['precisei'],
    },
    {
      sentence: 'Ela {blank} muito da sua sabedoria para nos ajudar.',
      verb: 'precisar',
      tense: 'pretérito perfeito',
      answers: ['precisou'],
    },
    {
      sentence: 'Nós {blank} levar um lanche para a viagem.',
      verb: 'precisar',
      tense: 'pretérito perfeito',
      answers: ['precisamos'],
    },
    {
      sentence: 'Você {blank} de um carro para ir ao trabalho ontem.',
      verb: 'precisar',
      tense: 'pretérito perfeito',
      answers: ['precisou'],
    },
    {
      sentence: 'Eles {blank} de mais tempo para terminar a tarefa.',
      verb: 'precisar',
      tense: 'pretérito perfeito',
      answers: ['precisaram'],
    },
    {
      sentence: 'Maria {blank} de uma pausa após o almoço.',
      verb: 'precisar',
      tense: 'pretérito perfeito',
      answers: ['precisou'],
    },
    {
      sentence: 'Nós {blank} de novas informações para a pesquisa.',
      verb: 'precisar',
      tense: 'pretérito perfeito',
      answers: ['precisamos'],
    },
    {
      sentence: 'Você e eu {blank} encontrar um bom restaurante.',
      verb: 'precisar',
      tense: 'pretérito perfeito',
      answers: ['precisamos'],
    },
    {
      sentence: 'Paulo {blank} de muita paciência para lidar com a situação.',
      verb: 'precisar',
      tense: 'pretérito perfeito',
      answers: ['precisou'],
    },
    {
      sentence: 'Elas {blank} de apoio emocional durante o processo.',
      verb: 'precisar',
      tense: 'pretérito perfeito',
      answers: ['precisaram'],
    },
  ],
};
