import { ProblemList } from '../Problems';

export const preparar: ProblemList = {
  verb: 'preparar',
  problems: [
    {
      sentence: 'Eu {blank} tudo para a festa de aniversário.',
      verb: 'preparar',
      tense: 'pretérito perfeito',
      answers: ['preparei'],
    },
    {
      sentence: 'Ela {blank} um ótimo jantar para os amigos.',
      verb: 'preparar',
      tense: 'pretérito perfeito',
      answers: ['preparou'],
    },
    {
      sentence: 'Nós {blank} as malas para a viagem de férias.',
      verb: 'preparar',
      tense: 'pretérito perfeito',
      answers: ['preparamos'],
    },
    {
      sentence: 'Carlos e Ana {blank} a apresentação para a reunião.',
      verb: 'preparar',
      tense: 'pretérito perfeito',
      answers: ['prepararam'],
    },
    {
      sentence: 'Você {blank} o relatório final antes do prazo.',
      verb: 'preparar',
      tense: 'pretérito perfeito',
      answers: ['preparou'],
    },
    {
      sentence: 'Nós {blank} várias receitas novas para o almoço.',
      verb: 'preparar',
      tense: 'pretérito perfeito',
      answers: ['preparamos'],
    },
    {
      sentence: 'Ele {blank} o discurso para a cerimônia.',
      verb: 'preparar',
      tense: 'pretérito perfeito',
      answers: ['preparou'],
    },
    {
      sentence: 'Maria {blank} tudo muito bem para o evento.',
      verb: 'preparar',
      tense: 'pretérito perfeito',
      answers: ['preparou'],
    },
    {
      sentence: 'Vocês {blank} uma surpresa incrível para o professor.',
      verb: 'preparar',
      tense: 'pretérito perfeito',
      answers: ['prepararam'],
    },
    {
      sentence: 'Eu e você {blank} as informações necessárias para a pesquisa.',
      verb: 'preparar',
      tense: 'pretérito perfeito',
      answers: ['preparamos'],
    },
    {
      sentence: 'Eu {blank} o relatório para a reunião amanhã.',
      verb: 'preparar',
      tense: 'futuro',
      answers: ['prepararei', 'vou preparar'],
    },
    {
      sentence: 'Vocês {blank} o evento para o próximo mês.',
      verb: 'preparar',
      tense: 'futuro',
      answers: ['prepararão', 'vão preparar'],
    },
    {
      sentence: 'Ela {blank} o jantar especial para o aniversário.',
      verb: 'preparar',
      tense: 'futuro',
      answers: ['preparará', 'vai preparar'],
    },
    {
      sentence: 'Nós {blank} as apresentações para a conferência.',
      verb: 'preparar',
      tense: 'futuro',
      answers: ['prepararemos', 'vamos preparar'],
    },
    {
      sentence: 'Eles {blank} os materiais antes da aula.',
      verb: 'preparar',
      tense: 'futuro',
      answers: ['prepararão', 'vão preparar'],
    },
    {
      sentence: 'Você {blank} a festa surpresa para o amigo.',
      verb: 'preparar',
      tense: 'futuro',
      answers: ['preparará', 'vai preparar'],
    },
    {
      sentence: 'João {blank} a apresentação para o trabalho.',
      verb: 'preparar',
      tense: 'futuro',
      answers: ['preparará', 'vai preparar'],
    },
    {
      sentence: 'Nós {blank} o terreno para o novo projeto.',
      verb: 'preparar',
      tense: 'futuro',
      answers: ['prepararemos', 'vamos preparar'],
    },
    {
      sentence: 'Você e eu {blank} o almoço para os convidados.',
      verb: 'preparar',
      tense: 'futuro',
      answers: ['prepararemos', 'vamos preparar'],
    },
    {
      sentence: 'Elas {blank} os documentos para a reunião de amanhã.',
      verb: 'preparar',
      tense: 'futuro',
      answers: ['prepararão', 'vão preparar'],
    },
    {
      sentence: 'Eu {blank} o jantar para nós esta noite.',
      verb: 'preparar',
      tense: 'presente',
      answers: ['preparo'],
    },
    {
      sentence: 'Ela {blank} um relatório para a reunião semanal.',
      verb: 'preparar',
      tense: 'presente',
      answers: ['prepara'],
    },
    {
      sentence: 'Nós {blank} um evento especial para o aniversário dele.',
      verb: 'preparar',
      tense: 'presente',
      answers: ['preparamos'],
    },
    {
      sentence: 'Vocês {blank} a apresentação para o projeto de amanhã.',
      verb: 'preparar',
      tense: 'presente',
      answers: ['preparam'],
    },
    {
      sentence: 'Você {blank} os alunos para o teste final.',
      verb: 'preparar',
      tense: 'presente',
      answers: ['prepara'],
    },
    {
      sentence: 'Eles {blank} as malas para a viagem.',
      verb: 'preparar',
      tense: 'presente',
      answers: ['preparam'],
    },
    {
      sentence: 'João {blank} o café todas as manhãs.',
      verb: 'preparar',
      tense: 'presente',
      answers: ['prepara'],
    },
    {
      sentence: 'Maria e Carlos {blank} tudo para o casamento.',
      verb: 'preparar',
      tense: 'presente',
      answers: ['preparam'],
    },
    {
      sentence: 'Eu e você {blank} a equipe para o torneio.',
      verb: 'preparar',
      tense: 'presente',
      answers: ['prepararmos'],
    },
    {
      sentence: 'A professora {blank} os alunos para a competição.',
      verb: 'preparar',
      tense: 'presente',
      answers: ['prepara'],
    },
  ],
};
