import { ProblemList } from '../Problems';

export const querer: ProblemList = {
  verb: 'querer',
  problems: [
    {
      sentence: 'Eu {blank} viajar nas férias do ano que vem.',
      verb: 'querer',
      tense: 'futuro',
      answers: ['quero', 'vou querer'],
    },
    {
      sentence: 'Ela {blank} um novo emprego até o próximo mês.',
      verb: 'querer',
      tense: 'futuro',
      answers: ['quer', 'vai querer'],
    },
    {
      sentence: 'Nós {blank} assistir ao filme no fim de semana.',
      verb: 'querer',
      tense: 'futuro',
      answers: ['queremos', 'vamos querer'],
    },
    {
      sentence: 'Vocês {blank} fazer um passeio pela cidade amanhã.',
      verb: 'querer',
      tense: 'futuro',
      answers: ['querem', 'vão querer'],
    },
    {
      sentence: 'Ele {blank} comprar um carro novo em breve.',
      verb: 'querer',
      tense: 'futuro',
      answers: ['quer', 'vai querer'],
    },
    {
      sentence: 'Tu {blank} participar da reunião na próxima semana.',
      verb: 'querer',
      tense: 'futuro',
      answers: ['queres', 'vais querer'],
    },
    {
      sentence: 'Maria e José {blank} se encontrar para estudar amanhã.',
      verb: 'querer',
      tense: 'futuro',
      answers: ['querem', 'vão querer'],
    },
    {
      sentence: 'Eu e você {blank} aquela sobremesa deliciosa no jantar.',
      verb: 'querer',
      tense: 'futuro',
      answers: ['queremos', 'vamos querer'],
    },
    {
      sentence: 'As crianças {blank} brincar no parque no sábado.',
      verb: 'querer',
      tense: 'futuro',
      answers: ['querem', 'vão querer'],
    },
    {
      sentence: 'Você {blank} ajudar com os preparativos da festa.',
      verb: 'querer',
      tense: 'futuro',
      answers: ['quer', 'vai querer'],
    },
    {
      sentence: 'Eu {blank} viajar para o Brasil no próximo mês.',
      verb: 'querer',
      tense: 'presente',
      answers: ['quero'],
    },
    {
      sentence: 'Você {blank} uma nova roupa para a festa?',
      verb: 'querer',
      tense: 'presente',
      answers: ['quer'],
    },
    {
      sentence: 'Ela {blank} aprender a tocar violão.',
      verb: 'querer',
      tense: 'presente',
      answers: ['quer'],
    },
    {
      sentence: 'Nós {blank} ter um dia de folga na próxima semana.',
      verb: 'querer',
      tense: 'presente',
      answers: ['queremos'],
    },
    {
      sentence: 'Eles {blank} ir ao cinema hoje à noite.',
      verb: 'querer',
      tense: 'presente',
      answers: ['querem'],
    },
    {
      sentence: 'Pedro {blank} comprar um carro novo.',
      verb: 'querer',
      tense: 'presente',
      answers: ['quer'],
    },
    {
      sentence: 'Maria e João {blank} uma casa maior.',
      verb: 'querer',
      tense: 'presente',
      answers: ['querem'],
    },
    {
      sentence: 'Você e eu {blank} fazer uma viagem juntos.',
      verb: 'querer',
      tense: 'presente',
      answers: ['queremos'],
    },
    {
      sentence: 'Ela e eu {blank} participar do projeto.',
      verb: 'querer',
      tense: 'presente',
      answers: ['queremos'],
    },
    {
      sentence: 'Vocês {blank} assistir aquele novo filme.',
      verb: 'querer',
      tense: 'presente',
      answers: ['querem'],
    },
    {
      sentence: 'Eu {blank} um novo plano para o projeto.',
      verb: 'querer',
      tense: 'pretérito perfeito',
      answers: ['quis'],
    },
    {
      sentence: 'Ela {blank} ir ao cinema ontem à noite.',
      verb: 'querer',
      tense: 'pretérito perfeito',
      answers: ['quis'],
    },
    {
      sentence: 'Nós {blank} viajar nas férias passadas.',
      verb: 'querer',
      tense: 'pretérito perfeito',
      answers: ['quisemos'],
    },
    {
      sentence: 'Você {blank} mudar de emprego no ano passado.',
      verb: 'querer',
      tense: 'pretérito perfeito',
      answers: ['quis'],
    },
    {
      sentence: 'Eles {blank} comprar um carro novo recentemente.',
      verb: 'querer',
      tense: 'pretérito perfeito',
      answers: ['quiseram'],
    },
    {
      sentence: 'Amanda {blank} ajudar na organização do evento.',
      verb: 'querer',
      tense: 'pretérito perfeito',
      answers: ['quis'],
    },
    {
      sentence: 'Eu e você {blank} fazer uma surpresa para o João.',
      verb: 'querer',
      tense: 'pretérito perfeito',
      answers: ['quisemos'],
    },
    {
      sentence: 'Os alunos {blank} participar da competição.',
      verb: 'querer',
      tense: 'pretérito perfeito',
      answers: ['quiseram'],
    },
    {
      sentence: 'Ela e eu {blank} conhecer mais sobre a cultura.',
      verb: 'querer',
      tense: 'pretérito perfeito',
      answers: ['quisemos'],
    },
    {
      sentence: 'Você {blank} comer sobremesa antes do jantar.',
      verb: 'querer',
      tense: 'pretérito perfeito',
      answers: ['quis'],
    },
  ],
};
