import { ProblemList } from '../Problems';

export const regar: ProblemList = {
  verb: 'regar',
  problems: [
    {
      sentence: 'Eu {blank} as plantas antes de viajar.',
      verb: 'regar',
      tense: 'pretérito perfeito',
      answers: ['reguei'],
    },
    {
      sentence: 'Ela {blank} o jardim no fim de semana passado.',
      verb: 'regar',
      tense: 'pretérito perfeito',
      answers: ['regou'],
    },
    {
      sentence: 'Nós {blank} as flores para a festa de aniversário.',
      verb: 'regar',
      tense: 'pretérito perfeito',
      answers: ['regamos'],
    },
    {
      sentence: 'Você {blank} as verduras para o almoço ontem.',
      verb: 'regar',
      tense: 'pretérito perfeito',
      answers: ['regou'],
    },
    {
      sentence: 'Eles {blank} as plantas que estavam secas.',
      verb: 'regar',
      tense: 'pretérito perfeito',
      answers: ['regaram'],
    },
    {
      sentence: 'João {blank} os bonsai com muito cuidado.',
      verb: 'regar',
      tense: 'pretérito perfeito',
      answers: ['regou'],
    },
    {
      sentence: 'Maria e eu {blank} os cactos ontem à tarde.',
      verb: 'regar',
      tense: 'pretérito perfeito',
      answers: ['regamos'],
    },
    {
      sentence: 'Vocês {blank} os vasos na varanda antes da chuva.',
      verb: 'regar',
      tense: 'pretérito perfeito',
      answers: ['regaram'],
    },
    {
      sentence: 'Ana {blank} as suculentas na semana passada.',
      verb: 'regar',
      tense: 'pretérito perfeito',
      answers: ['regou'],
    },
    {
      sentence: 'Eles {blank} a grama do quintal com muito zelo.',
      verb: 'regar',
      tense: 'pretérito perfeito',
      answers: ['regaram'],
    },
    {
      sentence: 'Eu {blank} as plantas no próximo fim de semana.',
      verb: 'regar',
      tense: 'futuro',
      answers: ['regarei', 'vou regar'],
    },
    {
      sentence: 'Ela {blank} o jardim amanhã de manhã.',
      verb: 'regar',
      tense: 'futuro',
      answers: ['regará', 'vai regar'],
    },
    {
      sentence: 'Nós {blank} as flores na semana que vem.',
      verb: 'regar',
      tense: 'futuro',
      answers: ['regaremos', 'vamos regar'],
    },
    {
      sentence: 'Vocês {blank} as plantas antes da festa.',
      verb: 'regar',
      tense: 'futuro',
      answers: ['regarão', 'vão regar'],
    },
    {
      sentence: 'O Paulo {blank} os vasos neste sábado.',
      verb: 'regar',
      tense: 'futuro',
      answers: ['regará', 'vai regar'],
    },
    {
      sentence: 'Ela e a Maria {blank} o jardim juntas na próxima quarta.',
      verb: 'regar',
      tense: 'futuro',
      answers: ['regarão', 'vão regar'],
    },
    {
      sentence: 'Você {blank} os pés de tomate esta semana.',
      verb: 'regar',
      tense: 'futuro',
      answers: ['regarás', 'vai regar'],
    },
    {
      sentence: 'Eu e o João {blank} as ervas da horta na próxima noite.',
      verb: 'regar',
      tense: 'futuro',
      answers: ['regaremos', 'vamos regar'],
    },
    {
      sentence: 'Eles {blank} as plantações antes da colheita.',
      verb: 'regar',
      tense: 'futuro',
      answers: ['regarão', 'vão regar'],
    },
    {
      sentence: 'Tu {blank} as flores do teu jardim neste domingo.',
      verb: 'regar',
      tense: 'futuro',
      answers: ['regarás', 'vais regar'],
    },
    {
      sentence: 'Eu {blank} as plantas toda semana.',
      verb: 'regar',
      tense: 'presente',
      answers: ['rego'],
    },
    {
      sentence: 'Você {blank} as flores no final da tarde.',
      verb: 'regar',
      tense: 'presente',
      answers: ['regas'],
    },
    {
      sentence: 'Ela {blank} o jardim com muito carinho.',
      verb: 'regar',
      tense: 'presente',
      answers: ['rega'],
    },
    {
      sentence: 'Nós {blank} a grama do parque em dias de sol.',
      verb: 'regar',
      tense: 'presente',
      answers: ['regamos'],
    },
    {
      sentence: 'Eles {blank} as ervas do quintal atualmente.',
      verb: 'regar',
      tense: 'presente',
      answers: ['regam'],
    },
    {
      sentence: 'João {blank} as plantas da sala diariamente.',
      verb: 'regar',
      tense: 'presente',
      answers: ['rega'],
    },
    {
      sentence: 'Maria e eu {blank} os vasos depois do almoço.',
      verb: 'regar',
      tense: 'presente',
      answers: ['regamos'],
    },
    {
      sentence: 'Você e Pedro {blank} os bonsais com atenção.',
      verb: 'regar',
      tense: 'presente',
      answers: ['regam'],
    },
    {
      sentence: 'As crianças {blank} as árvores no final de semana.',
      verb: 'regar',
      tense: 'presente',
      answers: ['regam'],
    },
    {
      sentence: 'Eu e você {blank} as flores da varanda juntos.',
      verb: 'regar',
      tense: 'presente',
      answers: ['regamos'],
    },
  ],
};
