import { ProblemList } from '../Problems';

export const remarcar: ProblemList = {
  verb: 'remarcar',
  problems: [
    {
      sentence: 'Eu {blank} a reunião para o mês que vem.',
      verb: 'remarcar',
      tense: 'futuro',
      answers: ['remarcarei', 'vou remarcar'],
    },
    {
      sentence: 'Ela {blank} o compromisso para outra data.',
      verb: 'remarcar',
      tense: 'futuro',
      answers: ['remarcará', 'vai remarcar'],
    },
    {
      sentence: 'Nós {blank} a consulta para a próxima semana.',
      verb: 'remarcar',
      tense: 'futuro',
      answers: ['remarcaremos', 'vamos remarcar'],
    },
    {
      sentence: 'Você {blank} o encontro para o dia seguinte.',
      verb: 'remarcar',
      tense: 'futuro',
      answers: ['remarcará', 'vai remarcar'],
    },
    {
      sentence: 'Eles {blank} a viagem para o próximo mês.',
      verb: 'remarcar',
      tense: 'futuro',
      answers: ['remarcarão', 'vão remarcar'],
    },
    {
      sentence: 'João {blank} a festa para o sábado.',
      verb: 'remarcar',
      tense: 'futuro',
      answers: ['remarcará', 'vai remarcar'],
    },
    {
      sentence: 'Maria e eu {blank} o almoço para domingo.',
      verb: 'remarcar',
      tense: 'futuro',
      answers: ['remarcaremos', 'vamos remarcar'],
    },
    {
      sentence: 'Vocês {blank} a apresentação para a outra semana.',
      verb: 'remarcar',
      tense: 'futuro',
      answers: ['remarcarão', 'vão remarcar'],
    },
    {
      sentence: 'Eu e você {blank} a aula para amanhã.',
      verb: 'remarcar',
      tense: 'futuro',
      answers: ['remarcaremos', 'vamos remarcar'],
    },
    {
      sentence: 'Ela e as amigas {blank} o passeio para depois.',
      verb: 'remarcar',
      tense: 'futuro',
      answers: ['remarcarão', 'vão remarcar'],
    },
    {
      sentence: 'Eu {blank} a nossa reunião para amanhã.',
      verb: 'remarcar',
      tense: 'presente',
      answers: ['remarco'],
    },
    {
      sentence: 'Você {blank} o encontro com o cliente na próxima semana.',
      verb: 'remarcar',
      tense: 'presente',
      answers: ['remarca'],
    },
    {
      sentence: 'Ela {blank} os voos para Paris frequentemente.',
      verb: 'remarcar',
      tense: 'presente',
      answers: ['remarca'],
    },
    {
      sentence: 'Nós {blank} a conferência todos os anos.',
      verb: 'remarcar',
      tense: 'presente',
      answers: ['remarcamos'],
    },
    {
      sentence: 'Vocês {blank} as atividades do projeto regularmente.',
      verb: 'remarcar',
      tense: 'presente',
      answers: ['remarcam'],
    },
    {
      sentence: 'Ele {blank} os jogos de futebol no calendário.',
      verb: 'remarcar',
      tense: 'presente',
      answers: ['remarca'],
    },
    {
      sentence: 'Maria {blank} o compromisso dela sempre.',
      verb: 'remarcar',
      tense: 'presente',
      answers: ['remarca'],
    },
    {
      sentence: 'João e eu {blank} nossas reuniões semanalmente.',
      verb: 'remarcar',
      tense: 'presente',
      answers: ['remarcamos'],
    },
    {
      sentence: 'Vocês {blank} a visita ao museu para o próximo mês.',
      verb: 'remarcar',
      tense: 'presente',
      answers: ['remarcam'],
    },
    {
      sentence: 'Laura {blank} os prazos para os projetos atuais.',
      verb: 'remarcar',
      tense: 'presente',
      answers: ['remarca'],
    },
    {
      sentence: 'Eu {blank} a minha consulta médica ontem.',
      verb: 'remarcar',
      tense: 'pretérito perfeito',
      answers: [' remarquei'],
    },
    {
      sentence: 'Ela {blank} a reunião para outra data.',
      verb: 'remarcar',
      tense: 'pretérito perfeito',
      answers: ['remarcou'],
    },
    {
      sentence: 'Nós {blank} o jantar para sábado.',
      verb: 'remarcar',
      tense: 'pretérito perfeito',
      answers: ['remarcamos'],
    },
    {
      sentence: 'Você {blank} a viagem para a próxima semana.',
      verb: 'remarcar',
      tense: 'pretérito perfeito',
      answers: ['remarcou'],
    },
    {
      sentence: 'Eles {blank} a festa de aniversário.',
      verb: 'remarcar',
      tense: 'pretérito perfeito',
      answers: ['remarcaram'],
    },
    {
      sentence: 'Maria {blank} o compromisso com o advogado.',
      verb: 'remarcar',
      tense: 'pretérito perfeito',
      answers: ['remarcou'],
    },
    {
      sentence: 'João {blank} a consulta com o dentista.',
      verb: 'remarcar',
      tense: 'pretérito perfeito',
      answers: ['remarcou'],
    },
    {
      sentence: 'Nós {blank} o treino para outro horário.',
      verb: 'remarcar',
      tense: 'pretérito perfeito',
      answers: ['remarcamos'],
    },
    {
      sentence: 'Vocês {blank} o atendimento para amanhã.',
      verb: 'remarcar',
      tense: 'pretérito perfeito',
      answers: ['remarcaram'],
    },
    {
      sentence: 'Ela {blank} a aula de yoga para mais tarde.',
      verb: 'remarcar',
      tense: 'pretérito perfeito',
      answers: ['remarcou'],
    },
  ],
};
