import { ProblemList } from '../Problems';

export const responder: ProblemList = {
  verb: 'responder',
  problems: [
    {
      sentence: 'Eu {blank} à sua mensagem amanhã.',
      verb: 'responder',
      tense: 'futuro',
      answers: ['responderei', 'vou responder'],
    },
    {
      sentence: 'Ela {blank} as perguntas no final da reunião.',
      verb: 'responder',
      tense: 'futuro',
      answers: ['responderá', 'vai responder'],
    },
    {
      sentence: 'Nós {blank} todos os [e-mails] até o próximo mês.',
      verb: 'responder',
      tense: 'futuro',
      answers: ['responderemos', 'vamos responder'],
    },
    {
      sentence: 'Vocês {blank} ao cliente na próxima terça-feira.',
      verb: 'responder',
      tense: 'futuro',
      answers: ['responderão', 'vão responder'],
    },
    {
      sentence: 'João {blank} às suas dúvidas amanhã.',
      verb: 'responder',
      tense: 'futuro',
      answers: ['responderá', 'vai responder'],
    },
    {
      sentence: 'Maria e eu {blank} a essa questão na próxima aula.',
      verb: 'responder',
      tense: 'futuro',
      answers: ['responderemos', 'vamos responder'],
    },
    {
      sentence: 'Um dos professores {blank} aos alunos depois da aula.',
      verb: 'responder',
      tense: 'futuro',
      answers: ['responderá', 'vai responder'],
    },
    {
      sentence: 'Você {blank} a pesquisa até o final da semana.',
      verb: 'responder',
      tense: 'futuro',
      answers: ['responderá', 'vai responder'],
    },
    {
      sentence: 'As crianças {blank} as cartas que receberam do correio.',
      verb: 'responder',
      tense: 'futuro',
      answers: ['responderão', 'vão responder'],
    },
    {
      sentence: 'Eu e a Ana {blank} aos pedidos de ajuda amanhã.',
      verb: 'responder',
      tense: 'futuro',
      answers: ['responderemos', 'vamos responder'],
    },
    {
      sentence: 'Eu {blank} todas as perguntas durante a reunião.',
      verb: 'responder',
      tense: 'presente',
      answers: ['respondo'],
    },
    {
      sentence: 'Ela {blank} rapidamente aos [e-mails] que recebe.',
      verb: 'responder',
      tense: 'presente',
      answers: ['responde'],
    },
    {
      sentence: 'Nós {blank} sempre as dúvidas dos alunos.',
      verb: 'responder',
      tense: 'presente',
      answers: ['respondemos'],
    },
    {
      sentence: 'Vocês {blank} com clareza as perguntas feitas.',
      verb: 'responder',
      tense: 'presente',
      answers: ['respondem'],
    },
    {
      sentence: 'Eles {blank} às críticas de forma construtiva.',
      verb: 'responder',
      tense: 'presente',
      answers: ['respondem'],
    },
    {
      sentence: 'João {blank} honestamente às indagações do professor.',
      verb: 'responder',
      tense: 'presente',
      answers: ['responde'],
    },
    {
      sentence: 'Maria {blank} as mensagens dos amigos rapidamente.',
      verb: 'responder',
      tense: 'presente',
      answers: ['responde'],
    },
    {
      sentence: 'Você {blank} todas as questões da prova com facilidade.',
      verb: 'responder',
      tense: 'presente',
      answers: ['responde'],
    },
    {
      sentence: 'Nós {blank} ao público após a apresentação.',
      verb: 'responder',
      tense: 'presente',
      answers: ['respondemos'],
    },
    {
      sentence: 'Eles {blank} às propostas de forma muito clara.',
      verb: 'responder',
      tense: 'presente',
      answers: ['respondem'],
    },
    {
      sentence: 'Eu {blank} à sua pergunta rapidamente.',
      verb: 'responder',
      tense: 'pretérito perfeito',
      answers: ['respondi'],
    },
    {
      sentence: 'Ela {blank} todas as cartas na semana passada.',
      verb: 'responder',
      tense: 'pretérito perfeito',
      answers: ['respondeu'],
    },
    {
      sentence: 'Nós {blank} ao cliente sobre o problema.',
      verb: 'responder',
      tense: 'pretérito perfeito',
      answers: ['respondemos'],
    },
    {
      sentence: 'Vocês {blank} às mensagens ontem à noite.',
      verb: 'responder',
      tense: 'pretérito perfeito',
      answers: ['responderam'],
    },
    {
      sentence: 'Ele {blank} ao professor sobre a atividade.',
      verb: 'responder',
      tense: 'pretérito perfeito',
      answers: ['respondeu'],
    },
    {
      sentence: 'Ana {blank} a todos os convites que recebeu.',
      verb: 'responder',
      tense: 'pretérito perfeito',
      answers: ['respondeu'],
    },
    {
      sentence: 'João e eu {blank} à pesquisa da empresa.',
      verb: 'responder',
      tense: 'pretérito perfeito',
      answers: ['respondemos'],
    },
    {
      sentence: 'Você {blank} corretamente às perguntas do teste.',
      verb: 'responder',
      tense: 'pretérito perfeito',
      answers: ['respondeu'],
    },
    {
      sentence: 'Elas {blank} ao [e-mail] do gerente hoje de manhã.',
      verb: 'responder',
      tense: 'pretérito perfeito',
      answers: ['responderam'],
    },
    {
      sentence: 'Nós {blank} sobre as estratégias do projeto.',
      verb: 'responder',
      tense: 'pretérito perfeito',
      answers: ['respondemos'],
    },
  ],
};
