import { ProblemList } from '../Problems';

export const sair: ProblemList = {
  verb: 'sair',
  problems: [
    {
      sentence: 'Eu {blank} cedo para a festa ontem.',
      verb: 'sair',
      tense: 'pretérito perfeito',
      answers: ['saí'],
    },
    {
      sentence: 'Você {blank} do trabalho mais tarde na sexta-feira.',
      verb: 'sair',
      tense: 'pretérito perfeito',
      answers: ['saiu'],
    },
    {
      sentence: 'Ela {blank} rapidamente quando viu a chuva.',
      verb: 'sair',
      tense: 'pretérito perfeito',
      answers: ['saiu'],
    },
    {
      sentence: 'Nós {blank} juntos para um jantar no sábado.',
      verb: 'sair',
      tense: 'pretérito perfeito',
      answers: ['saímos'],
    },
    {
      sentence: 'Eles {blank} apressadamente após a última aula.',
      verb: 'sair',
      tense: 'pretérito perfeito',
      answers: ['saíram'],
    },
    {
      sentence: 'Maria e João {blank} para a praia na semana passada.',
      verb: 'sair',
      tense: 'pretérito perfeito',
      answers: ['saíram'],
    },
    {
      sentence: 'Tu {blank} antes do amanhecer para a corrida.',
      verb: 'sair',
      tense: 'pretérito perfeito',
      answers: ['saíste'],
    },
    {
      sentence: 'Ele {blank} da reunião quando a discussão começou.',
      verb: 'sair',
      tense: 'pretérito perfeito',
      answers: ['saiu'],
    },
    {
      sentence: 'A gente {blank} do cinema logo após o filme.',
      verb: 'sair',
      tense: 'pretérito perfeito',
      answers: ['saiu'],
    },
    {
      sentence: 'Vocês {blank} para viajar na [quinta-feira] passada.',
      verb: 'sair',
      tense: 'pretérito perfeito',
      answers: ['saíram'],
    },
    {
      sentence: 'Eu {blank} mais cedo amanhã.',
      verb: 'sair',
      tense: 'futuro',
      answers: ['sairei', 'vou sair'],
    },
    {
      sentence: 'Ela {blank} com os amigos no sábado.',
      verb: 'sair',
      tense: 'futuro',
      answers: ['sairá', 'vai sair'],
    },
    {
      sentence: 'Nós {blank} para a festa na próxima semana.',
      verb: 'sair',
      tense: 'futuro',
      answers: ['sairemos', 'vamos sair'],
    },
    {
      sentence: 'Você {blank} da escola mais tarde.',
      verb: 'sair',
      tense: 'futuro',
      answers: ['sairá', 'vai sair'],
    },
    {
      sentence: 'Eles {blank} para a viagem no domingo.',
      verb: 'sair',
      tense: 'futuro',
      answers: ['sairão', 'vão sair'],
    },
    {
      sentence: 'João {blank} com a família na próxima sexta.',
      verb: 'sair',
      tense: 'futuro',
      answers: ['sairá', 'vai sair'],
    },
    {
      sentence: 'Nós {blank} da reunião caso não seja interessante.',
      verb: 'sair',
      tense: 'futuro',
      answers: ['sairemos', 'vamos sair'],
    },
    {
      sentence: 'Vocês {blank} para o cinema depois do jantar.',
      verb: 'sair',
      tense: 'futuro',
      answers: ['sairão', 'vão sair'],
    },
    {
      sentence: 'Ela {blank} do trabalho logo após o expediente.',
      verb: 'sair',
      tense: 'futuro',
      answers: ['sairá', 'vai sair'],
    },
    {
      sentence: 'Eu {blank} para o parque assim que der.',
      verb: 'sair',
      tense: 'futuro',
      answers: ['sairei', 'vou sair'],
    },
    {
      sentence: 'Eu {blank} com meus amigos depois da escola.',
      verb: 'sair',
      tense: 'presente',
      answers: ['saio'],
    },
    {
      sentence: 'Ela {blank} para o trabalho todos os dias.',
      verb: 'sair',
      tense: 'presente',
      answers: ['sai'],
    },
    {
      sentence: 'Nós {blank} juntos para a festa no sábado.',
      verb: 'sair',
      tense: 'presente',
      answers: ['saímos'],
    },
    {
      sentence: 'Você {blank} da casa cedo pela manhã.',
      verb: 'sair',
      tense: 'presente',
      answers: ['sai'],
    },
    {
      sentence: 'Eles {blank} para o cinema à noite.',
      verb: 'sair',
      tense: 'presente',
      answers: ['saem'],
    },
    {
      sentence: 'João {blank} com a família no feriado.',
      verb: 'sair',
      tense: 'presente',
      answers: ['sai'],
    },
    {
      sentence: 'Maria e eu {blank} para passear no parque.',
      verb: 'sair',
      tense: 'presente',
      answers: ['saímos'],
    },
    {
      sentence: 'Vocês {blank} para a escola a pé.',
      verb: 'sair',
      tense: 'presente',
      answers: ['saem'],
    },
    {
      sentence: 'Ana e Miguel {blank} da reunião mais cedo.',
      verb: 'sair',
      tense: 'presente',
      answers: ['saem'],
    },
    {
      sentence: 'Eu e você {blank} juntos para o treino.',
      verb: 'sair',
      tense: 'presente',
      answers: ['saímos'],
    },
  ],
};
