import { ProblemList } from '../Problems';

export const sentir: ProblemList = {
  verb: 'sentir',
  problems: [
    {
      sentence: 'Eu {blank} uma grande alegria ao vê-los novamente.',
      verb: 'sentir',
      tense: 'futuro',
      answers: ['sentirei', 'vou sentir'],
    },
    {
      sentence: 'Ela {blank} saudades da escola quando voltar de férias.',
      verb: 'sentir',
      tense: 'futuro',
      answers: ['sentirá', 'vai sentir'],
    },
    {
      sentence: 'Nós {blank} um alívio ao saber que você está bem.',
      verb: 'sentir',
      tense: 'futuro',
      answers: ['sentiremos', 'vamos sentir'],
    },
    {
      sentence: 'Vocês {blank} um pouco de medo na apresentação amanhã.',
      verb: 'sentir',
      tense: 'futuro',
      answers: ['sentirão', 'vão sentir'],
    },
    {
      sentence: 'João {blank} felicidade ao encontrar o presente.',
      verb: 'sentir',
      tense: 'futuro',
      answers: ['sentirá', 'vai sentir'],
    },
    {
      sentence: 'Eu {blank} um grande carinho por você sempre.',
      verb: 'sentir',
      tense: 'futuro',
      answers: ['sentirei', 'vou sentir'],
    },
    {
      sentence: 'Eles {blank} tristeza com a despedida.',
      verb: 'sentir',
      tense: 'futuro',
      answers: ['sentirão', 'vão sentir'],
    },
    {
      sentence: 'Maria {blank} muitas lembranças boas da infância.',
      verb: 'sentir',
      tense: 'futuro',
      answers: ['sentirá', 'vai sentir'],
    },
    {
      sentence: 'Nós {blank} compaixão pelos que estão sofrendo.',
      verb: 'sentir',
      tense: 'futuro',
      answers: ['sentiremos', 'vamos sentir'],
    },
    {
      sentence: 'Você {blank} um pouco de frustração com a situação.',
      verb: 'sentir',
      tense: 'futuro',
      answers: ['sentirá', 'vai sentir'],
    },
    {
      sentence: 'Eu {blank} uma emoção forte ao ouvir a música.',
      verb: 'sentir',
      tense: 'presente',
      answers: ['sinto'],
    },
    {
      sentence: 'Ela {blank} muita felicidade quando recebe flores.',
      verb: 'sentir',
      tense: 'presente',
      answers: ['sente'],
    },
    {
      sentence: 'Nós {blank} um grande alívio após a notícia.',
      verb: 'sentir',
      tense: 'presente',
      answers: ['sentimos'],
    },
    {
      sentence: 'Você {blank} ansiedade antes da prova.',
      verb: 'sentir',
      tense: 'presente',
      answers: ['sente'],
    },
    {
      sentence: 'Eles {blank} a dor da perda do amigo.',
      verb: 'sentir',
      tense: 'presente',
      answers: ['sentem'],
    },
    {
      sentence: 'Pedro {blank} saudade da infância.',
      verb: 'sentir',
      tense: 'presente',
      answers: ['sente'],
    },
    {
      sentence: 'Maria e eu {blank} uma grande conexão.',
      verb: 'sentir',
      tense: 'presente',
      answers: ['sentimos'],
    },
    {
      sentence: 'Vocês {blank} raiva quando o trânsito está ruim.',
      verb: 'sentir',
      tense: 'presente',
      answers: ['sentem'],
    },
    {
      sentence: 'Carlos {blank} alegria em compartilhar momentos especiais.',
      verb: 'sentir',
      tense: 'presente',
      answers: ['sente'],
    },
    {
      sentence: 'Ela e eu {blank} um apreço pela natureza.',
      verb: 'sentir',
      tense: 'presente',
      answers: ['sentimos'],
    },
    {
      sentence: 'Eu {blank} uma grande felicidade ao receber a notícia.',
      verb: 'sentir',
      tense: 'pretérito perfeito',
      answers: ['senti'],
    },
    {
      sentence: 'Ela {blank} um alívio depois de terminar o projeto.',
      verb: 'sentir',
      tense: 'pretérito perfeito',
      answers: ['sentiu'],
    },
    {
      sentence: 'Nós {blank} uma tristeza profunda na despedida.',
      verb: 'sentir',
      tense: 'pretérito perfeito',
      answers: ['sentimos'],
    },
    {
      sentence: 'Você {blank} uma confusão ao ler o documento.',
      verb: 'sentir',
      tense: 'pretérito perfeito',
      answers: ['sentiu'],
    },
    {
      sentence: 'Eles {blank} muita emoção ao ver o show.',
      verb: 'sentir',
      tense: 'pretérito perfeito',
      answers: ['sentiram'],
    },
    {
      sentence: 'Maria {blank} uma dor forte depois da corrida.',
      verb: 'sentir',
      tense: 'pretérito perfeito',
      answers: ['sentiu'],
    },
    {
      sentence: 'João {blank} um orgulho imenso ao ver sua filha formada.',
      verb: 'sentir',
      tense: 'pretérito perfeito',
      answers: ['sentiu'],
    },
    {
      sentence: 'Nós {blank} um entusiasmo contagiante durante a festa.',
      verb: 'sentir',
      tense: 'pretérito perfeito',
      answers: ['sentimos'],
    },
    {
      sentence: 'Você e eu {blank} uma conexão especial durante a conversa.',
      verb: 'sentir',
      tense: 'pretérito perfeito',
      answers: ['sentimos'],
    },
    {
      sentence: 'Os alunos {blank} a pressão antes do exame.',
      verb: 'sentir',
      tense: 'pretérito perfeito',
      answers: ['sentiram'],
    },
  ],
};
