import { ProblemList } from '../Problems';

export const subir: ProblemList = {
  verb: 'subir',
  problems: [
    {
      sentence: 'Eu {blank} ao topo da montanha todas as manhãs.',
      verb: 'subir',
      tense: 'presente',
      answers: ['subo'],
    },
    {
      sentence: 'Ela {blank} mais rápido do que eu.',
      verb: 'subir',
      tense: 'presente',
      answers: ['sobe'],
    },
    {
      sentence: 'Nós {blank} as escadas em vez de usar o elevador.',
      verb: 'subir',
      tense: 'presente',
      answers: ['subimos'],
    },
    {
      sentence: 'Você {blank} com suas amigas para o evento amanhã.',
      verb: 'subir',
      tense: 'presente',
      answers: ['sobe'],
    },
    {
      sentence: 'Eles {blank} as informações na plataforma online.',
      verb: 'subir',
      tense: 'presente',
      answers: ['sobem'],
    },
    {
      sentence: 'João {blank} ao palco para se apresentar.',
      verb: 'subir',
      tense: 'presente',
      answers: ['sobe'],
    },
    {
      sentence: 'Nós {blank} frequentemente para visitar os avós.',
      verb: 'subir',
      tense: 'presente',
      answers: ['subimos'],
    },
    {
      sentence: 'Você e eu {blank} sempre juntos nas trilhas.',
      verb: 'subir',
      tense: 'presente',
      answers: ['subimos'],
    },
    {
      sentence: 'Maria {blank} bem cedo para o trabalho.',
      verb: 'subir',
      tense: 'presente',
      answers: ['sobe'],
    },
    {
      sentence: 'As crianças {blank} as árvores no parque.',
      verb: 'subir',
      tense: 'presente',
      answers: ['sobem'],
    },
    {
      sentence: 'Eu {blank} a escada para consertar o telhado.',
      verb: 'subir',
      tense: 'pretérito perfeito',
      answers: ['subi'],
    },
    {
      sentence: 'Ela {blank} na montanha mais alta do país.',
      verb: 'subir',
      tense: 'pretérito perfeito',
      answers: ['subiu'],
    },
    {
      sentence: 'Nós {blank} juntos para ver o pôr do sol.',
      verb: 'subir',
      tense: 'pretérito perfeito',
      answers: ['subimos'],
    },
    {
      sentence: 'Você {blank} a colina rapidamente.',
      verb: 'subir',
      tense: 'pretérito perfeito',
      answers: ['subiu'],
    },
    {
      sentence: 'Eles {blank} para o andar de cima do prédio.',
      verb: 'subir',
      tense: 'pretérito perfeito',
      answers: ['subiram'],
    },
    {
      sentence: 'João {blank} a ladeira para jogar futebol.',
      verb: 'subir',
      tense: 'pretérito perfeito',
      answers: ['subiu'],
    },
    {
      sentence: 'Ana e eu {blank} no elevador ao invés de escada.',
      verb: 'subir',
      tense: 'pretérito perfeito',
      answers: ['subimos'],
    },
    {
      sentence: 'Você e seu irmão {blank} na trilha do parque.',
      verb: 'subir',
      tense: 'pretérito perfeito',
      answers: ['subiram'],
    },
    {
      sentence: 'As crianças {blank} a árvore para colher frutas.',
      verb: 'subir',
      tense: 'pretérito perfeito',
      answers: ['subiram'],
    },
    {
      sentence: 'Ela {blank} escadas até chegar no topo.',
      verb: 'subir',
      tense: 'pretérito perfeito',
      answers: ['subiu'],
    },
    {
      sentence: 'Eu {blank} a montanha no próximo fim de semana.',
      verb: 'subir',
      tense: 'futuro',
      answers: ['subirei', 'vou subir'],
    },
    {
      sentence: 'Ela {blank} as escadas rapidamente amanhã.',
      verb: 'subir',
      tense: 'futuro',
      answers: ['subirá', 'vai subir'],
    },
    {
      sentence: 'Nós {blank} as dificuldades juntos no próximo mês.',
      verb: 'subir',
      tense: 'futuro',
      answers: ['subiremos', 'vamos subir'],
    },
    {
      sentence: 'Vocês {blank} o caminho certo na próxima viagem.',
      verb: 'subir',
      tense: 'futuro',
      answers: ['subirão', 'vão subir'],
    },
    {
      sentence: 'Ele {blank} a ladeira com facilidade esta semana.',
      verb: 'subir',
      tense: 'futuro',
      answers: ['subirá', 'vai subir'],
    },
    {
      sentence: 'Ana e eu {blank} as escadas do prédio amanhã.',
      verb: 'subir',
      tense: 'futuro',
      answers: ['subiremos', 'vamos subir'],
    },
    {
      sentence: 'Você {blank} os dados ao próximo nível na próxima competição.',
      verb: 'subir',
      tense: 'futuro',
      answers: ['subirá', 'vai subir'],
    },
    {
      sentence: 'Eles {blank} a montanha juntos no verão.',
      verb: 'subir',
      tense: 'futuro',
      answers: ['subirão', 'vão subir'],
    },
    {
      sentence: 'Eu e você {blank} ao topo do prédio na próxima semana.',
      verb: 'subir',
      tense: 'futuro',
      answers: ['subiremos', 'vamos subir'],
    },
    {
      sentence: 'Maria {blank} as escadas até o escritório amanhã de manhã.',
      verb: 'subir',
      tense: 'futuro',
      answers: ['subirá', 'vai subir'],
    },
  ],
};
