import { ProblemList } from '../Problems';

export const ter: ProblemList = {
  verb: 'ter',
  problems: [
    {
      sentence: 'Eu {blank} uma surpresa para o seu aniversário.',
      verb: 'ter',
      tense: 'futuro',
      answers: ['terei', 'vou ter'],
    },
    {
      sentence: 'Ela {blank} um novo carro até o final do ano.',
      verb: 'ter',
      tense: 'futuro',
      answers: ['terá', 'vai ter'],
    },
    {
      sentence: 'Nós {blank} a resposta correta na prova.',
      verb: 'ter',
      tense: 'futuro',
      answers: ['teremos', 'vamos ter'],
    },
    {
      sentence: 'Vocês {blank} tempo suficiente para terminar o trabalho.',
      verb: 'ter',
      tense: 'futuro',
      answers: ['terão', 'vão ter'],
    },
    {
      sentence: 'Ele {blank} muitos amigos na nova escola.',
      verb: 'ter',
      tense: 'futuro',
      answers: ['terá', 'vai ter'],
    },
    {
      sentence: 'Ana e eu {blank} um bom motivo para celebrar.',
      verb: 'ter',
      tense: 'futuro',
      answers: ['teremos', 'vamos ter'],
    },
    {
      sentence: 'Vocês {blank} a chance de viajar no próximo mês.',
      verb: 'ter',
      tense: 'futuro',
      answers: ['terão', 'vão ter'],
    },
    {
      sentence: 'Ela {blank} um projeto interessante para apresentar.',
      verb: 'ter',
      tense: 'futuro',
      answers: ['terá', 'vai ter'],
    },
    {
      sentence: 'Pedro e Maria {blank} um novo cachorro em breve.',
      verb: 'ter',
      tense: 'futuro',
      answers: ['terão', 'vão ter'],
    },
    {
      sentence: 'Eu {blank} a resposta pronta amanhã.',
      verb: 'ter',
      tense: 'futuro',
      answers: ['terei', 'vou ter'],
    },
    {
      sentence: 'Eu {blank} um novo desafio na escola.',
      verb: 'ter',
      tense: 'presente',
      answers: ['tenho'],
    },
    {
      sentence: 'Ela {blank} um plano para o fim de semana.',
      verb: 'ter',
      tense: 'presente',
      answers: ['tem'],
    },
    {
      sentence: 'Nós {blank} que estudar mais para a prova.',
      verb: 'ter',
      tense: 'presente',
      answers: ['temos'],
    },
    {
      sentence: 'Você {blank} um ótimo senso de humor.',
      verb: 'ter',
      tense: 'presente',
      answers: ['tem'],
    },
    {
      sentence: 'Eles {blank} muitos amigos na escola.',
      verb: 'ter',
      tense: 'presente',
      answers: ['têm'],
    },
    {
      sentence: 'João {blank} uma coleção impressionante de livros.',
      verb: 'ter',
      tense: 'presente',
      answers: ['tem'],
    },
    {
      sentence: 'Maria e José {blank} um sonho de viajar pelo mundo.',
      verb: 'ter',
      tense: 'presente',
      answers: ['têm'],
    },
    {
      sentence: 'O cachorro {blank} muito carinho de sua família.',
      verb: 'ter',
      tense: 'presente',
      answers: ['tem'],
    },
    {
      sentence: 'Vocês {blank} várias opções para escolher.',
      verb: 'ter',
      tense: 'presente',
      answers: ['têm'],
    },
    {
      sentence: 'Eu e você {blank} um grande desafio pela frente.',
      verb: 'ter',
      tense: 'presente',
      answers: ['temos'],
    },
    {
      sentence: 'Eu {blank} um novo carro na semana passada.',
      verb: 'ter',
      tense: 'pretérito perfeito',
      answers: ['tive'],
    },
    {
      sentence: 'Ela {blank} um ótimo desempenho na prova.',
      verb: 'ter',
      tense: 'pretérito perfeito',
      answers: ['teve'],
    },
    {
      sentence: 'Nós {blank} uma reunião importante ontem.',
      verb: 'ter',
      tense: 'pretérito perfeito',
      answers: ['tivemos'],
    },
    {
      sentence: 'Você {blank} a oportunidade de viajar com a família.',
      verb: 'ter',
      tense: 'pretérito perfeito',
      answers: ['teve'],
    },
    {
      sentence: 'Eles {blank} um dia incrível na praia.',
      verb: 'ter',
      tense: 'pretérito perfeito',
      answers: ['tiveram'],
    },
    {
      sentence: 'João {blank} uma ideia brilhante para o projeto.',
      verb: 'ter',
      tense: 'pretérito perfeito',
      answers: ['teve'],
    },
    {
      sentence: 'Maria e eu {blank} uma conversa interessante sobre arte.',
      verb: 'ter',
      tense: 'pretérito perfeito',
      answers: ['tivemos'],
    },
    {
      sentence: 'Vocês {blank} um ano desafiador, mas gratificante.',
      verb: 'ter',
      tense: 'pretérito perfeito',
      answers: ['tiveram'],
    },
    {
      sentence: 'Ela {blank} todos os requisitos para a vaga.',
      verb: 'ter',
      tense: 'pretérito perfeito',
      answers: ['teve'],
    },
    {
      sentence: 'Nós {blank} que tomar uma decisão rápida.',
      verb: 'ter',
      tense: 'pretérito perfeito',
      answers: ['tivemos'],
    },
  ],
};
