import { ProblemList } from '../Problems';

export const terminar: ProblemList = {
  verb: 'terminar',
  problems: [
    {
      sentence: 'Eu {blank} meu projeto hoje à noite.',
      verb: 'terminar',
      tense: 'presente',
      answers: ['termino'],
    },
    {
      sentence: 'Ela {blank} os estudos na escola.',
      verb: 'terminar',
      tense: 'presente',
      answers: ['termina'],
    },
    {
      sentence: 'Nós {blank} aquilo que começamos juntos.',
      verb: 'terminar',
      tense: 'presente',
      answers: ['terminamos'],
    },
    {
      sentence: 'Você {blank} seu trabalho sempre a tempo.',
      verb: 'terminar',
      tense: 'presente',
      answers: ['termina'],
    },
    {
      sentence: 'Eles {blank} o projeto com sucesso.',
      verb: 'terminar',
      tense: 'presente',
      answers: ['terminam'],
    },
    {
      sentence: 'Mariana {blank} as compras antes de voltar para casa.',
      verb: 'terminar',
      tense: 'presente',
      answers: ['termina'],
    },
    {
      sentence: 'Carlos e eu {blank} a apresentação no prazo.',
      verb: 'terminar',
      tense: 'presente',
      answers: ['terminamos'],
    },
    {
      sentence: 'Juliana {blank} seus treinos todos os dias.',
      verb: 'terminar',
      tense: 'presente',
      answers: ['termina'],
    },
    {
      sentence: 'Vocês {blank} as tarefas rapidamente.',
      verb: 'terminar',
      tense: 'presente',
      answers: ['terminam'],
    },
    {
      sentence: 'Ele {blank} seus estudos antes do exame.',
      verb: 'terminar',
      tense: 'presente',
      answers: ['termina'],
    },
    {
      sentence: 'Eu {blank} o projeto a tempo.',
      verb: 'terminar',
      tense: 'pretérito perfeito',
      answers: ['terminei'],
    },
    {
      sentence: 'Ela {blank} as tarefas antes do prazo.',
      verb: 'terminar',
      tense: 'pretérito perfeito',
      answers: ['terminou'],
    },
    {
      sentence: 'Nós {blank} de assistir ao filme ontem.',
      verb: 'terminar',
      tense: 'pretérito perfeito',
      answers: ['terminamos'],
    },
    {
      sentence: 'Você {blank} de ler o livro que recomendei?',
      verb: 'terminar',
      tense: 'pretérito perfeito',
      answers: ['terminou'],
    },
    {
      sentence: 'Eles {blank} a reunião mais cedo.',
      verb: 'terminar',
      tense: 'pretérito perfeito',
      answers: ['terminaram'],
    },
    {
      sentence: 'A Maria {blank} o curso no semestre passado.',
      verb: 'terminar',
      tense: 'pretérito perfeito',
      answers: ['terminou'],
    },
    {
      sentence: 'João e eu {blank} a apresentação ontem à noite.',
      verb: 'terminar',
      tense: 'pretérito perfeito',
      answers: ['terminamos'],
    },
    {
      sentence: 'Vocês {blank} a limpeza da casa antes da festa.',
      verb: 'terminar',
      tense: 'pretérito perfeito',
      answers: ['terminaram'],
    },
    {
      sentence: 'Ela {blank} o trabalho de casa antes da aula.',
      verb: 'terminar',
      tense: 'pretérito perfeito',
      answers: ['terminou'],
    },
    {
      sentence: 'Nós {blank} o planejamento do evento ontem.',
      verb: 'terminar',
      tense: 'pretérito perfeito',
      answers: ['terminamos'],
    },
    {
      sentence: 'Eu {blank} meu projeto na próxima semana.',
      verb: 'terminar',
      tense: 'futuro',
      answers: ['terminarei', 'vou terminar'],
    },
    {
      sentence: 'Ela {blank} a lição de casa amanhã.',
      verb: 'terminar',
      tense: 'futuro',
      answers: ['terminará', 'vai terminar'],
    },
    {
      sentence: 'Nós {blank} a reunião até sexta-feira.',
      verb: 'terminar',
      tense: 'futuro',
      answers: ['terminaremos', 'vamos terminar'],
    },
    {
      sentence: 'Você {blank} a leitura do livro esta semana.',
      verb: 'terminar',
      tense: 'futuro',
      answers: ['terminará', 'vai terminar'],
    },
    {
      sentence: 'Eles {blank} o trabalho em grupo na próxima aula.',
      verb: 'terminar',
      tense: 'futuro',
      answers: ['terminarão', 'vão terminar'],
    },
    {
      sentence: 'João {blank} o curso de francês no mês que vem.',
      verb: 'terminar',
      tense: 'futuro',
      answers: ['terminará', 'vai terminar'],
    },
    {
      sentence: 'Maria e eu {blank} o exercício antes de sair.',
      verb: 'terminar',
      tense: 'futuro',
      answers: ['terminaremos', 'vamos terminar'],
    },
    {
      sentence: 'Vocês {blank} os treinos antes da competição.',
      verb: 'terminar',
      tense: 'futuro',
      answers: ['terminarão', 'vão terminar'],
    },
    {
      sentence: 'As crianças {blank} o desenho até a tarde.',
      verb: 'terminar',
      tense: 'futuro',
      answers: ['terminarão', 'vão terminar'],
    },
    {
      sentence: 'Ele {blank} a sua apresentação logo mais.',
      verb: 'terminar',
      tense: 'futuro',
      answers: ['terminará', 'vai terminar'],
    },
  ],
};
