import { ProblemList } from '../Problems';

export const ver: ProblemList = {
  verb: 'ver',
  problems: [
    {
      sentence: 'Eu {blank} a película nova que está em cartaz.',
      verb: 'ver',
      tense: 'futuro',
      answers: ['verei', 'vou ver'],
    },
    {
      sentence: 'Ela {blank} o encontro marcado para a próxima semana.',
      verb: 'ver',
      tense: 'futuro',
      answers: ['verá', 'vai ver'],
    },
    {
      sentence: 'Nós {blank} a apresentação das novidades no evento.',
      verb: 'ver',
      tense: 'futuro',
      answers: ['veremos', 'vamos ver'],
    },
    {
      sentence: 'Vocês {blank} a festa que vai acontecer amanhã.',
      verb: 'ver',
      tense: 'futuro',
      answers: ['verão', 'vão ver'],
    },
    {
      sentence: 'Pedro {blank} a prova na próxima quarta-feira.',
      verb: 'ver',
      tense: 'futuro',
      answers: ['verá', 'vai ver'],
    },
    {
      sentence: 'Maria e eu {blank} o filme de suspense este final de semana.',
      verb: 'ver',
      tense: 'futuro',
      answers: ['veremos', 'vamos ver'],
    },
    {
      sentence: 'Você {blank} as fotos da viagem em breve.',
      verb: 'ver',
      tense: 'futuro',
      answers: ['verá', 'vai ver'],
    },
    {
      sentence: 'Ana e Carlos {blank} a nova exposição no museu.',
      verb: 'ver',
      tense: 'futuro',
      answers: ['verão', 'vão ver'],
    },
    {
      sentence: 'Eu e você {blank} a série que todo mundo está comentando.',
      verb: 'ver',
      tense: 'futuro',
      answers: ['veremos', 'vamos ver'],
    },
    {
      sentence: 'Eles {blank} as novas opções de menu no restaurante.',
      verb: 'ver',
      tense: 'futuro',
      answers: ['verão', 'vão ver'],
    },
    {
      sentence: 'Eu {blank} o filme que você recomendou.',
      verb: 'ver',
      tense: 'presente',
      answers: ['vejo'],
    },
    {
      sentence: 'Ela {blank} a série nova todos os sábados.',
      verb: 'ver',
      tense: 'presente',
      answers: ['vê'],
    },
    {
      sentence: 'Nós {blank} o jogo na televisão agora.',
      verb: 'ver',
      tense: 'presente',
      answers: ['vemos'],
    },
    {
      sentence: 'Vocês {blank} a apresentação deles ao vivo?',
      verb: 'ver',
      tense: 'presente',
      answers: ['veem'],
    },
    {
      sentence: 'O João {blank} a cidade de Lisboa com frequência.',
      verb: 'ver',
      tense: 'presente',
      answers: ['vê'],
    },
    {
      sentence: 'Eu e você {blank} o sol nascer pela manhã.',
      verb: 'ver',
      tense: 'presente',
      answers: ['vemos'],
    },
    {
      sentence: 'As crianças {blank} os pássaros no parque.',
      verb: 'ver',
      tense: 'presente',
      answers: ['veem'],
    },
    {
      sentence: 'Você {blank} as mudanças que aconteceram?',
      verb: 'ver',
      tense: 'presente',
      answers: ['vê'],
    },
    {
      sentence: 'Maria {blank} o que acontece ao seu redor.',
      verb: 'ver',
      tense: 'presente',
      answers: ['vê'],
    },
    {
      sentence: 'Nós {blank} as notícias diariamente.',
      verb: 'ver',
      tense: 'presente',
      answers: ['vemos'],
    },
    {
      sentence: 'Eu {blank} o filme que você me recomendou.',
      verb: 'ver',
      tense: 'pretérito perfeito',
      answers: ['vi'],
    },
    {
      sentence: 'Ela {blank} a apresentação ontem à noite.',
      verb: 'ver',
      tense: 'pretérito perfeito',
      answers: ['viu'],
    },
    {
      sentence: 'Nós {blank} as obras de arte no museu.',
      verb: 'ver',
      tense: 'pretérito perfeito',
      answers: ['vimos'],
    },
    {
      sentence: 'Você {blank} como ele tocava piano.',
      verb: 'ver',
      tense: 'pretérito perfeito',
      answers: ['viu'],
    },
    {
      sentence: 'Eles {blank} a situação com atenção.',
      verb: 'ver',
      tense: 'pretérito perfeito',
      answers: ['viram'],
    },
    {
      sentence: 'João {blank} seu amigo no parque.',
      verb: 'ver',
      tense: 'pretérito perfeito',
      answers: ['viu'],
    },
    {
      sentence: 'Nós {blank} as flores que plantamos.',
      verb: 'ver',
      tense: 'pretérito perfeito',
      answers: ['vimos'],
    },
    {
      sentence: 'Você e eu {blank} o jogo juntos.',
      verb: 'ver',
      tense: 'pretérito perfeito',
      answers: ['vimos'],
    },
    {
      sentence: 'Maria {blank} o resultado do exame.',
      verb: 'ver',
      tense: 'pretérito perfeito',
      answers: ['viu'],
    },
    {
      sentence: 'Os alunos {blank} a palestra interessante.',
      verb: 'ver',
      tense: 'pretérito perfeito',
      answers: ['viram'],
    },
  ],
};
