import { ProblemList } from '../Problems';

export const verificar: ProblemList = {
  verb: 'verificar',
  problems: [
    {
      sentence: 'Eu {blank} meus [e-mails] todas as manhãs.',
      verb: 'verificar',
      tense: 'presente',
      answers: ['verifico'],
    },
    {
      sentence: 'Ela {blank} as mensagens antes de responder.',
      verb: 'verificar',
      tense: 'presente',
      answers: ['verifica'],
    },
    {
      sentence: 'Nós {blank} os relatórios juntos.',
      verb: 'verificar',
      tense: 'presente',
      answers: ['verificamos'],
    },
    {
      sentence: 'Eles {blank} as contas mensalmente.',
      verb: 'verificar',
      tense: 'presente',
      answers: ['verificam'],
    },
    {
      sentence: 'Pedro {blank} os dados diariamente.',
      verb: 'verificar',
      tense: 'presente',
      answers: ['verifica'],
    },
    {
      sentence: 'Você {blank} o documento antes de enviá-lo?',
      verb: 'verificar',
      tense: 'presente',
      answers: ['verifica'],
    },
    {
      sentence: 'Maria e João {blank} o estoque toda semana.',
      verb: 'verificar',
      tense: 'presente',
      answers: ['verificam'],
    },
    {
      sentence: 'Eu e você {blank} as informações juntos.',
      verb: 'verificar',
      tense: 'presente',
      answers: ['verificamos'],
    },
    {
      sentence: 'As crianças {blank} os deveres antes de brincar.',
      verb: 'verificar',
      tense: 'presente',
      answers: ['verificam'],
    },
    {
      sentence: 'Vocês {blank} os resultados do teste?',
      verb: 'verificar',
      tense: 'presente',
      answers: ['verificam'],
    },
    {
      sentence: 'Eu {blank} meus [e-mails] ontem.',
      verb: 'verificar',
      tense: 'pretérito perfeito',
      answers: ['verifiquei'],
    },
    {
      sentence: 'Ela {blank} as mensagens antes de responder.',
      verb: 'verificar',
      tense: 'pretérito perfeito',
      answers: ['verificou'],
    },
    {
      sentence: 'Nós {blank} os relatórios juntos ontem.',
      verb: 'verificar',
      tense: 'pretérito perfeito',
      answers: ['verificamos'],
    },
    {
      sentence: 'Eles {blank} as contas no mês passado.',
      verb: 'verificar',
      tense: 'pretérito perfeito',
      answers: ['verificaram'],
    },
    {
      sentence: 'Pedro {blank} os dados na semana passada.',
      verb: 'verificar',
      tense: 'pretérito perfeito',
      answers: ['verificou'],
    },
    {
      sentence: 'Você {blank} o documento antes de enviá-lo?',
      verb: 'verificar',
      tense: 'pretérito perfeito',
      answers: ['verificou'],
    },
    {
      sentence: 'Maria e João {blank} o estoque ontem.',
      verb: 'verificar',
      tense: 'pretérito perfeito',
      answers: ['verificaram'],
    },
    {
      sentence: 'Eu e você {blank} as informações juntos.',
      verb: 'verificar',
      tense: 'pretérito perfeito',
      answers: ['verificamos'],
    },
    {
      sentence: 'As crianças {blank} os deveres antes de brincar.',
      verb: 'verificar',
      tense: 'pretérito perfeito',
      answers: ['verificaram'],
    },
    {
      sentence: 'Vocês {blank} os resultados do teste?',
      verb: 'verificar',
      tense: 'pretérito perfeito',
      answers: ['verificaram'],
    },
    {
      sentence: 'Eu {blank} meus [e-mails] amanhã cedo.',
      verb: 'verificar',
      tense: 'futuro',
      answers: ['verificarei', 'vou verificar'],
    },
    {
      sentence: 'Ela {blank} as mensagens antes de responder.',
      verb: 'verificar',
      tense: 'futuro',
      answers: ['verificará', 'vai verificar'],
    },
    {
      sentence: 'Nós {blank} os relatórios juntos amanhã.',
      verb: 'verificar',
      tense: 'futuro',
      answers: ['verificaremos', 'vamos verificar'],
    },
    {
      sentence: 'Eles {blank} as contas no próximo mês.',
      verb: 'verificar',
      tense: 'futuro',
      answers: ['verificarão', 'vão verificar'],
    },
    {
      sentence: 'Pedro {blank} os dados na semana que vem.',
      verb: 'verificar',
      tense: 'futuro',
      answers: ['verificará', 'vai verificar'],
    },
    {
      sentence: 'Você {blank} o documento antes de enviá-lo?',
      verb: 'verificar',
      tense: 'futuro',
      answers: ['verificará', 'vai verificar'],
    },
    {
      sentence: 'Maria e João {blank} o estoque amanhã.',
      verb: 'verificar',
      tense: 'futuro',
      answers: ['verificarão', 'vão verificar'],
    },
    {
      sentence: 'Eu e você {blank} as informações juntos.',
      verb: 'verificar',
      tense: 'futuro',
      answers: ['verificaremos', 'vamos verificar'],
    },
    {
      sentence: 'As crianças {blank} os deveres antes de brincar.',
      verb: 'verificar',
      tense: 'futuro',
      answers: ['verificarão', 'vão verificar'],
    },
    {
      sentence: 'Vocês {blank} os resultados do teste?',
      verb: 'verificar',
      tense: 'futuro',
      answers: ['verificarão', 'vão verificar'],
    },
  ],
};
