import { ProblemList } from '../Problems';

export const viajar: ProblemList = {
  verb: 'viajar',
  problems: [
    {
      sentence: 'Eu {blank} para o trabalho todos os dias.',
      verb: 'viajar',
      tense: 'presente',
      answers: ['viajo'],
    },
    {
      sentence: 'Ela {blank} frequentemente a negócios.',
      verb: 'viajar',
      tense: 'presente',
      answers: ['viaja'],
    },
    {
      sentence: 'Nós {blank} juntos nas férias.',
      verb: 'viajar',
      tense: 'presente',
      answers: ['viajamos'],
    },
    {
      sentence: 'Eles {blank} para diferentes países.',
      verb: 'viajar',
      tense: 'presente',
      answers: ['viajam'],
    },
    {
      sentence: 'Pedro {blank} muito a trabalho.',
      verb: 'viajar',
      tense: 'presente',
      answers: ['viaja'],
    },
    {
      sentence: 'Você {blank} de avião ou de carro?',
      verb: 'viajar',
      tense: 'presente',
      answers: ['viaja'],
    },
    {
      sentence: 'Maria e João {blank} pelo mundo.',
      verb: 'viajar',
      tense: 'presente',
      answers: ['viajam'],
    },
    {
      sentence: 'Eu e você {blank} juntos nas férias.',
      verb: 'viajar',
      tense: 'presente',
      answers: ['viajamos'],
    },
    {
      sentence: 'As crianças {blank} com os pais nas férias.',
      verb: 'viajar',
      tense: 'presente',
      answers: ['viajam'],
    },
    {
      sentence: 'Vocês {blank} muito a trabalho?',
      verb: 'viajar',
      tense: 'presente',
      answers: ['viajam'],
    },
    {
      sentence: 'Eu {blank} para a Europa no ano passado.',
      verb: 'viajar',
      tense: 'pretérito perfeito',
      answers: ['viajei'],
    },
    {
      sentence: 'Ela {blank} a trabalho na semana passada.',
      verb: 'viajar',
      tense: 'pretérito perfeito',
      answers: ['viajou'],
    },
    {
      sentence: 'Nós {blank} juntos nas últimas férias.',
      verb: 'viajar',
      tense: 'pretérito perfeito',
      answers: ['viajamos'],
    },
    {
      sentence: 'Eles {blank} para diferentes países no ano passado.',
      verb: 'viajar',
      tense: 'pretérito perfeito',
      answers: ['viajaram'],
    },
    {
      sentence: 'Pedro {blank} muito a trabalho no mês passado.',
      verb: 'viajar',
      tense: 'pretérito perfeito',
      answers: ['viajou'],
    },
    {
      sentence: 'Você {blank} de avião ou de carro nas férias?',
      verb: 'viajar',
      tense: 'pretérito perfeito',
      answers: ['viajou'],
    },
    {
      sentence: 'Maria e João {blank} pelo mundo juntos.',
      verb: 'viajar',
      tense: 'pretérito perfeito',
      answers: ['viajaram'],
    },
    {
      sentence: 'Eu e você {blank} juntos nas férias passadas.',
      verb: 'viajar',
      tense: 'pretérito perfeito',
      answers: ['viajamos'],
    },
    {
      sentence: 'As crianças {blank} com os pais nas últimas férias.',
      verb: 'viajar',
      tense: 'pretérito perfeito',
      answers: ['viajaram'],
    },
    {
      sentence: 'Vocês {blank} muito a trabalho no ano passado?',
      verb: 'viajar',
      tense: 'pretérito perfeito',
      answers: ['viajaram'],
    },
    {
      sentence: 'Eu {blank} para a Europa no próximo ano.',
      verb: 'viajar',
      tense: 'futuro',
      answers: ['viajarei', 'vou viajar'],
    },
    {
      sentence: 'Ela {blank} a trabalho na semana que vem.',
      verb: 'viajar',
      tense: 'futuro',
      answers: ['viajará', 'vai viajar'],
    },
    {
      sentence: 'Nós {blank} juntos nas próximas férias.',
      verb: 'viajar',
      tense: 'futuro',
      answers: ['viajaremos', 'vamos viajar'],
    },
    {
      sentence: 'Eles {blank} para diferentes países no ano que vem.',
      verb: 'viajar',
      tense: 'futuro',
      answers: ['viajarão', 'vão viajar'],
    },
    {
      sentence: 'Pedro {blank} muito a trabalho no mês que vem.',
      verb: 'viajar',
      tense: 'futuro',
      answers: ['viajará', 'vai viajar'],
    },
    {
      sentence: 'Você {blank} de avião ou de carro nas próximas férias?',
      verb: 'viajar',
      tense: 'futuro',
      answers: ['viajará', 'vai viajar'],
    },
    {
      sentence: 'Maria e João {blank} pelo mundo juntos.',
      verb: 'viajar',
      tense: 'futuro',
      answers: ['viajarão', 'vão viajar'],
    },
    {
      sentence: 'Eu e você {blank} juntos nas próximas férias.',
      verb: 'viajar',
      tense: 'futuro',
      answers: ['viajaremos', 'vamos viajar'],
    },
    {
      sentence: 'As crianças {blank} com os pais nas próximas férias.',
      verb: 'viajar',
      tense: 'futuro',
      answers: ['viajarão', 'vão viajar'],
    },
    {
      sentence: 'Vocês {blank} muito a trabalho no ano que vem?',
      verb: 'viajar',
      tense: 'futuro',
      answers: ['viajarão', 'vão viajar'],
    },
  ],
};
