import { ProblemList } from '../Problems';

export const vir: ProblemList = {
  verb: 'vir',
  problems: [
    {
      sentence: 'Você {blank} para a festa?',
      verb: 'vir',
      tense: 'presente',
      answers: ['vem'],
    },
    {
      sentence: 'Eu {blank} para o trabalho de bicicleta.',
      verb: 'vir',
      tense: 'presente',
      answers: ['venho'],
    },
    {
      sentence: 'Ele {blank} à escola todos os dias.',
      verb: 'vir',
      tense: 'presente',
      answers: ['vem'],
    },
    {
      sentence: 'Maria {blank} nos visitar [hoje à noite].',
      verb: 'vir',
      tense: 'presente',
      answers: ['vem'],
    },
    {
      sentence: 'Nós {blank} ao parque aos fins de semana.',
      verb: 'vir',
      tense: 'presente',
      answers: ['vimos'],
    },
    {
      sentence: 'Eles {blank} de longe para ver o show.',
      verb: 'vir',
      tense: 'presente',
      answers: ['vêm'],
    },
    {
      sentence: 'As crianças {blank} correndo quando ouvem o sino.',
      verb: 'vir',
      tense: 'presente',
      answers: ['vêm'],
    },
    {
      sentence: 'Você e eu {blank} juntos para a festa?',
      verb: 'vir',
      tense: 'presente',
      answers: ['vimos'],
    },
    {
      sentence: 'O trem {blank} às 8 horas.',
      verb: 'vir',
      tense: 'presente',
      answers: ['vem'],
    },
    {
      sentence: 'Vocês {blank} para o almoço?',
      verb: 'vir',
      tense: 'presente',
      answers: ['vêm'],
    },
    {
      sentence: 'Eu {blank} ao mercado ontem à tarde.',
      verb: 'vir',
      tense: 'pretérito perfeito',
      answers: ['vim'],
    },
    {
      sentence: 'Você {blank} me ajudar na mudança?',
      verb: 'vir',
      tense: 'pretérito perfeito',
      answers: ['veio'],
    },
    {
      sentence: 'Nós {blank} juntos para a conferência semana passada.',
      verb: 'vir',
      tense: 'pretérito perfeito',
      answers: ['viemos'],
    },
    {
      sentence: 'Eles {blank} de carro para o casamento.',
      verb: 'vir',
      tense: 'pretérito perfeito',
      answers: ['vieram'],
    },
    {
      sentence: 'Ana {blank} visitar seus avós no domingo.',
      verb: 'vir',
      tense: 'pretérito perfeito',
      answers: ['veio'],
    },
    {
      sentence: 'João e Maria {blank} cedo para a aula ontem.',
      verb: 'vir',
      tense: 'pretérito perfeito',
      answers: ['vieram'],
    },
    {
      sentence: 'Nós {blank} ao parque aproveitar o dia ensolarado.',
      verb: 'vir',
      tense: 'pretérito perfeito',
      answers: ['viemos'],
    },
    {
      sentence: 'Eles {blank} correndo quando ouviram a notícia.',
      verb: 'vir',
      tense: 'pretérito perfeito',
      answers: ['vieram'],
    },
    {
      sentence: 'Eu {blank} o mais rápido que pude.',
      verb: 'vir',
      tense: 'pretérito perfeito',
      answers: ['vim'],
    },
    {
      sentence: 'Vocês {blank} participar do evento na sexta-feira?',
      verb: 'vir',
      tense: 'pretérito perfeito',
      answers: ['vieram'],
    },
    {
      sentence: 'Eu {blank} visitar meus pais no próximo mês.',
      verb: 'vir',
      tense: 'futuro',
      answers: ['virei', 'vou vir'],
    },
    {
      sentence: 'Ela {blank} para a festa amanhã.',
      verb: 'vir',
      tense: 'futuro',
      answers: ['virá', 'vai vir'],
    },
    {
      sentence: 'Nós {blank} para o evento especial.',
      verb: 'vir',
      tense: 'futuro',
      answers: ['viremos', 'vamos vir'],
    },
    {
      sentence: 'Eles {blank} conhecer a nova casa.',
      verb: 'vir',
      tense: 'futuro',
      answers: ['virão', 'vão vir'],
    },
    {
      sentence: 'João e Maria {blank} ao cinema conosco.',
      verb: 'vir',
      tense: 'futuro',
      answers: ['virão', 'vão vir'],
    },
    {
      sentence: 'Você {blank} para a reunião na sexta-feira?',
      verb: 'vir',
      tense: 'futuro',
      answers: ['virá', 'vai vir'],
    },
    {
      sentence: 'Ana {blank} buscar o documento mais tarde.',
      verb: 'vir',
      tense: 'futuro',
      answers: ['virá', 'vai vir'],
    },
    {
      sentence: 'Vocês {blank} ao casamento?',
      verb: 'vir',
      tense: 'futuro',
      answers: ['virão', 'vão vir'],
    },
    {
      sentence: 'Meu amigo Pedro {blank} me visitar em breve.',
      verb: 'vir',
      tense: 'futuro',
      answers: ['virá', 'vai vir'],
    },
    {
      sentence: 'Nós {blank} aqui amanhã às 9h.',
      verb: 'vir',
      tense: 'futuro',
      answers: ['viremos', 'vamos vir'],
    },
  ],
};
