import { ProblemList } from '../Problems';

export const visitar: ProblemList = {
  verb: 'visitar',
  problems: [
    {
      sentence: 'Eu {blank} meus avós todos os finais de semana.',
      verb: 'visitar',
      tense: 'presente',
      answers: ['visito'],
    },
    {
      sentence: 'Ela {blank} o museu regularmente.',
      verb: 'visitar',
      tense: 'presente',
      answers: ['visita'],
    },
    {
      sentence: 'Nós {blank} diferentes países nas férias.',
      verb: 'visitar',
      tense: 'presente',
      answers: ['visitamos'],
    },
    {
      sentence: 'Eles {blank} amigos em outras cidades.',
      verb: 'visitar',
      tense: 'presente',
      answers: ['visitam'],
    },
    {
      sentence: 'Pedro {blank} a biblioteca toda semana.',
      verb: 'visitar',
      tense: 'presente',
      answers: ['visita'],
    },
    {
      sentence: 'Você {blank} novos lugares durante as férias?',
      verb: 'visitar',
      tense: 'presente',
      answers: ['visita'],
    },
    {
      sentence: 'Maria e João {blank} museus de [arte moderna].',
      verb: 'visitar',
      tense: 'presente',
      answers: ['visitam'],
    },
    {
      sentence: 'Eu e você {blank} a exposição amanhã.',
      verb: 'visitar',
      tense: 'presente',
      answers: ['visitamos'],
    },
    {
      sentence: 'As crianças {blank} o zoológico na primavera.',
      verb: 'visitar',
      tense: 'presente',
      answers: ['visitam'],
    },
    {
      sentence: 'Vocês {blank} parentes em outras cidades?',
      verb: 'visitar',
      tense: 'presente',
      answers: ['visitam'],
    },
    {
      sentence: 'Eu {blank} meus avós no fim de semana passado.',
      verb: 'visitar',
      tense: 'pretérito perfeito',
      answers: ['visitei'],
    },
    {
      sentence: 'Ela {blank} o museu ontem.',
      verb: 'visitar',
      tense: 'pretérito perfeito',
      answers: ['visitou'],
    },
    {
      sentence: 'Nós {blank} diferentes países nas últimas férias.',
      verb: 'visitar',
      tense: 'pretérito perfeito',
      answers: ['visitamos'],
    },
    {
      sentence: 'Eles {blank} amigos em outras cidades no ano passado.',
      verb: 'visitar',
      tense: 'pretérito perfeito',
      answers: ['visitaram'],
    },
    {
      sentence: 'Pedro {blank} a biblioteca na semana passada.',
      verb: 'visitar',
      tense: 'pretérito perfeito',
      answers: ['visitou'],
    },
    {
      sentence: 'Você {blank} novos lugares durante as férias?',
      verb: 'visitar',
      tense: 'pretérito perfeito',
      answers: ['visitou'],
    },
    {
      sentence: 'Maria e João {blank} museus de [arte moderna].',
      verb: 'visitar',
      tense: 'pretérito perfeito',
      answers: ['visitaram'],
    },
    {
      sentence: 'Eu e você {blank} a exposição ontem.',
      verb: 'visitar',
      tense: 'pretérito perfeito',
      answers: ['visitamos'],
    },
    {
      sentence: 'As crianças {blank} o zoológico na primavera passada.',
      verb: 'visitar',
      tense: 'pretérito perfeito',
      answers: ['visitaram'],
    },
    {
      sentence: 'Vocês {blank} parentes em outras cidades?',
      verb: 'visitar',
      tense: 'pretérito perfeito',
      answers: ['visitaram'],
    },
    {
      sentence: 'Eu {blank} meus avós no próximo fim de semana.',
      verb: 'visitar',
      tense: 'futuro',
      answers: ['visitarei', 'vou visitar'],
    },
    {
      sentence: 'Ela {blank} o museu amanhã.',
      verb: 'visitar',
      tense: 'futuro',
      answers: ['visitará', 'vai visitar'],
    },
    {
      sentence: 'Nós {blank} diferentes países nas próximas férias.',
      verb: 'visitar',
      tense: 'futuro',
      answers: ['visitaremos', 'vamos visitar'],
    },
    {
      sentence: 'Eles {blank} amigos em outras cidades no ano que vem.',
      verb: 'visitar',
      tense: 'futuro',
      answers: ['visitarão', 'vão visitar'],
    },
    {
      sentence: 'Pedro {blank} a biblioteca amanhã.',
      verb: 'visitar',
      tense: 'futuro',
      answers: ['visitará', 'vai visitar'],
    },
    {
      sentence: 'Você {blank} novos lugares durante as férias?',
      verb: 'visitar',
      tense: 'futuro',
      answers: ['visitará', 'vai visitar'],
    },
    {
      sentence: 'Maria e João {blank} museus de [arte moderna].',
      verb: 'visitar',
      tense: 'futuro',
      answers: ['visitarão', 'vão visitar'],
    },
    {
      sentence: 'Eu e você {blank} a exposição amanhã.',
      verb: 'visitar',
      tense: 'futuro',
      answers: ['visitaremos', 'vamos visitar'],
    },
    {
      sentence: 'As crianças {blank} o zoológico na próxima primavera.',
      verb: 'visitar',
      tense: 'futuro',
      answers: ['visitarão', 'vão visitar'],
    },
    {
      sentence: 'Vocês {blank} parentes em outras cidades?',
      verb: 'visitar',
      tense: 'futuro',
      answers: ['visitarão', 'vão visitar'],
    },
  ],
};
