import { ProblemList } from '../Problems';

export const viver: ProblemList = {
  verb: 'viver',
  problems: [
    {
      sentence: 'Eu {blank} numa cidade linda.',
      verb: 'viver',
      tense: 'presente',
      answers: ['vivo'],
    },
    {
      sentence: 'Ela {blank} com a família no novo apartamento.',
      verb: 'viver',
      tense: 'presente',
      answers: ['vive'],
    },
    {
      sentence: 'Nós {blank} felizes com as nossas conquistas.',
      verb: 'viver',
      tense: 'presente',
      answers: ['vivemos'],
    },
    {
      sentence: 'Você {blank} muito bem aqui.',
      verb: 'viver',
      tense: 'presente',
      answers: ['vive'],
    },
    {
      sentence: 'Eles {blank} a vida do jeito que desejam.',
      verb: 'viver',
      tense: 'presente',
      answers: ['vivem'],
    },
    {
      sentence: 'Maria e João {blank} em harmonia.',
      verb: 'viver',
      tense: 'presente',
      answers: ['vivem'],
    },
    {
      sentence: 'Nós {blank} muitas aventuras juntos.',
      verb: 'viver',
      tense: 'presente',
      answers: ['vivemos'],
    },
    {
      sentence: 'Tu {blank} bem perto do trabalho.',
      verb: 'viver',
      tense: 'presente',
      answers: ['vives'],
    },
    {
      sentence: 'Ela e você {blank} momentos incríveis.',
      verb: 'viver',
      tense: 'presente',
      answers: ['vivem'],
    },
    {
      sentence: 'Meu irmão {blank} em outro país agora.',
      verb: 'viver',
      tense: 'presente',
      answers: ['vive'],
    },
    {
      sentence: 'Eu {blank} em São Paulo por cinco anos.',
      verb: 'viver',
      tense: 'pretérito perfeito',
      answers: ['vivi'],
    },
    {
      sentence: 'Ela {blank} uma experiência incrível na viagem.',
      verb: 'viver',
      tense: 'pretérito perfeito',
      answers: ['viveu'],
    },
    {
      sentence: 'Nós {blank} momentos inesquecíveis juntos.',
      verb: 'viver',
      tense: 'pretérito perfeito',
      answers: ['vivemos'],
    },
    {
      sentence: 'Você {blank} tantas aventuras na sua infância.',
      verb: 'viver',
      tense: 'pretérito perfeito',
      answers: ['viveu'],
    },
    {
      sentence: 'Eles {blank} na Europa durante um semestre.',
      verb: 'viver',
      tense: 'pretérito perfeito',
      answers: ['viveram'],
    },
    {
      sentence: 'Ricardo {blank} na praia todo o verão.',
      verb: 'viver',
      tense: 'pretérito perfeito',
      answers: ['viveu'],
    },
    {
      sentence: 'Maria e eu {blank} a mesma situação durante a festa.',
      verb: 'viver',
      tense: 'pretérito perfeito',
      answers: ['vivemos'],
    },
    {
      sentence: 'Vocês {blank} muitas emoções em seus treinos.',
      verb: 'viver',
      tense: 'pretérito perfeito',
      answers: ['viveram'],
    },
    {
      sentence: 'Ana {blank} suas férias mais legais este ano.',
      verb: 'viver',
      tense: 'pretérito perfeito',
      answers: ['viveu'],
    },
    {
      sentence: 'Nós {blank} momentos de alegria e tristeza.',
      verb: 'viver',
      tense: 'pretérito perfeito',
      answers: ['vivemos'],
    },
    {
      sentence: 'Eu {blank} em Paris durante o próximo verão.',
      verb: 'viver',
      tense: 'futuro',
      answers: ['viverei', 'vou viver'],
    },
    {
      sentence: 'Ela {blank} novas experiências na Austrália.',
      verb: 'viver',
      tense: 'futuro',
      answers: ['viverá', 'vai viver'],
    },
    {
      sentence: 'Nós {blank} momentos inesquecíveis na viagem.',
      verb: 'viver',
      tense: 'futuro',
      answers: ['vivemos', 'vamos viver'],
    },
    {
      sentence: 'Vocês {blank} uma nova fase de suas vidas.',
      verb: 'viver',
      tense: 'futuro',
      answers: ['viverão', 'vão viver'],
    },
    {
      sentence: 'João {blank} uma nova aventura em breve.',
      verb: 'viver',
      tense: 'futuro',
      answers: ['viverá', 'vai viver'],
    },
    {
      sentence: 'Maria e eu {blank} uma experiência cultural única.',
      verb: 'viver',
      tense: 'futuro',
      answers: ['viveremos', 'vamos viver'],
    },
    {
      sentence: 'Vocês {blank} um ano incrível juntos.',
      verb: 'viver',
      tense: 'futuro',
      answers: ['viverão', 'vão viver'],
    },
    {
      sentence: 'Carlos {blank} a vida plena de fé e amor.',
      verb: 'viver',
      tense: 'futuro',
      answers: ['viverá', 'vai viver'],
    },
    {
      sentence: 'Nós {blank} uma reforma extraordinária na casa.',
      verb: 'viver',
      tense: 'futuro',
      answers: ['vivemos', 'vamos viver'],
    },
    {
      sentence: 'Você {blank} um futuro brilhante pela frente.',
      verb: 'viver',
      tense: 'futuro',
      answers: ['viverá', 'vai viver'],
    },
  ],
};
