import { ProblemList } from '../Problems';

export const voltar: ProblemList = {
  verb: 'voltar',
  problems: [
    {
      sentence: 'Eu {blank} para casa todos os dias às 18h.',
      verb: 'voltar',
      tense: 'presente',
      answers: ['volto'],
    },
    {
      sentence: 'Ela {blank} do trabalho de ônibus.',
      verb: 'voltar',
      tense: 'presente',
      answers: ['volta'],
    },
    {
      sentence: 'Nós {blank} da escola juntos.',
      verb: 'voltar',
      tense: 'presente',
      answers: ['voltamos'],
    },
    {
      sentence: 'Eles {blank} para o Brasil no próximo mês.',
      verb: 'voltar',
      tense: 'presente',
      answers: ['voltam'],
    },
    {
      sentence: 'Pedro {blank} para a faculdade após o almoço.',
      verb: 'voltar',
      tense: 'presente',
      answers: ['volta'],
    },
    {
      sentence: 'Você {blank} para casa de carro?',
      verb: 'voltar',
      tense: 'presente',
      answers: ['volta'],
    },
    {
      sentence: 'Maria e João {blank} para o escritório após a reunião.',
      verb: 'voltar',
      tense: 'presente',
      answers: ['voltam'],
    },
    {
      sentence: 'Eu e você {blank} para a academia depois do trabalho.',
      verb: 'voltar',
      tense: 'presente',
      answers: ['voltamos'],
    },
    {
      sentence: 'As crianças {blank} da escola às 15h.',
      verb: 'voltar',
      tense: 'presente',
      answers: ['voltam'],
    },
    {
      sentence: 'Vocês {blank} para o hotel todas as noites?',
      verb: 'voltar',
      tense: 'presente',
      answers: ['voltam'],
    },
    {
      sentence: 'Eu {blank} para casa ontem à noite.',
      verb: 'voltar',
      tense: 'pretérito perfeito',
      answers: ['voltei'],
    },
    {
      sentence: 'Ela {blank} do trabalho mais cedo.',
      verb: 'voltar',
      tense: 'pretérito perfeito',
      answers: ['voltou'],
    },
    {
      sentence: 'Nós {blank} da viagem na semana passada.',
      verb: 'voltar',
      tense: 'pretérito perfeito',
      answers: ['voltamos'],
    },
    {
      sentence: 'Eles {blank} para o Brasil no mês passado.',
      verb: 'voltar',
      tense: 'pretérito perfeito',
      answers: ['voltaram'],
    },
    {
      sentence: 'Pedro {blank} para a faculdade após as férias.',
      verb: 'voltar',
      tense: 'pretérito perfeito',
      answers: ['voltou'],
    },
    {
      sentence: 'Você {blank} para casa de carro ontem?',
      verb: 'voltar',
      tense: 'pretérito perfeito',
      answers: ['voltou'],
    },
    {
      sentence: 'Maria e João {blank} para o escritório após a conferência.',
      verb: 'voltar',
      tense: 'pretérito perfeito',
      answers: ['voltaram'],
    },
    {
      sentence: 'Eu e você {blank} para a academia depois do trabalho.',
      verb: 'voltar',
      tense: 'pretérito perfeito',
      answers: ['voltamos'],
    },
    {
      sentence: 'As crianças {blank} da escola às 15h ontem.',
      verb: 'voltar',
      tense: 'pretérito perfeito',
      answers: ['voltaram'],
    },
    {
      sentence: 'Vocês {blank} para o hotel após o passeio?',
      verb: 'voltar',
      tense: 'pretérito perfeito',
      answers: ['voltaram'],
    },
    {
      sentence: 'Eu {blank} para casa mais tarde.',
      verb: 'voltar',
      tense: 'futuro',
      answers: ['voltarei', 'vou voltar'],
    },
    {
      sentence: 'Ela {blank} do trabalho às 18h.',
      verb: 'voltar',
      tense: 'futuro',
      answers: ['voltará', 'vai voltar'],
    },
    {
      sentence: 'Nós {blank} da viagem no próximo mês.',
      verb: 'voltar',
      tense: 'futuro',
      answers: ['voltaremos', 'vamos voltar'],
    },
    {
      sentence: 'Eles {blank} para o Brasil em breve.',
      verb: 'voltar',
      tense: 'futuro',
      answers: ['voltarão', 'vão voltar'],
    },
    {
      sentence: 'Pedro {blank} para a faculdade após as férias.',
      verb: 'voltar',
      tense: 'futuro',
      answers: ['voltará', 'vai voltar'],
    },
    {
      sentence: 'Você {blank} para casa de carro amanhã?',
      verb: 'voltar',
      tense: 'futuro',
      answers: ['voltará', 'vai voltar'],
    },
    {
      sentence: 'Maria e João {blank} para o escritório após o almoço.',
      verb: 'voltar',
      tense: 'futuro',
      answers: ['voltarão', 'vão voltar'],
    },
    {
      sentence: 'Eu e você {blank} para a academia depois do trabalho.',
      verb: 'voltar',
      tense: 'futuro',
      answers: ['voltaremos', 'vamos voltar'],
    },
    {
      sentence: 'As crianças {blank} da escola às 15h amanhã.',
      verb: 'voltar',
      tense: 'futuro',
      answers: ['voltarão', 'vão voltar'],
    },
    {
      sentence: 'Vocês {blank} para o hotel após o passeio?',
      verb: 'voltar',
      tense: 'futuro',
      answers: ['voltarão', 'vão voltar'],
    },
  ],
};
