import { ProblemList } from '../Problems';

export const voluntariar: ProblemList = {
  verb: 'voluntariar',
  problems: [
    {
      sentence: 'Eu {blank} no evento beneficente ontem.',
      verb: 'voluntariar',
      tense: 'pretérito perfeito',
      answers: ['voluntariei'],
    },
    {
      sentence: 'Ela {blank} na campanha de doação de sangue.',
      verb: 'voluntariar',
      tense: 'pretérito perfeito',
      answers: ['voluntariou'],
    },
    {
      sentence: 'Nós {blank} juntos na limpeza da praia.',
      verb: 'voluntariar',
      tense: 'pretérito perfeito',
      answers: ['voluntariamos'],
    },
    {
      sentence: 'Eles {blank} no abrigo de animais no fim de semana passado.',
      verb: 'voluntariar',
      tense: 'pretérito perfeito',
      answers: ['voluntariaram'],
    },
    {
      sentence: 'Maria {blank} para ajudar na escola.',
      verb: 'voluntariar',
      tense: 'pretérito perfeito',
      answers: ['voluntariou'],
    },
    {
      sentence: 'Vocês {blank} na organização do evento cultural?',
      verb: 'voluntariar',
      tense: 'pretérito perfeito',
      answers: ['voluntariaram'],
    },
    {
      sentence: 'Meu irmão {blank} em um projeto comunitário.',
      verb: 'voluntariar',
      tense: 'pretérito perfeito',
      answers: ['voluntariou'],
    },
    {
      sentence: 'Eu e você {blank} na arrecadação de alimentos.',
      verb: 'voluntariar',
      tense: 'pretérito perfeito',
      answers: ['voluntariamos'],
    },
    {
      sentence: 'As meninas {blank} no hospital ontem.',
      verb: 'voluntariar',
      tense: 'pretérito perfeito',
      answers: ['voluntariaram'],
    },
    {
      sentence: 'Você {blank} para ajudar na limpeza do parque?',
      verb: 'voluntariar',
      tense: 'pretérito perfeito',
      answers: ['voluntariou'],
    },
    {
      sentence: 'Eu {blank} no evento comunitário na próxima semana.',
      verb: 'voluntariar',
      tense: 'futuro',
      answers: ['voluntariarei', 'vou voluntariar'],
    },
    {
      sentence: 'Ela {blank} na campanha de reciclagem.',
      verb: 'voluntariar',
      tense: 'futuro',
      answers: ['voluntariará', 'vai voluntariar'],
    },
    {
      sentence: 'Nós {blank} juntos na construção da escola.',
      verb: 'voluntariar',
      tense: 'futuro',
      answers: ['voluntariaremos', 'vamos voluntariar'],
    },
    {
      sentence: 'Eles {blank} no abrigo de animais no próximo mês.',
      verb: 'voluntariar',
      tense: 'futuro',
      answers: ['voluntariarão', 'vão voluntariar'],
    },
    {
      sentence: 'João {blank} na organização do evento esportivo.',
      verb: 'voluntariar',
      tense: 'futuro',
      answers: ['voluntariará', 'vai voluntariar'],
    },
    {
      sentence: 'Você {blank} na campanha de doação?',
      verb: 'voluntariar',
      tense: 'futuro',
      answers: ['voluntariará', 'vai voluntariar'],
    },
    {
      sentence: 'Maria e Ana {blank} no hospital infantil.',
      verb: 'voluntariar',
      tense: 'futuro',
      answers: ['voluntariarão', 'vão voluntariar'],
    },
    {
      sentence: 'Nós {blank} na limpeza da praia neste fim de semana.',
      verb: 'voluntariar',
      tense: 'futuro',
      answers: ['voluntariaremos', 'vamos voluntariar'],
    },
    {
      sentence: 'Meu irmão {blank} na arrecadação de alimentos.',
      verb: 'voluntariar',
      tense: 'futuro',
      answers: ['voluntariará', 'vai voluntariar'],
    },
    {
      sentence: 'Vocês {blank} na campanha ambiental?',
      verb: 'voluntariar',
      tense: 'futuro',
      answers: ['voluntariarão', 'vão voluntariar'],
    },
    {
      sentence: 'Eu {blank} no evento comunitário todas as semanas.',
      verb: 'voluntariar',
      tense: 'presente',
      answers: ['voluntario'],
    },
    {
      sentence: 'Ela {blank} na campanha de doação de sangue.',
      verb: 'voluntariar',
      tense: 'presente',
      answers: ['voluntaria'],
    },
    {
      sentence: 'Nós {blank} juntos na limpeza da praia.',
      verb: 'voluntariar',
      tense: 'presente',
      answers: ['voluntariamos'],
    },
    {
      sentence: 'Eles {blank} no abrigo de animais aos sábados.',
      verb: 'voluntariar',
      tense: 'presente',
      answers: ['voluntariam'],
    },
    {
      sentence: 'Maria {blank} para ajudar na escola local.',
      verb: 'voluntariar',
      tense: 'presente',
      answers: ['voluntaria'],
    },
    {
      sentence: 'Você {blank} na organização do evento cultural?',
      verb: 'voluntariar',
      tense: 'presente',
      answers: ['voluntaria'],
    },
    {
      sentence: 'Meu irmão {blank} em um projeto comunitário.',
      verb: 'voluntariar',
      tense: 'presente',
      answers: ['voluntaria'],
    },
    {
      sentence: 'Eu e você {blank} na arrecadação de alimentos.',
      verb: 'voluntariar',
      tense: 'presente',
      answers: ['voluntariamos'],
    },
    {
      sentence: 'As meninas {blank} no hospital toda semana.',
      verb: 'voluntariar',
      tense: 'presente',
      answers: ['voluntariam'],
    },
    {
      sentence: 'Vocês {blank} para ajudar na limpeza do parque?',
      verb: 'voluntariar',
      tense: 'presente',
      answers: ['voluntariam'],
    },
  ],
};
