type Tense = 'presente' | 'pretérito perfeito' | 'futuro';

export interface Problem {
  sentence: string;
  verb: string;
  tense: Tense;
  answer: string;
}

export const problems: Problem[] = [
  {
    sentence: 'Eu {blank} café todas as manhãs.',
    verb: 'beber',
    tense: 'presente',
    answer: 'bebo',
  },
  {
    sentence: 'Ela {blank} ao trabalho de carro.',
    verb: 'ir',
    tense: 'presente',
    answer: 'vai',
  },
  {
    sentence: 'Nós {blank} muito no final de semana passado.',
    verb: 'trabalhar',
    tense: 'pretérito perfeito',
    answer: 'trabalhamos',
  },
  {
    sentence: 'Eles {blank} as tarefas antes de dormir.',
    verb: 'fazer',
    tense: 'presente',
    answer: 'fazem',
  },
  {
    sentence: 'Você {blank} com seus pais ontem?',
    verb: 'falar',
    tense: 'pretérito perfeito',
    answer: 'falou',
  },
  {
    sentence: 'Eu não {blank} o que aconteceu.',
    verb: 'entender',
    tense: 'presente',
    answer: 'entendo',
  },
  {
    sentence: 'Nós {blank} um novo livro toda semana.',
    verb: 'ler',
    tense: 'presente',
    answer: 'lemos',
  },
  {
    sentence: 'Ele {blank} em casa durante as férias.',
    verb: 'ficar',
    tense: 'pretérito perfeito',
    answer: 'ficou',
  },
  {
    sentence: 'Você {blank} para a festa?',
    verb: 'vir',
    tense: 'presente',
    answer: 'vem',
  },
  {
    sentence: 'Ela {blank} tudo antes de decidir.',
    verb: 'pensar',
    tense: 'presente',
    answer: 'pensa',
  },
  {
    sentence: 'Eu {blank} para a academia todos os dias.',
    verb: 'ir',
    tense: 'presente',
    answer: 'vou',
  },
  {
    sentence: 'Nós {blank} uma casa nova no ano passado.',
    verb: 'comprar',
    tense: 'pretérito perfeito',
    answer: 'compramos',
  },
  {
    sentence: 'Eles {blank} sobre o problema durante a reunião.',
    verb: 'discutir',
    tense: 'pretérito perfeito',
    answer: 'discutiram',
  },
  {
    sentence: 'Ela {blank} um novo curso na universidade.',
    verb: 'começar',
    tense: 'pretérito perfeito',
    answer: 'começou',
  },
  {
    sentence: 'Você {blank} o documento no e-mail?',
    verb: 'enviar',
    tense: 'pretérito perfeito',
    answer: 'enviou',
  },
  {
    sentence: 'Eu {blank} feliz por ver você novamente.',
    verb: 'ficar',
    tense: 'presente',
    answer: 'fico',
  },
  {
    sentence: 'Nós {blank} um almoço especial para o aniversário dele.',
    verb: 'preparar',
    tense: 'pretérito perfeito',
    answer: 'preparamos',
  },
  {
    sentence: 'Eles {blank} em um apartamento no centro.',
    verb: 'morar',
    tense: 'presente',
    answer: 'moram',
  },
  {
    sentence: 'Ela {blank} muito durante o fim de semana.',
    verb: 'descansar',
    tense: 'pretérito perfeito',
    answer: 'descansou',
  },
  {
    sentence: 'Você {blank} na apresentação de hoje?',
    verb: 'participar',
    tense: 'pretérito perfeito',
    answer: 'participou',
  },
  {
    sentence: 'Nós {blank} de manhã no parque.',
    verb: 'correr',
    tense: 'presente',
    answer: 'corremos',
  },
  {
    sentence: 'Ela {blank} a comida na mesa agora.',
    verb: 'colocar',
    tense: 'presente',
    answer: 'coloca',
  },
  {
    sentence: 'Eu {blank} uma mensagem para ele mais tarde.',
    verb: 'enviar',
    tense: 'futuro',
    answer: 'enviarei',
  },
  {
    sentence: 'Você {blank} o jantar ontem à noite?',
    verb: 'preparar',
    tense: 'pretérito perfeito',
    answer: 'preparou',
  },
  {
    sentence: 'Eles {blank} um filme juntos.',
    verb: 'assistir',
    tense: 'presente',
    answer: 'assistem',
  },
  {
    sentence: 'Nós {blank} o projeto na próxima semana.',
    verb: 'concluir',
    tense: 'futuro',
    answer: 'concluiremos',
  },
  {
    sentence: 'Ele {blank} todos os exercícios no domingo.',
    verb: 'completar',
    tense: 'pretérito perfeito',
    answer: 'completou',
  },
  {
    sentence: 'Eu {blank} para o cinema amanhã.',
    verb: 'ir',
    tense: 'futuro',
    answer: 'irei',
  },
  {
    sentence: 'Ana e João {blank} para a festa juntos.',
    verb: 'ir',
    tense: 'pretérito perfeito',
    answer: 'foram',
  },
  {
    sentence: 'Você {blank} uma ótima apresentação hoje!',
    verb: 'dar',
    tense: 'pretérito perfeito',
    answer: 'deu',
  },
  {
    sentence: 'Nós {blank} um encontro com eles na sexta.',
    verb: 'marcar',
    tense: 'presente',
    answer: 'marcamos',
  },
  {
    sentence: 'Eles {blank} a nova série na semana passada.',
    verb: 'começar',
    tense: 'pretérito perfeito',
    answer: 'começaram',
  },
  {
    sentence: 'Ela {blank} que eu estava certo.',
    verb: 'admitir',
    tense: 'pretérito perfeito',
    answer: 'admitiu',
  },
  {
    sentence: 'Eu {blank} muito sobre o tema.',
    verb: 'estudar',
    tense: 'pretérito perfeito',
    answer: 'estudei',
  },
  {
    sentence: 'Você {blank} o relatório na quinta?',
    verb: 'entregar',
    tense: 'pretérito perfeito',
    answer: 'entregou',
  },
  {
    sentence: 'Ele {blank} para o mercado agora.',
    verb: 'ir',
    tense: 'presente',
    answer: 'vai',
  },
  {
    sentence: 'Nós {blank} muito da sua companhia.',
    verb: 'gostar',
    tense: 'presente',
    answer: 'gostamos',
  },
  {
    sentence: 'Eles {blank} juntos no último verão.',
    verb: 'viajar',
    tense: 'pretérito perfeito',
    answer: 'viajaram',
  },
  {
    sentence: 'Ela {blank} o café todas as manhãs.',
    verb: 'fazer',
    tense: 'presente',
    answer: 'faz',
  },
  {
    sentence: 'Você {blank} o jantar na última semana?',
    verb: 'preparar',
    tense: 'pretérito perfeito',
    answer: 'preparou',
  },
  {
    sentence: 'Eles {blank} a comida para a festa.',
    verb: 'levar',
    tense: 'presente',
    answer: 'levam',
  },
  {
    sentence: 'Nós {blank} o carro ontem.',
    verb: 'lavar',
    tense: 'pretérito perfeito',
    answer: 'lavamos',
  },
  {
    sentence: 'Ela {blank} o livro no final de semana.',
    verb: 'ler',
    tense: 'pretérito perfeito',
    answer: 'leu',
  },
  {
    sentence: 'Eu {blank} a lição de casa mais tarde.',
    verb: 'fazer',
    tense: 'futuro',
    answer: 'farei',
  },
  {
    sentence: 'Você {blank} a verdade agora.',
    verb: 'saber',
    tense: 'presente',
    answer: 'sabe',
  },
  {
    sentence: 'Eles {blank} o almoço enquanto eu estudava.',
    verb: 'preparar',
    tense: 'pretérito perfeito',
    answer: 'prepararam',
  },
  {
    sentence: 'Eu {blank} a aula na terça-feira passada.',
    verb: 'perder',
    tense: 'pretérito perfeito',
    answer: 'perdi',
  },
  {
    sentence: 'Ela {blank} a sobremesa para nós.',
    verb: 'trazer',
    tense: 'pretérito perfeito',
    answer: 'trouxe',
  },
  {
    sentence: 'Você {blank} na viagem?',
    verb: 'participar',
    tense: 'pretérito perfeito',
    answer: 'participou',
  },
  {
    sentence: 'Eu {blank} muito cansado hoje.',
    verb: 'estar',
    tense: 'presente',
    answer: 'estou',
  },
  {
    sentence: 'Nós {blank} no parque ontem.',
    verb: 'caminhar',
    tense: 'pretérito perfeito',
    answer: 'caminhamos',
  },
  {
    sentence: 'Eles {blank} a música quando eu liguei.',
    verb: 'ouvir',
    tense: 'pretérito perfeito',
    answer: 'ouviram',
  },
  {
    sentence: 'Ele {blank} no concurso na semana passada.',
    verb: 'passar',
    tense: 'pretérito perfeito',
    answer: 'passou',
  },
  {
    sentence: 'Eu {blank} a reunião para quinta-feira.',
    verb: 'remarcar',
    tense: 'presente',
    answer: 'remarco',
  },
  {
    sentence: 'Você {blank} para a faculdade em 2019?',
    verb: 'entrar',
    tense: 'pretérito perfeito',
    answer: 'entrou',
  },
  {
    sentence: 'Ela {blank} para o escritório às 9h.',
    verb: 'chegar',
    tense: 'presente',
    answer: 'chega',
  },
  {
    sentence: 'Eu {blank} sobre a proposta de emprego.',
    verb: 'pensar',
    tense: 'pretérito perfeito',
    answer: 'pensei',
  },
  {
    sentence: 'Você {blank} meu nome corretamente?',
    verb: 'escrever',
    tense: 'pretérito perfeito',
    answer: 'escreveu',
  },
  {
    sentence: 'Eles {blank} o carro para a garagem ontem.',
    verb: 'levar',
    tense: 'pretérito perfeito',
    answer: 'levaram',
  },
  {
    sentence: 'Nós {blank} tudo antes de partir.',
    verb: 'arrumar',
    tense: 'pretérito perfeito',
    answer: 'arrumamos',
  },
  {
    sentence: 'Ele {blank} os novos projetos no próximo mês.',
    verb: 'lançar',
    tense: 'futuro',
    answer: 'lançará',
  },
  {
    sentence: 'Você {blank} o plano antes de começar?',
    verb: 'discutir',
    tense: 'pretérito perfeito',
    answer: 'discutiu',
  },
  {
    sentence: 'Nós {blank} a tarefa logo mais.',
    verb: 'terminar',
    tense: 'futuro',
    answer: 'terminaremos',
  },
  {
    sentence: 'Ela {blank} as plantas na última primavera.',
    verb: 'regar',
    tense: 'pretérito perfeito',
    answer: 'regou',
  },
  {
    sentence: 'Eles {blank} cedo para a festa hoje.',
    verb: 'chegar',
    tense: 'presente',
    answer: 'chegam',
  },
  {
    sentence: 'Nós {blank} as crianças para a escola agora.',
    verb: 'levar',
    tense: 'presente',
    answer: 'levamos',
  },
  {
    sentence: 'Eu {blank} uma nova língua no ano passado.',
    verb: 'aprender',
    tense: 'pretérito perfeito',
    answer: 'aprendi',
  },
  {
    sentence: 'Você {blank} a roupa ontem?',
    verb: 'lavar',
    tense: 'pretérito perfeito',
    answer: 'lavou',
  },
  {
    sentence: 'Eles {blank} muitas perguntas na aula.',
    verb: 'fazer',
    tense: 'presente',
    answer: 'fazem',
  },
  {
    sentence: 'Ela {blank} a visita ao museu na terça.',
    verb: 'marcar',
    tense: 'pretérito perfeito',
    answer: 'marcou',
  },
  {
    sentence: 'Eu {blank} no sofá toda a tarde ontem.',
    verb: 'ficar',
    tense: 'pretérito perfeito',
    answer: 'fiquei',
  },
  {
    sentence: 'Nós {blank} a lição de casa agora.',
    verb: 'começar',
    tense: 'presente',
    answer: 'começamos',
  },
  {
    sentence: 'Eles {blank} a casa de Maria no fim de semana.',
    verb: 'visitar',
    tense: 'pretérito perfeito',
    answer: 'visitaram',
  },
  {
    sentence: 'Ela {blank} a receita com detalhes.',
    verb: 'explicar',
    tense: 'pretérito perfeito',
    answer: 'explicou',
  },
  {
    sentence: 'Você {blank} para o professor?',
    verb: 'responder',
    tense: 'pretérito perfeito',
    answer: 'respondeu',
  },
  {
    sentence: 'Eles {blank} para o jogo na sexta-feira.',
    verb: 'ir',
    tense: 'futuro',
    answer: 'irão',
  },
  {
    sentence: 'Eu {blank} mais tarde para resolver isso.',
    verb: 'ligar',
    tense: 'futuro',
    answer: 'ligarei',
  },
  {
    sentence: 'Você {blank} comigo na próxima semana?',
    verb: 'trabalhar',
    tense: 'futuro',
    answer: 'trabalhará',
  },
  {
    sentence: 'Ela {blank} a festa com todos os amigos.',
    verb: 'organizar',
    tense: 'pretérito perfeito',
    answer: 'organizou',
  },
  {
    sentence: 'Nós {blank} a cidade inteira durante as férias.',
    verb: 'explorar',
    tense: 'pretérito perfeito',
    answer: 'exploramos',
  },
  {
    sentence: 'Eles {blank} tudo antes de assinar o contrato.',
    verb: 'verificar',
    tense: 'pretérito perfeito',
    answer: 'verificaram',
  },
  {
    sentence: 'Eu {blank} mais cedo amanhã para a reunião.',
    verb: 'chegar',
    tense: 'futuro',
    answer: 'chegarei',
  },
  {
    sentence: 'Você {blank} todos os capítulos hoje?',
    verb: 'ler',
    tense: 'pretérito perfeito',
    answer: 'leu',
  },
  {
    sentence: 'Nós {blank} um novo carro no mês passado.',
    verb: 'comprar',
    tense: 'pretérito perfeito',
    answer: 'compramos',
  },
  {
    sentence: 'Eles {blank} a pesquisa na segunda-feira.',
    verb: 'finalizar',
    tense: 'pretérito perfeito',
    answer: 'finalizaram',
  },
  {
    sentence: 'Ela {blank} para a prova durante todo o fim de semana.',
    verb: 'estudar',
    tense: 'pretérito perfeito',
    answer: 'estudou',
  },
  {
    sentence: 'Eu {blank} a viagem com todos os detalhes.',
    verb: 'planejar',
    tense: 'pretérito perfeito',
    answer: 'planejei',
  },
  {
    sentence: 'Nós {blank} o relatório no prazo.',
    verb: 'entregar',
    tense: 'pretérito perfeito',
    answer: 'entregamos',
  },
  {
    sentence: 'Você {blank} o artigo antes de publicar?',
    verb: 'revisar',
    tense: 'pretérito perfeito',
    answer: 'revisou',
  },
  {
    sentence: 'Eles {blank} o concerto amanhã.',
    verb: 'assistir',
    tense: 'futuro',
    answer: 'assistirão',
  },
  {
    sentence: 'Ela {blank} para a reunião na terça-feira passada.',
    verb: 'vir',
    tense: 'pretérito perfeito',
    answer: 'veio',
  },
  {
    sentence: 'Eu {blank} um novo curso no mês que vem.',
    verb: 'começar',
    tense: 'futuro',
    answer: 'começarei',
  },
  {
    sentence: 'Nós {blank} para o evento em grupo.',
    verb: 'ir',
    tense: 'pretérito perfeito',
    answer: 'fomos',
  },
  {
    sentence: 'Eles {blank} um grande esforço para terminar.',
    verb: 'fazer',
    tense: 'pretérito perfeito',
    answer: 'fizeram',
  },
  {
    sentence: 'Você {blank} o problema antes de resolver?',
    verb: 'analisar',
    tense: 'pretérito perfeito',
    answer: 'analisou',
  },
  {
    sentence: 'Eu {blank} para o médico amanhã cedo.',
    verb: 'ir',
    tense: 'futuro',
    answer: 'irei',
  },
  {
    sentence: 'Ela {blank} o bolo na festa.',
    verb: 'levar',
    tense: 'pretérito perfeito',
    answer: 'levou',
  },
  {
    sentence: 'Eles {blank} na competição no mês passado.',
    verb: 'participar',
    tense: 'pretérito perfeito',
    answer: 'participaram',
  },
  {
    sentence: 'Eu {blank} o presente para ela ontem.',
    verb: 'comprar',
    tense: 'pretérito perfeito',
    answer: 'comprei',
  },
  {
    sentence: 'Nós {blank} a estrada errada durante a viagem.',
    verb: 'pegar',
    tense: 'pretérito perfeito',
    answer: 'pegamos',
  },
  {
    sentence: 'Eles {blank} o jantar para o grupo inteiro.',
    verb: 'cozinhar',
    tense: 'pretérito perfeito',
    answer: 'cozinharam',
  },
  {
    sentence: 'Ela {blank} a carta antes de enviar.',
    verb: 'escrever',
    tense: 'pretérito perfeito',
    answer: 'escreveu',
  },
  {
    sentence: 'Eu {blank} para a festa na sexta-feira.',
    verb: 'sair',
    tense: 'futuro',
    answer: 'sairei',
  },
  {
    sentence: 'Você {blank} um bom trabalho no projeto!',
    verb: 'fazer',
    tense: 'pretérito perfeito',
    answer: 'fez',
  },
  {
    sentence: 'Nós {blank} o barco ao longo do rio.',
    verb: 'navegar',
    tense: 'pretérito perfeito',
    answer: 'navegamos',
  },
  {
    sentence: 'Eles {blank} a loja no mês passado.',
    verb: 'abrir',
    tense: 'pretérito perfeito',
    answer: 'abriram',
  },
  {
    sentence: 'Você {blank} a lista de convidados?',
    verb: 'conferir',
    tense: 'pretérito perfeito',
    answer: 'conferiu',
  },
  {
    sentence: 'Nós {blank} a ideia para o chefe na semana passada.',
    verb: 'apresentar',
    tense: 'pretérito perfeito',
    answer: 'apresentamos',
  },
  {
    sentence: 'Ele {blank} para ajudar no trabalho.',
    verb: 'voluntariar',
    tense: 'pretérito perfeito',
    answer: 'voluntariou',
  },
  {
    sentence: 'Eu {blank} o filme na semana que vem.',
    verb: 'assistir',
    tense: 'futuro',
    answer: 'assistirei',
  },
  {
    sentence: 'Você {blank} um tempo para pensar?',
    verb: 'precisar',
    tense: 'presente',
    answer: 'precisa',
  },
  {
    sentence: 'Nós {blank} a ideia antes de implementar.',
    verb: 'considerar',
    tense: 'pretérito perfeito',
    answer: 'consideramos',
  },
  {
    sentence: 'Eles {blank} o documento no final da reunião.',
    verb: 'assinar',
    tense: 'pretérito perfeito',
    answer: 'assinaram',
  },
  {
    sentence: 'Ela {blank} a resposta correta durante o teste.',
    verb: 'encontrar',
    tense: 'pretérito perfeito',
    answer: 'encontrou',
  },
  {
    sentence: 'Eu {blank} em casa durante o fim de semana.',
    verb: 'ficar',
    tense: 'pretérito perfeito',
    answer: 'fiquei',
  },
  {
    sentence: 'Nós {blank} a prova na última sexta-feira.',
    verb: 'fazer',
    tense: 'pretérito perfeito',
    answer: 'fizemos',
  },
  {
    sentence: 'Eles {blank} sobre o problema antes da decisão.',
    verb: 'falar',
    tense: 'pretérito perfeito',
    answer: 'falaram',
  },
  {
    sentence: 'Ela {blank} as flores para a mãe dela.',
    verb: 'dar',
    tense: 'pretérito perfeito',
    answer: 'deu',
  },
  {
    sentence: 'Eu {blank} em casa quando eles chegaram.',
    verb: 'estar',
    tense: 'pretérito perfeito',
    answer: 'estava',
  },
  {
    sentence: 'Você {blank} o documento na mesa?',
    verb: 'deixar',
    tense: 'pretérito perfeito',
    answer: 'deixou',
  },
  {
    sentence: 'Eles {blank} para o restaurante amanhã.',
    verb: 'voltar',
    tense: 'futuro',
    answer: 'voltarão',
  },
  {
    sentence: 'Nós {blank} o filme juntos amanhã.',
    verb: 'assistir',
    tense: 'futuro',
    answer: 'assistiremos',
  },
  {
    sentence: 'Ela {blank} o problema com paciência.',
    verb: 'resolver',
    tense: 'pretérito perfeito',
    answer: 'resolveu',
  },
  {
    sentence: 'Eu {blank} no telefone por muito tempo ontem.',
    verb: 'ficar',
    tense: 'pretérito perfeito',
    answer: 'fiquei',
  },
  {
    sentence: 'Você {blank} muito bem no teste!',
    verb: 'ir',
    tense: 'pretérito perfeito',
    answer: 'foi',
  },
  {
    sentence: 'Nós {blank} para a festa juntos.',
    verb: 'ir',
    tense: 'pretérito perfeito',
    answer: 'fomos',
  },
  {
    sentence: 'Eles {blank} a notícia durante a reunião.',
    verb: 'anunciar',
    tense: 'pretérito perfeito',
    answer: 'anunciaram',
  },
  {
    sentence: 'Ela {blank} com a situação difícil.',
    verb: 'lidar',
    tense: 'pretérito perfeito',
    answer: 'lidou',
  },
  {
    sentence: 'Eu {blank} as caixas para o quarto.',
    verb: 'levar',
    tense: 'pretérito perfeito',
    answer: 'levei',
  },
];
