type Tense = 'presente' | 'pretérito perfeito' | 'futuro';

export interface Problem {
  sentence: string;
  verb: string;
  tense: Tense;
  answers: string[];
}

export const problems: Problem[] = [
  {
    sentence: 'Eu {blank} café todas as manhãs.',
    verb: 'beber',
    tense: 'presente',
    answers: ['bebo'],
  },
  {
    sentence: 'Ela {blank} ao trabalho de carro.',
    verb: 'ir',
    tense: 'presente',
    answers: ['vai'],
  },
  {
    sentence: 'Nós {blank} muito no final de semana passado.',
    verb: 'trabalhar',
    tense: 'pretérito perfeito',
    answers: ['trabalhamos'],
  },
  {
    sentence: 'Eles {blank} as tarefas antes de dormir.',
    verb: 'fazer',
    tense: 'presente',
    answers: ['fazem'],
  },
  {
    sentence: 'Você {blank} com seus pais ontem?',
    verb: 'falar',
    tense: 'pretérito perfeito',
    answers: ['falou'],
  },
  {
    sentence: 'Eu não {blank} o que aconteceu.',
    verb: 'entender',
    tense: 'presente',
    answers: ['entendo'],
  },
  {
    sentence: 'Nós {blank} um novo livro toda semana.',
    verb: 'ler',
    tense: 'presente',
    answers: ['lemos'],
  },
  {
    sentence: 'Ele {blank} em casa durante as férias.',
    verb: 'ficar',
    tense: 'pretérito perfeito',
    answers: ['ficou'],
  },
  {
    sentence: 'Você {blank} para a festa?',
    verb: 'vir',
    tense: 'presente',
    answers: ['vem'],
  },
  {
    sentence: 'Ela {blank} tudo antes de decidir.',
    verb: 'pensar',
    tense: 'presente',
    answers: ['pensa'],
  },
  {
    sentence: 'Eu {blank} para a academia todos os dias.',
    verb: 'ir',
    tense: 'presente',
    answers: ['vou'],
  },
  {
    sentence: 'Nós {blank} uma casa nova no ano passado.',
    verb: 'comprar',
    tense: 'pretérito perfeito',
    answers: ['compramos'],
  },
  {
    sentence: 'Eles {blank} sobre o problema durante a reunião.',
    verb: 'discutir',
    tense: 'pretérito perfeito',
    answers: ['discutiram'],
  },
  {
    sentence: 'Ela {blank} um novo curso na universidade.',
    verb: 'começar',
    tense: 'pretérito perfeito',
    answers: ['começou'],
  },
  {
    sentence: 'Você {blank} o documento no e-mail?',
    verb: 'enviar',
    tense: 'pretérito perfeito',
    answers: ['enviou'],
  },
  {
    sentence: 'Eu {blank} feliz por ver você novamente.',
    verb: 'ficar',
    tense: 'presente',
    answers: ['fico'],
  },
  {
    sentence: 'Nós {blank} um almoço especial para o aniversário dele.',
    verb: 'preparar',
    tense: 'pretérito perfeito',
    answers: ['preparamos'],
  },
  {
    sentence: 'Eles {blank} em um apartamento no centro.',
    verb: 'morar',
    tense: 'presente',
    answers: ['moram'],
  },
  {
    sentence: 'Ela {blank} muito durante o fim de semana.',
    verb: 'descansar',
    tense: 'pretérito perfeito',
    answers: ['descansou'],
  },
  {
    sentence: 'Você {blank} na apresentação de hoje?',
    verb: 'participar',
    tense: 'pretérito perfeito',
    answers: ['participou'],
  },
  {
    sentence: 'Nós {blank} de manhã no parque.',
    verb: 'correr',
    tense: 'presente',
    answers: ['corremos'],
  },
  {
    sentence: 'Ela {blank} a comida na mesa agora.',
    verb: 'colocar',
    tense: 'presente',
    answers: ['coloca'],
  },
  {
    sentence: 'Eu {blank} uma mensagem para ele mais tarde.',
    verb: 'enviar',
    tense: 'futuro',
    answers: ['enviarei', 'vou enviar'],
  },
  {
    sentence: 'Você {blank} o jantar ontem à noite?',
    verb: 'preparar',
    tense: 'pretérito perfeito',
    answers: ['preparou'],
  },
  {
    sentence: 'Eles {blank} um filme juntos.',
    verb: 'assistir',
    tense: 'presente',
    answers: ['assistem'],
  },
  {
    sentence: 'Nós {blank} o projeto na próxima semana.',
    verb: 'concluir',
    tense: 'futuro',
    answers: ['concluiremos', 'vamos concluir'],
  },
  {
    sentence: 'Ele {blank} todos os exercícios no domingo.',
    verb: 'completar',
    tense: 'pretérito perfeito',
    answers: ['completou'],
  },
  {
    sentence: 'Eu {blank} para o cinema amanhã.',
    verb: 'ir',
    tense: 'futuro',
    answers: ['irei', 'vou'],
  },
  {
    sentence: 'Ana e João {blank} para a festa juntos.',
    verb: 'ir',
    tense: 'pretérito perfeito',
    answers: ['foram'],
  },
  {
    sentence: 'Você {blank} uma ótima apresentação hoje!',
    verb: 'dar',
    tense: 'pretérito perfeito',
    answers: ['deu'],
  },
  {
    sentence: 'Nós {blank} um encontro com eles na sexta.',
    verb: 'marcar',
    tense: 'presente',
    answers: ['marcamos'],
  },
  {
    sentence: 'Eles {blank} a nova série na semana passada.',
    verb: 'começar',
    tense: 'pretérito perfeito',
    answers: ['começaram'],
  },
  {
    sentence: 'Ela {blank} que eu estava certo.',
    verb: 'admitir',
    tense: 'pretérito perfeito',
    answers: ['admitiu'],
  },
  {
    sentence: 'Eu {blank} muito sobre o tema.',
    verb: 'estudar',
    tense: 'pretérito perfeito',
    answers: ['estudei'],
  },
  {
    sentence: 'Você {blank} o relatório na quinta?',
    verb: 'entregar',
    tense: 'pretérito perfeito',
    answers: ['entregou'],
  },
  {
    sentence: 'Ele {blank} para o mercado agora.',
    verb: 'ir',
    tense: 'presente',
    answers: ['vai'],
  },
  {
    sentence: 'Nós {blank} muito da sua companhia.',
    verb: 'gostar',
    tense: 'presente',
    answers: ['gostamos'],
  },
  {
    sentence: 'Eles {blank} juntos no último verão.',
    verb: 'viajar',
    tense: 'pretérito perfeito',
    answers: ['viajaram'],
  },
  {
    sentence: 'Ela {blank} o café todas as manhãs.',
    verb: 'fazer',
    tense: 'presente',
    answers: ['faz'],
  },
  {
    sentence: 'Você {blank} o jantar na última semana?',
    verb: 'preparar',
    tense: 'pretérito perfeito',
    answers: ['preparou'],
  },
  {
    sentence: 'Eles {blank} a comida para a festa.',
    verb: 'levar',
    tense: 'presente',
    answers: ['levam'],
  },
  {
    sentence: 'Nós {blank} o carro ontem.',
    verb: 'lavar',
    tense: 'pretérito perfeito',
    answers: ['lavamos'],
  },
  {
    sentence: 'Ela {blank} o livro no final de semana.',
    verb: 'ler',
    tense: 'pretérito perfeito',
    answers: ['leu'],
  },
  {
    sentence: 'Eu {blank} a lição de casa mais tarde.',
    verb: 'fazer',
    tense: 'futuro',
    answers: ['farei', 'vou fazer'],
  },
  {
    sentence: 'Você {blank} a verdade agora.',
    verb: 'saber',
    tense: 'presente',
    answers: ['sabe'],
  },
  {
    sentence: 'Eles {blank} o almoço enquanto eu estudava.',
    verb: 'preparar',
    tense: 'pretérito perfeito',
    answers: ['prepararam'],
  },
  {
    sentence: 'Eu {blank} a aula na terça-feira passada.',
    verb: 'perder',
    tense: 'pretérito perfeito',
    answers: ['perdi'],
  },
  {
    sentence: 'Ela {blank} a sobremesa para nós.',
    verb: 'trazer',
    tense: 'pretérito perfeito',
    answers: ['trouxe'],
  },
  {
    sentence: 'Você {blank} na viagem?',
    verb: 'participar',
    tense: 'pretérito perfeito',
    answers: ['participou'],
  },
  {
    sentence: 'Eu {blank} muito cansado hoje.',
    verb: 'estar',
    tense: 'presente',
    answers: ['estou'],
  },
  {
    sentence: 'Nós {blank} no parque ontem.',
    verb: 'caminhar',
    tense: 'pretérito perfeito',
    answers: ['caminhamos'],
  },
  {
    sentence: 'Eles {blank} a música quando eu liguei.',
    verb: 'ouvir',
    tense: 'pretérito perfeito',
    answers: ['ouviram'],
  },
  {
    sentence: 'Ele {blank} no concurso na semana passada.',
    verb: 'passar',
    tense: 'pretérito perfeito',
    answers: ['passou'],
  },
  {
    sentence: 'Eu {blank} a reunião para quinta-feira.',
    verb: 'remarcar',
    tense: 'presente',
    answers: ['remarco'],
  },
  {
    sentence: 'Você {blank} para a faculdade em 2019?',
    verb: 'entrar',
    tense: 'pretérito perfeito',
    answers: ['entrou'],
  },
  {
    sentence: 'Ela {blank} para o escritório às 9h.',
    verb: 'chegar',
    tense: 'presente',
    answers: ['chega'],
  },
  {
    sentence: 'Eu {blank} sobre a proposta de emprego.',
    verb: 'pensar',
    tense: 'pretérito perfeito',
    answers: ['pensei'],
  },
  {
    sentence: 'Você {blank} meu nome corretamente?',
    verb: 'escrever',
    tense: 'pretérito perfeito',
    answers: ['escreveu'],
  },
  {
    sentence: 'Eles {blank} o carro para a garagem ontem.',
    verb: 'levar',
    tense: 'pretérito perfeito',
    answers: ['levaram'],
  },
  {
    sentence: 'Nós {blank} tudo antes de partir.',
    verb: 'arrumar',
    tense: 'pretérito perfeito',
    answers: ['arrumamos'],
  },
  {
    sentence: 'Ele {blank} os novos projetos no próximo mês.',
    verb: 'lançar',
    tense: 'futuro',
    answers: ['lançará', 'vai lançar'],
  },
  {
    sentence: 'Você {blank} o plano antes de começar?',
    verb: 'discutir',
    tense: 'pretérito perfeito',
    answers: ['discutiu'],
  },
  {
    sentence: 'Nós {blank} a tarefa logo mais.',
    verb: 'terminar',
    tense: 'futuro',
    answers: ['terminaremos', 'vamos terminar'],
  },
  {
    sentence: 'Ela {blank} as plantas na última primavera.',
    verb: 'regar',
    tense: 'pretérito perfeito',
    answers: ['regou'],
  },
  {
    sentence: 'Eles {blank} cedo para a festa hoje.',
    verb: 'chegar',
    tense: 'presente',
    answers: ['chegam'],
  },
  {
    sentence: 'Nós {blank} as crianças para a escola agora.',
    verb: 'levar',
    tense: 'presente',
    answers: ['levamos'],
  },
  {
    sentence: 'Eu {blank} uma nova língua no ano passado.',
    verb: 'aprender',
    tense: 'pretérito perfeito',
    answers: ['aprendi'],
  },
  {
    sentence: 'Você {blank} a roupa ontem?',
    verb: 'lavar',
    tense: 'pretérito perfeito',
    answers: ['lavou'],
  },
  {
    sentence: 'Eles {blank} muitas perguntas na aula.',
    verb: 'fazer',
    tense: 'presente',
    answers: ['fazem'],
  },
  {
    sentence: 'Ela {blank} a visita ao museu na terça.',
    verb: 'marcar',
    tense: 'pretérito perfeito',
    answers: ['marcou'],
  },
  {
    sentence: 'Eu {blank} no sofá toda a tarde ontem.',
    verb: 'ficar',
    tense: 'pretérito perfeito',
    answers: ['fiquei'],
  },
  {
    sentence: 'Nós {blank} a lição de casa agora.',
    verb: 'começar',
    tense: 'presente',
    answers: ['começamos'],
  },
  {
    sentence: 'Eles {blank} a casa de Maria no fim de semana.',
    verb: 'visitar',
    tense: 'pretérito perfeito',
    answers: ['visitaram'],
  },
  {
    sentence: 'Ela {blank} a receita com detalhes.',
    verb: 'explicar',
    tense: 'pretérito perfeito',
    answers: ['explicou'],
  },
  {
    sentence: 'Você {blank} para o professor?',
    verb: 'responder',
    tense: 'pretérito perfeito',
    answers: ['respondeu'],
  },
  {
    sentence: 'Eles {blank} para o jogo na sexta-feira.',
    verb: 'ir',
    tense: 'futuro',
    answers: ['irão', 'vão'],
  },
  {
    sentence: 'Eu {blank} mais tarde para resolver isso.',
    verb: 'ligar',
    tense: 'futuro',
    answers: ['ligarei', 'vou ligar'],
  },
  {
    sentence: 'Você {blank} comigo na próxima semana?',
    verb: 'trabalhar',
    tense: 'futuro',
    answers: ['trabalhará', 'vai trabalhar'],
  },
  {
    sentence: 'Ela {blank} a festa com todos os amigos.',
    verb: 'organizar',
    tense: 'pretérito perfeito',
    answers: ['organizou'],
  },
  {
    sentence: 'Nós {blank} a cidade inteira durante as férias.',
    verb: 'explorar',
    tense: 'pretérito perfeito',
    answers: ['exploramos'],
  },
  {
    sentence: 'Eles {blank} tudo antes de assinar o contrato.',
    verb: 'verificar',
    tense: 'pretérito perfeito',
    answers: ['verificaram'],
  },
  {
    sentence: 'Eu {blank} mais cedo amanhã para a reunião.',
    verb: 'chegar',
    tense: 'futuro',
    answers: ['chegarei', 'vou chegar'],
  },
  {
    sentence: 'Você {blank} todos os capítulos hoje?',
    verb: 'ler',
    tense: 'pretérito perfeito',
    answers: ['leu'],
  },
  {
    sentence: 'Nós {blank} um novo carro no mês passado.',
    verb: 'comprar',
    tense: 'pretérito perfeito',
    answers: ['compramos'],
  },
  {
    sentence: 'Eles {blank} a pesquisa na segunda-feira.',
    verb: 'finalizar',
    tense: 'pretérito perfeito',
    answers: ['finalizaram'],
  },
  {
    sentence: 'Ela {blank} para a prova durante todo o fim de semana.',
    verb: 'estudar',
    tense: 'pretérito perfeito',
    answers: ['estudou'],
  },
  {
    sentence: 'Eu {blank} a viagem com todos os detalhes.',
    verb: 'planejar',
    tense: 'pretérito perfeito',
    answers: ['planejei'],
  },
  {
    sentence: 'Nós {blank} o relatório no prazo.',
    verb: 'entregar',
    tense: 'pretérito perfeito',
    answers: ['entregamos'],
  },
  {
    sentence: 'Você {blank} o artigo antes de publicar?',
    verb: 'revisar',
    tense: 'pretérito perfeito',
    answers: ['revisou'],
  },
  {
    sentence: 'Eles {blank} o concerto amanhã.',
    verb: 'assistir',
    tense: 'futuro',
    answers: ['assistirão', 'vão assistir'],
  },
  {
    sentence: 'Ela {blank} para a reunião na terça-feira passada.',
    verb: 'vir',
    tense: 'pretérito perfeito',
    answers: ['veio'],
  },
  {
    sentence: 'Eu {blank} um novo curso no mês que vem.',
    verb: 'começar',
    tense: 'futuro',
    answers: ['começarei', 'vou começar'],
  },
  {
    sentence: 'Nós {blank} para o evento em grupo.',
    verb: 'ir',
    tense: 'pretérito perfeito',
    answers: ['fomos'],
  },
  {
    sentence: 'Eles {blank} um grande esforço para terminar.',
    verb: 'fazer',
    tense: 'pretérito perfeito',
    answers: ['fizeram'],
  },
  {
    sentence: 'Você {blank} o problema antes de resolver?',
    verb: 'analisar',
    tense: 'pretérito perfeito',
    answers: ['analisou'],
  },
  {
    sentence: 'Eu {blank} para o médico amanhã cedo.',
    verb: 'ir',
    tense: 'futuro',
    answers: ['irei', 'vou'],
  },
  {
    sentence: 'Ela {blank} o bolo na festa.',
    verb: 'levar',
    tense: 'pretérito perfeito',
    answers: ['levou'],
  },
  {
    sentence: 'Eles {blank} na competição no mês passado.',
    verb: 'participar',
    tense: 'pretérito perfeito',
    answers: ['participaram'],
  },
  {
    sentence: 'Eu {blank} o presente para ela ontem.',
    verb: 'comprar',
    tense: 'pretérito perfeito',
    answers: ['comprei'],
  },
  {
    sentence: 'Nós {blank} a estrada errada durante a viagem.',
    verb: 'pegar',
    tense: 'pretérito perfeito',
    answers: ['pegamos'],
  },
  {
    sentence: 'Eles {blank} o jantar para o grupo inteiro.',
    verb: 'cozinhar',
    tense: 'pretérito perfeito',
    answers: ['cozinharam'],
  },
  {
    sentence: 'Ela {blank} a carta antes de enviar.',
    verb: 'escrever',
    tense: 'pretérito perfeito',
    answers: ['escreveu'],
  },
  {
    sentence: 'Eu {blank} para a festa na sexta-feira.',
    verb: 'sair',
    tense: 'futuro',
    answers: ['sairei', 'vou sair'],
  },
  {
    sentence: 'Você {blank} um bom trabalho no projeto!',
    verb: 'fazer',
    tense: 'pretérito perfeito',
    answers: ['fez'],
  },
  {
    sentence: 'Nós {blank} o barco ao longo do rio.',
    verb: 'navegar',
    tense: 'pretérito perfeito',
    answers: ['navegamos'],
  },
  {
    sentence: 'Eles {blank} a loja no mês passado.',
    verb: 'abrir',
    tense: 'pretérito perfeito',
    answers: ['abriram'],
  },
  {
    sentence: 'Você {blank} a lista de convidados?',
    verb: 'conferir',
    tense: 'pretérito perfeito',
    answers: ['conferiu'],
  },
  {
    sentence: 'Nós {blank} a ideia para o chefe na semana passada.',
    verb: 'apresentar',
    tense: 'pretérito perfeito',
    answers: ['apresentamos'],
  },
  {
    sentence: 'Ele {blank} para ajudar no trabalho.',
    verb: 'voluntariar',
    tense: 'pretérito perfeito',
    answers: ['voluntariou'],
  },
  {
    sentence: 'Eu {blank} o filme na semana que vem.',
    verb: 'assistir',
    tense: 'futuro',
    answers: ['assistirei', 'vou assistir'],
  },
  {
    sentence: 'Você {blank} um tempo para pensar?',
    verb: 'precisar',
    tense: 'presente',
    answers: ['precisa'],
  },
  {
    sentence: 'Nós {blank} a ideia antes de implementar.',
    verb: 'considerar',
    tense: 'pretérito perfeito',
    answers: ['consideramos'],
  },
  {
    sentence: 'Eles {blank} o documento no final da reunião.',
    verb: 'assinar',
    tense: 'pretérito perfeito',
    answers: ['assinaram'],
  },
  {
    sentence: 'Ela {blank} a resposta correta durante o teste.',
    verb: 'encontrar',
    tense: 'pretérito perfeito',
    answers: ['encontrou'],
  },
  {
    sentence: 'Eu {blank} em casa durante o fim de semana.',
    verb: 'ficar',
    tense: 'pretérito perfeito',
    answers: ['fiquei'],
  },
  {
    sentence: 'Nós {blank} a prova na última sexta-feira.',
    verb: 'fazer',
    tense: 'pretérito perfeito',
    answers: ['fizemos'],
  },
  {
    sentence: 'Eles {blank} sobre o problema antes da decisão.',
    verb: 'falar',
    tense: 'pretérito perfeito',
    answers: ['falaram'],
  },
  {
    sentence: 'Ela {blank} as flores para a mãe dela.',
    verb: 'dar',
    tense: 'pretérito perfeito',
    answers: ['deu'],
  },
  {
    sentence: 'Eu {blank} em casa quando eles chegaram.',
    verb: 'estar',
    tense: 'pretérito perfeito',
    answers: ['estava'],
  },
  {
    sentence: 'Você {blank} o documento na mesa?',
    verb: 'deixar',
    tense: 'pretérito perfeito',
    answers: ['deixou'],
  },
  {
    sentence: 'Eles {blank} para o restaurante amanhã.',
    verb: 'voltar',
    tense: 'futuro',
    answers: ['voltarão', 'vão voltar'],
  },
  {
    sentence: 'Nós {blank} o filme juntos amanhã.',
    verb: 'assistir',
    tense: 'futuro',
    answers: ['assistiremos', 'vamos assistir'],
  },
  {
    sentence: 'Ela {blank} o problema com paciência.',
    verb: 'resolver',
    tense: 'pretérito perfeito',
    answers: ['resolveu'],
  },
  {
    sentence: 'Eu {blank} no telefone por muito tempo ontem.',
    verb: 'ficar',
    tense: 'pretérito perfeito',
    answers: ['fiquei'],
  },
  {
    sentence: 'Você {blank} muito bem no teste!',
    verb: 'fazer',
    tense: 'pretérito perfeito',
    answers: ['fez'],
  },
  {
    sentence: 'Eles {blank} a notícia durante a reunião.',
    verb: 'anunciar',
    tense: 'pretérito perfeito',
    answers: ['anunciaram'],
  },
  {
    sentence: 'Ela {blank} com a situação difícil.',
    verb: 'lidar',
    tense: 'pretérito perfeito',
    answers: ['lidou'],
  },
  {
    sentence: 'Eu {blank} as caixas para o quarto.',
    verb: 'levar',
    tense: 'pretérito perfeito',
    answers: ['levei'],
  },
];
