#!/usr/bin/env python3
"""Generate data.js from source files. Run with: python3 scripts/generate-data.py"""

import json
import os
import sys


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    verbs_dir = os.path.join(root, 'src', 'Model', 'verbs')

    with open(os.path.join(verbs_dir, 'index.json'), encoding='utf-8') as f:
        verb_names = json.load(f)

    all_problems = []
    for verb_name in verb_names:
        path = os.path.join(verbs_dir, f'{verb_name}.json')
        if os.path.exists(path):
            with open(path, encoding='utf-8') as f:
                all_problems.extend(json.load(f)['problems'])
        else:
            print(f'Warning: {path} not found', file=sys.stderr)

    with open(os.path.join(root, 'src', 'Model', 'Definitions.json'), encoding='utf-8') as f:
        defs = json.load(f)

    output_path = os.path.join(root, 'data.js')
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by scripts/generate-data.py — do not edit manually\n\n')
        f.write(f'const problemData = {json.dumps(all_problems, ensure_ascii=False)};\n\n')
        f.write(f'const verbsDictionaryData = {json.dumps(defs["verbsDictionary"], ensure_ascii=False)};\n\n')
        f.write(f'const keywordsData = {json.dumps(defs["keywords"], ensure_ascii=False)};\n\n')
        f.write(f'const allVerbs = {json.dumps(verb_names, ensure_ascii=False)};\n')

    print(f'data.js generated: {len(all_problems)} problems, {len(verb_names)} verbs')


if __name__ == '__main__':
    main()
